#
# AdjustDeviceCapitalCosts_TOM.jl
#
using EnergyModel

module AdjustDeviceCapitalCosts_TOM

import ...EnergyModel: ReadDisk,WriteDisk,Select
import ...EnergyModel: HisTime,ITime,MaxTime,First,Future,Final,Yr
import ...EnergyModel: @finite_math,finite_inverse,finite_divide,finite_power,finite_exp,finite_log
import ...EnergyModel: DB

const VariableArray{N} = Array{Float32,N} where {N}
const SetArray = Vector{String}

Base.@kwdef struct CControl
  db::String

  CalDB::String = "CCalDB"
  Input::String = "CInput"
  Outpt::String = "COutput"
  BCNameDB::String = ReadDisk(db,"MainDB/BCNameDB") # Base Case Name

  Area::SetArray = ReadDisk(db,"MainDB/AreaKey")
  AreaDS::SetArray = ReadDisk(db,"MainDB/AreaDS")
  Areas::Vector{Int} = collect(Select(Area))
  EC::SetArray = ReadDisk(db,"$Input/ECKey")
  ECDS::SetArray = ReadDisk(db,"$Input/ECDS")
  ECs::Vector{Int} = collect(Select(EC))
  Enduse::SetArray = ReadDisk(db,"$Input/EnduseKey")
  EnduseDS::SetArray = ReadDisk(db,"$Input/EnduseDS")
  Enduses::Vector{Int} = collect(Select(Enduse))
  Nation::SetArray = ReadDisk(db,"MainDB/NationKey")
  NationDS::SetArray = ReadDisk(db,"MainDB/NationDS")
  Nations::Vector{Int} = collect(Select(Nation))
  Tech::SetArray = ReadDisk(db,"$Input/TechKey")
  TechDS::SetArray = ReadDisk(db,"$Input/TechDS")
  Techs::Vector{Int} = collect(Select(Tech))
  Year::SetArray = ReadDisk(db,"MainDB/YearKey")
  YearDS::SetArray = ReadDisk(db,"MainDB/YearDS")
  Years::Vector{Int} = collect(Select(Year))

  MacroSwitch::Vector{String} = ReadDisk(db,"MInput/MacroSwitch") # [Nation] String Indicator of Macroeconomic Forecast (TOM,Stokes,AEO,CER)
  xInflation::VariableArray{2} = ReadDisk(db,"MInput/xInflation") # [Area,Year] Inflation Index ($/$)
  xDCC::VariableArray{5} = ReadDisk(db,"$Input/xDCC") # [Enduse,Tech,EC,Area,Year] Device Capital Cost (Real $/mmBtu/Yr)

  # Scratch Variables
  DCCAdjust::VariableArray{2} = zeros(Float32,length(EC),length(Area)) # [EC,Area] Device Capital Cost Adjustment ($/$)
end

function CCalibration(db)
  data = CControl(; db)
  (;Input) = data
  (;Area,AreaDS,Areas,EC,ECDS,ECs,Enduse,EnduseDS,Enduses,Nation) = data
  (;NationDS,Nations,Tech,TechDS,Techs,Year,YearDS,Years) = data
  (;MacroSwitch,xInflation,xDCC) = data
  (;DCCAdjust) = data

  #
  # Adjust capital costs to align device investments to TOM in year 2024
  # Based on September 2024 Walnut version of model. Updated 09/21/2024 R.Levesque
  #
  areas=Select(Area,(from="ON", to="Pac"))

  ON=Select(Area,"ON")
  QC=Select(Area,"QC")
  BC=Select(Area,"BC")
  AB=Select(Area,"AB")
  MB=Select(Area,"MB")
  SK=Select(Area,"SK")
  NB=Select(Area,"NB")
  NS=Select(Area,"NS")
  NL=Select(Area,"NL")
  PE=Select(Area,"PE")
  YT=Select(Area,"YT")
  NT=Select(Area,"NT")
  NU=Select(Area,"NU")
  CA=Select(Area,"CA")
  NEng=Select(Area,"NEng")
  MAtl=Select(Area,"MAtl")
  ENC=Select(Area,"ENC")
  WNC=Select(Area,"WNC")
  SAtl=Select(Area,"SAtl")
  ESC=Select(Area,"ESC")
  WSC=Select(Area,"WSC")
  Mtn=Select(Area,"Mtn")
  Pac=Select(Area,"Pac")

  ecs=Select(EC,(from="Wholesale", to="NGPipeline"))

  Wholesale=Select(EC,"Wholesale")
  Retail=Select(EC,"Retail")
  Warehouse=Select(EC,"Warehouse")
  Information=Select(EC,"Information")
  Offices=Select(EC,"Offices")
  Education=Select(EC,"Education")
  Health=Select(EC,"Health")
  OtherCommercial=Select(EC,"OtherCommercial")
  NGDistribution=Select(EC,"NGDistribution")
  OilPipeline=Select(EC,"OilPipeline")
  NGPipeline=Select(EC,"NGPipeline")
  
  @. DCCAdjust = 1.0

  DCCAdjust[Wholesale,ON]=1.6512
  DCCAdjust[Retail,ON]=0.8309
  DCCAdjust[Warehouse,ON]=2.4754
  DCCAdjust[Information,ON]=57.7599
  DCCAdjust[Offices,ON]=2.9825
  DCCAdjust[Education,ON]=0.4987
  DCCAdjust[Health,ON]=1.1311
  DCCAdjust[OtherCommercial,ON]=1.096
  DCCAdjust[NGDistribution,ON]=29.1898
  DCCAdjust[OilPipeline,ON]=1.8835
  DCCAdjust[NGPipeline,ON]=0.3691
  DCCAdjust[Wholesale,QC]=2.1172
  DCCAdjust[Retail,QC]=1.0331
  DCCAdjust[Warehouse,QC]=1.4936
  DCCAdjust[Information,QC]=52.5151
  DCCAdjust[Offices,QC]=3.8794
  DCCAdjust[Education,QC]=1.4288
  DCCAdjust[Health,QC]=1.5048
  DCCAdjust[OtherCommercial,QC]=1.1847
  DCCAdjust[NGDistribution,QC]=200
  DCCAdjust[OilPipeline,QC]=1
  DCCAdjust[NGPipeline,QC]=6.5382
  DCCAdjust[Wholesale,BC]=1.7408
  DCCAdjust[Retail,BC]=0.9233
  DCCAdjust[Warehouse,BC]=3.3198
  DCCAdjust[Information,BC]=67.3973
  DCCAdjust[Offices,BC]=3.835
  DCCAdjust[Education,BC]=1.2441
  DCCAdjust[Health,BC]=1.5528
  DCCAdjust[OtherCommercial,BC]=1.1527
  DCCAdjust[NGDistribution,BC]=9.1831
  DCCAdjust[OilPipeline,BC]=19.5166
  DCCAdjust[NGPipeline,BC]=4.5415
  DCCAdjust[Wholesale,AB]=3.4817
  DCCAdjust[Retail,AB]=1.3297
  DCCAdjust[Warehouse,AB]=4.6633
  DCCAdjust[Information,AB]=23.6602
  DCCAdjust[Offices,AB]=7.5819
  DCCAdjust[Education,AB]=1.0839
  DCCAdjust[Health,AB]=2.0301
  DCCAdjust[OtherCommercial,AB]=1.4492
  DCCAdjust[NGDistribution,AB]=5.0553
  DCCAdjust[OilPipeline,AB]=2.069
  DCCAdjust[NGPipeline,AB]=0.5637
  DCCAdjust[Wholesale,MB]=2.2902
  DCCAdjust[Retail,MB]=1.1053
  DCCAdjust[Warehouse,MB]=1.0532
  DCCAdjust[Information,MB]=28.1939
  DCCAdjust[Offices,MB]=2.2001
  DCCAdjust[Education,MB]=0.4315
  DCCAdjust[Health,MB]=0.8012
  DCCAdjust[OtherCommercial,MB]=0.7365
  DCCAdjust[NGDistribution,MB]=0.2355
  DCCAdjust[OilPipeline,MB]=0.7863
  DCCAdjust[NGPipeline,MB]=0.0916
  DCCAdjust[Wholesale,SK]=3.665
  DCCAdjust[Retail,SK]=1.4983
  DCCAdjust[Warehouse,SK]=0.3009
  DCCAdjust[Information,SK]=86.9475
  DCCAdjust[Offices,SK]=4.9893
  DCCAdjust[Education,SK]=0.5385
  DCCAdjust[Health,SK]=1.0837
  DCCAdjust[OtherCommercial,SK]=1.7805
  DCCAdjust[NGDistribution,SK]=0.4506
  DCCAdjust[OilPipeline,SK]=0.8873
  DCCAdjust[NGPipeline,SK]=0.0212
  DCCAdjust[Wholesale,NB]=1.1299
  DCCAdjust[Retail,NB]=0.6199
  DCCAdjust[Warehouse,NB]=1.1338
  DCCAdjust[Information,NB]=54.0185
  DCCAdjust[Offices,NB]=2.6763
  DCCAdjust[Education,NB]= 0.16
  DCCAdjust[Health,NB]=0.6419
  DCCAdjust[OtherCommercial,NB]=0.6862
  DCCAdjust[NGDistribution,NB]= 0.24
  DCCAdjust[OilPipeline,NB]=1
  DCCAdjust[NGPipeline,NB]=1
  DCCAdjust[Wholesale,NS]=1.0195
  DCCAdjust[Retail,NS]=0.8823
  DCCAdjust[Warehouse,NS]=0.8881
  DCCAdjust[Information,NS]=50.3794
  DCCAdjust[Offices,NS]=11.2362
  DCCAdjust[Education,NS]=0.5869
  DCCAdjust[Health,NS]=0.9151
  DCCAdjust[OtherCommercial,NS]=1.0837
  DCCAdjust[NGDistribution,NS]=2.2528
  DCCAdjust[OilPipeline,NS]=1
  DCCAdjust[NGPipeline,NS]=0.0806
  DCCAdjust[Wholesale,NL]=1.1334
  DCCAdjust[Retail,NL]=1.0882
  DCCAdjust[Warehouse,NL]=1.2229
  DCCAdjust[Information,NL]=26.3365
  DCCAdjust[Offices,NL]=3.7947
  DCCAdjust[Education,NL]=2.2524
  DCCAdjust[Health,NL]=1.288
  DCCAdjust[OtherCommercial,NL]=0.6221
  DCCAdjust[NGDistribution,NL]=1
  DCCAdjust[OilPipeline,NL]=1
  DCCAdjust[NGPipeline,NL]=1
  DCCAdjust[Wholesale,PE]=0.9152
  DCCAdjust[Retail,PE]=0.647
  DCCAdjust[Warehouse,PE]=1.3901
  DCCAdjust[Information,PE]=32.1572
  DCCAdjust[Offices,PE]=2.3932
  DCCAdjust[Education,PE]=1.8967
  DCCAdjust[Health,PE]=1.2606
  DCCAdjust[OtherCommercial,PE]=1.2379
  DCCAdjust[NGDistribution,PE]=1
  DCCAdjust[OilPipeline,PE]=1
  DCCAdjust[NGPipeline,PE]=1
  DCCAdjust[Wholesale,YT]=0.3809
  DCCAdjust[Retail,YT]=0.7107
  DCCAdjust[Warehouse,YT]=0.9632
  DCCAdjust[Information,YT]=11.0708
  DCCAdjust[Offices,YT]=3.3807
  DCCAdjust[Education,YT]=0.3797
  DCCAdjust[Health,YT]=3.284
  DCCAdjust[OtherCommercial,YT]=0.7726
  DCCAdjust[NGDistribution,YT]=1
  DCCAdjust[OilPipeline,YT]=1
  DCCAdjust[NGPipeline,YT]=1
  DCCAdjust[Wholesale,NT]=0.1731
  DCCAdjust[Retail,NT]= 0.15
  DCCAdjust[Warehouse,NT]=0.6725
  DCCAdjust[Information,NT]=11.5387
  DCCAdjust[Offices,NT]=3.6794
  DCCAdjust[Education,NT]=0.1654
  DCCAdjust[Health,NT]=1.0452
  DCCAdjust[OtherCommercial,NT]=0.4189
  DCCAdjust[NGDistribution,NT]=1
  DCCAdjust[OilPipeline,NT]=262.19
  DCCAdjust[NGPipeline,NT]=1
  DCCAdjust[Wholesale,NU]=1.0269
  DCCAdjust[Retail,NU]=1.3721
  DCCAdjust[Warehouse,NU]=2.631
  DCCAdjust[Information,NU]=14.371
  DCCAdjust[Offices,NU]=10.1839
  DCCAdjust[Education,NU]=1
  DCCAdjust[Health,NU]=1.1779
  DCCAdjust[OtherCommercial,NU]=0.9434
  DCCAdjust[NGDistribution,NU]=1
  DCCAdjust[OilPipeline,NU]=1
  DCCAdjust[NGPipeline,NU]=1
  DCCAdjust[Wholesale,CA]=0.0922
  DCCAdjust[Retail,CA]=0.2133
  DCCAdjust[Warehouse,CA]=0.012
  DCCAdjust[Information,CA]=0.9045
  DCCAdjust[Offices,CA]=0.2547
  DCCAdjust[Education,CA]=0.1893
  DCCAdjust[Health,CA]=0.7059
  DCCAdjust[OtherCommercial,CA]=0.0794
  DCCAdjust[NGDistribution,CA]=12.3474
  DCCAdjust[OilPipeline,CA]=5.497
  DCCAdjust[NGPipeline,CA]=3.4103
  DCCAdjust[Wholesale,NEng]=0.4066
  DCCAdjust[Retail,NEng]=1.0296
  DCCAdjust[Warehouse,NEng]=0.0365
  DCCAdjust[Information,NEng]=0.2683
  DCCAdjust[Offices,NEng]=1.8504
  DCCAdjust[Education,NEng]=0.6532
  DCCAdjust[Health,NEng]=3.246
  DCCAdjust[OtherCommercial,NEng]=0.3236
  DCCAdjust[NGDistribution,NEng]=47.3319
  DCCAdjust[OilPipeline,NEng]=16.1949
  DCCAdjust[NGPipeline,NEng]=3.1005
  DCCAdjust[Wholesale,MAtl]=0.507
  DCCAdjust[Retail,MAtl]=1.2054
  DCCAdjust[Warehouse,MAtl]=0.0361
  DCCAdjust[Information,MAtl]=0.6894
  DCCAdjust[Offices,MAtl]=1.2932
  DCCAdjust[Education,MAtl]=0.5803
  DCCAdjust[Health,MAtl]=2.3622
  DCCAdjust[OtherCommercial,MAtl]=0.4617
  DCCAdjust[NGDistribution,MAtl]=11.0945
  DCCAdjust[OilPipeline,MAtl]=2.6927
  DCCAdjust[NGPipeline,MAtl]=0.5519
  DCCAdjust[Wholesale,ENC]=0.4016
  DCCAdjust[Retail,ENC]=0.9979
  DCCAdjust[Warehouse,ENC]=0.0522
  DCCAdjust[Information,ENC]=1.1875
  DCCAdjust[Offices,ENC]=1.4158
  DCCAdjust[Education,ENC]=0.1951
  DCCAdjust[Health,ENC]=2.1154
  DCCAdjust[OtherCommercial,ENC]=0.3895
  DCCAdjust[NGDistribution,ENC]=25.9969
  DCCAdjust[OilPipeline,ENC]=7.3373
  DCCAdjust[NGPipeline,ENC]=0.627
  DCCAdjust[Wholesale,WNC]=0.308
  DCCAdjust[Retail,WNC]=0.8346
  DCCAdjust[Warehouse,WNC]=0.0328
  DCCAdjust[Information,WNC]=0.6897
  DCCAdjust[Offices,WNC]=1.1497
  DCCAdjust[Education,WNC]=0.2412
  DCCAdjust[Health,WNC]=2.2707
  DCCAdjust[OtherCommercial,WNC]=0.3097
  DCCAdjust[NGDistribution,WNC]=31.1923
  DCCAdjust[OilPipeline,WNC]=1.461
  DCCAdjust[NGPipeline,WNC]=0.1654
  DCCAdjust[Wholesale,SAtl]=0.1274
  DCCAdjust[Retail,SAtl]=0.3089
  DCCAdjust[Warehouse,SAtl]=0.0123
  DCCAdjust[Information,SAtl]=0.1287
  DCCAdjust[Offices,SAtl]=0.393
  DCCAdjust[Education,SAtl]=0.0775
  DCCAdjust[Health,SAtl]=0.4314
  DCCAdjust[OtherCommercial,SAtl]=0.136
  DCCAdjust[NGDistribution,SAtl]=17.4901
  DCCAdjust[OilPipeline,SAtl]=3.9434
  DCCAdjust[NGPipeline,SAtl]=0.1672
  DCCAdjust[Wholesale,ESC]=0.3402
  DCCAdjust[Retail,ESC]=0.7807
  DCCAdjust[Warehouse,ESC]=0.0478
  DCCAdjust[Information,ESC]=0.0574
  DCCAdjust[Offices,ESC]=1.0996
  DCCAdjust[Education,ESC]=0.1348
  DCCAdjust[Health,ESC]=1.3956
  DCCAdjust[OtherCommercial,ESC]=0.2263
  DCCAdjust[NGDistribution,ESC]=27.992
  DCCAdjust[OilPipeline,ESC]=0.773
  DCCAdjust[NGPipeline,ESC]=0.0256
  DCCAdjust[Wholesale,WSC]=0.1379
  DCCAdjust[Retail,WSC]=0.3315
  DCCAdjust[Warehouse,WSC]=0.0126
  DCCAdjust[Information,WSC]=0.3972
  DCCAdjust[Offices,WSC]=0.3189
  DCCAdjust[Education,WSC]=0.0198
  DCCAdjust[Health,WSC]=0.6263
  DCCAdjust[OtherCommercial,WSC]=0.1261
  DCCAdjust[NGDistribution,WSC]=4.1464
  DCCAdjust[OilPipeline,WSC]=1.2444
  DCCAdjust[NGPipeline,WSC]=0.4195
  DCCAdjust[Wholesale,Mtn]=0.1541
  DCCAdjust[Retail,Mtn]=0.3823
  DCCAdjust[Warehouse,Mtn]=0.025
  DCCAdjust[Information,Mtn]=0.3358
  DCCAdjust[Offices,Mtn]=0.7253
  DCCAdjust[Education,Mtn]=0.0228
  DCCAdjust[Health,Mtn]=1.5405
  DCCAdjust[OtherCommercial,Mtn]=0.1802
  DCCAdjust[NGDistribution,Mtn]=33.28
  DCCAdjust[OilPipeline,Mtn]=0.894
  DCCAdjust[NGPipeline,Mtn]=0.0363
  DCCAdjust[Wholesale,Pac]=0.0952
  DCCAdjust[Retail,Pac]=0.9001
  DCCAdjust[Warehouse,Pac]=0.0063
  DCCAdjust[Information,Pac]=0.2329
  DCCAdjust[Offices,Pac]=0.4792
  DCCAdjust[Education,Pac]=0.2176
  DCCAdjust[Health,Pac]=0.6232
  DCCAdjust[OtherCommercial,Pac]=0.1198
  DCCAdjust[NGDistribution,Pac]=72.7503
  DCCAdjust[OilPipeline,Pac]=10.4576
  DCCAdjust[NGPipeline,Pac]=2.6639

  CN=Select(Nation,"CN")
  if MacroSwitch[CN] == "TOM"
    for year in Years, area in areas, ec in ecs, tech in Techs, enduse in Enduses
      if xDCC[enduse,tech,ec,area,year] != -99
        xDCC[enduse,tech,ec,area,year]=xDCC[enduse,tech,ec,area,year]*DCCAdjust[ec,area]
      end
    end
    WriteDisk(db,"$Input/xDCC",xDCC)
  end
  
end

Base.@kwdef struct IControl
  db::String

  CalDB::String = "ICalDB"
  Input::String = "IInput"
  Outpt::String = "IOutput"
  BCNameDB::String = ReadDisk(db,"MainDB/BCNameDB") # Base Case Name

  Area::SetArray = ReadDisk(db,"MainDB/AreaKey")
  AreaDS::SetArray = ReadDisk(db,"MainDB/AreaDS")
  Areas::Vector{Int} = collect(Select(Area))
  EC::SetArray = ReadDisk(db,"$Input/ECKey")
  ECDS::SetArray = ReadDisk(db,"$Input/ECDS")
  ECs::Vector{Int} = collect(Select(EC))
  Enduse::SetArray = ReadDisk(db,"$Input/EnduseKey")
  EnduseDS::SetArray = ReadDisk(db,"$Input/EnduseDS")
  Enduses::Vector{Int} = collect(Select(Enduse))
  Nation::SetArray = ReadDisk(db,"MainDB/NationKey")
  NationDS::SetArray = ReadDisk(db,"MainDB/NationDS")
  Nations::Vector{Int} = collect(Select(Nation))
  Tech::SetArray = ReadDisk(db,"$Input/TechKey")
  TechDS::SetArray = ReadDisk(db,"$Input/TechDS")
  Techs::Vector{Int} = collect(Select(Tech))
  Year::SetArray = ReadDisk(db,"MainDB/YearKey")
  YearDS::SetArray = ReadDisk(db,"MainDB/YearDS")
  Years::Vector{Int} = collect(Select(Year))

  MacroSwitch::Vector{String} = ReadDisk(db,"MInput/MacroSwitch") # [Nation] String Indicator of Macroeconomic Forecast (TOM,Stokes,AEO,CER)
  xDCC::VariableArray{5} = ReadDisk(db,"$Input/xDCC") # [Enduse,Tech,EC,Area,Year] Device Capital Cost ($/mmBtu/Yr)
  xInflation::VariableArray{2} = ReadDisk(db,"MInput/xInflation") # [Area,Year] Inflation Index ($/$)

  # Scratch Variables
  DCCAdjust::VariableArray{2} = zeros(Float32,length(EC),length(Area)) # [EC,Area] Device Capital Cost Adjustment ($/$)
end

function ICalibration(db)
  data = IControl(; db)
  (;Input) = data
  (;Area,AreaDS,Areas,EC,ECDS,ECs,Enduse,EnduseDS,Enduses,Nation) = data
  (;NationDS,Nations,Tech,TechDS,Techs,Year,YearDS,Years) = data
  (;MacroSwitch,xDCC,xInflation) = data
  (;DCCAdjust) = data

  areas=Select(Area,(from="ON", to="Pac"))

  ON=Select(Area,"ON")
  QC=Select(Area,"QC")
  BC=Select(Area,"BC")
  AB=Select(Area,"AB")
  MB=Select(Area,"MB")
  SK=Select(Area,"SK")
  NB=Select(Area,"NB")
  NS=Select(Area,"NS")
  NL=Select(Area,"NL")
  PE=Select(Area,"PE")
  YT=Select(Area,"YT")
  NT=Select(Area,"NT")
  NU=Select(Area,"NU")
  CA=Select(Area,"CA")
  NEng=Select(Area,"NEng")
  MAtl=Select(Area,"MAtl")
  ENC=Select(Area,"ENC")
  WNC=Select(Area,"WNC")
  SAtl=Select(Area,"SAtl")
  ESC=Select(Area,"ESC")
  WSC=Select(Area,"WSC")
  Mtn=Select(Area,"Mtn")
  Pac=Select(Area,"Pac")

  ecs1=Select(EC,(from="Food", to="NonMetalMining"))
  ecs2=Select(EC,(from="CoalMining", to="AnimalProduction"))
  ecs=union(ecs1,ecs2)

  Food=Select(EC,"Food")
  Textiles=Select(EC,"Textiles")
  Lumber=Select(EC,"Lumber")
  Furniture=Select(EC,"Furniture")
  PulpPaperMills=Select(EC,"PulpPaperMills")
  Petrochemicals=Select(EC,"Petrochemicals")
  IndustrialGas=Select(EC,"IndustrialGas")
  OtherChemicals=Select(EC,"OtherChemicals")
  Fertilizer=Select(EC,"Fertilizer")
  Petroleum=Select(EC,"Petroleum")
  Rubber=Select(EC,"Rubber")
  Cement=Select(EC,"Cement")
  Glass=Select(EC,"Glass")
  LimeGypsum=Select(EC,"LimeGypsum")
  OtherNonMetallic=Select(EC,"OtherNonMetallic")
  IronSteel=Select(EC,"IronSteel")
  Aluminum=Select(EC,"Aluminum")
  OtherNonferrous=Select(EC,"OtherNonferrous")
  TransportEquipment=Select(EC,"TransportEquipment")
  OtherManufacturing=Select(EC,"OtherManufacturing")
  IronOreMining=Select(EC,"IronOreMining")
  OtherMetalMining=Select(EC,"OtherMetalMining")
  NonMetalMining=Select(EC,"NonMetalMining")
  CoalMining=Select(EC,"CoalMining")
  Construction=Select(EC,"Construction")
  Forestry=Select(EC,"Forestry")
  OnFarmFuelUse=Select(EC,"OnFarmFuelUse")
  CropProduction=Select(EC,"CropProduction")
  AnimalProduction=Select(EC,"AnimalProduction")

  @. DCCAdjust = 1.0

  DCCAdjust[Food,ON]=3.4488
  DCCAdjust[Textiles,ON]=6.6313
  DCCAdjust[Lumber,ON]=1.2477
  DCCAdjust[Furniture,ON]=0.9597
  DCCAdjust[PulpPaperMills,ON]=1.6662
  DCCAdjust[Petrochemicals,ON]=1.8577
  DCCAdjust[IndustrialGas,ON]=10.8626
  DCCAdjust[OtherChemicals,ON]=0.5999
  DCCAdjust[Fertilizer,ON]=0.2889
  DCCAdjust[Petroleum,ON]=0.6685
  DCCAdjust[Rubber,ON]=3.8846
  DCCAdjust[Cement,ON]=2.2837
  DCCAdjust[Glass,ON]=10.1369
  DCCAdjust[LimeGypsum,ON]= 7.967
  DCCAdjust[OtherNonMetallic,ON]=6.5722
  DCCAdjust[IronSteel,ON]= 1.845
  DCCAdjust[Aluminum,ON]=0.7954
  DCCAdjust[OtherNonferrous,ON]=5.0148
  DCCAdjust[TransportEquipment,ON]=43.2762
  DCCAdjust[OtherManufacturing,ON]=2.2247
  DCCAdjust[IronOreMining,ON]=   1
  DCCAdjust[OtherMetalMining,ON]=3.5797
  DCCAdjust[NonMetalMining,ON]=8.0726
  DCCAdjust[CoalMining,ON]=   1
  DCCAdjust[Construction,ON]=13.5393
  DCCAdjust[Forestry,ON]=12.4674
  DCCAdjust[OnFarmFuelUse,ON]=3.3586
  DCCAdjust[CropProduction,ON]= 1
  DCCAdjust[AnimalProduction,ON]=1
  DCCAdjust[Food,QC]=4.3136
  DCCAdjust[Textiles,QC]=4.8521
  DCCAdjust[Lumber,QC]=3.2787
  DCCAdjust[Furniture,QC]=1.8397
  DCCAdjust[PulpPaperMills,QC]=0.9126
  DCCAdjust[Petrochemicals,QC]=6.9847
  DCCAdjust[IndustrialGas,QC]=14.8948
  DCCAdjust[OtherChemicals,QC]=0.5397
  DCCAdjust[Fertilizer,QC]=0.2344
  DCCAdjust[Petroleum,QC]=0.7531
  DCCAdjust[Rubber,QC]= 2.526
  DCCAdjust[Cement,QC]=0.9083
  DCCAdjust[Glass,QC]=10.9119
  DCCAdjust[LimeGypsum,QC]=6.2719
  DCCAdjust[OtherNonMetallic,QC]=4.5484
  DCCAdjust[IronSteel,QC]=7.5863
  DCCAdjust[Aluminum,QC]=0.8567
  DCCAdjust[OtherNonferrous,QC]=4.8697
  DCCAdjust[TransportEquipment,QC]=15.5944
  DCCAdjust[OtherManufacturing,QC]=3.2741
  DCCAdjust[IronOreMining,QC]=0.9222
  DCCAdjust[OtherMetalMining,QC]=1.0532
  DCCAdjust[NonMetalMining,QC]=1.4842
  DCCAdjust[CoalMining,QC]=   1
  DCCAdjust[Construction,QC]=21.4105
  DCCAdjust[Forestry,QC]=4.6041
  DCCAdjust[OnFarmFuelUse,QC]=4.2268
  DCCAdjust[CropProduction,QC]= 1
  DCCAdjust[AnimalProduction,QC]=1
  DCCAdjust[Food,BC]=15.8949
  DCCAdjust[Textiles,BC]=8.0062
  DCCAdjust[Lumber,BC]= 8.811
  DCCAdjust[Furniture,BC]=4.7891
  DCCAdjust[PulpPaperMills,BC]=2.6199
  DCCAdjust[Petrochemicals,BC]=4.5722
  DCCAdjust[IndustrialGas,BC]=5.6593
  DCCAdjust[OtherChemicals,BC]=0.1149
  DCCAdjust[Fertilizer,BC]=0.6468
  DCCAdjust[Petroleum,BC]=1.4684
  DCCAdjust[Rubber,BC]=3.9565
  DCCAdjust[Cement,BC]=3.2427
  DCCAdjust[Glass,BC]=18.4643
  DCCAdjust[LimeGypsum,BC]=7.2399
  DCCAdjust[OtherNonMetallic,BC]=10.229
  DCCAdjust[IronSteel,BC]=5.0963
  DCCAdjust[Aluminum,BC]=0.5634
  DCCAdjust[OtherNonferrous,BC]=1.4422
  DCCAdjust[TransportEquipment,BC]=32.8191
  DCCAdjust[OtherManufacturing,BC]=6.1648
  DCCAdjust[IronOreMining,BC]=   1
  DCCAdjust[OtherMetalMining,BC]=1.9351
  DCCAdjust[NonMetalMining,BC]=6.0416
  DCCAdjust[CoalMining,BC]=5.3327
  DCCAdjust[Construction,BC]=18.1584
  DCCAdjust[Forestry,BC]=9.4237
  DCCAdjust[OnFarmFuelUse,BC]=8.0962
  DCCAdjust[CropProduction,BC]= 1
  DCCAdjust[AnimalProduction,BC]=1
  DCCAdjust[Food,AB]=1.3358
  DCCAdjust[Textiles,AB]=0.8586
  DCCAdjust[Lumber,AB]=0.7492
  DCCAdjust[Furniture,AB]=0.7517
  DCCAdjust[PulpPaperMills,AB]=2.2065
  DCCAdjust[Petrochemicals,AB]=2.8502
  DCCAdjust[IndustrialGas,AB]=  4.55
  DCCAdjust[OtherChemicals,AB]=1.274
  DCCAdjust[Fertilizer,AB]=0.2383
  DCCAdjust[Petroleum,AB]=0.6245
  DCCAdjust[Rubber,AB]=0.9582
  DCCAdjust[Cement,AB]=1.8698
  DCCAdjust[Glass,AB]=6.1855
  DCCAdjust[LimeGypsum,AB]=4.9686
  DCCAdjust[OtherNonMetallic,AB]=1.4072
  DCCAdjust[IronSteel,AB]=20.0875
  DCCAdjust[Aluminum,AB]=0.0572
  DCCAdjust[OtherNonferrous,AB]=0.0746
  DCCAdjust[TransportEquipment,AB]=8.6007
  DCCAdjust[OtherManufacturing,AB]=1.2805
  DCCAdjust[IronOreMining,AB]=   1
  DCCAdjust[OtherMetalMining,AB]=   1
  DCCAdjust[NonMetalMining,AB]=1.3174
  DCCAdjust[CoalMining,AB]=3.9633
  DCCAdjust[Construction,AB]=28.162
  DCCAdjust[Forestry,AB]=0.8008
  DCCAdjust[OnFarmFuelUse,AB]=4.6975
  DCCAdjust[CropProduction,AB]= 1
  DCCAdjust[AnimalProduction,AB]=1
  DCCAdjust[Food,MB]=8.3062
  DCCAdjust[Textiles,MB]=2.0106
  DCCAdjust[Lumber,MB]=1.4129
  DCCAdjust[Furniture,MB]=7.4628
  DCCAdjust[PulpPaperMills,MB]=1.9652
  DCCAdjust[Petrochemicals,MB]=2.3375
  DCCAdjust[IndustrialGas,MB]= 1.761
  DCCAdjust[OtherChemicals,MB]=0.2822
  DCCAdjust[Fertilizer,MB]=0.5019
  DCCAdjust[Petroleum,MB]=  1.0
  DCCAdjust[Rubber,MB]=  2.71
  DCCAdjust[Cement,MB]=13.1241
  DCCAdjust[Glass,MB]=7.6899
  DCCAdjust[LimeGypsum,MB]=1.2765
  DCCAdjust[OtherNonMetallic,MB]=2.3457
  DCCAdjust[IronSteel,MB]=7.7937
  DCCAdjust[Aluminum,MB]=2.3806
  DCCAdjust[OtherNonferrous,MB]=0.3033
  DCCAdjust[TransportEquipment,MB]=8.8159
  DCCAdjust[OtherManufacturing,MB]=2.9197
  DCCAdjust[IronOreMining,MB]=   1
  DCCAdjust[OtherMetalMining,MB]=17.3655
  DCCAdjust[NonMetalMining,MB]=86.1644
  DCCAdjust[CoalMining,MB]=   1
  DCCAdjust[Construction,MB]=16.5906
  DCCAdjust[Forestry,MB]=4.4624
  DCCAdjust[OnFarmFuelUse,MB]=6.3082
  DCCAdjust[CropProduction,MB]= 1
  DCCAdjust[AnimalProduction,MB]=1
  DCCAdjust[Food,SK]=2.5491
  DCCAdjust[Textiles,SK]=2.3742
  DCCAdjust[Lumber,SK]=0.9002
  DCCAdjust[Furniture,SK]=2.7835
  DCCAdjust[PulpPaperMills,SK]=0.3641
  DCCAdjust[Petrochemicals,SK]=360.5328
  DCCAdjust[IndustrialGas,SK]=21.5483
  DCCAdjust[OtherChemicals,SK]=5.7377
  DCCAdjust[Fertilizer,SK]=7.0682
  DCCAdjust[Petroleum,SK]=0.4864
  DCCAdjust[Rubber,SK]=0.7133
  DCCAdjust[Cement,SK]=8.0152
  DCCAdjust[Glass,SK]=2.9372
  DCCAdjust[LimeGypsum,SK]=10.7989
  DCCAdjust[OtherNonMetallic,SK]=0.6107
  DCCAdjust[IronSteel,SK]=20.9207
  DCCAdjust[Aluminum,SK]=  1.0
  DCCAdjust[OtherNonferrous,SK]=   1
  DCCAdjust[TransportEquipment,SK]=1.9262
  DCCAdjust[OtherManufacturing,SK]=1.7054
  DCCAdjust[IronOreMining,SK]=   1
  DCCAdjust[OtherMetalMining,SK]=0.9382
  DCCAdjust[NonMetalMining,SK]=4.2126
  DCCAdjust[CoalMining,SK]= 2.486
  DCCAdjust[Construction,SK]=24.0061
  DCCAdjust[Forestry,SK]=9.0361
  DCCAdjust[OnFarmFuelUse,SK]=10.8921
  DCCAdjust[CropProduction,SK]= 1
  DCCAdjust[AnimalProduction,SK]=1
  DCCAdjust[Food,NB]= 5.648
  DCCAdjust[Textiles,NB]=13.5542
  DCCAdjust[Lumber,NB]=1.8395
  DCCAdjust[Furniture,NB]=3.3017
  DCCAdjust[PulpPaperMills,NB]=1.0394
  DCCAdjust[Petrochemicals,NB]=0.6293
  DCCAdjust[IndustrialGas,NB]=0.4797
  DCCAdjust[OtherChemicals,NB]=0.1244
  DCCAdjust[Fertilizer,NB]=0.6216
  DCCAdjust[Petroleum,NB]=1.7088
  DCCAdjust[Rubber,NB]=1.5563
  DCCAdjust[Cement,NB]=51.6379
  DCCAdjust[Glass,NB]=49.7767
  DCCAdjust[LimeGypsum,NB]=4.6422
  DCCAdjust[OtherNonMetallic,NB]=6.7598
  DCCAdjust[IronSteel,NB]=9.2504
  DCCAdjust[Aluminum,NB]=  1.0
  DCCAdjust[OtherNonferrous,NB]=10.636
  DCCAdjust[TransportEquipment,NB]=44.352
  DCCAdjust[OtherManufacturing,NB]=3.8165
  DCCAdjust[IronOreMining,NB]=   1
  DCCAdjust[OtherMetalMining,NB]=   1
  DCCAdjust[NonMetalMining,NB]=7.4683
  DCCAdjust[CoalMining,NB]=   1
  DCCAdjust[Construction,NB]=32.7318
  DCCAdjust[Forestry,NB]=9.5611
  DCCAdjust[OnFarmFuelUse,NB]=2.9797
  DCCAdjust[CropProduction,NB]= 1
  DCCAdjust[AnimalProduction,NB]=1
  DCCAdjust[Food,NS]=8.1734
  DCCAdjust[Textiles,NS]=13.7245
  DCCAdjust[Lumber,NS]=2.9664
  DCCAdjust[Furniture,NS]=2.1442
  DCCAdjust[PulpPaperMills,NS]=1.6861
  DCCAdjust[Petrochemicals,NS]=55.473
  DCCAdjust[IndustrialGas,NS]=49.1946
  DCCAdjust[OtherChemicals,NS]=0.7793
  DCCAdjust[Fertilizer,NS]= 1.809
  DCCAdjust[Petroleum,NS]=  1.0
  DCCAdjust[Rubber,NS]=2.1577
  DCCAdjust[Cement,NS]=4.0198
  DCCAdjust[Glass,NS]=22.0667
  DCCAdjust[LimeGypsum,NS]=136.0517
  DCCAdjust[OtherNonMetallic,NS]=1.2485
  DCCAdjust[IronSteel,NS]=0.0936
  DCCAdjust[Aluminum,NS]=  1.0
  DCCAdjust[OtherNonferrous,NS]=341.989
  DCCAdjust[TransportEquipment,NS]=15.2971
  DCCAdjust[OtherManufacturing,NS]=3.1727
  DCCAdjust[IronOreMining,NS]=   1
  DCCAdjust[OtherMetalMining,NS]=0.0795
  DCCAdjust[NonMetalMining,NS]=1.1655
  DCCAdjust[CoalMining,NS]=0.5023
  DCCAdjust[Construction,NS]=12.2099
  DCCAdjust[Forestry,NS]=2.0415
  DCCAdjust[OnFarmFuelUse,NS]=4.7524
  DCCAdjust[CropProduction,NS]= 1
  DCCAdjust[AnimalProduction,NS]=1
  DCCAdjust[Food,NL]=12.4116
  DCCAdjust[Textiles,NL]=   1
  DCCAdjust[Lumber,NL]=2.9244
  DCCAdjust[Furniture,NL]=0.2268
  DCCAdjust[PulpPaperMills,NL]= 0.833
  DCCAdjust[Petrochemicals,NL]=22.1502
  DCCAdjust[IndustrialGas,NL]=3.4482
  DCCAdjust[OtherChemicals,NL]=0.1299
  DCCAdjust[Fertilizer,NL]=   1
  DCCAdjust[Petroleum,NL]=1.9552
  DCCAdjust[Rubber,NL]=11.9275
  DCCAdjust[Cement,NL]=5.1892
  DCCAdjust[Glass,NL]=15.1227
  DCCAdjust[LimeGypsum,NL]=0.4934
  DCCAdjust[OtherNonMetallic,NL]= 1.096
  DCCAdjust[IronSteel,NL]=  300
  DCCAdjust[Aluminum,NL]=  1.0
  DCCAdjust[OtherNonferrous,NL]=1.2824
  DCCAdjust[TransportEquipment,NL]=13.7637
  DCCAdjust[OtherManufacturing,NL]=2.9097
  DCCAdjust[IronOreMining,NL]=  2.63
  DCCAdjust[OtherMetalMining,NL]= 0.078
  DCCAdjust[NonMetalMining,NL]=5.9736
  DCCAdjust[CoalMining,NL]=   1
  DCCAdjust[Construction,NL]=18.5652
  DCCAdjust[Forestry,NL]=0.6327
  DCCAdjust[OnFarmFuelUse,NL]=41.2863
  DCCAdjust[CropProduction,NL]= 1
  DCCAdjust[AnimalProduction,NL]=1
  DCCAdjust[Food,PE]=2.3218
  DCCAdjust[Textiles,PE]=   1
  DCCAdjust[Lumber,PE]=2.4889
  DCCAdjust[Furniture,PE]=2.3865
  DCCAdjust[PulpPaperMills,PE]=  1.0
  DCCAdjust[Petrochemicals,PE]=   1
  DCCAdjust[IndustrialGas,PE]=   1
  DCCAdjust[OtherChemicals,PE]=3.5407
  DCCAdjust[Fertilizer,PE]=2.7666
  DCCAdjust[Petroleum,PE]=   1
  DCCAdjust[Rubber,PE]=   1
  DCCAdjust[Cement,PE]=50.0038
  DCCAdjust[Glass,PE]=0.4777
  DCCAdjust[LimeGypsum,PE]=144.2492
  DCCAdjust[OtherNonMetallic,PE]=0.8723
  DCCAdjust[IronSteel,PE]=15.1859
  DCCAdjust[Aluminum,PE]=  1.0
  DCCAdjust[OtherNonferrous,PE]=  1.0
  DCCAdjust[TransportEquipment,PE]=0.8825
  DCCAdjust[OtherManufacturing,PE]=3.9048
  DCCAdjust[IronOreMining,PE]=   1
  DCCAdjust[OtherMetalMining,PE]=   1
  DCCAdjust[NonMetalMining,PE]=80.2296
  DCCAdjust[CoalMining,PE]=   1
  DCCAdjust[Construction,PE]=10.0229
  DCCAdjust[Forestry,PE]=   1
  DCCAdjust[OnFarmFuelUse,PE]=7.0736
  DCCAdjust[CropProduction,PE]= 1
  DCCAdjust[AnimalProduction,PE]=1
  DCCAdjust[Food,YT]=12.5535
  DCCAdjust[Textiles,YT]=   1
  DCCAdjust[Lumber,YT]=   1
  DCCAdjust[Furniture,YT]=   1
  DCCAdjust[PulpPaperMills,YT]=   1
  DCCAdjust[Petrochemicals,YT]=   1
  DCCAdjust[IndustrialGas,YT]=   1
  DCCAdjust[OtherChemicals,YT]=0.0771
  DCCAdjust[Fertilizer,YT]=   1
  DCCAdjust[Petroleum,YT]=   1
  DCCAdjust[Rubber,YT]=1.2322
  DCCAdjust[Cement,YT]=   1
  DCCAdjust[Glass,YT]=  1.0
  DCCAdjust[LimeGypsum,YT]=  1.0
  DCCAdjust[OtherNonMetallic,YT]=  1.0
  DCCAdjust[IronSteel,YT]=  1.0
  DCCAdjust[Aluminum,YT]=  1.0
  DCCAdjust[OtherNonferrous,YT]=  1.0
  DCCAdjust[TransportEquipment,YT]=   1
  DCCAdjust[OtherManufacturing,YT]=21.5421
  DCCAdjust[IronOreMining,YT]=   1
  DCCAdjust[OtherMetalMining,YT]=0.6212
  DCCAdjust[NonMetalMining,YT]=5.2009
  DCCAdjust[CoalMining,YT]=   1
  DCCAdjust[Construction,YT]=17.3771
  DCCAdjust[Forestry,YT]=   1
  DCCAdjust[OnFarmFuelUse,YT]=   1
  DCCAdjust[CropProduction,YT]= 1
  DCCAdjust[AnimalProduction,YT]=1
  DCCAdjust[Food,NT]=   1
  DCCAdjust[Textiles,NT]=   1
  DCCAdjust[Lumber,NT]=   1
  DCCAdjust[Furniture,NT]=   1
  DCCAdjust[PulpPaperMills,NT]=   1
  DCCAdjust[Petrochemicals,NT]=   1
  DCCAdjust[IndustrialGas,NT]=   1
  DCCAdjust[OtherChemicals,NT]=   1
  DCCAdjust[Fertilizer,NT]=   1
  DCCAdjust[Petroleum,NT]=   1
  DCCAdjust[Rubber,NT]=   1
  DCCAdjust[Cement,NT]=   1
  DCCAdjust[Glass,NT]=   1
  DCCAdjust[LimeGypsum,NT]=   1
  DCCAdjust[OtherNonMetallic,NT]=   1
  DCCAdjust[IronSteel,NT]=  1.0
  DCCAdjust[Aluminum,NT]=  1.0
  DCCAdjust[OtherNonferrous,NT]=  1.0
  DCCAdjust[TransportEquipment,NT]=   1
  DCCAdjust[OtherManufacturing,NT]=   1
  DCCAdjust[IronOreMining,NT]=   1
  DCCAdjust[OtherMetalMining,NT]=0.0419
  DCCAdjust[NonMetalMining,NT]=5.0759
  DCCAdjust[CoalMining,NT]=   1
  DCCAdjust[Construction,NT]=197.3428
  DCCAdjust[Forestry,NT]=   1
  DCCAdjust[OnFarmFuelUse,NT]=   1
  DCCAdjust[CropProduction,NT]= 1
  DCCAdjust[AnimalProduction,NT]=1
  DCCAdjust[Food,NU]=   1
  DCCAdjust[Textiles,NU]=   1
  DCCAdjust[Lumber,NU]=   1
  DCCAdjust[Furniture,NU]=   1
  DCCAdjust[PulpPaperMills,NU]=   1
  DCCAdjust[Petrochemicals,NU]=  1.0
  DCCAdjust[IndustrialGas,NU]=  1.0
  DCCAdjust[OtherChemicals,NU]=  198
  DCCAdjust[Fertilizer,NU]=   1
  DCCAdjust[Petroleum,NU]=   1
  DCCAdjust[Rubber,NU]=   1
  DCCAdjust[Cement,NU]=   1
  DCCAdjust[Glass,NU]=  1.0
  DCCAdjust[LimeGypsum,NU]=  1.0
  DCCAdjust[OtherNonMetallic,NU]=  1.0
  DCCAdjust[IronSteel,NU]=  1.0
  DCCAdjust[Aluminum,NU]=  1.0
  DCCAdjust[OtherNonferrous,NU]=  1.0
  DCCAdjust[TransportEquipment,NU]=   1
  DCCAdjust[OtherManufacturing,NU]=   1
  DCCAdjust[IronOreMining,NU]=0.2466
  # DCCAdjust[OtherMetalMining,NU]=0.00104 Removed by Ian 08/24/25
  DCCAdjust[NonMetalMining,NU]=   1
  DCCAdjust[CoalMining,NU]=   1
  DCCAdjust[Construction,NU]=0.5722
  DCCAdjust[Forestry,NU]=   1
  DCCAdjust[OnFarmFuelUse,NU]=   1
  DCCAdjust[CropProduction,NU]= 1
  DCCAdjust[AnimalProduction,NU]=1
  DCCAdjust[Food,CA]= 10.82
  DCCAdjust[Textiles,CA]=   1
  DCCAdjust[Lumber,CA]=25.1756
  DCCAdjust[Furniture,CA]=   1
  DCCAdjust[PulpPaperMills,CA]=6.8841
  DCCAdjust[Petrochemicals,CA]=3.5847
  DCCAdjust[IndustrialGas,CA]=   1
  DCCAdjust[OtherChemicals,CA]=44.2229
  DCCAdjust[Fertilizer,CA]=47.8878
  DCCAdjust[Petroleum,CA]=13.9397
  DCCAdjust[Rubber,CA]=46.3925
  DCCAdjust[Cement,CA]=1.1257
  DCCAdjust[Glass,CA]=91.1023
  DCCAdjust[LimeGypsum,CA]=   1
  DCCAdjust[OtherNonMetallic,CA]=   1
  DCCAdjust[IronSteel,CA]=3.9427
  DCCAdjust[Aluminum,CA]=16.4913
  DCCAdjust[OtherNonferrous,CA]=   1
  DCCAdjust[TransportEquipment,CA]=25.2647
  DCCAdjust[OtherManufacturing,CA]=35.0264
  DCCAdjust[IronOreMining,CA]=   1
  DCCAdjust[OtherMetalMining,CA]=   1
  DCCAdjust[NonMetalMining,CA]=13.8599
  DCCAdjust[CoalMining,CA]=   1
  DCCAdjust[Construction,CA]=9.7946
  DCCAdjust[Forestry,CA]=   1
  DCCAdjust[OnFarmFuelUse,CA]=13.4445
  DCCAdjust[CropProduction,CA]= 1
  DCCAdjust[AnimalProduction,CA]=1
  DCCAdjust[Food,NEng]=9.7538
  DCCAdjust[Textiles,NEng]=   1
  DCCAdjust[Lumber,NEng]=0.6008
  DCCAdjust[Furniture,NEng]=   1
  DCCAdjust[PulpPaperMills,NEng]= 9.889
  DCCAdjust[Petrochemicals,NEng]=0.0064
  DCCAdjust[IndustrialGas,NEng]=   1
  DCCAdjust[OtherChemicals,NEng]=73.9274
  DCCAdjust[Fertilizer,NEng]=34.4858
  DCCAdjust[Petroleum,NEng]=6.4071
  DCCAdjust[Rubber,NEng]=56.3569
  DCCAdjust[Cement,NEng]=3.5939
  DCCAdjust[Glass,NEng]=290.5036
  DCCAdjust[LimeGypsum,NEng]=   1
  DCCAdjust[OtherNonMetallic,NEng]=   1
  DCCAdjust[IronSteel,NEng]=1.2913
  DCCAdjust[Aluminum,NEng]=29.9148
  DCCAdjust[OtherNonferrous,NEng]=   1
  DCCAdjust[TransportEquipment,NEng]=32.5645
  DCCAdjust[OtherManufacturing,NEng]=98.0934
  DCCAdjust[IronOreMining,NEng]=   1
  DCCAdjust[OtherMetalMining,NEng]=   1
  DCCAdjust[NonMetalMining,NEng]=1.2175
  DCCAdjust[CoalMining,NEng]=   1
  DCCAdjust[Construction,NEng]=8.6252
  DCCAdjust[Forestry,NEng]=3.4779
  DCCAdjust[OnFarmFuelUse,NEng]= 4.183
  DCCAdjust[CropProduction,NEng]= 1
  DCCAdjust[AnimalProduction,NEng]=1
  DCCAdjust[Food,MAtl]=14.3037
  DCCAdjust[Textiles,MAtl]=   1
  DCCAdjust[Lumber,MAtl]=1.5279
  DCCAdjust[Furniture,MAtl]=   1
  DCCAdjust[PulpPaperMills,MAtl]=11.8199
  DCCAdjust[Petrochemicals,MAtl]=2.0946
  DCCAdjust[IndustrialGas,MAtl]=   1
  DCCAdjust[OtherChemicals,MAtl]=13.2912
  DCCAdjust[Fertilizer,MAtl]=54.4701
  DCCAdjust[Petroleum,MAtl]=9.9317
  DCCAdjust[Rubber,MAtl]=44.9453
  DCCAdjust[Cement,MAtl]=1.1944
  DCCAdjust[Glass,MAtl]=94.4909
  DCCAdjust[LimeGypsum,MAtl]=   1
  DCCAdjust[OtherNonMetallic,MAtl]=   1
  DCCAdjust[IronSteel,MAtl]=0.3116
  DCCAdjust[Aluminum,MAtl]=20.6052
  DCCAdjust[OtherNonferrous,MAtl]=   1
  DCCAdjust[TransportEquipment,MAtl]=50.3986
  DCCAdjust[OtherManufacturing,MAtl]=60.9213
  DCCAdjust[IronOreMining,MAtl]=   1
  DCCAdjust[OtherMetalMining,MAtl]=   1
  DCCAdjust[NonMetalMining,MAtl]= 0.024
  DCCAdjust[CoalMining,MAtl]=77.2668
  DCCAdjust[Construction,MAtl]=11.169
  DCCAdjust[Forestry,MAtl]=8.6674
  DCCAdjust[OnFarmFuelUse,MAtl]=22.5543
  DCCAdjust[CropProduction,MAtl]= 1
  DCCAdjust[AnimalProduction,MAtl]=1
  DCCAdjust[Food,ENC]= 8.926
  DCCAdjust[Textiles,ENC]=   1
  DCCAdjust[Lumber,ENC]=1.9695
  DCCAdjust[Furniture,ENC]=   1
  DCCAdjust[PulpPaperMills,ENC]=7.8294
  DCCAdjust[Petrochemicals,ENC]=1.6542
  DCCAdjust[IndustrialGas,ENC]=   1
  DCCAdjust[OtherChemicals,ENC]=10.3096
  DCCAdjust[Fertilizer,ENC]=45.4063
  DCCAdjust[Petroleum,ENC]=0.9876
  DCCAdjust[Rubber,ENC]=61.2047
  DCCAdjust[Cement,ENC]=1.9008
  DCCAdjust[Glass,ENC]=52.529
  DCCAdjust[LimeGypsum,ENC]=   1
  DCCAdjust[OtherNonMetallic,ENC]=   1
  DCCAdjust[IronSteel,ENC]=0.5265
  DCCAdjust[Aluminum,ENC]=17.4548
  DCCAdjust[OtherNonferrous,ENC]=   1
  DCCAdjust[TransportEquipment,ENC]=23.6353
  DCCAdjust[OtherManufacturing,ENC]=63.1011
  DCCAdjust[IronOreMining,ENC]=   1
  DCCAdjust[OtherMetalMining,ENC]=   1
  DCCAdjust[NonMetalMining,ENC]=0.2761
  DCCAdjust[CoalMining,ENC]=19.479
  DCCAdjust[Construction,ENC]=15.2027
  DCCAdjust[Forestry,ENC]=4.5777
  DCCAdjust[OnFarmFuelUse,ENC]=164.9795
  DCCAdjust[CropProduction,ENC]= 1
  DCCAdjust[AnimalProduction,ENC]=1
  DCCAdjust[Food,WNC]=7.4817
  DCCAdjust[Textiles,WNC]=   1
  DCCAdjust[Lumber,WNC]=0.7735
  DCCAdjust[Furniture,WNC]=   1
  DCCAdjust[PulpPaperMills,WNC]=5.7703
  DCCAdjust[Petrochemicals,WNC]= 6.969
  DCCAdjust[IndustrialGas,WNC]=   1
  DCCAdjust[OtherChemicals,WNC]=54.6819
  DCCAdjust[Fertilizer,WNC]=1.1546
  DCCAdjust[Petroleum,WNC]= 1.763
  DCCAdjust[Rubber,WNC]=33.9273
  DCCAdjust[Cement,WNC]=0.5251
  DCCAdjust[Glass,WNC]=71.6446
  DCCAdjust[LimeGypsum,WNC]=   1
  DCCAdjust[OtherNonMetallic,WNC]=   1
  DCCAdjust[IronSteel,WNC]= 1.735
  DCCAdjust[Aluminum,WNC]=5.6959
  DCCAdjust[OtherNonferrous,WNC]=   1
  DCCAdjust[TransportEquipment,WNC]=12.0934
  DCCAdjust[OtherManufacturing,WNC]=35.494
  DCCAdjust[IronOreMining,WNC]=   1
  DCCAdjust[OtherMetalMining,WNC]=   1
  DCCAdjust[NonMetalMining,WNC]=   1
  DCCAdjust[CoalMining,WNC]=435.6491
  DCCAdjust[Construction,WNC]=  9.18
  DCCAdjust[Forestry,WNC]=0.3132
  DCCAdjust[OnFarmFuelUse,WNC]=58.8663
  DCCAdjust[CropProduction,WNC]= 1
  DCCAdjust[AnimalProduction,WNC]=1
  DCCAdjust[Food,SAtl]= 8.738
  DCCAdjust[Textiles,SAtl]=   1
  DCCAdjust[Lumber,SAtl]=1.3321
  DCCAdjust[Furniture,SAtl]=   1
  DCCAdjust[PulpPaperMills,SAtl]=  8.88
  DCCAdjust[Petrochemicals,SAtl]=0.1355
  DCCAdjust[IndustrialGas,SAtl]=   1
  DCCAdjust[OtherChemicals,SAtl]=2.3898
  DCCAdjust[Fertilizer,SAtl]=11.1974
  DCCAdjust[Petroleum,SAtl]=6.6846
  DCCAdjust[Rubber,SAtl]=30.628
  DCCAdjust[Cement,SAtl]=1.2511
  DCCAdjust[Glass,SAtl]=64.3134
  DCCAdjust[LimeGypsum,SAtl]=   1
  DCCAdjust[OtherNonMetallic,SAtl]=   1
  DCCAdjust[IronSteel,SAtl]=0.2602
  DCCAdjust[Aluminum,SAtl]=10.0956
  DCCAdjust[OtherNonferrous,SAtl]=   1
  DCCAdjust[TransportEquipment,SAtl]=35.3081
  DCCAdjust[OtherManufacturing,SAtl]=29.7076
  DCCAdjust[IronOreMining,SAtl]=   1
  DCCAdjust[OtherMetalMining,SAtl]=   1
  DCCAdjust[NonMetalMining,SAtl]=0.0017
  DCCAdjust[CoalMining,SAtl]=14.5036
  DCCAdjust[Construction,SAtl]=8.2801
  DCCAdjust[Forestry,SAtl]= 6.567
  DCCAdjust[OnFarmFuelUse,SAtl]=76.8116
  DCCAdjust[CropProduction,SAtl]= 1
  DCCAdjust[AnimalProduction,SAtl]=1
  DCCAdjust[Food,ESC]=15.2248
  DCCAdjust[Textiles,ESC]=   1
  DCCAdjust[Lumber,ESC]=2.6924
  DCCAdjust[Furniture,ESC]=   1
  DCCAdjust[PulpPaperMills,ESC]=4.1005
  DCCAdjust[Petrochemicals,ESC]=0.0079
  DCCAdjust[IndustrialGas,ESC]=   1
  DCCAdjust[OtherChemicals,ESC]=1.9648
  DCCAdjust[Fertilizer,ESC]=12.2826
  DCCAdjust[Petroleum,ESC]=1.7837
  DCCAdjust[Rubber,ESC]=38.2835
  DCCAdjust[Cement,ESC]=1.0655
  DCCAdjust[Glass,ESC]=68.9114
  DCCAdjust[LimeGypsum,ESC]=   1
  DCCAdjust[OtherNonMetallic,ESC]=   1
  DCCAdjust[IronSteel,ESC]=0.8804
  DCCAdjust[Aluminum,ESC]=5.3842
  DCCAdjust[OtherNonferrous,ESC]=   1
  DCCAdjust[TransportEquipment,ESC]=53.8753
  DCCAdjust[OtherManufacturing,ESC]=32.818
  DCCAdjust[IronOreMining,ESC]=   1
  DCCAdjust[OtherMetalMining,ESC]=   1
  DCCAdjust[NonMetalMining,ESC]=0.0047
  DCCAdjust[CoalMining,ESC]=23.5903
  DCCAdjust[Construction,ESC]=12.4364
  DCCAdjust[Forestry,ESC]=62.8039
  DCCAdjust[OnFarmFuelUse,ESC]=108.7927
  DCCAdjust[CropProduction,ESC]= 1
  DCCAdjust[AnimalProduction,ESC]=1
  DCCAdjust[Food,WSC]=4.0141
  DCCAdjust[Textiles,WSC]=   1
  DCCAdjust[Lumber,WSC]=2.0978
  DCCAdjust[Furniture,WSC]=   1
  DCCAdjust[PulpPaperMills,WSC]=3.7135
  DCCAdjust[Petrochemicals,WSC]=13.6742
  DCCAdjust[IndustrialGas,WSC]=   1
  DCCAdjust[OtherChemicals,WSC]=2.5896
  DCCAdjust[Fertilizer,WSC]=4.6543
  DCCAdjust[Petroleum,WSC]=0.9796
  DCCAdjust[Rubber,WSC]=18.3588
  DCCAdjust[Cement,WSC]= 1.547
  DCCAdjust[Glass,WSC]=32.3283
  DCCAdjust[LimeGypsum,WSC]=   1
  DCCAdjust[OtherNonMetallic,WSC]=   1
  DCCAdjust[IronSteel,WSC]=0.4848
  DCCAdjust[Aluminum,WSC]=6.8802
  DCCAdjust[OtherNonferrous,WSC]=   1
  DCCAdjust[TransportEquipment,WSC]=18.4103
  DCCAdjust[OtherManufacturing,WSC]=21.1388
  DCCAdjust[IronOreMining,WSC]=   1
  DCCAdjust[OtherMetalMining,WSC]=   1
  DCCAdjust[NonMetalMining,WSC]=0.0348
  DCCAdjust[CoalMining,WSC]=299.2823
  DCCAdjust[Construction,WSC]=4.8001
  DCCAdjust[Forestry,WSC]=7.4646
  DCCAdjust[OnFarmFuelUse,WSC]=26.8825
  DCCAdjust[CropProduction,WSC]= 1
  DCCAdjust[AnimalProduction,WSC]=1
  DCCAdjust[Food,Mtn]= 7.492
  DCCAdjust[Textiles,Mtn]=   1
  DCCAdjust[Lumber,Mtn]=2.8832
  DCCAdjust[Furniture,Mtn]=   1
  DCCAdjust[PulpPaperMills,Mtn]=7.6511
  DCCAdjust[Petrochemicals,Mtn]=2.5241
  DCCAdjust[IndustrialGas,Mtn]=   1
  DCCAdjust[OtherChemicals,Mtn]=32.9313
  DCCAdjust[Fertilizer,Mtn]=0.5093
  DCCAdjust[Petroleum,Mtn]=4.2955
  DCCAdjust[Rubber,Mtn]=34.5496
  DCCAdjust[Cement,Mtn]=0.6133
  DCCAdjust[Glass,Mtn]=58.9656
  DCCAdjust[LimeGypsum,Mtn]=   1
  DCCAdjust[OtherNonMetallic,Mtn]=   1
  DCCAdjust[IronSteel,Mtn]=0.7974
  DCCAdjust[Aluminum,Mtn]=7.6426
  DCCAdjust[OtherNonferrous,Mtn]=   1
  DCCAdjust[TransportEquipment,Mtn]=40.7307
  DCCAdjust[OtherManufacturing,Mtn]=54.1032
  DCCAdjust[IronOreMining,Mtn]=   1
  DCCAdjust[OtherMetalMining,Mtn]=   1
  DCCAdjust[NonMetalMining,Mtn]=0.2105
  DCCAdjust[CoalMining,Mtn]=113.5597
  DCCAdjust[Construction,Mtn]=11.4059
  DCCAdjust[Forestry,Mtn]=2.5923
  DCCAdjust[OnFarmFuelUse,Mtn]=19.5611
  DCCAdjust[CropProduction,Mtn]= 1
  DCCAdjust[AnimalProduction,Mtn]=1
  DCCAdjust[Food,Pac]=6.1326
  DCCAdjust[Textiles,Pac]=   1
  DCCAdjust[Lumber,Pac]=2.1492
  DCCAdjust[Furniture,Pac]=   1
  DCCAdjust[PulpPaperMills,Pac]=10.8687
  DCCAdjust[Petrochemicals,Pac]=23.8653
  DCCAdjust[IndustrialGas,Pac]=   1
  DCCAdjust[OtherChemicals,Pac]=26.3471
  DCCAdjust[Fertilizer,Pac]=27.8209
  DCCAdjust[Petroleum,Pac]=2.7379
  DCCAdjust[Rubber,Pac]=35.6354
  DCCAdjust[Cement,Pac]=1.4943
  DCCAdjust[Glass,Pac]=63.1706
  DCCAdjust[LimeGypsum,Pac]=   1
  DCCAdjust[OtherNonMetallic,Pac]=   1
  DCCAdjust[IronSteel,Pac]=1.2318
  DCCAdjust[Aluminum,Pac]=3.3898
  DCCAdjust[OtherNonferrous,Pac]=   1
  DCCAdjust[TransportEquipment,Pac]=1252.575
  DCCAdjust[OtherManufacturing,Pac]=41.7462
  DCCAdjust[IronOreMining,Pac]=   1
  DCCAdjust[OtherMetalMining,Pac]=   1
  DCCAdjust[NonMetalMining,Pac]=1.7352
  DCCAdjust[CoalMining,Pac]=   1
  DCCAdjust[Construction,Pac]=21.4226
  DCCAdjust[Forestry,Pac]=2.5247
  DCCAdjust[OnFarmFuelUse,Pac]=13.0413
  DCCAdjust[CropProduction,Pac]= 1
  DCCAdjust[AnimalProduction,Pac]=1
  
  CN=Select(Nation,"CN")
  if MacroSwitch[CN] == "TOM"
    for year in Years, area in areas, ec in ecs, tech in Techs, enduse in Enduses
      if xDCC[enduse,tech,ec,area,year] != -99
        xDCC[enduse,tech,ec,area,year]=xDCC[enduse,tech,ec,area,year]*DCCAdjust[ec,area]
      end
    end
    WriteDisk(db,"$Input/xDCC",xDCC)
  end

end

function CalibrationControl(db)
  @info "AdjustDeviceCapitalCosts_TOM.jl - CalibrationControl"

  CCalibration(db)
  ICalibration(db)

end

if abspath(PROGRAM_FILE) == @__FILE__
  CalibrationControl(DB)
end

end
