#
# AdjustProcessCapitalCosts_TOM.jl
#
using EnergyModel

module AdjustProcessCapitalCosts_TOM

import ...EnergyModel: ReadDisk,WriteDisk,Select
import ...EnergyModel: HisTime,ITime,MaxTime,First,Future,Final,Yr
import ...EnergyModel: @finite_math,finite_inverse,finite_divide,finite_power,finite_exp,finite_log
import ...EnergyModel: DB

const VariableArray{N} = Array{Float32,N} where {N}
const SetArray = Vector{String}

Base.@kwdef struct CControl
  db::String

  CalDB::String = "CCalDB"
  Input::String = "CInput"
  Outpt::String = "COutput"
  BCNameDB::String = ReadDisk(db,"MainDB/BCNameDB") # Base Case Name

  Area::SetArray = ReadDisk(db,"MainDB/AreaKey")
  AreaDS::SetArray = ReadDisk(db,"MainDB/AreaDS")
  Areas::Vector{Int} = collect(Select(Area))
  EC::SetArray = ReadDisk(db,"$Input/ECKey")
  ECDS::SetArray = ReadDisk(db,"$Input/ECDS")
  ECs::Vector{Int} = collect(Select(EC))
  Enduse::SetArray = ReadDisk(db,"$Input/EnduseKey")
  EnduseDS::SetArray = ReadDisk(db,"$Input/EnduseDS")
  Enduses::Vector{Int} = collect(Select(Enduse))
  Nation::SetArray = ReadDisk(db,"MainDB/NationKey")
  NationDS::SetArray = ReadDisk(db,"MainDB/NationDS")
  Nations::Vector{Int} = collect(Select(Nation))
  Tech::SetArray = ReadDisk(db,"$Input/TechKey")
  TechDS::SetArray = ReadDisk(db,"$Input/TechDS")
  Techs::Vector{Int} = collect(Select(Tech))
  Year::SetArray = ReadDisk(db,"MainDB/YearKey")
  YearDS::SetArray = ReadDisk(db,"MainDB/YearDS")
  Years::Vector{Int} = collect(Select(Year))

  MacroSwitch::Vector{String} = ReadDisk(db,"MInput/MacroSwitch") # [Nation] String Indicator of Macroeconomic Forecast (TOM,Stokes,AEO,CER)
  xInflation::VariableArray{2} = ReadDisk(db,"MInput/xInflation") # [Area,Year] Inflation Index ($/$)
  xPCC::VariableArray{5} = ReadDisk(db,"$Input/xPCC") # [Enduse,Tech,EC,Area,Year] Process Capital Cost ($/Driver/Yr)

  # Scratch Variables
  PCCAdjust::VariableArray{2} = zeros(Float32,length(EC),length(Area)) # [EC,Area] Process Capital Cost Adjustment ($/$)
end

function CCalibration(db)
  data = CControl(; db)
  (;Input) = data
  (;Area,AreaDS,Areas,EC,ECDS,ECs,Enduse,EnduseDS,Enduses,Nation) = data
  (;NationDS,Nations,Tech,TechDS,Techs,Year,YearDS,Years) = data
  (;MacroSwitch,xInflation,xPCC) = data
  (;PCCAdjust) = data
  #
  # Adjust capital costs to align process investments to TOM's construction plus M&E in year 2024
  # Based on September 2024 Walnut version of model. 09/21/24 R.Levesque
  #
  
  areas=Select(Area,(from="ON", to="Pac"))

  ON=Select(Area,"ON")
  QC=Select(Area,"QC")
  BC=Select(Area,"BC")
  AB=Select(Area,"AB")
  MB=Select(Area,"MB")
  SK=Select(Area,"SK")
  NB=Select(Area,"NB")
  NS=Select(Area,"NS")
  NL=Select(Area,"NL")
  PE=Select(Area,"PE")
  YT=Select(Area,"YT")
  NT=Select(Area,"NT")
  NU=Select(Area,"NU")
  CA=Select(Area,"CA")
  NEng=Select(Area,"NEng")
  MAtl=Select(Area,"MAtl")
  ENC=Select(Area,"ENC")
  WNC=Select(Area,"WNC")
  SAtl=Select(Area,"SAtl")
  ESC=Select(Area,"ESC")
  WSC=Select(Area,"WSC")
  Mtn=Select(Area,"Mtn")
  Pac=Select(Area,"Pac")

  ecs=Select(EC,(from="Wholesale", to="NGPipeline"))

  Wholesale=Select(EC,"Wholesale")
  Retail=Select(EC,"Retail")
  Warehouse=Select(EC,"Warehouse")
  Information=Select(EC,"Information")
  Offices=Select(EC,"Offices")
  Education=Select(EC,"Education")
  Health=Select(EC,"Health")
  OtherCommercial=Select(EC,"OtherCommercial")
  NGDistribution=Select(EC,"NGDistribution")
  OilPipeline=Select(EC,"OilPipeline")
  NGPipeline=Select(EC,"NGPipeline")
  
  @. PCCAdjust = 1.0

  PCCAdjust[Wholesale,ON]=3.3496
  PCCAdjust[Retail,ON]=1.0854
  PCCAdjust[Warehouse,ON]=2.8408
  PCCAdjust[Information,ON]=581.5277
  PCCAdjust[Offices,ON]=10.9663
  PCCAdjust[Education,ON]=9.1737
  PCCAdjust[Health,ON]=5.4505
  PCCAdjust[OtherCommercial,ON]=2.1099
  PCCAdjust[NGDistribution,ON]=1
  PCCAdjust[OilPipeline,ON]=1
  PCCAdjust[NGPipeline,ON]=1
  PCCAdjust[Wholesale,QC]=3.9802
  PCCAdjust[Retail,QC]=1.2703
  PCCAdjust[Warehouse,QC]=1.0121
  PCCAdjust[Information,QC]=1192.572
  PCCAdjust[Offices,QC]=17.0305
  PCCAdjust[Education,QC]=23.4852
  PCCAdjust[Health,QC]=10.1862
  PCCAdjust[OtherCommercial,QC]=1.9118
  PCCAdjust[NGDistribution,QC]=1
  PCCAdjust[OilPipeline,QC]=1
  PCCAdjust[NGPipeline,QC]=1
  PCCAdjust[Wholesale,BC]=2.2894
  PCCAdjust[Retail,BC]=1.0002
  PCCAdjust[Warehouse,BC]=2.633
  PCCAdjust[Information,BC]=66.5141
  PCCAdjust[Offices,BC]=22.2075
  PCCAdjust[Education,BC]=19.6677
  PCCAdjust[Health,BC]=20.5553
  PCCAdjust[OtherCommercial,BC]=1.947
  PCCAdjust[NGDistribution,BC]=1
  PCCAdjust[OilPipeline,BC]=1
  PCCAdjust[NGPipeline,BC]=1
  PCCAdjust[Wholesale,AB]=5.7984
  PCCAdjust[Retail,AB]=1.3878
  PCCAdjust[Warehouse,AB]=2.9398
  PCCAdjust[Information,AB]=22.8127
  PCCAdjust[Offices,AB]=15.8424
  PCCAdjust[Education,AB]=13.6049
  PCCAdjust[Health,AB]=11.4115
  PCCAdjust[OtherCommercial,AB]=2.1972
  PCCAdjust[NGDistribution,AB]=1
  PCCAdjust[OilPipeline,AB]=1
  PCCAdjust[NGPipeline,AB]=1
  PCCAdjust[Wholesale,MB]=5.2703
  PCCAdjust[Retail,MB]=2.4937
  PCCAdjust[Warehouse,MB]=0.8224
  PCCAdjust[Information,MB]=44.2514
  PCCAdjust[Offices,MB]=11.35
  PCCAdjust[Education,MB]=4.6645
  PCCAdjust[Health,MB]=2.9488
  PCCAdjust[OtherCommercial,MB]=1.4286
  PCCAdjust[NGDistribution,MB]=1
  PCCAdjust[OilPipeline,MB]=1
  PCCAdjust[NGPipeline,MB]=1
  PCCAdjust[Wholesale,SK]=10.5581
  PCCAdjust[Retail,SK]=2.387
  PCCAdjust[Warehouse,SK]=0.2623
  PCCAdjust[Information,SK]=684.233
  PCCAdjust[Offices,SK]=21.4771
  PCCAdjust[Education,SK]=24.3929
  PCCAdjust[Health,SK]=4.9647
  PCCAdjust[OtherCommercial,SK]=2.1259
  PCCAdjust[NGDistribution,SK]=1
  PCCAdjust[OilPipeline,SK]=1
  PCCAdjust[NGPipeline,SK]=1
  PCCAdjust[Wholesale,NB]=2.4122
  PCCAdjust[Retail,NB]=0.9661
  PCCAdjust[Warehouse,NB]=0.3703
  PCCAdjust[Information,NB]=659.72
  PCCAdjust[Offices,NB]=16.9918
  PCCAdjust[Education,NB]=10.2695
  PCCAdjust[Health,NB]=15.7327
  PCCAdjust[OtherCommercial,NB]=1.325
  PCCAdjust[NGDistribution,NB]=1
  PCCAdjust[OilPipeline,NB]=1
  PCCAdjust[NGPipeline,NB]=1
  PCCAdjust[Wholesale,NS]=1.8217
  PCCAdjust[Retail,NS]=1.0283
  PCCAdjust[Warehouse,NS]=0.3565
  PCCAdjust[Information,NS]=365.4763
  PCCAdjust[Offices,NS]=21.5722
  PCCAdjust[Education,NS]=19.0925
  PCCAdjust[Health,NS]=17.0043
  PCCAdjust[OtherCommercial,NS]=1.6232
  PCCAdjust[NGDistribution,NS]=1
  PCCAdjust[OilPipeline,NS]=1
  PCCAdjust[NGPipeline,NS]=1
  PCCAdjust[Wholesale,NL]=1.7694
  PCCAdjust[Retail,NL]=1.0538
  PCCAdjust[Warehouse,NL]=0.4156
  PCCAdjust[Information,NL]=113.7998
  PCCAdjust[Offices,NL]=9.6743
  PCCAdjust[Education,NL]=24.1644
  PCCAdjust[Health,NL]=32.0593
  PCCAdjust[OtherCommercial,NL]=1.4717
  PCCAdjust[NGDistribution,NL]=1
  PCCAdjust[OilPipeline,NL]=1
  PCCAdjust[NGPipeline,NL]=1
  PCCAdjust[Wholesale,PE]=1.2739
  PCCAdjust[Retail,PE]=0.8088
  PCCAdjust[Warehouse,PE]=0.5029
  PCCAdjust[Information,PE]=73.7881
  PCCAdjust[Offices,PE]=7.1425
  PCCAdjust[Education,PE]=28.5477
  PCCAdjust[Health,PE]=15.6934
  PCCAdjust[OtherCommercial,PE]=2.3995
  PCCAdjust[NGDistribution,PE]=1
  PCCAdjust[OilPipeline,PE]=1
  PCCAdjust[NGPipeline,PE]=1
  PCCAdjust[Wholesale,YT]=1.3542
  PCCAdjust[Retail,YT]=1.8949
  PCCAdjust[Warehouse,YT]=0.548
  PCCAdjust[Information,YT]=214.2775
  PCCAdjust[Offices,YT]=33.2898
  PCCAdjust[Education,YT]=11.457
  PCCAdjust[Health,YT]=45.4252
  PCCAdjust[OtherCommercial,YT]=1.3825
  PCCAdjust[NGDistribution,YT]=1
  PCCAdjust[OilPipeline,YT]=1
  PCCAdjust[NGPipeline,YT]=1
  PCCAdjust[Wholesale,NT]=0.5248
  PCCAdjust[Retail,NT]=0.159
  PCCAdjust[Warehouse,NT]=0.1427
  PCCAdjust[Information,NT]=957.7703
  PCCAdjust[Offices,NT]=17.5706
  PCCAdjust[Education,NT]=1.3069
  PCCAdjust[Health,NT]=8.8587
  PCCAdjust[OtherCommercial,NT]=0.4869
  PCCAdjust[NGDistribution,NT]=1
  PCCAdjust[OilPipeline,NT]=1
  PCCAdjust[NGPipeline,NT]=1
  PCCAdjust[Wholesale,NU]=1.3588
  PCCAdjust[Retail,NU]=3.7596
  PCCAdjust[Warehouse,NU]=0.7512
  PCCAdjust[Information,NU]=122.7379
  PCCAdjust[Offices,NU]=25.6817
  PCCAdjust[Education,NU]=6.9874
  PCCAdjust[Health,NU]=17.0678
  PCCAdjust[OtherCommercial,NU]=0.7137
  PCCAdjust[NGDistribution,NU]=1
  PCCAdjust[OilPipeline,NU]=1
  PCCAdjust[NGPipeline,NU]=1
  PCCAdjust[Wholesale,CA]=0.0088
  PCCAdjust[Retail,CA]=0.0249
  PCCAdjust[Warehouse,CA]=0.0005
  PCCAdjust[Information,CA]=0.0237
  PCCAdjust[Offices,CA]=0.0298
  PCCAdjust[Education,CA]=0.2633
  PCCAdjust[Health,CA]=0.0576
  PCCAdjust[OtherCommercial,CA]=0.0177
  PCCAdjust[NGDistribution,CA]=1
  PCCAdjust[OilPipeline,CA]=1
  PCCAdjust[NGPipeline,CA]=1
  PCCAdjust[Wholesale,NEng]=0.0086
  PCCAdjust[Retail,NEng]=0.0265
  PCCAdjust[Warehouse,NEng]=0.0003
  PCCAdjust[Information,NEng]=0.0249
  PCCAdjust[Offices,NEng]=0.0277
  PCCAdjust[Education,NEng]=0.3307
  PCCAdjust[Health,NEng]=0.0603
  PCCAdjust[OtherCommercial,NEng]=0.0167
  PCCAdjust[NGDistribution,NEng]=1
  PCCAdjust[OilPipeline,NEng]=1
  PCCAdjust[NGPipeline,NEng]=1
  PCCAdjust[Wholesale,MAtl]=0.0083
  PCCAdjust[Retail,MAtl]=0.0252
  PCCAdjust[Warehouse,MAtl]=0.0004
  PCCAdjust[Information,MAtl]=0.028
  PCCAdjust[Offices,MAtl]=0.03
  PCCAdjust[Education,MAtl]=0.3005
  PCCAdjust[Health,MAtl]=0.0602
  PCCAdjust[OtherCommercial,MAtl]=0.0184
  PCCAdjust[NGDistribution,MAtl]=1
  PCCAdjust[OilPipeline,MAtl]=1
  PCCAdjust[NGPipeline,MAtl]=1
  PCCAdjust[Wholesale,ENC]=0.0083
  PCCAdjust[Retail,ENC]=0.0259
  PCCAdjust[Warehouse,ENC]=0.0006
  PCCAdjust[Information,ENC]=0.0298
  PCCAdjust[Offices,ENC]=0.0303
  PCCAdjust[Education,ENC]=0.313
  PCCAdjust[Health,ENC]=0.0612
  PCCAdjust[OtherCommercial,ENC]=0.0173
  PCCAdjust[NGDistribution,ENC]=1
  PCCAdjust[OilPipeline,ENC]=1
  PCCAdjust[NGPipeline,ENC]=1
  PCCAdjust[Wholesale,WNC]=0.0083
  PCCAdjust[Retail,WNC]=0.0255
  PCCAdjust[Warehouse,WNC]=0.0004
  PCCAdjust[Information,WNC]=0.0281
  PCCAdjust[Offices,WNC]=0.0327
  PCCAdjust[Education,WNC]=0.3099
  PCCAdjust[Health,WNC]=0.0599
  PCCAdjust[OtherCommercial,WNC]=0.0187
  PCCAdjust[NGDistribution,WNC]=1
  PCCAdjust[OilPipeline,WNC]=1
  PCCAdjust[NGPipeline,WNC]=1
  PCCAdjust[Wholesale,SAtl]=0.0084
  PCCAdjust[Retail,SAtl]=0.0247
  PCCAdjust[Warehouse,SAtl]=0.0005
  PCCAdjust[Information,SAtl]=0.0254
  PCCAdjust[Offices,SAtl]=0.0311
  PCCAdjust[Education,SAtl]=0.3117
  PCCAdjust[Health,SAtl]=0.0564
  PCCAdjust[OtherCommercial,SAtl]=0.017
  PCCAdjust[NGDistribution,SAtl]=1
  PCCAdjust[OilPipeline,SAtl]=1
  PCCAdjust[NGPipeline,SAtl]=1
  PCCAdjust[Wholesale,ESC]=0.0087
  PCCAdjust[Retail,ESC]=0.025
  PCCAdjust[Warehouse,ESC]=0.001
  PCCAdjust[Information,ESC]=0.0288
  PCCAdjust[Offices,ESC]=0.0355
  PCCAdjust[Education,ESC]=0.2973
  PCCAdjust[Health,ESC]=0.0577
  PCCAdjust[OtherCommercial,ESC]=0.0181
  PCCAdjust[NGDistribution,ESC]=1
  PCCAdjust[OilPipeline,ESC]=1
  PCCAdjust[NGPipeline,ESC]=1
  PCCAdjust[Wholesale,WSC]=0.0083
  PCCAdjust[Retail,WSC]=0.0239
  PCCAdjust[Warehouse,WSC]=0.0005
  PCCAdjust[Information,WSC]=0.0293
  PCCAdjust[Offices,WSC]=0.0328
  PCCAdjust[Education,WSC]=0.319
  PCCAdjust[Health,WSC]=0.0584
  PCCAdjust[OtherCommercial,WSC]=0.0162
  PCCAdjust[NGDistribution,WSC]=1
  PCCAdjust[OilPipeline,WSC]=1
  PCCAdjust[NGPipeline,WSC]=1
  PCCAdjust[Wholesale,Mtn]=0.0087
  PCCAdjust[Retail,Mtn]=0.0246
  PCCAdjust[Warehouse,Mtn]=0.0005
  PCCAdjust[Information,Mtn]=0.026
  PCCAdjust[Offices,Mtn]=0.0307
  PCCAdjust[Education,Mtn]=0.2971
  PCCAdjust[Health,Mtn]=0.056
  PCCAdjust[OtherCommercial,Mtn]=0.0165
  PCCAdjust[NGDistribution,Mtn]=1
  PCCAdjust[OilPipeline,Mtn]=1
  PCCAdjust[NGPipeline,Mtn]=1
  PCCAdjust[Wholesale,Pac]=0.0084
  PCCAdjust[Retail,Pac]=0.1461
  PCCAdjust[Warehouse,Pac]=0.0004
  PCCAdjust[Information,Pac]=0.0209
  PCCAdjust[Offices,Pac]=0.0331
  PCCAdjust[Education,Pac]=0.3227
  PCCAdjust[Health,Pac]=0.0542
  PCCAdjust[OtherCommercial,Pac]=0.0154
  PCCAdjust[NGDistribution,Pac]=1
  PCCAdjust[OilPipeline,Pac]=1
  PCCAdjust[NGPipeline,Pac]=1

  CN=Select(Nation,"CN")
  if MacroSwitch[CN] == "TOM"
    for year in Years, area in areas, ec in ecs, tech in Techs, enduse in Enduses
      if xPCC[enduse,tech,ec,area,year] != -99
        xPCC[enduse,tech,ec,area,year]=xPCC[enduse,tech,ec,area,year]*PCCAdjust[ec,area]
      end
    end
    WriteDisk(db,"$Input/xPCC",xPCC)
  end

end

Base.@kwdef struct IControl
  db::String

  CalDB::String = "ICalDB"
  Input::String = "IInput"
  Outpt::String = "IOutput"
  BCNameDB::String = ReadDisk(db,"MainDB/BCNameDB") # Base Case Name

  Area::SetArray = ReadDisk(db,"MainDB/AreaKey")
  AreaDS::SetArray = ReadDisk(db,"MainDB/AreaDS")
  Areas::Vector{Int} = collect(Select(Area))
  EC::SetArray = ReadDisk(db,"$Input/ECKey")
  ECDS::SetArray = ReadDisk(db,"$Input/ECDS")
  ECs::Vector{Int} = collect(Select(EC))
  Enduse::SetArray = ReadDisk(db,"$Input/EnduseKey")
  EnduseDS::SetArray = ReadDisk(db,"$Input/EnduseDS")
  Enduses::Vector{Int} = collect(Select(Enduse))
  Nation::SetArray = ReadDisk(db,"MainDB/NationKey")
  NationDS::SetArray = ReadDisk(db,"MainDB/NationDS")
  Nations::Vector{Int} = collect(Select(Nation))
  Tech::SetArray = ReadDisk(db,"$Input/TechKey")
  TechDS::SetArray = ReadDisk(db,"$Input/TechDS")
  Techs::Vector{Int} = collect(Select(Tech))
  Year::SetArray = ReadDisk(db,"MainDB/YearKey")
  YearDS::SetArray = ReadDisk(db,"MainDB/YearDS")
  Years::Vector{Int} = collect(Select(Year))

  MacroSwitch::Vector{String} = ReadDisk(db,"MInput/MacroSwitch") # [Nation] String Indicator of Macroeconomic Forecast (TOM,Stokes,AEO,CER)
  xInflation::VariableArray{2} = ReadDisk(db,"MInput/xInflation") # [Area,Year] Inflation Index ($/$)
  xPCC::VariableArray{5} = ReadDisk(db,"$Input/xPCC") # [Enduse,Tech,EC,Area,Year] Process Capital Cost ($/Driver/Yr)

  # Scratch Variables
  PCCAdjust::VariableArray{2} = zeros(Float32,length(EC),length(Area)) # [EC,Area] Process Capital Cost Adjustment ($/$)
end

function ICalibration(db)
  data = IControl(; db)
  (;Input) = data
  (;Area,AreaDS,Areas,EC,ECDS,ECs,Enduse,EnduseDS,Enduses,Nation) = data
  (;NationDS,Nations,Tech,TechDS,Techs,Year,YearDS,Years) = data
  (;MacroSwitch,xInflation,xPCC) = data
  (;PCCAdjust) = data

  areas=Select(Area,(from="ON", to="Pac"))

  ON=Select(Area,"ON")
  QC=Select(Area,"QC")
  BC=Select(Area,"BC")
  AB=Select(Area,"AB")
  MB=Select(Area,"MB")
  SK=Select(Area,"SK")
  NB=Select(Area,"NB")
  NS=Select(Area,"NS")
  NL=Select(Area,"NL")
  PE=Select(Area,"PE")
  YT=Select(Area,"YT")
  NT=Select(Area,"NT")
  NU=Select(Area,"NU")
  CA=Select(Area,"CA")
  NEng=Select(Area,"NEng")
  MAtl=Select(Area,"MAtl")
  ENC=Select(Area,"ENC")
  WNC=Select(Area,"WNC")
  SAtl=Select(Area,"SAtl")
  ESC=Select(Area,"ESC")
  WSC=Select(Area,"WSC")
  Mtn=Select(Area,"Mtn")
  Pac=Select(Area,"Pac")

  ecs1=Select(EC,(from="Food", to="NonMetalMining"))
  ecs2=Select(EC,(from="CoalMining", to="AnimalProduction"))
  ecs=union(ecs1,ecs2)

  Food=Select(EC,"Food")
  Textiles=Select(EC,"Textiles")
  Lumber=Select(EC,"Lumber")
  Furniture=Select(EC,"Furniture")
  PulpPaperMills=Select(EC,"PulpPaperMills")
  Petrochemicals=Select(EC,"Petrochemicals")
  IndustrialGas=Select(EC,"IndustrialGas")
  OtherChemicals=Select(EC,"OtherChemicals")
  Fertilizer=Select(EC,"Fertilizer")
  Petroleum=Select(EC,"Petroleum")
  Rubber=Select(EC,"Rubber")
  Cement=Select(EC,"Cement")
  Glass=Select(EC,"Glass")
  LimeGypsum=Select(EC,"LimeGypsum")
  OtherNonMetallic=Select(EC,"OtherNonMetallic")
  IronSteel=Select(EC,"IronSteel")
  Aluminum=Select(EC,"Aluminum")
  OtherNonferrous=Select(EC,"OtherNonferrous")
  TransportEquipment=Select(EC,"TransportEquipment")
  OtherManufacturing=Select(EC,"OtherManufacturing")
  IronOreMining=Select(EC,"IronOreMining")
  OtherMetalMining=Select(EC,"OtherMetalMining")
  NonMetalMining=Select(EC,"NonMetalMining")
  CoalMining=Select(EC,"CoalMining")
  Construction=Select(EC,"Construction")
  Forestry=Select(EC,"Forestry")
  OnFarmFuelUse=Select(EC,"OnFarmFuelUse")
  CropProduction=Select(EC,"CropProduction")
  AnimalProduction=Select(EC,"AnimalProduction")
  
  @. PCCAdjust = 1.0

  PCCAdjust[Food,ON]=0.1939
  PCCAdjust[Textiles,ON]=0.3333
  PCCAdjust[Lumber,ON]=0.3992
  PCCAdjust[Furniture,ON]=0.0894
  PCCAdjust[PulpPaperMills,ON]=4.2477
  PCCAdjust[Petrochemicals,ON]=0.6308
  PCCAdjust[IndustrialGas,ON]=5.7497
  PCCAdjust[OtherChemicals,ON]=0.3399
  PCCAdjust[Fertilizer,ON]=0.221
  PCCAdjust[Petroleum,ON]=3.1469
  PCCAdjust[Rubber,ON]=0.4148
  PCCAdjust[Cement,ON]=1.3815
  PCCAdjust[Glass,ON]=4.8146
  PCCAdjust[LimeGypsum,ON]=33.2302
  PCCAdjust[OtherNonMetallic,ON]=11.0937
  PCCAdjust[IronSteel,ON]=1.2993
  PCCAdjust[Aluminum,ON]=1.8068
  PCCAdjust[OtherNonferrous,ON]=9.0734
  PCCAdjust[TransportEquipment,ON]=1.2398
  PCCAdjust[OtherManufacturing,ON]=0.2201
  PCCAdjust[IronOreMining,ON]=1
  PCCAdjust[OtherMetalMining,ON]=4.275
  PCCAdjust[NonMetalMining,ON]=0.8852
  PCCAdjust[CoalMining,ON]=1
  PCCAdjust[Construction,ON]=0.392
  PCCAdjust[Forestry,ON]=1
  PCCAdjust[OnFarmFuelUse,ON]=1.8335
  PCCAdjust[CropProduction,ON]=1
  PCCAdjust[AnimalProduction,ON]=1
  PCCAdjust[Food,QC]=0.2112
  PCCAdjust[Textiles,QC]=0.1814
  PCCAdjust[Lumber,QC]=1.3422
  PCCAdjust[Furniture,QC]=0.1854
  PCCAdjust[PulpPaperMills,QC]=0.7091
  PCCAdjust[Petrochemicals,QC]=1.0902
  PCCAdjust[IndustrialGas,QC]=7.9018
  PCCAdjust[OtherChemicals,QC]=0.3036
  PCCAdjust[Fertilizer,QC]=0.0689
  PCCAdjust[Petroleum,QC]=1.7311
  PCCAdjust[Rubber,QC]=0.4131
  PCCAdjust[Cement,QC]=4.5935
  PCCAdjust[Glass,QC]=15.8112
  PCCAdjust[LimeGypsum,QC]=15.8621
  PCCAdjust[OtherNonMetallic,QC]=14.3396
  PCCAdjust[IronSteel,QC]=3.8301
  PCCAdjust[Aluminum,QC]=8.4287
  PCCAdjust[OtherNonferrous,QC]=4.0271
  PCCAdjust[TransportEquipment,QC]=0.5858
  PCCAdjust[OtherManufacturing,QC]=0.362
  PCCAdjust[IronOreMining,QC]=1.649
  PCCAdjust[OtherMetalMining,QC]=2.5612
  PCCAdjust[NonMetalMining,QC]=1.2322
  PCCAdjust[CoalMining,QC]=1
  PCCAdjust[Construction,QC]=0.3856
  PCCAdjust[Forestry,QC]=1.0368
  PCCAdjust[OnFarmFuelUse,QC]=1.5665
  PCCAdjust[CropProduction,QC]=1
  PCCAdjust[AnimalProduction,QC]=1
  PCCAdjust[Food,BC]=0.3073
  PCCAdjust[Textiles,BC]=0.1876
  PCCAdjust[Lumber,BC]=0.8267
  PCCAdjust[Furniture,BC]=0.2164
  PCCAdjust[PulpPaperMills,BC]=69.7132
  PCCAdjust[Petrochemicals,BC]=7.3894
  PCCAdjust[IndustrialGas,BC]=7.93
  PCCAdjust[OtherChemicals,BC]=0.3661
  PCCAdjust[Fertilizer,BC]=0.4494
  PCCAdjust[Petroleum,BC]=7.8045
  PCCAdjust[Rubber,BC]=0.3254
  PCCAdjust[Cement,BC]=13.3125
  PCCAdjust[Glass,BC]=19.3164
  PCCAdjust[LimeGypsum,BC]=64.1396
  PCCAdjust[OtherNonMetallic,BC]=32.9554
  PCCAdjust[IronSteel,BC]=0.4043
  PCCAdjust[Aluminum,BC]=100.8111
  PCCAdjust[OtherNonferrous,BC]=19.7611
  PCCAdjust[TransportEquipment,BC]=1.3151
  PCCAdjust[OtherManufacturing,BC]=0.2687
  PCCAdjust[IronOreMining,BC]=1
  PCCAdjust[OtherMetalMining,BC]=1.542
  PCCAdjust[NonMetalMining,BC]=25.8027
  PCCAdjust[CoalMining,BC]=7.6047
  PCCAdjust[Construction,BC]=0.357
  PCCAdjust[Forestry,BC]=1
  PCCAdjust[OnFarmFuelUse,BC]=1.4908
  PCCAdjust[CropProduction,BC]=1
  PCCAdjust[AnimalProduction,BC]=1
  PCCAdjust[Food,AB]=0.1924
  PCCAdjust[Textiles,AB]=0.1334
  PCCAdjust[Lumber,AB]=0.9835
  PCCAdjust[Furniture,AB]=0.2036
  PCCAdjust[PulpPaperMills,AB]=2.6808
  PCCAdjust[Petrochemicals,AB]=1.0103
  PCCAdjust[IndustrialGas,AB]=6.4953
  PCCAdjust[OtherChemicals,AB]=0.5843
  PCCAdjust[Fertilizer,AB]=0.2679
  PCCAdjust[Petroleum,AB]=2.9379
  PCCAdjust[Rubber,AB]=0.3602
  PCCAdjust[Cement,AB]=1.5741
  PCCAdjust[Glass,AB]=5.8116
  PCCAdjust[LimeGypsum,AB]=9.7952
  PCCAdjust[OtherNonMetallic,AB]=3.6393
  PCCAdjust[IronSteel,AB]=22.9099
  PCCAdjust[Aluminum,AB]=4.1392
  PCCAdjust[OtherNonferrous,AB]=1.6458
  PCCAdjust[TransportEquipment,AB]=0.7521
  PCCAdjust[OtherManufacturing,AB]=0.2934
  PCCAdjust[IronOreMining,AB]=1
  PCCAdjust[OtherMetalMining,AB]=0.017
  PCCAdjust[NonMetalMining,AB]=0.517
  PCCAdjust[CoalMining,AB]=2.3696
  PCCAdjust[Construction,AB]=0.432
  PCCAdjust[Forestry,AB]=1
  PCCAdjust[OnFarmFuelUse,AB]=3.2695
  PCCAdjust[CropProduction,AB]=1
  PCCAdjust[AnimalProduction,AB]=1
  PCCAdjust[Food,MB]=0.6319
  PCCAdjust[Textiles,MB]=0.2468
  PCCAdjust[Lumber,MB]=0.9648
  PCCAdjust[Furniture,MB]=0.9107
  PCCAdjust[PulpPaperMills,MB]=1.2242
  PCCAdjust[Petrochemicals,MB]=2.3251
  PCCAdjust[IndustrialGas,MB]=1.5451
  PCCAdjust[OtherChemicals,MB]=0.3732
  PCCAdjust[Fertilizer,MB]=0.3894
  PCCAdjust[Petroleum,MB]=1
  PCCAdjust[Rubber,MB]=0.661
  PCCAdjust[Cement,MB]=1
  PCCAdjust[Glass,MB]=2.3293
  PCCAdjust[LimeGypsum,MB]=3.15
  PCCAdjust[OtherNonMetallic,MB]=2.7074
  PCCAdjust[IronSteel,MB]=1.4179
  PCCAdjust[Aluminum,MB]=295.1325
  PCCAdjust[OtherNonferrous,MB]=4.8277
  PCCAdjust[TransportEquipment,MB]=1.2786
  PCCAdjust[OtherManufacturing,MB]=0.372
  PCCAdjust[IronOreMining,MB]=1
  PCCAdjust[OtherMetalMining,MB]=2.0429
  PCCAdjust[NonMetalMining,MB]=0.3787
  PCCAdjust[CoalMining,MB]=1
  PCCAdjust[Construction,MB]=0.4125
  PCCAdjust[Forestry,MB]=1
  PCCAdjust[OnFarmFuelUse,MB]=1.4712
  PCCAdjust[CropProduction,MB]=1
  PCCAdjust[AnimalProduction,MB]=1
  PCCAdjust[Food,SK]=0.2124
  PCCAdjust[Textiles,SK]=0.3036
  PCCAdjust[Lumber,SK]=13.4316
  PCCAdjust[Furniture,SK]=1.2288
  PCCAdjust[PulpPaperMills,SK]=4.3918
  PCCAdjust[Petrochemicals,SK]=44.0425
  PCCAdjust[IndustrialGas,SK]=21.1514
  PCCAdjust[OtherChemicals,SK]=0.7537
  PCCAdjust[Fertilizer,SK]=0.4989
  PCCAdjust[Petroleum,SK]=5.1451
  PCCAdjust[Rubber,SK]=0.2346
  PCCAdjust[Cement,SK]=1
  PCCAdjust[Glass,SK]=10.0508
  PCCAdjust[LimeGypsum,SK]=37.5147
  PCCAdjust[OtherNonMetallic,SK]=6.4543
  PCCAdjust[IronSteel,SK]=1.9471
  PCCAdjust[Aluminum,SK]=1
  PCCAdjust[OtherNonferrous,SK]=1
  PCCAdjust[TransportEquipment,SK]=6.884
  PCCAdjust[OtherManufacturing,SK]=0.3662
  PCCAdjust[IronOreMining,SK]=1
  PCCAdjust[OtherMetalMining,SK]=0.9747
  PCCAdjust[NonMetalMining,SK]=2.4592
  PCCAdjust[CoalMining,SK]=0.453
  PCCAdjust[Construction,SK]=0.2403
  PCCAdjust[Forestry,SK]=1
  PCCAdjust[OnFarmFuelUse,SK]=3.2672
  PCCAdjust[CropProduction,SK]=1
  PCCAdjust[AnimalProduction,SK]=1
  PCCAdjust[Food,NB]=0.2123
  PCCAdjust[Textiles,NB]=11.7764
  PCCAdjust[Lumber,NB]=0.7002
  PCCAdjust[Furniture,NB]=0.1477
  PCCAdjust[PulpPaperMills,NB]=1.3729
  PCCAdjust[Petrochemicals,NB]=0.5578
  PCCAdjust[IndustrialGas,NB]=5.1749
  PCCAdjust[OtherChemicals,NB]=0.4267
  PCCAdjust[Fertilizer,NB]=0.4834
  PCCAdjust[Petroleum,NB]=4.0732
  PCCAdjust[Rubber,NB]=0.2061
  PCCAdjust[Cement,NB]=1
  PCCAdjust[Glass,NB]=51.2048
  PCCAdjust[LimeGypsum,NB]=45.3461
  PCCAdjust[OtherNonMetallic,NB]=35.0585
  PCCAdjust[IronSteel,NB]=1846.022
  PCCAdjust[Aluminum,NB]=1
  PCCAdjust[OtherNonferrous,NB]=1
  PCCAdjust[TransportEquipment,NB]=0.8627
  PCCAdjust[OtherManufacturing,NB]=0.3177
  PCCAdjust[IronOreMining,NB]=1
  PCCAdjust[OtherMetalMining,NB]=1
  PCCAdjust[NonMetalMining,NB]=4.5186
  PCCAdjust[CoalMining,NB]=1
  PCCAdjust[Construction,NB]=0.5358
  PCCAdjust[Forestry,NB]=1
  PCCAdjust[OnFarmFuelUse,NB]=1.3994
  PCCAdjust[CropProduction,NB]=1
  PCCAdjust[AnimalProduction,NB]=1
  PCCAdjust[Food,NS]=0.29
  PCCAdjust[Textiles,NS]=0.3554
  PCCAdjust[Lumber,NS]=1.0404
  PCCAdjust[Furniture,NS]=0.3169
  PCCAdjust[PulpPaperMills,NS]=0.9456
  PCCAdjust[Petrochemicals,NS]=2032.86
  PCCAdjust[IndustrialGas,NS]=938.1586
  PCCAdjust[OtherChemicals,NS]=0.3316
  PCCAdjust[Fertilizer,NS]=0.0921
  PCCAdjust[Petroleum,NS]=1
  PCCAdjust[Rubber,NS]=0.2906
  PCCAdjust[Cement,NS]=2.2201
  PCCAdjust[Glass,NS]=2.2235
  PCCAdjust[LimeGypsum,NS]=7.6103
  PCCAdjust[OtherNonMetallic,NS]=1.6437
  PCCAdjust[IronSteel,NS]=1
  PCCAdjust[Aluminum,NS]=1
  PCCAdjust[OtherNonferrous,NS]=1
  PCCAdjust[TransportEquipment,NS]=0.4999
  PCCAdjust[OtherManufacturing,NS]=0.3716
  PCCAdjust[IronOreMining,NS]=1
  PCCAdjust[OtherMetalMining,NS]=1.7628
  PCCAdjust[NonMetalMining,NS]=0.6542
  PCCAdjust[CoalMining,NS]=2000
  PCCAdjust[Construction,NS]=0.451
  PCCAdjust[Forestry,NS]=1
  PCCAdjust[OnFarmFuelUse,NS]=1.6127
  PCCAdjust[CropProduction,NS]=1
  PCCAdjust[AnimalProduction,NS]=1
  PCCAdjust[Food,NL]=1.2375
  PCCAdjust[Textiles,NL]=15.5607
  PCCAdjust[Lumber,NL]=1.7384
  PCCAdjust[Furniture,NL]=0.3218
  PCCAdjust[PulpPaperMills,NL]=3.843
  PCCAdjust[Petrochemicals,NL]=26.628
  PCCAdjust[IndustrialGas,NL]=36.2315
  PCCAdjust[OtherChemicals,NL]=0.097
  PCCAdjust[Fertilizer,NL]=1
  PCCAdjust[Petroleum,NL]=43.7517
  PCCAdjust[Rubber,NL]=12.0312
  PCCAdjust[Cement,NL]=1
  PCCAdjust[Glass,NL]=222.5852
  PCCAdjust[LimeGypsum,NL]=12.6009
  PCCAdjust[OtherNonMetallic,NL]=220.8786
  PCCAdjust[IronSteel,NL]=1000
  PCCAdjust[Aluminum,NL]=1
  PCCAdjust[OtherNonferrous,NL]=145.0727
  PCCAdjust[TransportEquipment,NL]=9.7603
  PCCAdjust[OtherManufacturing,NL]=35.7004
  PCCAdjust[IronOreMining,NL]=2.6484
  PCCAdjust[OtherMetalMining,NL]=58.002
  PCCAdjust[NonMetalMining,NL]=4.8197
  PCCAdjust[CoalMining,NL]=1
  PCCAdjust[Construction,NL]=0.2612
  PCCAdjust[Forestry,NL]=1
  PCCAdjust[OnFarmFuelUse,NL]=1.9997
  PCCAdjust[CropProduction,NL]=1
  PCCAdjust[AnimalProduction,NL]=1
  PCCAdjust[Food,PE]=0.2351
  PCCAdjust[Textiles,PE]=1
  PCCAdjust[Lumber,PE]=9.0116
  PCCAdjust[Furniture,PE]=0.1284
  PCCAdjust[PulpPaperMills,PE]=1
  PCCAdjust[Petrochemicals,PE]=1
  PCCAdjust[IndustrialGas,PE]=1
  PCCAdjust[OtherChemicals,PE]=0.5834
  PCCAdjust[Fertilizer,PE]=0.1047
  PCCAdjust[Petroleum,PE]=1
  PCCAdjust[Rubber,PE]=1
  PCCAdjust[Cement,PE]=1
  PCCAdjust[Glass,PE]=10.3905
  PCCAdjust[LimeGypsum,PE]=4.9553
  PCCAdjust[OtherNonMetallic,PE]=1.49
  PCCAdjust[IronSteel,PE]=684.2621
  PCCAdjust[Aluminum,PE]=1
  PCCAdjust[OtherNonferrous,PE]=1
  PCCAdjust[TransportEquipment,PE]=0.2863
  PCCAdjust[OtherManufacturing,PE]=0.4289
  PCCAdjust[IronOreMining,PE]=1
  PCCAdjust[OtherMetalMining,PE]=1
  PCCAdjust[NonMetalMining,PE]=59.2621
  PCCAdjust[CoalMining,PE]=1
  PCCAdjust[Construction,PE]=0.4052
  PCCAdjust[Forestry,PE]=1
  PCCAdjust[OnFarmFuelUse,PE]=1.652
  PCCAdjust[CropProduction,PE]=1
  PCCAdjust[AnimalProduction,PE]=1
  PCCAdjust[Food,YT]=0.4593
  PCCAdjust[Textiles,YT]=1
  PCCAdjust[Lumber,YT]=1
  PCCAdjust[Furniture,YT]=1
  PCCAdjust[PulpPaperMills,YT]=1
  PCCAdjust[Petrochemicals,YT]=1
  PCCAdjust[IndustrialGas,YT]=1
  PCCAdjust[OtherChemicals,YT]=0.7517
  PCCAdjust[Fertilizer,YT]=1
  PCCAdjust[Petroleum,YT]=1
  PCCAdjust[Rubber,YT]=1
  PCCAdjust[Cement,YT]=1
  PCCAdjust[Glass,YT]=1
  PCCAdjust[LimeGypsum,YT]=1
  PCCAdjust[OtherNonMetallic,YT]=1
  PCCAdjust[IronSteel,YT]=1
  PCCAdjust[Aluminum,YT]=1
  PCCAdjust[OtherNonferrous,YT]=1
  PCCAdjust[TransportEquipment,YT]=1
  PCCAdjust[OtherManufacturing,YT]=3.3252
  PCCAdjust[IronOreMining,YT]=1
  PCCAdjust[OtherMetalMining,YT]=95.6731
  PCCAdjust[NonMetalMining,YT]=0.0962
  PCCAdjust[CoalMining,YT]=1
  PCCAdjust[Construction,YT]=0.4637
  PCCAdjust[Forestry,YT]=1
  PCCAdjust[OnFarmFuelUse,YT]=1
  PCCAdjust[CropProduction,YT]=1
  PCCAdjust[AnimalProduction,YT]=1
  PCCAdjust[Food,NT]=1
  PCCAdjust[Textiles,NT]=1
  PCCAdjust[Lumber,NT]=1
  PCCAdjust[Furniture,NT]=1
  PCCAdjust[PulpPaperMills,NT]=1
  PCCAdjust[Petrochemicals,NT]=1
  PCCAdjust[IndustrialGas,NT]=1
  PCCAdjust[OtherChemicals,NT]=1
  PCCAdjust[Fertilizer,NT]=1
  PCCAdjust[Petroleum,NT]=1
  PCCAdjust[Rubber,NT]=1
  PCCAdjust[Cement,NT]=1
  PCCAdjust[Glass,NT]=1
  PCCAdjust[LimeGypsum,NT]=1
  PCCAdjust[OtherNonMetallic,NT]=1
  PCCAdjust[IronSteel,NT]=1
  PCCAdjust[Aluminum,NT]=1
  PCCAdjust[OtherNonferrous,NT]=1
  PCCAdjust[TransportEquipment,NT]=1
  PCCAdjust[OtherManufacturing,NT]=1
  PCCAdjust[IronOreMining,NT]=1
  PCCAdjust[OtherMetalMining,NT]=56.7078
  PCCAdjust[NonMetalMining,NT]=16.5419
  PCCAdjust[CoalMining,NT]=1
  PCCAdjust[Construction,NT]=0.4201
  PCCAdjust[Forestry,NT]=1
  PCCAdjust[OnFarmFuelUse,NT]=1
  PCCAdjust[CropProduction,NT]=1
  PCCAdjust[AnimalProduction,NT]=1
  PCCAdjust[Food,NU]=1
  PCCAdjust[Textiles,NU]=1
  PCCAdjust[Lumber,NU]=1
  PCCAdjust[Furniture,NU]=1
  PCCAdjust[PulpPaperMills,NU]=1
  PCCAdjust[Petrochemicals,NU]=1
  PCCAdjust[IndustrialGas,NU]=1
  PCCAdjust[OtherChemicals,NU]=4.2504
  PCCAdjust[Fertilizer,NU]=1
  PCCAdjust[Petroleum,NU]=1
  PCCAdjust[Rubber,NU]=1
  PCCAdjust[Cement,NU]=1
  PCCAdjust[Glass,NU]=1
  PCCAdjust[LimeGypsum,NU]=1
  PCCAdjust[OtherNonMetallic,NU]=1
  PCCAdjust[IronSteel,NU]=1
  PCCAdjust[Aluminum,NU]=1
  PCCAdjust[OtherNonferrous,NU]=1
  PCCAdjust[TransportEquipment,NU]=1
  PCCAdjust[OtherManufacturing,NU]=1
  PCCAdjust[IronOreMining,NU]=1
  PCCAdjust[OtherMetalMining,NU]=0.9935
  PCCAdjust[NonMetalMining,NU]=1
  PCCAdjust[CoalMining,NU]=1
  PCCAdjust[Construction,NU]=1
  PCCAdjust[Forestry,NU]=1
  PCCAdjust[OnFarmFuelUse,NU]=1
  PCCAdjust[CropProduction,NU]=1
  PCCAdjust[AnimalProduction,NU]=1
  PCCAdjust[Food,CA]=0.2974
  PCCAdjust[Textiles,CA]=1
  PCCAdjust[Lumber,CA]=0.868
  PCCAdjust[Furniture,CA]=1
  PCCAdjust[PulpPaperMills,CA]=1.3737
  PCCAdjust[Petrochemicals,CA]=1.0262
  PCCAdjust[IndustrialGas,CA]=1
  PCCAdjust[OtherChemicals,CA]=0.0189
  PCCAdjust[Fertilizer,CA]=0.0038
  PCCAdjust[Petroleum,CA]=0.5501
  PCCAdjust[Rubber,CA]=1.1897
  PCCAdjust[Cement,CA]=0.0023
  PCCAdjust[Glass,CA]=247.3172
  PCCAdjust[LimeGypsum,CA]=1
  PCCAdjust[OtherNonMetallic,CA]=1
  PCCAdjust[IronSteel,CA]=0.0026
  PCCAdjust[Aluminum,CA]=0.004
  PCCAdjust[OtherNonferrous,CA]=1
  PCCAdjust[TransportEquipment,CA]=0.7133
  PCCAdjust[OtherManufacturing,CA]=0.9569
  PCCAdjust[IronOreMining,CA]=1
  PCCAdjust[OtherMetalMining,CA]=1
  PCCAdjust[NonMetalMining,CA]=1.7002
  PCCAdjust[CoalMining,CA]=1
  PCCAdjust[Construction,CA]=0.4322
  PCCAdjust[Forestry,CA]=1
  PCCAdjust[OnFarmFuelUse,CA]=7.84
  PCCAdjust[CropProduction,CA]=1
  PCCAdjust[AnimalProduction,CA]=1
  PCCAdjust[Food,NEng]=0.3587
  PCCAdjust[Textiles,NEng]=1
  PCCAdjust[Lumber,NEng]=0.7849
  PCCAdjust[Furniture,NEng]=1
  PCCAdjust[PulpPaperMills,NEng]=2.3482
  PCCAdjust[Petrochemicals,NEng]=1
  PCCAdjust[IndustrialGas,NEng]=1
  PCCAdjust[OtherChemicals,NEng]=0.0337
  PCCAdjust[Fertilizer,NEng]=0.0045
  PCCAdjust[Petroleum,NEng]=7.8936
  PCCAdjust[Rubber,NEng]=1.268
  PCCAdjust[Cement,NEng]=0.0021
  PCCAdjust[Glass,NEng]=186.3695
  PCCAdjust[LimeGypsum,NEng]=1
  PCCAdjust[OtherNonMetallic,NEng]=1
  PCCAdjust[IronSteel,NEng]=0.0039
  PCCAdjust[Aluminum,NEng]=0.0063
  PCCAdjust[OtherNonferrous,NEng]=1
  PCCAdjust[TransportEquipment,NEng]=0.5627
  PCCAdjust[OtherManufacturing,NEng]=1.3048
  PCCAdjust[IronOreMining,NEng]=1
  PCCAdjust[OtherMetalMining,NEng]=1
  PCCAdjust[NonMetalMining,NEng]=35.1528
  PCCAdjust[CoalMining,NEng]=1
  PCCAdjust[Construction,NEng]=0.4071
  PCCAdjust[Forestry,NEng]=7.1688
  PCCAdjust[OnFarmFuelUse,NEng]=4.9914
  PCCAdjust[CropProduction,NEng]=1
  PCCAdjust[AnimalProduction,NEng]=1
  PCCAdjust[Food,MAtl]=0.3738
  PCCAdjust[Textiles,MAtl]=1
  PCCAdjust[Lumber,MAtl]=0.758
  PCCAdjust[Furniture,MAtl]=1
  PCCAdjust[PulpPaperMills,MAtl]=1.5311
  PCCAdjust[Petrochemicals,MAtl]=0.3379
  PCCAdjust[IndustrialGas,MAtl]=1
  PCCAdjust[OtherChemicals,MAtl]=0.0175
  PCCAdjust[Fertilizer,MAtl]=0.006
  PCCAdjust[Petroleum,MAtl]=1.353
  PCCAdjust[Rubber,MAtl]=1.1885
  PCCAdjust[Cement,MAtl]=0.0037
  PCCAdjust[Glass,MAtl]=69.5519
  PCCAdjust[LimeGypsum,MAtl]=1
  PCCAdjust[OtherNonMetallic,MAtl]=1
  PCCAdjust[IronSteel,MAtl]=0.0069
  PCCAdjust[Aluminum,MAtl]=0.015
  PCCAdjust[OtherNonferrous,MAtl]=1
  PCCAdjust[TransportEquipment,MAtl]=0.7451
  PCCAdjust[OtherManufacturing,MAtl]=1.0475
  PCCAdjust[IronOreMining,MAtl]=1
  PCCAdjust[OtherMetalMining,MAtl]=1
  PCCAdjust[NonMetalMining,MAtl]=0.7647
  PCCAdjust[CoalMining,MAtl]=11.2849
  PCCAdjust[Construction,MAtl]=0.406
  PCCAdjust[Forestry,MAtl]=13.456
  PCCAdjust[OnFarmFuelUse,MAtl]=9.0901
  PCCAdjust[CropProduction,MAtl]=1
  PCCAdjust[AnimalProduction,MAtl]=1
  PCCAdjust[Food,ENC]=0.4001
  PCCAdjust[Textiles,ENC]=1
  PCCAdjust[Lumber,ENC]=0.8722
  PCCAdjust[Furniture,ENC]=1
  PCCAdjust[PulpPaperMills,ENC]=1.769
  PCCAdjust[Petrochemicals,ENC]=0.3187
  PCCAdjust[IndustrialGas,ENC]=1
  PCCAdjust[OtherChemicals,ENC]=0.0237
  PCCAdjust[Fertilizer,ENC]=0.0131
  PCCAdjust[Petroleum,ENC]=0.3501
  PCCAdjust[Rubber,ENC]=1.4519
  PCCAdjust[Cement,ENC]=0.0065
  PCCAdjust[Glass,ENC]=118.6354
  PCCAdjust[LimeGypsum,ENC]=1
  PCCAdjust[OtherNonMetallic,ENC]=1
  PCCAdjust[IronSteel,ENC]=0.0283
  PCCAdjust[Aluminum,ENC]=0.0484
  PCCAdjust[OtherNonferrous,ENC]=1
  PCCAdjust[TransportEquipment,ENC]=1.1108
  PCCAdjust[OtherManufacturing,ENC]=1.2157
  PCCAdjust[IronOreMining,ENC]=1
  PCCAdjust[OtherMetalMining,ENC]=1
  PCCAdjust[NonMetalMining,ENC]=1.1481
  PCCAdjust[CoalMining,ENC]=2.1501
  PCCAdjust[Construction,ENC]=0.433
  PCCAdjust[Forestry,ENC]=10.0933
  PCCAdjust[OnFarmFuelUse,ENC]=6.6228
  PCCAdjust[CropProduction,ENC]=1
  PCCAdjust[AnimalProduction,ENC]=1
  PCCAdjust[Food,WNC]=0.4633
  PCCAdjust[Textiles,WNC]=1
  PCCAdjust[Lumber,WNC]=0.7569
  PCCAdjust[Furniture,WNC]=1
  PCCAdjust[PulpPaperMills,WNC]=2.2083
  PCCAdjust[Petrochemicals,WNC]=1.6636
  PCCAdjust[IndustrialGas,WNC]=1
  PCCAdjust[OtherChemicals,WNC]=0.0349
  PCCAdjust[Fertilizer,WNC]=0.0017
  PCCAdjust[Petroleum,WNC]=0.4011
  PCCAdjust[Rubber,WNC]=1.0491
  PCCAdjust[Cement,WNC]=0.0041
  PCCAdjust[Glass,WNC]=8.4851
  PCCAdjust[LimeGypsum,WNC]=1
  PCCAdjust[OtherNonMetallic,WNC]=1
  PCCAdjust[IronSteel,WNC]=0.0109
  PCCAdjust[Aluminum,WNC]=0.0098
  PCCAdjust[OtherNonferrous,WNC]=1
  PCCAdjust[TransportEquipment,WNC]=0.7653
  PCCAdjust[OtherManufacturing,WNC]=1.0396
  PCCAdjust[IronOreMining,WNC]=1
  PCCAdjust[OtherMetalMining,WNC]=1
  PCCAdjust[NonMetalMining,WNC]=0.1688
  PCCAdjust[CoalMining,WNC]=615.321
  PCCAdjust[Construction,WNC]=0.4182
  PCCAdjust[Forestry,WNC]=6.8134
  PCCAdjust[OnFarmFuelUse,WNC]=3.007
  PCCAdjust[CropProduction,WNC]=1
  PCCAdjust[AnimalProduction,WNC]=1
  PCCAdjust[Food,SAtl]=0.3628
  PCCAdjust[Textiles,SAtl]=1
  PCCAdjust[Lumber,SAtl]=0.869
  PCCAdjust[Furniture,SAtl]=1
  PCCAdjust[PulpPaperMills,SAtl]=1.4102
  PCCAdjust[Petrochemicals,SAtl]=0.3975
  PCCAdjust[IndustrialGas,SAtl]=1
  PCCAdjust[OtherChemicals,SAtl]=0.0088
  PCCAdjust[Fertilizer,SAtl]=0.0059
  PCCAdjust[Petroleum,SAtl]=8.8107
  PCCAdjust[Rubber,SAtl]=1.0705
  PCCAdjust[Cement,SAtl]=0.0043
  PCCAdjust[Glass,SAtl]=6.8686
  PCCAdjust[LimeGypsum,SAtl]=1
  PCCAdjust[OtherNonMetallic,SAtl]=1
  PCCAdjust[IronSteel,SAtl]=0.0036
  PCCAdjust[Aluminum,SAtl]=0.0109
  PCCAdjust[OtherNonferrous,SAtl]=1
  PCCAdjust[TransportEquipment,SAtl]=0.7031
  PCCAdjust[OtherManufacturing,SAtl]=1.0433
  PCCAdjust[IronOreMining,SAtl]=1
  PCCAdjust[OtherMetalMining,SAtl]=1
  PCCAdjust[NonMetalMining,SAtl]=1.9462
  PCCAdjust[CoalMining,SAtl]=15.7123
  PCCAdjust[Construction,SAtl]=0.4014
  PCCAdjust[Forestry,SAtl]=145.0387
  PCCAdjust[OnFarmFuelUse,SAtl]=105.9015
  PCCAdjust[CropProduction,SAtl]=1
  PCCAdjust[AnimalProduction,SAtl]=1
  PCCAdjust[Food,ESC]=0.3988
  PCCAdjust[Textiles,ESC]=1
  PCCAdjust[Lumber,ESC]=0.9628
  PCCAdjust[Furniture,ESC]=1
  PCCAdjust[PulpPaperMills,ESC]=1.6346
  PCCAdjust[Petrochemicals,ESC]=1
  PCCAdjust[IndustrialGas,ESC]=1
  PCCAdjust[OtherChemicals,ESC]=0.0088
  PCCAdjust[Fertilizer,ESC]=0.0091
  PCCAdjust[Petroleum,ESC]=0.3883
  PCCAdjust[Rubber,ESC]=1.1966
  PCCAdjust[Cement,ESC]=0.0077
  PCCAdjust[Glass,ESC]=83.0646
  PCCAdjust[LimeGypsum,ESC]=1
  PCCAdjust[OtherNonMetallic,ESC]=1
  PCCAdjust[IronSteel,ESC]=0.0256
  PCCAdjust[Aluminum,ESC]=0.055
  PCCAdjust[OtherNonferrous,ESC]=1
  PCCAdjust[TransportEquipment,ESC]=0.8937
  PCCAdjust[OtherManufacturing,ESC]=1.0898
  PCCAdjust[IronOreMining,ESC]=1
  PCCAdjust[OtherMetalMining,ESC]=1
  PCCAdjust[NonMetalMining,ESC]=1.4759
  PCCAdjust[CoalMining,ESC]=11.0218
  PCCAdjust[Construction,ESC]=0.4209
  PCCAdjust[Forestry,ESC]=31.4229
  PCCAdjust[OnFarmFuelUse,ESC]=152.8646
  PCCAdjust[CropProduction,ESC]=1
  PCCAdjust[AnimalProduction,ESC]=1
  PCCAdjust[Food,WSC]=0.4101
  PCCAdjust[Textiles,WSC]=1
  PCCAdjust[Lumber,WSC]=0.9114
  PCCAdjust[Furniture,WSC]=1
  PCCAdjust[PulpPaperMills,WSC]=1.1107
  PCCAdjust[Petrochemicals,WSC]=0.7887
  PCCAdjust[IndustrialGas,WSC]=1
  PCCAdjust[OtherChemicals,WSC]=0.0232
  PCCAdjust[Fertilizer,WSC]=0.0076
  PCCAdjust[Petroleum,WSC]=0.3684
  PCCAdjust[Rubber,WSC]=1.0516
  PCCAdjust[Cement,WSC]=0.0037
  PCCAdjust[Glass,WSC]=7.6124
  PCCAdjust[LimeGypsum,WSC]=1
  PCCAdjust[OtherNonMetallic,WSC]=1
  PCCAdjust[IronSteel,WSC]=0.0086
  PCCAdjust[Aluminum,WSC]=0.0211
  PCCAdjust[OtherNonferrous,WSC]=1
  PCCAdjust[TransportEquipment,WSC]=0.7382
  PCCAdjust[OtherManufacturing,WSC]=0.9515
  PCCAdjust[IronOreMining,WSC]=1
  PCCAdjust[OtherMetalMining,WSC]=1
  PCCAdjust[NonMetalMining,WSC]=0.2204
  PCCAdjust[CoalMining,WSC]=845.4664
  PCCAdjust[Construction,WSC]=0.4164
  PCCAdjust[Forestry,WSC]=8.8688
  PCCAdjust[OnFarmFuelUse,WSC]=10.8646
  PCCAdjust[CropProduction,WSC]=1
  PCCAdjust[AnimalProduction,WSC]=1
  PCCAdjust[Food,Mtn]=0.3796
  PCCAdjust[Textiles,Mtn]=1
  PCCAdjust[Lumber,Mtn]=0.8461
  PCCAdjust[Furniture,Mtn]=1
  PCCAdjust[PulpPaperMills,Mtn]=1.3505
  PCCAdjust[Petrochemicals,Mtn]=1.9602
  PCCAdjust[IndustrialGas,Mtn]=1
  PCCAdjust[OtherChemicals,Mtn]=0.0102
  PCCAdjust[Fertilizer,Mtn]=0.0003
  PCCAdjust[Petroleum,Mtn]=0.5347
  PCCAdjust[Rubber,Mtn]=1.6717
  PCCAdjust[Cement,Mtn]=0.0028
  PCCAdjust[Glass,Mtn]=4.6541
  PCCAdjust[LimeGypsum,Mtn]=1
  PCCAdjust[OtherNonMetallic,Mtn]=1
  PCCAdjust[IronSteel,Mtn]=0.0085
  PCCAdjust[Aluminum,Mtn]=0.0074
  PCCAdjust[OtherNonferrous,Mtn]=1
  PCCAdjust[TransportEquipment,Mtn]=0.7677
  PCCAdjust[OtherManufacturing,Mtn]=1.1219
  PCCAdjust[IronOreMining,Mtn]=1
  PCCAdjust[OtherMetalMining,Mtn]=1
  PCCAdjust[NonMetalMining,Mtn]=0.936
  PCCAdjust[CoalMining,Mtn]=11.4077
  PCCAdjust[Construction,Mtn]=0.3995
  PCCAdjust[Forestry,Mtn]=6.6444
  PCCAdjust[OnFarmFuelUse,Mtn]=16.3341
  PCCAdjust[CropProduction,Mtn]=1
  PCCAdjust[AnimalProduction,Mtn]=1
  PCCAdjust[Food,Pac]=0.3498
  PCCAdjust[Textiles,Pac]=1
  PCCAdjust[Lumber,Pac]=1.1608
  PCCAdjust[Furniture,Pac]=1
  PCCAdjust[PulpPaperMills,Pac]=1.8214
  PCCAdjust[Petrochemicals,Pac]=1.8701
  PCCAdjust[IndustrialGas,Pac]=1
  PCCAdjust[OtherChemicals,Pac]=0.0009
  PCCAdjust[Fertilizer,Pac]=0.0038
  PCCAdjust[Petroleum,Pac]=4.4262
  PCCAdjust[Rubber,Pac]=39.4776
  PCCAdjust[Cement,Pac]=0.0023
  PCCAdjust[Glass,Pac]=10.3734
  PCCAdjust[LimeGypsum,Pac]=1
  PCCAdjust[OtherNonMetallic,Pac]=1
  PCCAdjust[IronSteel,Pac]=0.0054
  PCCAdjust[Aluminum,Pac]=0.0074
  PCCAdjust[OtherNonferrous,Pac]=1
  PCCAdjust[TransportEquipment,Pac]=13.249
  PCCAdjust[OtherManufacturing,Pac]=1.0459
  PCCAdjust[IronOreMining,Pac]=1
  PCCAdjust[OtherMetalMining,Pac]=1
  PCCAdjust[NonMetalMining,Pac]=0.6907
  PCCAdjust[CoalMining,Pac]=1
  PCCAdjust[Construction,Pac]=0.3987
  PCCAdjust[Forestry,Pac]=7.9821
  PCCAdjust[OnFarmFuelUse,Pac]=5.6587
  PCCAdjust[CropProduction,Pac]=1
  PCCAdjust[AnimalProduction,Pac]=1
  
  CN=Select(Nation,"CN")
  if MacroSwitch[CN] == "TOM"
    for year in Years, area in areas, ec in ecs, tech in Techs, enduse in Enduses
      if xPCC[enduse,tech,ec,area,year] != -99
        xPCC[enduse,tech,ec,area,year]=xPCC[enduse,tech,ec,area,year]*PCCAdjust[ec,area]
      end
    end
    WriteDisk(db,"$Input/xPCC",xPCC)
  end

end

function CalibrationControl(db)
  @info "AdjustProcessCapitalCosts_TOM.jl - CalibrationControl"

  CCalibration(db)
  ICalibration(db)

end

if abspath(PROGRAM_FILE) == @__FILE__
  CalibrationControl(DB)
end

end
