module Comparison

import EnergyModel as M
import PromulaDBA as P
using HDF5
using DataFrames
using CSV

const PRM_FOLDER = joinpath(@__DIR__, "../../EnergyModelPromula/2020Model")

const MATCHES = Dict(
  "Start" => [
    "IInput/DCCR",
    "IInput/DCMM",
    "IInput/DDay",
    "IInput/DDayNorm",
    "IInput/DDCoefficient",
    "IInput/DEM",
    "IInput/DEMM",
    "IInput/DEPM",
    "IInput/DEStd",
    "IInput/DEStdP",
    "IInput/DmdSw",
    "IInput/DmFracMax",
    "IInput/DmFracMin",
    "IInput/DmFracTime",
    "IInput/DOCF",
    "IInput/DUCFSw",
    "IInput/ECCMap",
    "IInput/FsPEE",
    "IInput/FsPOCA",
    "IInput/InitialDemandYear",
    "IInput/MMSM0",
    "IInput/MSMM",
    "IInput/PEEA0",
    "IInput/PEEB0",
    "IInput/PEEC0",
    "IInput/PEESw",
    "IInput/PEM",
    "IInput/PEMM",
    "IInput/PEPL",
    "IInput/PEPM",
    "IInput/POCA",
    "IInput/POCX",
    "IInput/RPEI",
    "IInput/xDEMM",
    "IInput/xDmd",
    "IInput/xFsFrac",
    "IInput/xMVF",
    "IInput/xPEE",
    "IInput/xPEMM",
    "IOutput/AMSF",
    "IOutput/DCC",
    "IOutput/DCCN",
    "IOutput/DCTC",
    "IOutput/DEE",
    "IOutput/DEEA",
    "IOutput/DER",
    "IOutput/DERA",
    "IOutput/DERAD",
    "IOutput/DERAP",
    "IOutput/DERR",
    "IOutput/DERRD",
    "IOutput/Dmd",
    "IOutput/DmFracMarginal",
    "IOutput/DPL",
    "IOutput/ECFP",
    "IOutput/ECFPFuel",
    "IOutput/EuDem",
    "IOutput/EUPC",
    "IOutput/EUPCA",
    "IOutput/EUPCAPC",
    "IOutput/EUPCR",
    "IOutput/EUPCRPC",
    "IOutput/FsDem",
    "IOutput/FsDmd",
    "IOutput/FsPol",
    "IOutput/PC",
    "IOutput/PCA",
    "IOutput/PCTC",
    "IOutput/PEEA",
    "IOutput/PER",
    "IOutput/PERAP",
    "IOutput/PERAPC",
    "IOutput/PERR",
    "IOutput/PERRP",
    "IOutput/PFTC",
    "IOutput/Polute",
    "RInput/CalibTime",
    "RInput/CERSM",
    "RInput/DCCR",
    "RInput/DDay",
    "RInput/DDayNorm",
    "RInput/DDCoefficient",
    "RInput/DEMM",
    "RInput/DEStdP",
    "RInput/DmFracTime",
    "RInput/DOCF",
    "RInput/ECCMap",
    "RInput/FsPEE",
    "RInput/FsPOCA",
    "RInput/InitialDemandYear",
    "RInput/MSMM",
    "RInput/MVF",
    "RInput/PCCMM",
    "RInput/PCPEM",
    "RInput/PEEA0",
    "RInput/PEEB0",
    "RInput/PEESw",
    "RInput/PEM",
    "RInput/PEMM",
    "RInput/PEPL",
    "RInput/POCA",
    "RInput/POCX",
    "RInput/RPEI",
    "RInput/TSLoad",
    "RInput/xDEMM",
    "RInput/xDmd",
    "RInput/xFsFrac",
    "ROutput/DCC",
    "ROutput/DCCN",
    "ROutput/DCTC",
    "ROutput/DEE",
    "ROutput/DEEA",
    "ROutput/DEEPrice",
    "ROutput/DER",
    "ROutput/DERA",
    "ROutput/DERR",
    "ROutput/DERRD",
    "ROutput/DERRPC",
    "ROutput/DFPN",
    "ROutput/DFTC",
    "ROutput/DmFrac",
    "ROutput/DmFracMarginal",
    "ROutput/DmFracMSF",
    "ROutput/DPL",
    "ROutput/ECFP",
    "ROutput/ECFPFuel",
    "ROutput/EuDem",
    "ROutput/EUPC",
    "ROutput/EUPCA",
    "ROutput/EUPCR",
    "ROutput/EUPCRPC",
    "ROutput/FsDem",
    "ROutput/FsDmd",
    "ROutput/FsFrac",
    "ROutput/MCFU",
    "ROutput/PCA",
    "ROutput/PCC",
    "ROutput/PCTC",
    "ROutput/PEE",
    "ROutput/PEEA",
    "ROutput/PER",
    "ROutput/PERA",
    "ROutput/PERAP",
    "ROutput/PERR",
    "ROutput/PERRP",
    "ROutput/PERRPC",
    "ROutput/PFPN",
    "ROutput/Polute",
    "MainDB/ANMap",
    "MInput/Driver",
    "SInput/FFPMap",
    "SInput/FlPlnMap",
    "SInput/FPSMF",
    "SInput/FPTaxF",
    "SInput/GCCC",
    "SInput/Hours",
    "SInput/MCE",
    "SInput/SecMap",
    "SInput/xEISector",
    "SInput/xEuDemand",
    "SInput/xFsDemand",
    "SInput/xTotDemand",
    "SOutput/CAProd",
    "SOutput/CgCap",
    "SOutput/CgGen",
    "SOutput/DInv",
    "SOutput/DOMExp",
    "SOutput/ENPN",
    "SOutput/EuDemand",
    "SOutput/FPBaseF",
    "SOutput/FPF",
    "SOutput/FPPolTaxF",
    "SOutput/FsDemand",
    "SOutput/FuelExpenditures",
    "SOutput/H2PipelineMultiplier",
    "SOutput/LDCECC",
    "SOutput/NcFPol",
    "SOutput/NcPol",
    "SOutput/OMExp",
    "SOutput/PCost",
    "SOutput/PInv",
    "SOutput/POMExp",
    "SOutput/SaEC",
    "SOutput/SqPol",
    "SOutput/TotDemand",
    "SOutput/TotFPol",
    "SOutput/TotPol",
    "spinput/CgCC",
    "spinput/CPrTax",
    "spinput/H2CCM",
    "spinput/H2CCN",
    "spinput/H2CD",
    "spinput/H2CUFMax",
    "spinput/H2CUFP",
    "spinput/H2DemandMSM0",
    "spinput/H2Eff",
    "spinput/H2ExportsCharge",
    "spinput/H2FsFrac",
    "spinput/H2FsPOCX",
    "spinput/H2FsYield",
    "spinput/H2GridFraction",
    "spinput/H2ImportsCharge",
    "spinput/H2ImportsMSM0",
    "spinput/H2MSFSwitch",
    "spinput/H2PipeA0",
    "spinput/H2PipeB0",
    "spinput/H2PipeC0",
    "spinput/H2PlantMap",
    "spinput/H2POCX",
    "spinput/H2SqFr",
    "spinput/H2Subsidy",
    "spinput/H2SupplyMSM0",
    "spinput/H2VF",
    "spinput/xExports",
    "spoutput/CADemand",
    "spoutput/CgDmd",
    "spoutput/Exports",
    "spoutput/H2Cap",
    "spoutput/H2CapCR",
    "spoutput/H2CapI",
    "spoutput/H2CapRR",
    "spoutput/H2CC",
    "spoutput/H2CUF",
    "spoutput/H2Dem",
    "spoutput/H2DemNation",
    "spoutput/H2Dmd",
    "spoutput/H2DmdEmissionCost",
    "spoutput/H2ECFP",
    "spoutput/H2EI",
    "spoutput/H2EIDmd",
    "spoutput/H2EmissionCost",
    "spoutput/H2ENPN",
    "spoutput/H2ENPNExports",
    "spoutput/H2ENPNImports",
    "spoutput/H2Exports",
    "spoutput/H2ExportsEst",
    "spoutput/H2ExportsMSF",
    "spoutput/H2FeedstockCost",
    "spoutput/H2FOMCost",
    "spoutput/H2FsDem",
    "spoutput/H2FsPol",
    "spoutput/H2FsPrice",
    "spoutput/H2FsReq",
    "spoutput/H2FuelCost",
    "spoutput/H2Imports",
    "spoutput/H2MCE",
    "spoutput/H2MSF",
    "spoutput/H2PipelineFraction",
    "spoutput/H2Prod",
    "spoutput/H2ProdNation",
    "spoutput/H2ProdTargetN",
    "spoutput/H2Production",
    "spoutput/H2SaEC",
    "spoutput/H2SqPol",
    "spoutput/H2VC",
    "spoutput/H2VOMCost",
    "spoutput/Imports",
    "spoutput/SupplyAdjustments",
    "IOutput/DmFracMSF",
    "ROutput/DERAD",
    "ROutput/FsPol",
    "IOutput/PERA",
    "IOutput/MMSF",
    "spoutput/H2Pol",
    "spoutput/H2Demand",
    "IInput/PCCMM",
    "spoutput/H2ImportsMSF",
    "spinput/H2ExportsMSM0",
    "IInput/xDmFrac",
    "SOutput/EnPol",
    "IOutput/PCC",
    "IOutput/DmFrac",
    "ROutput/MMSF",
    "IOutput/FsFrac",
    "SInput/Days",
    "IOutput/DERRP",
    "IInput/CalibTime",
    "IInput/PCPEM",
    "ROutput/PCCN",
    "SOutput/FsFP",
    "IOutput/MCFU",
    "spoutput/NGDemNation",
    "RInput/DEPM",
    "ROutput/PFTC",
    "MInput/PCPL",
    "ROutput/Dmd",
    "RInput/DEM",
    "spinput/H2ExportsVF",
    "spoutput/H2TransCost",
    "spoutput/H2ImportsEst",
    "ROutput/PC",
    "ROutput/PERAPC",
    "spinput/H2ImportsVF",
    "SOutput/CgInv",
    "IInput/MVF",
    "IInput/CERSM",
    "IOutput/PFPN",
    "RInput/PEEC0",
    "ROutput/DERAPC",
    "RInput/DmdSw",
    "spinput/xImports",
    "IOutput/DFPN",
    "IInput/TSLoad",
    "IOutput/DERAPC",
    "IOutput/DFTC",
    "ROutput/AMSF",
    "IOutput/PERRPC",
    "ROutput/EUPCAPC",
    "SInput/FPMarginF",
    "IOutput/DERRPC",
    "spoutput/NGDem",
    "RInput/DUCFSw",
    "spoutput/CProd",
    "SOutput/EnFPol",
    "RInput/DEStd",
    "SInput/xFPF",
    "SInput/xENPN",
    "spoutput/H2ProdTarget",
    "IOutput/PEE",
    "ROutput/DERRP",
    "IOutput/DEEPrice",
    "IInput/CUF",
    "RInput/PEPM",
    "RInput/CUF",
    "spoutput/CDemand",
    "RInput/xMVF",
    "spoutput/H2FPWholesale",
    "RInput/DCMM",
    "spinput/H2IPMultiplier",
    "RInput/DmFracMin",
    "ROutput/DERAP",
    "spoutput/H2EIFs",
    "spinput/H2Trans",
    "RInput/DmFracMax",
    "spoutput/H2FsEmissionCost",
    "IOutput/PCCN",
  ],
)

function main(db, kind)

  prm_folder = joinpath(PRM_FOLDER, kind)

  variables = Dict()

  h5open(db) do f
    for group in f
      for dataset in group
        attr = Dict(attrs(dataset))
        if "type" in keys(attr) && attr["type"] == "variable"
          variables[lstrip(HDF5.name(dataset), '/')] =
            [Symbol(dim) => collect(read(group["$dim"])) for dim in attr["dims"]]
        end
      end
    end
  end

  success_matches = []

  for k in keys(variables)
    if k in MATCHES[kind]
      continue
    end
    r = compare(db, prm_folder, k)
    if isnothing(r)
      @info "Unable to find $k in dba files"
      continue
    end
    df, _df = r
    if isempty(df)
      push!(success_matches, k)
      printstyled(
        "✓ $(round(size(df, 1) / size(_df, 1) * 100, digits=4))% difference when comparing $k\n";
        color = :blue,
      )
      # mkpath(joinpath(M.OutputFolder, dirname(k)))
      # CSV.write(joinpath(M.OutputFolder, "$k.csv"), df)
    else
      printstyled(
        "✗ $(round(size(df, 1) / size(_df, 1) * 100, digits=4))% difference when comparing $k\n";
        color = :red,
      )
      println(first(df,3))
    end
  end
end

function compare(db, prm_folder, k)
  filename, variable_name = String.(split(k, '/'))
  filename = joinpath(prm_folder, "$filename.dba")
  if !P.is_in_dba(filename, variable_name)
    return
  end
  _df = P.dataframe(filename, variable_name; skip_zeros = false)
  df = M.Outputs.output_df(db, k; skip_zeros = false)
  df[!, "prm_$variable_name"] = _df[!, variable_name]
  rename!(df, variable_name => "jl_$variable_name")
  df = subset(
    df,
    AsTable(["jl_$variable_name", "prm_$variable_name"]) => (x) -> (!).(isapprox.(first(x), last(x), rtol = 1e-3)),
  )
  (df, _df)
end

end
