#
# SuPollutionCFS.jl
#

module SuPollutionCFS

import ...EnergyModel: ReadDisk,WriteDisk,Select,ITime,MaxTime,HisTime,DT
import ...EnergyModel:@finite_math,finite_inverse,finite_divide,finite_power,finite_exp,finite_log

const VariableArray{N} = Array{Float32,N} where {N}
const SetArray = Vector{String}

Base.@kwdef struct Data
  db::String
  year::Int
  prior::Int
  next::Int
  CTime::Int
  BaseYearCg = 2020-ITime+1

  Area::SetArray = ReadDisk(db,"MainDB/AreaKey")
  Areas::Vector{Int} = collect(Select(Area))
  ECC::SetArray = ReadDisk(db,"MainDB/ECCKey")
  ECCs::Vector{Int} = collect(Select(ECC))
  ES::SetArray = ReadDisk(db,"MainDB/ESKey")
  ESes::Vector{Int} = collect(Select(ES))
  Fuel::SetArray = ReadDisk(db,"MainDB/FuelKey")
  Fuels::Vector{Int} = collect(Select(Fuel))
  FuelEP::SetArray = ReadDisk(db,"MainDB/FuelEPKey")
  FuelEPs::Vector{Int} = collect(Select(FuelEP))
  Market::SetArray = ReadDisk(db,"MainDB/MarketKey")
  Markets::Vector{Int} = collect(Select(Market))
  Nation::SetArray = ReadDisk(db,"MainDB/NationKey")
  Nations::Vector{Int} = collect(Select(Nation))
  Poll::SetArray = ReadDisk(db,"MainDB/PollKey")
  Polls::Vector{Int} = collect(Select(Poll))
  Process::SetArray = ReadDisk(db,"MainDB/ProcessKey")
  Processes::Vector{Int} = collect(Select(Process))
  Year::SetArray = ReadDisk(db,"MainDB/YearKey")
  
  RefNameDB::String = ReadDisk(db,"MainDB/RefNameDB") #  Reference Case Name

  ANMap::VariableArray{2} = ReadDisk(db,"MainDB/ANMap") #[Area,Nation]  Map between Area and Nation
  AreaMarket::VariableArray{2} = ReadDisk(db,"SInput/AreaMarket",year) #[Area,Market,Year]  Areas included in Market
  BaseSw::Float32 = ReadDisk(db,"SInput/BaseSw")[1] #[tv]  Base Case Switch (1=Base Case)
  CapTrade::VariableArray{1} = ReadDisk(db,"SInput/CapTrade",year) #[Market,Year]  Emission Cap and Trading Switch (1=Trade, Cap Only=2)
  CgCredits::VariableArray{1} = ReadDisk(db,"SInput/CgCredits",year) #[Market,Year]  CFS Credits for Cogeneration (Tonnes/GWh)
  CgDemand::VariableArray{3} = ReadDisk(db,"SOutput/CgDemand",year) #[Fuel,ECC,Area,Year]  Cogeneration Demands (TBtu/Yr)
  CgEC::VariableArray{2} = ReadDisk(db,"SOutput/CgEC",year) #[ECC,Area,Year]  Cogeneration Generation (GWh/Yr)
  CgECBaseYear::VariableArray{2} = ReadDisk(db,"SOutput/CgEC",BaseYearCg) #[ECC,Area,Year]  Cogeneration Generation (GWh/Yr)
  # CgECRef::VariableArray{2} = ReadDisk(RefNameDB,"SOutput/CgEC",year) #[ECC,Area,Year]  Cogeneration Generation from Reference Case (GWh/Yr)
  CgPol::VariableArray{3} = ReadDisk(db,"SOutput/CgPol",year) #[ECC,Poll,Area,Year]  Cogeneration Related Pollution (Tonnes/Yr)
  CgPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/CgPol",year) #[ECC,Poll,Area,Year]  Cogeneration Related Pollution (Tonnes/Yr)
  CoverageCFS::VariableArray{3} = ReadDisk(db,"SInput/CoverageCFS",year) #[Fuel,ECC,Area,Year]  Fuel Coverage for CFS (1=Covered)
  CreditsBanked::VariableArray{1} = ReadDisk(db,"SOutput/CreditsBanked",year) #[Market,Year]  CFS Credits Banked into Inventory (Tonnes/Yr)
  CreditsCogeneration::VariableArray{2} = ReadDisk(db,"SOutput/CreditsCogeneration",year) #[ECC,Area,Year]  CFS Credits Generated by Cogeneration (Tonnes/Yr)
  CreditsFossil::VariableArray{3} = ReadDisk(db,"SOutput/CreditsFossil",year) #[Fuel,ECC,Area,Year]  CFS Credits Generated by reducing Intensity of Fossil Fuels (Tonnes/Yr)
  CreditsFossilGenerated::VariableArray{1} = ReadDisk(db,"SOutput/CreditsFossilGenerated",year) #[Area,Year]  Fossil Credits Generated (Tonnes/Yr)
  CreditsFossilLimit::VariableArray{2} = ReadDisk(db,"SInput/CreditsFossilLimit",year) #[ECC,Area,Year]  Limit Fossil Credits used to meet Obligations (Tonnes/Tonne)
  CreditsFossilMaximum::VariableArray{1} = ReadDisk(db,"SOutput/CreditsFossilMaximum",year) #[Area,Year]  Maximum Usable Fossil Credits (Tonnes/Yr)
  CreditsFugitive::VariableArray{2} = ReadDisk(db,"SOutput/CreditsFugitive",year) #[ECC,Area,Year]  Fugitive Credits (Tonnes/Yr)
  CreditsGenerated::VariableArray{1} = ReadDisk(db,"SOutput/CreditsGenerated",year) #[Area,Year]  CFS Credits Generated (Tonnes/Yr)
  CreditsInventory::VariableArray{1} = ReadDisk(db,"SOutput/CreditsInventory",year) #[Market,Year]  CFS Credits Inventory (Tonnes/Yr)
  CreditsInventoryPrior::VariableArray{1} = ReadDisk(db,"SOutput/CreditsInventory",prior) #[Market,Prior]  CFS Credits Inventory (Tonnes/Yr)
  CreditsLowCarbon::VariableArray{3} = ReadDisk(db,"SOutput/CreditsLowCarbon",year) #[Fuel,ECC,Area,Year]  CFS Credits Generated by Low Carbon Fuels (Tonnes/Yr)
  CreditsNeeded::VariableArray{3} = ReadDisk(db,"SOutput/CreditsNeeded",year) #[Fuel,ECC,Area,Year]  CFS Credits Needed (Tonnes/Yr)
  CreditsOther::VariableArray{1} = ReadDisk(db,"SInput/CreditsOther",year) #[Area,Year]  CFS Credits Generated by Other Methods (Tonnes/Yr)
  CreditsRedeemed::VariableArray{1} = ReadDisk(db,"SOutput/CreditsRedeemed",year) #[Market,Year]  CFS Credits Redeemed from Inventory (Tonnes/Yr)
  CreditsRequired::VariableArray{1} = ReadDisk(db,"SOutput/CreditsRequired",year) #[Area,Year]  CFS Credits Required (Tonnes/Yr)
  CreditsSequester::VariableArray{2} = ReadDisk(db,"SOutput/CreditsSequester",year) #[ECC,Area,Year]  CFS Credits from Sequestering (Tonnes/Yr)
  CreditSwitch::VariableArray{3} = ReadDisk(db,"SInput/CreditSwitch",year) #[Fuel,ECC,Area,Year]  Switch to Indicate Fuels which must Purchase CFS Credits (1=Purchase)
  DemandCFS::VariableArray{3} = ReadDisk(db,"SOutput/DemandCFS",year) #[Fuel,ECC,Area,Year]  Energy Demands for CFS (TBtu/Yr)
  DirectCredits::VariableArray{1} = ReadDisk(db,"SInput/DirectCredits",year) #[Market,Year]  Direct Emission Reduction Credits (Tonnes/Tonnes)
  Driver::VariableArray{2} = ReadDisk(db,"MOutput/Driver",year) #[ECC,Area,Year]  Economic Driver (Various Millions/Yr)
  DriverRef::VariableArray{2} = ReadDisk(RefNameDB,"MOutput/Driver",year) #[ECC,Area,Year]  Economic Driver (Various Millions/Yr)
  EICFS::VariableArray{2} = ReadDisk(db,"SOutput/EICFS",year) #[Fuel,Area,Year]  Emission Intensity (Tonnes/TBtu)
  EIGapCFS::VariableArray{3} = ReadDisk(db,"SOutput/EIGapCFS",year) #[Fuel,ES,Area,Year]  Emission Intensity Gap between EI and EI Goal (Tonnes/TBtu)
  EIGapCFSPrior::VariableArray{3} = ReadDisk(db,"SOutput/EIGapCFS",prior) #[Fuel,ES,Area,Year]  Emission Intensity Gap between EI and EI Goal (Tonnes/TBtu)
  EIGoalCFS::VariableArray{3} = ReadDisk(db,"SInput/EIGoalCFS",year) #[Fuel,ES,Area,Year]  Emission Intensity Goal for CFS (Tonnes/TBtu)
  EIOfficial::VariableArray{2} = ReadDisk(db,"SInput/EIOfficial",year) #[Fuel,Area,Year]  Official Value for Emission Intensity (Tonnes/TBtu)
  EISector::VariableArray{2} = ReadDisk(db,"SOutput/EISector",year) #[ECC,Area,Year]  Sector Emission Intensity (Tonnes/TBtu)
  EISectorRef::VariableArray{2} = ReadDisk(RefNameDB,"SOutput/EISector",year) #[ECC,Area,Year]  Sector Emission Intensity for Reference Case (Tonnes/TBtu)
  EuPol::VariableArray{3} = ReadDisk(db,"SOutput/EuPol",year) #[ECC,Poll,Area,Year]  Enduse Energy Related Pollution (Tonnes/Yr)
  EnPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/EuPol",year) #[ECC,Poll,Area,Year]  Energy Related Pollution in Reference Case (Tonnes/Yr)
  ETADAP::VariableArray{1} = ReadDisk(db,"SInput/ETADAP",year) #[Market,Year]  Cost of Domestic Allowances from Government (Real US$/Tonne)
  ETAPr::VariableArray{1} = ReadDisk(db,"SOutput/ETAPr",year) #[Market,Year]  Cost of Emission Trading Allowances (US$/Tonne)
  ETRSw::VariableArray{1} = ReadDisk(db,"SInput/ETRSw") #[Market]  Permit Cost Switch (1 = Iterate Credits,2=Iterate Emissions,0 = Exogenous)
  EuDemand::VariableArray{3} = ReadDisk(db,"SOutput/EuDemand",year) #[Fuel,ECC,Area,Year]  Enduse Energy Demands (TBtu/Yr)
  ExchangeRate::VariableArray{1} = ReadDisk(db,"MOutput/ExchangeRate",year) #[Area,Year]  Local Currency/US$ Exchange Rate (Local/US$)
  Exports::VariableArray{2} = ReadDisk(db,"SpOutput/Exports",year) #[FuelEP,Nation,Year]  Primary Exports (TBtu/Yr)
  FFPMap::VariableArray{2} = ReadDisk(db,"SInput/FFPMap") #[FuelEP,Fuel]  Map between FuelEP and Fuel
  FlPol::VariableArray{3} = ReadDisk(db,"SOutput/FlPol",year) #[ECC,Poll,Area,Year]  Flaring Pollution (Tonnes/Yr)
  FlPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/FlPol",year) #[ECC,Poll,Area,Year]  Flaring Pollution in Reference Case (Tonnes/Yr)
  FPCFSFuel::VariableArray{3} = ReadDisk(db,"SOutput/FPCFSFuel",year) #[Fuel,ES,Area,Year]  CFS Fuel Price ($/mmBtu)
  FPCFSCredit::VariableArray{3} = ReadDisk(db,"SOutput/FPCFSCredit",year) #[Fuel,ES,Area,Year]  CFS Credit Price ($/Tonnes)
  FPCFSObligated::VariableArray{2} = ReadDisk(db,"SOutput/FPCFSObligated",year) #[ECC,Area,Year]  CFS Price for Obligated Sectors ($/Tonnes)
  FPCFSSwitch::VariableArray{2} = ReadDisk(db,"SInput/FPCFSSwitch",year) #[ECC,Area,Year]  CFS Price Switch (1=Full, 2=Partial, 0 = None)
  FSell::VariableArray{1} = ReadDisk(db,"SOutput/FSell",year) #[Market,Year]  Tech Fund Credits Sold into Market (Tonnes/Yr)
  FSellFraction::VariableArray{1} = ReadDisk(db,"SInput/FSellFraction",year) #[Market,Year]  Fraction of Credit Requirements Sold as Tech Fund Credits (Tonne/Tonne)
  FuCredits::VariableArray{1} = ReadDisk(db,"SInput/FuCredits",year) #[Market,Year]  Fugitive Emission Reduction Credits (Tonnes/Tonnes)
  FuPol::VariableArray{3} = ReadDisk(db,"SOutput/FuPol",year) #[ECC,Poll,Area,Year]  Other Fugitive Emissions (Tonnes/Yr)
  FuPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/FuPol",year) #[ECC,Poll,Area,Year]  Other Fugitive Emissions in Reference Case (Tonnes/Yr)
  Inflation::VariableArray{1} = ReadDisk(db,"MOutput/Inflation",year) #[Area,Year]  Inflation Index ($/$)
  ISell::VariableArray{1} = ReadDisk(db,"SOutput/ISell",year) #[Market,Year]  International Permits Sold (Tonnes/Yr)
  ObligatedCFS::VariableArray{2} = ReadDisk(db,"SInput/ObligatedCFS",year) #[ECC,Area,Year]  Obligated Sectors for CFS Emission Reductions (1=Obligated)
  OverBAB::VariableArray{1} = ReadDisk(db,"SOutput/OverBAB",year) #[Market,Year]  Overage Before Adjustment to Bank (Tonnes)
  MEPol::VariableArray{3} = ReadDisk(db,"SOutput/MEPol",year) #[ECC,Poll,Area,Year]  Non-Energy Pollution (Tonnes/Yr)
  MEPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/MEPol",year) #[ECC,Poll,Area,Year]  Non-Energy Pollution in Reference Case (Tonnes/Yr)
  NcPol::VariableArray{3} = ReadDisk(db,"SOutput/NcPol",year) #[ECC,Poll,Area,Year]  Non-Combustion Pollution (Tonnes/Yr)
  NcPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/NcPol",year) #[ECC,Poll,Area,Year]  Non-Combustion Pollution in Reference Case (Tonnes/Yr)
  OProd::VariableArray{2} = ReadDisk(db,"SOutput/OProd",year) #[Process,Nation,Year]  Primary Oil Production (TBtu/Yr)
  Part3::Float32 = ReadDisk(db,"SOutput/Part3",year) #[Year]  Part3 Credits Generated (Tonnes)
  Part3AT::Float32 = ReadDisk(db,"SInput/Part3AT",year) #[Year]  Part3 Averaging Time (Years)
  Part3GrossFraction::Float32 = ReadDisk(db,"SInput/Part3GrossFraction",year) #[Year]  Fraction of Credit Requirements Sold as Part 3 Credits (Tonne/Tonne)
  Part3Lv1::Float32 = ReadDisk(db,"SOutput/Part3Lv1",year) #[Year]  Part3 Credits in Level 1 (Tonnes)
  Part3Lv1Prior::Float32 = ReadDisk(db,"SOutput/Part3Lv1",prior) #[Prior]  Part3 Credits in Level 1 in Previous Year (Tonnes)
  Part3Lv2::Float32 = ReadDisk(db,"SOutput/Part3Lv2",year) #[Year]  Part3 Credits in Level 2 (Tonnes)
  Part3Lv2Prior::Float32 = ReadDisk(db,"SOutput/Part3Lv2",prior) #[Prior]  Part3 Credits in Level 2 in Previous Year (Tonnes)
  Part3Rt1::Float32 = ReadDisk(db,"SOutput/Part3Rt1",year) #[Year]  Part3 Credits leaving Level 1 (Tonnes)
  Part3Rt2::Float32 = ReadDisk(db,"SOutput/Part3Rt2",year) #[Year]  Part3 Credits leaving Level 2 (Tonnes)
  PBnkSw::VariableArray{1} = ReadDisk(db,"SInput/PBnkSw",year) #[Market,Year]  Banking Switch (1=Endo Prices, 2=Exog Prices)
  PolConv::VariableArray{1} = ReadDisk(db,"SInput/PolConv") #[Poll]  Pollution Conversion Factor (convert GHGs to eCO2)
  PSoECC::VariableArray{2} = ReadDisk(db,"SOutput/PSoECC",year) #[ECC,Area,Year]  Power Sold to Grid (GWh)
  PSoECCBaseYear::VariableArray{2} = ReadDisk(db,"SOutput/PSoECC", BaseYearCg) #[ECC,Area,Year]  Power Sold to Grid (GWh)
  RPPAProd::VariableArray{1} = ReadDisk(db,"SpOutput/RPPAProd",year) #[Area,Year]  Refined Petroleum Products (RPP) Production (TBtu/Yr)
  SecMap::VariableArray{1} = ReadDisk(db,"SInput/SecMap") #[ECC]  EC to ECC Set Map
  SqCredits::VariableArray{1} = ReadDisk(db,"SInput/SqCredits",year) #[Market,Year]  Sequestering  Credits (Tonnes/Tonnes)
  SqPol::VariableArray{3} = ReadDisk(db,"SOutput/SqPol",year) #[ECC,Poll,Area,Year]  Sequestering Emissions (Tonnes/Yr)
  SqPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/SqPol",year) #[ECC,Poll,Area,Year]  Sequestering Emissions in Reference Case (Tonnes/Yr)
  SqPolNet::VariableArray{3} = ReadDisk(db,"SOutput/SqPolNet",year) #[ECC,Poll,Area,Year]  Net Sequestering Emissions (Tonnes/Yr)
  TBuy::VariableArray{1} = ReadDisk(db,"SOutput/TBuy",year) #[Market,Year]  Total Permit Bought (Tonnes/Yr)
  TFP3Switch::VariableArray{1} = ReadDisk(db,"SInput/TFP3Switch",year) #[Market,Year]  Tech Fund or Part3 Switch (1=Tech Fund, 2=Part3)
  TotPol::VariableArray{3} = ReadDisk(db,"SOutput/TotPol",year) #[ECC,Poll,Area,Year]  Pollution (Tonnes/Yr)
  TotPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/TotPol",year) #[ECC,Poll,Area,Year]  Pollution in Reference Case (Tonnes/Yr)
  TSell::VariableArray{1} = ReadDisk(db,"SOutput/TSell",year) #[Market,Year]  Total Permit Sold (Tonnes/Yr)
  VnPol::VariableArray{3} = ReadDisk(db,"SOutput/VnPol",year) #[ECC,Poll,Area,Year]  Venting Pollution (Tonnes/Yr)
  VnPolRef::VariableArray{3} = ReadDisk(RefNameDB,"SOutput/VnPol",year) #[ECC,Poll,Area,Year]  Venting Pollution in Reference Case (Tonnes/Yr)
  xETAPr::VariableArray{1} = ReadDisk(db,"SInput/xETAPr",year) #[Market,Year]  Exogenous Cost of Emission Trading Allowances (1985 US$/Tonne)
  xFSell::VariableArray{1} = ReadDisk(db,"SInput/xFSell",year) #[Market,Year]  Tech Fund Permits Available (Tonnes/Yr)
  xISell::VariableArray{1} = ReadDisk(db,"SInput/xISell",year) #[Market,Year]  International Permits Available (Tonnes/Yr)

  #
  # Scratch Variables
  #
  DirectEICFS::VariableArray{2} = zeros(Float32,length(ECC),length(Area))
  DirectEICFSRef::VariableArray{2} = zeros(Float32,length(ECC),length(Area))
  DirectEmissions::VariableArray{2} = zeros(Float32,length(ECC),length(Area))
  DirectEmissionsRef::VariableArray{2} = zeros(Float32,length(ECC),length(Area))
  SqPolTotal::VariableArray{2} = zeros(Float32,length(ECC),length(Area))
end

#
# Coversions
#
# Tonnes/TBtu = g/MJ*Tonnes/g*MJ/TBtu
# Tonnes/TBtu = g/MJ*1/1000000*1054615/1
# Tonnes/TBtu = g/MJ*1.054615
# 1 TBtu = 1,054,615 megajoule
# 1 tonne = 1,000,000 gram
#

function ReferenceValues(data::Data)

  #@debug "  SuPollutionCFS.jl - Control - ReferenceValues
  
  # Nothing to do in Julia - Jeff Amlinh 6/18/24

end

function EIGap(data::Data,areas)
  (; db,year) = data
  (; ESes,Fuels) = data #sets
  (; EIGapCFS,EIGoalCFS,EIOfficial) = data

  @debug "  SuPollutionCFS.jl - Control - EIGap"

  for area in areas, es in ESes, fuel in Fuels
    EIGapCFS[fuel,es,area] = EIOfficial[fuel,area]-EIGoalCFS[fuel,es,area]
  end

  WriteDisk(db,"SOutput/EIGapCFS",year,EIGapCFS)

end

function CFSDemand(data::Data,areas)
  (; db,year) = data
  (; ECCs,Fuels) = data #sets
  (; CgDemand,CoverageCFS,DemandCFS,EuDemand) = data

  @debug "  SuPollutionCFS.jl - Control - CFSDemand"
  
  #
  # Demands Covered by CFS
  #
  for area in areas, ecc in ECCs, fuel in Fuels
    DemandCFS[fuel,ecc,area] = (EuDemand[fuel,ecc,area]+CgDemand[fuel,ecc,area])*CoverageCFS[fuel,ecc,area]
  end

  WriteDisk(db,"SOutput/DemandCFS",year,DemandCFS)

end

function RequiredCredits(data::Data,areas)
  (; db,year) = data
  (; ECCs,ESes,Fuels) = data #sets
  (; CreditsNeeded,CreditsRequired,CreditSwitch,DemandCFS,EIGoalCFS,EIOfficial,SecMap) = data

  @debug "  SuPollutionCFS.jl - Control - RequiredCredits"

  for es in ESes
    eccs = findall(SecMap .== es)
    for fuel in Fuels, ecc in eccs, area in areas
      CreditsNeeded[fuel,ecc,area] = 
        max(EIOfficial[fuel,area]-EIGoalCFS[fuel,es,area],0)*
        DemandCFS[fuel,ecc,area]*CreditSwitch[fuel,ecc,area]
    end
  end

  WriteDisk(db,"SOutput/CreditsNeeded",year,CreditsNeeded)

  for area in areas
    CreditsRequired[area] = sum(CreditsNeeded[fuel,ecc,area] for ecc in ECCs, fuel in Fuels)
  end

  WriteDisk(db,"SOutput/CreditsRequired",year,CreditsRequired)

end

function LowCarbonFuelCredits(data::Data,areas)
  (; db,year) = data
  (; Area,ECCs,ES,ESes,Fuel,Fuels) = data #sets
  (; CreditsLowCarbon,CreditsRequired,CreditSwitch,DemandCFS,EIGoalCFS,EIOfficial,SecMap) = data
  CreditsGaseousGenerated::VariableArray{1} = zeros(Float32,length(Area))
  CreditsGaseousMaximum::VariableArray{1} = zeros(Float32,length(Area))

  #@debug "  SuPollutionCFS.jl - Control - LowCarbonFuelCredits

  for area in areas, es in ESes, fuel in Fuels
    if ES[es] != "Transport"
      eccs = findall(SecMap .== es)
      for ecc in eccs
          CreditsLowCarbon[fuel,ecc,area] = max(EIGoalCFS[fuel,es,area]-EIOfficial[fuel,area],0)*DemandCFS[fuel,ecc,area]*(1-CreditSwitch[fuel,ecc,area])
      end
    end
  end

  #
  # Limit Credits from Gaseous stream
  #
  gaseousfuels = Select(Fuel,["Hydrogen","LPG","NaturalGas","RNG"])
  for area in areas
    CreditsGaseousMaximum[area] = CreditsRequired[area]*0.10
    CreditsGaseousGenerated[area] = sum(CreditsLowCarbon[fuel,ecc,area] for ecc in ECCs, fuel in gaseousfuels)
    for ecc in ECCs, fuel in gaseousfuels
      @finite_math CreditsLowCarbon[fuel,ecc,area] = CreditsLowCarbon[fuel,ecc,area]/CreditsGaseousGenerated[area]*CreditsGaseousMaximum[area]
    end
  end

  WriteDisk(db,"SOutput/CreditsLowCarbon",year,CreditsLowCarbon)

end

function FugitiveCredits(data::Data,areas)
  (; db,year) = data
  (; ECCs) = data #sets
  (; CreditsFugitive) = data

  #@debug "  SuPollutionCFS.jl - Control - FugitiveCredits

  #
  # Fugitive Credits are now part of Fossil Credits - Jeff Amlin 9/2/22
  #

  for area in areas, ecc in ECCs
    CreditsFugitive[ecc,area] = 0
  end

  WriteDisk(db,"SOutput/CreditsFugitive",year,CreditsFugitive)

  ##### Commented Out in Promula
  # 
  # Select Poll(CO2,CH4,N2O,SF6,PFC,HFC)
  # FugitiveEmissions=FlPol+FuPol+VnPol
  # FugitiveEmissionsRef=FlPolRef+FuPolRef+VnPolRef
  # 
  # FugitiveEICFS(ECC,Area)=sum(Poll)(FugitiveEmissions(ECC,Poll,Area)*PolConv(Poll))/
  #                         Driver(ECC,Area)
  # FugitiveEICFSRef(ECC,Area)=sum(Poll)(FugitiveEmissionsRef(ECC,Poll,Area)*PolConv(Poll))/
  #                            DriverRef(ECC,Area)
  # Select Poll*
  # 
  # CreditsFugitive = xmax(FugitiveEICFSRef-FugitiveEICFS,0)*Driver*ObligatedCFS*FuCredits
  # 
  # Write Disk(CreditsFugitive)
  # 

end

function CogenerationCredits(data::Data,areas,market)
  (; db,year) = data
  (; ECCs) = data #sets
  (; CgECBaseYear,PSoECCBaseYear,CgEC,CreditsCogeneration,PSoECC,CgCredits,ObligatedCFS) = data

  #@debug "  SuPollutionCFS.jl - Control - CogenerationCredits"

  for area in areas, ecc in ECCs
    CreditsCogeneration[ecc,area] = 
      max(((CgEC[ecc,area]-CgECBaseYear[ecc,area])-(PSoECC[ecc,area]-PSoECCBaseYear[ecc,area])),0)*
      CgCredits[market]*ObligatedCFS[ecc,area]
  end

  WriteDisk(db,"SOutput/CreditsCogeneration",year,CreditsCogeneration)

end

function SequesteringCredits(data::Data,areas,market)
  (; db,year) = data
  (; ECC,ECCs,FuelEP,Nation,Polls,Processes) = data #sets
  (; CreditsSequester,Exports,ObligatedCFS,OProd,PolConv,SqCredits,SqPolNet) = data
  (; SqPolTotal) = data

  #@debug "  SuPollutionCFS.jl - Control - SequesteringCredits"

  for area in areas, ecc in ECCs
    CreditsSequester[ecc,area] = 
      sum(0-SqPolNet[ecc,poll,area]*PolConv[poll] for poll in Polls)*  
      ObligatedCFS[ecc,area]*SqCredits[market]
  end

  CrudeOil = Select(FuelEP,"CrudeOil")
  CN = Select(Nation,"CN")
  eccs = Select(ECC,["LightOilMining","HeavyOilMining"])
  for area in areas, ecc in eccs
    CreditsSequester[ecc,area] = 
      sum(0-SqPolNet[ecc,poll,area]*PolConv[poll] for poll in Polls)*  
      ObligatedCFS[ecc,area]*SqCredits[market]*
      (1-Exports[CrudeOil,CN]/sum(OProd[process,CN] for process in Processes))
  end

  WriteDisk(db,"SOutput/CreditsSequester",year,CreditsSequester)

end

function FossilCredits(data::Data,areas,market)
  (; db,year) = data
  (; ECCs,Fuel,Fuels,Poll) = data
  (; CgPol,CgPolRef,CreditsFossil,CreditsFossilGenerated,CreditsFossilLimit) = data
  (; CreditsFossilMaximum,CreditsNeeded,DirectCredits,Driver,DriverRef) = data
  (; EuPol,EnPolRef,FlPol,FlPolRef,FuPol,FuPolRef,MEPol,MEPolRef) = data
  (; NcPol,NcPolRef,ObligatedCFS,PolConv,VnPol,VnPolRef) = data
  (; DirectEICFS,DirectEICFSRef,DirectEmissions,DirectEmissionsRef) = data  

  #@debug "  SuPollutionCFS.jl - Control - FossilCredits"

  GHG = Select(Poll,["CO2","CH4","N2O","SF6","PFC","HFC"])

  for area in areas, ecc in ECCs
    DirectEmissions[ecc,area] = sum((EuPol[ecc,poll,area]+
      CgPol[ecc,poll,area]+NcPol[ecc,poll,area]+MEPol[ecc,poll,area]+
      FlPol[ecc,poll,area]+FuPol[ecc,poll,area]+VnPol[ecc,poll,area])*PolConv[poll]
      for poll in GHG)
    DirectEmissionsRef[ecc,area] = sum((EnPolRef[ecc,poll,area]+
      CgPolRef[ecc,poll,area]+NcPolRef[ecc,poll,area]+MEPolRef[ecc,poll,area]+
      FlPolRef[ecc,poll,area]+FuPolRef[ecc,poll,area]+VnPolRef[ecc,poll,area])*PolConv[poll]
      for poll in GHG)

    @finite_math DirectEICFS[ecc,area] = DirectEmissions[ecc,area]/Driver[ecc,area]
    @finite_math DirectEICFSRef[ecc,area] = DirectEmissionsRef[ecc,area]/DriverRef[ecc,area]
  end

  for area in areas
    CreditsFossilMaximum[area] = sum(CreditsNeeded[fuel,ecc,area]*CreditsFossilLimit[ecc,area]
      for ecc in ECCs, fuel in Fuels)
  end

  fuel = Select(Fuel,"Gasoline")
  for area in areas, ecc in ECCs
    CreditsFossil[fuel,ecc,area] = max(DirectEICFSRef[ecc,area]-DirectEICFS[ecc,area],0)*
      Driver[ecc,area]*ObligatedCFS[ecc,area]*DirectCredits[market]
  end

  for area in areas
    CreditsFossilGenerated[area] = sum(CreditsFossil[fuel,ecc,area] for ecc in ECCs, fuel in Fuels)
  end

  for area in areas, fuel in Fuels, ecc in ECCs
    @finite_math CreditsFossil[fuel,ecc,area] = CreditsFossil[fuel,ecc,area]/
      CreditsFossilGenerated[area]*CreditsFossilMaximum[area]
  end

  WriteDisk(db,"SOutput/CreditsFossil",year,CreditsFossil)

end

function GeneratedCredits(data::Data,areas)
  (; db,year) = data
  (; ECCs,Fuels) = data #sets
  (; CreditsCogeneration,CreditsFossil,CreditsFugitive,CreditsGenerated) = data
  (; CreditsLowCarbon,CreditsOther,CreditsSequester) = data

  for area in areas
    CreditsGenerated[area] = sum(CreditsLowCarbon[fuel,ecc,area] for ecc in ECCs, fuel in Fuels)+
                           sum(CreditsFossil[fuel,ecc,area] for ecc in ECCs, fuel in Fuels)+
                           sum(CreditsFugitive[ecc,area] for ecc in ECCs)+
                           sum(CreditsCogeneration[ecc,area] for ecc in ECCs)+
                           sum(CreditsSequester[ecc,area] for ecc in ECCs)+
                               CreditsOther[area]
    end

  WriteDisk(db,"SOutput/CreditsGenerated",year,CreditsGenerated)

end

function VintagePart3Credits(data::Data,Part3)
  (; db,year) = data
  (; ) = data #sets
  (; Part3Rt1,Part3Lv1Prior,Part3AT,Part3Rt2,Part3Lv2Prior,Part3Lv1,Part3Lv2) = data

  #@debug "  SuPollutionCFS.jl - Control - TechFundPart3Credits - VintagePart3Credits"

  Part3Rt1 = Part3Lv1Prior/(Part3AT/2)
  Part3Rt2 = Part3Lv2Prior/(Part3AT/2)

  Part3Lv1 = Part3Lv1Prior+Part3-Part3Rt1
  Part3Lv2 = Part3Lv2Prior+Part3Rt1-Part3Rt2

  WriteDisk(db,"SOutput/Part3Lv1",year,Part3Lv1)
  WriteDisk(db,"SOutput/Part3Lv2",year,Part3Lv2)
  WriteDisk(db,"SOutput/Part3Rt1",year,Part3Rt1)
  WriteDisk(db,"SOutput/Part3Rt2",year,Part3Rt2)

end

function TechFundPart3Credits(data::Data,areas,market)
  (; db,year) = data
  (; CreditsGenerated,CreditsRequired,FSellFraction,Part3,Part3Rt2) = data
  (; Part3GrossFraction,TFP3Switch,xFSell) = data
  
  Loc1::Float32 = 0.0
  Loc2::Float32 = 0.0

  #@debug "  SuPollutionCFS.jl - Control - TechFundPart3Credits"

  # Read Disk(Part3,xFSell)

  if TFP3Switch[market] == 2
    #@debug "  SuPollutionCFS.jl - TechFundPart3Credits - TFP3Switch eq 2"
    Part3 = max(sum(CreditsRequired[area]-CreditsGenerated[area] for area in areas)*FSellFraction[market],
              sum(CreditsRequired[area]*Part3GrossFraction for area in areas))

    VintagePart3Credits(data,Part3)
    xFSell[market] = Part3Rt2

  else
    #@debug "  SuPollutionCFS.jl - TechFundPart3Credits - Else"
    xFSell[market] = sum(CreditsRequired[area] for area in areas)*FSellFraction[market]
  end

  WriteDisk(db,"SOutput/Part3",year,Part3)
  WriteDisk(db,"SInput/xFSell",year,xFSell)

  #@debug " "
  #@debug Market[market] Area[areas] year
  #@debug CreditsRequired[areas]
  #@debug CreditsGenerated[areas]
  #@debug FSellFraction[market]
  # Loc2 = sum(CreditsRequired[area]-CreditsGenerated[area] for area in areas)*FSellFraction[market]
  # Loc1 = max(Loc2,0)
  #@debug "Part3 Net          =" Loc1
  #@debug Part3GrossFraction
  # Loc1=sum(CreditsRequired[area] for area in areas)*Part3GrossFraction
  #@debug "Part3 Gross        =" Loc1
  #@debug Part3
  #@debug xFSell[market]
  #@debug FSell[market]
  #@debug " "

end

function CreditsForMarket(data::Data,areas,market)
  (; db,year) = data
  (; CreditsGenerated,CreditsInventoryPrior,CreditsRequired,ETRSw) = data
  (; ETADAP,FSell,ISell,TBuy,TFP3Switch,TSell,xETAPr,xFSell,xISell) = data

  #@debug "  SuPollutionCFS.jl - Control - CreditsForMarket"

  if ETRSw[market] == 0
    ISell[market] = xISell[market]
    WriteDisk(db,"SOutput/ISell",year,ISell)
    
    if xETAPr[market] >= ETADAP[market]
      FSell[market] = xFSell[market]
      WriteDisk(db,"SOutput/FSell",year,FSell)
    end
  end

  TBuy[market] = sum(CreditsRequired[area] for area in areas)

  if TFP3Switch[market] == 2
    TSell[market] = sum(CreditsGenerated[area] for area in areas)+
      CreditsInventoryPrior[market]+xFSell[market]
  else
    TSell[market] = sum(CreditsGenerated[area] for area in areas)+
      CreditsInventoryPrior[market]
  end
  WriteDisk(db,"SOutput/TBuy",year,TBuy)
  WriteDisk(db,"SOutput/TSell",year,TSell)

end

function CreditsBanking(data::Data,areas,market)
  (; db,year) = data
  (; CreditsBanked,CreditsGenerated,CreditsInventory,CreditsInventoryPrior) = data
  (; CreditsRedeemed,CreditsRequired,FSell,ISell,OverBAB) = data  

  #@debug "  SuPollutionCFS.jl - CFSCredits - CreditsBanking"

  #
  # Overage before adjustment to Banking
  #
  OverBAB[market] = sum(CreditsRequired[area]-CreditsGenerated[area] for area in areas)-
                  FSell[market]-ISell[market]

  WriteDisk(db,"SOutput/OverBAB",year,OverBAB)

  #
  # Force Redemption of Banked Credits to meet Goal
  #
  CreditsRedeemed[market] = max(min(OverBAB[market],CreditsInventoryPrior[market]),0)

  #
  #  Force Banking of Credits when Goal is exceeded
  #
  CreditsBanked[market] = max((0-OverBAB[market]),0)

  #
  #  Update Credit Inventory
  #
  CreditsInventory[market] = CreditsInventoryPrior[market]+
                           DT*(CreditsBanked[market]-CreditsRedeemed[market])  


  WriteDisk(db,"SOutput/CreditsBanked",year,CreditsBanked)
  WriteDisk(db,"SOutput/CreditsInventory",year,CreditsInventory)
  WriteDisk(db,"SOutput/CreditsRedeemed",year,CreditsRedeemed)

end

function Control(data::Data)
  (; Markets) = data #sets
  (; CapTrade,AreaMarket) = data

  @debug "  SuPollutionCFS.jl - Control"

  # Prior=Current-1
  # Prior=xmax(1,Prior)
  # Prior2=xmax(1,Prior-1)
  # 
  for market in Markets
    if (CapTrade[market] == 6) || (CapTrade[market] == 7)
      areas = findall(AreaMarket[:,market] .== 1)
      if !isempty(areas)
        #  ReferenceValues
        EIGap(data,areas)
        CFSDemand(data,areas)
        RequiredCredits(data,areas)
        LowCarbonFuelCredits(data,areas)
        FugitiveCredits(data,areas)
        CogenerationCredits(data,areas,market)
        SequesteringCredits(data,areas,market)
        FossilCredits(data,areas,market)
        GeneratedCredits(data,areas)
        TechFundPart3Credits(data,areas,market)
        CreditsForMarket(data,areas,market)
      end
    end
  end


end # function Control

function CFSCredits(data::Data)
  (; Markets) = data #sets
  (; AreaMarket,CapTrade) = data

  @debug "  SuPollutionCFS.jl - CFSCredits"

  for market in Markets
    if (CapTrade[market] == 6) || (CapTrade[market] == 7)
      areas = findall(AreaMarket[:,market] .== 1)
      if !isempty(areas)
        CreditsBanking(data,areas,market)
      end
    end
  end

end # function CFSCredits

function CFSPrices(data::Data)
  (; db,year) = data
  (; Areas,ESes,Fuels,Markets) = data #sets
  (; AreaMarket,CapTrade,EIGapCFSPrior,ETAPr,ExchangeRate) = data
  (; FPCFSCredit,FPCFSFuel,FPCFSObligated,ObligatedCFS,SecMap) = data

  #@debug "  SuPollutionCFS.jl - CFSPrices"

  for market in Markets
    if (CapTrade[market] == 6) || (CapTrade[market] == 7)
      for area in Areas
        if AreaMarket[area,market] == 1
          for es in ESes, fuel in Fuels
            FPCFSCredit[fuel,es,area] = ETAPr[market]
            FPCFSFuel[fuel,es,area] = EIGapCFSPrior[fuel,es,area]*
              FPCFSCredit[fuel,es,area]*ExchangeRate[area]/1000000
          end
          for es in ESes
            eccs = findall(SecMap .== es)
            for ecc in eccs
              FPCFSObligated[ecc,area] = maximum(FPCFSCredit[:,es,area])*ObligatedCFS[ecc,area]
            end
          end
        end
      end
    end
  end

  WriteDisk(db,"SOutput/FPCFSCredit",year,FPCFSCredit)
  WriteDisk(db,"SOutput/FPCFSFuel",year,FPCFSFuel)
  WriteDisk(db,"SOutput/FPCFSObligated",year,FPCFSObligated)

end # function CFSPrices

end # module SuPollutionCFS
