#
# TDemand2.jl
#

module TDemand2

import ...EnergyModel: ReadDisk,WriteDisk,Select,Yr
import ...EnergyModel: ITime,HisTime,MaxTime,Zero,First,Last,Future,Final,DT
import ...EnergyModel: @finite_math,EnergyModel,finite_inverse,finite_divide,finite_power,finite_exp,finite_log

const Input = "TInput"
const Outpt = "TOutput"
const CalDB = "TCalDB"

const VariableArray{N} = Array{Float32,N} where {N}
const SetArray = Vector{String}

const Sector::String = "Transport"

Base.@kwdef struct Data
    db::String
    year::Int
    prior::Int
    next::Int
    CTime::Int
    SceName::String

    Yr2010 = Yr(2010) # Pointer to 2010
    Yr1997 = Yr(1997) # Pointer to 1997
    Yr2000 = Yr(2000) # Pointer to 2000
    BaseYr = Yr(2018) # Pointer to Base Year
    CurTime::Float32 = ReadDisk(db,"$Input/CurTime")[1] # Year for capital costs [tv]
    YrDCC::Int = Int.(CurTime)  # Base Year for Device Capital Costs

    Age::SetArray = ReadDisk(db,"MainDB/AgeKey")
    Area::SetArray = ReadDisk(db,"MainDB/AreaKey")
    Areas::Vector{Int} = collect(Select(Area))
    EC::SetArray = ReadDisk(db,"$Input/ECKey")
    ECs::Vector{Int} = collect(Select(EC))
    ECC::SetArray = ReadDisk(db,"MainDB/ECCKey")
    Enduse::SetArray = ReadDisk(db,"$Input/EnduseKey")
    Enduses::Vector{Int} = collect(Select(Enduse))
    ES::SetArray = ReadDisk(db,"MainDB/ESKey")
    Fuel::SetArray = ReadDisk(db,"MainDB/FuelKey")
    Fuels::Vector{Int} = collect(Select(Fuel))
    FuelEP::SetArray = ReadDisk(db,"MainDB/FuelEPKey")
    Market::SetArray = ReadDisk(db,"MainDB/MarketKey")
    Month::SetArray = ReadDisk(db,"MainDB/MonthKey")
    Nation::SetArray = ReadDisk(db,"MainDB/NationKey")
    PCov::SetArray = ReadDisk(db,"MainDB/PCovKey")
    Poll::SetArray = ReadDisk(db,"MainDB/PollKey")
    Polls::Vector{Int} = collect(Select(Poll))
    Tech::SetArray = ReadDisk(db,"$Input/TechKey")
    Techs::Vector{Int} = collect(Select(Tech))
    CTech::SetArray = ReadDisk(db,"$Input/TechKey")

    ANMap::VariableArray{2} = ReadDisk(db,"MainDB/ANMap") # Map between Area and Nation [Area,Nation]
    CERSM::VariableArray{3} = ReadDisk(db,"$CalDB/CERSM",year) # Capital Energy Requirement (Btu/Btu) [Enduse,EC,Area]
    CoverageCFS::VariableArray{3} = ReadDisk(db,"SInput/CoverageCFS",year) # [Fuel,ECC,Area,Year] Fuel Coverage for CFS (1=Covered) 
    CreditsTech::VariableArray{5} = ReadDisk(db,"$Outpt/CreditsTech",year) # Credits Generated by Low Carbon Fuels (Tonnes/Yr)
    CreditsLowCarbon::VariableArray{3} = ReadDisk(db,"SOutput/CreditsLowCarbon",year) # [Enduse,Fuel,Tech,EC,Area,Year] Fuel Coverage for CFS (1=Covered) [Fuel,ECC,Area]
    CreditSwitch::VariableArray{3} = ReadDisk(db,"SInput/CreditSwitch",year) # Switch to Indicate Fuels which must Purchase Credits (1=Purchase) [Fuel,ECC,Area]
    CUF::VariableArray{4} = ReadDisk(db,"$CalDB/CUF",year) # Capacity Utilization Factor ($/Yr/$/Yr) [Enduse,Tech,EC,Area]
    DCCFullCost::VariableArray{4} = ReadDisk(db,"$Outpt/DCCFullCost",year) # Device Capital Cost Full Cost ($/mmBtu/Yr) [Enduse,Tech,EC,Area]
    DEE::VariableArray{4} = ReadDisk(db,"$Outpt/DEE",year) # Device Efficiency (Btu/Btu) [Enduse,Tech,EC,Area]
    DEEA::VariableArray{4} = ReadDisk(db,"$Outpt/DEEA",year) # Average Device Efficiency (Btu/Btu) [Enduse,Tech,EC,Area]
    DER::VariableArray{4} = ReadDisk(db,"$Outpt/DER",year) # Energy Requirement (mmBtu/YR) [Enduse,Tech,EC,Area]
    DERA::VariableArray{4} = ReadDisk(db,"$Outpt/DERA",year) # Energy Requirement Addition (mmBtu/YR) [Enduse,Tech,EC,Area]
    DERR::VariableArray{4} = ReadDisk(db,"$Outpt/DERR",year) # Device Energy Rqmt. Retire. (mmBtu/Yr/Yr) [Enduse,Tech,EC,Area]
    Dmd::VariableArray{4} = ReadDisk(db,"$Outpt/Dmd",year) # Total Energy Demand (TBtu/Yr) [Enduse,Tech,EC,Area]
    DmdFuelTech::VariableArray{5} = ReadDisk(db,"$Outpt/DmdFuelTech",year) # Energy Demands (TBtu/Yr) [Enduse,Fuel,Tech,EC,Area]
    DmdFuelTechBaseYr::VariableArray{5} = ReadDisk(db,"$Outpt/DmdFuelTech",BaseYr) # Energy Demands (TBtu/Yr) [Enduse,Fuel,Tech,EC,Area]
    EIGoal::VariableArray{5} = ReadDisk(db,"$Outpt/EIGoal",year) # Emission Intensity Goal for CFS (Tonnes/TBtu) [Enduse,Fuel,Tech,EC,Area]
    EIOfficial::VariableArray{2} = ReadDisk(db,"SInput/EIOfficial",year) # Official Value for Emission Intensity (Tonnes/TBtu) [Fuel,Area]
    EnergyPerStock::VariableArray{4} = ReadDisk(db,"$Outpt/EnergyPerStock",year) # Energy Capital per Vehicle Stock (Btu/Vehicle) [Enduse,Tech,EC,Area]
    EnergyPerStockPrior::VariableArray{4} = ReadDisk(db,"$Outpt/EnergyPerStock",prior) # Energy Capital per Vehicle Stock (Btu/Vehicle) [Enduse,Tech,EC,Area]
    Inflation::VariableArray{1} = ReadDisk(db,"MOutput/Inflation",year) # Inflation Index ($/$) [Area]
    Inflation2000::VariableArray{1} = ReadDisk(db,"MOutput/Inflation",Yr2000) # Inflation Index for 2010 ($/$) [Area]
    MEDriver::VariableArray{2} = ReadDisk(db,"MOutput/MEDriver",year) # Driver for Process Emissions (Various Millions/Yr)  [ECIM,Area]
    MEPOCX::VariableArray{3} = ReadDisk(db,"MEInput/MEPOCX",year) # Non-Energy Pollution Coefficient (Tonnes/$B-output)  [ECC,Poll,Area]
    MEPol::VariableArray{3} = ReadDisk(db,"SOutput/MEPol",year) # Process Pollution (Tonnes/Yr) [ECC,Poll,Area]
    MEPolSwitch::VariableArray{3} = ReadDisk(db,"SInput/MEPolSwitch",year) # Process Pollution Switch (0 = Exogenous) [ECC,Poll,Area]
    ORMEPOCX::VariableArray{3} = ReadDisk(db,"MEInput/ORMEPOCX",year) # Non-Energy Off Road Pollution Coefficient (Tonnes/Economic Driver) [ECC,Poll,Area]
    ORMEPol::VariableArray{3} = ReadDisk(db,"SOutput/ORMEPol",year) # Process Off Road Pollution (Tonnes/Year) [ECC,Poll,Area]
    PER::VariableArray{4} = ReadDisk(db,"$Outpt/PER",year) # Process Energy Requirement (mmBtu/YR) [Enduse,Tech,EC,Area]
    PERA::VariableArray{4} = ReadDisk(db,"$Outpt/PERA",year) # Process Energy Rqmt. Addition (mmBtu/Yr/Yr) [Enduse,Tech,EC,Area]
    RDCC::VariableArray{4} = ReadDisk(db,"$Outpt/RDCC",year) # Retrofit Device Capital Cost ($/($/Yr)) [Enduse,Tech,EC,Area]
    RDMSF::VariableArray{4} = ReadDisk(db,"$Outpt/RDMSF",year) # Device Retrofit Market Share Fraction by Device (1/Yr) [Enduse,Tech,EC,Area]
    THHS::VariableArray{1} = ReadDisk(db,"MOutput/THHS",year) # Total Households (Households) [Area]
    TrMEPol::VariableArray{4} = ReadDisk(db,"$Outpt/TrMEPol",year) # Non-Energy Pollution (Tonnes/Yr) [Tech,EC,Poll,Area]
    TrMEPX::VariableArray{4} = ReadDisk(db,"$Input/TrMEPX",year) # Non-Energy Pollution Coefficient (Tonnes/Vehicle Miles) [Tech,EC,Poll,Area]
    VDT::VariableArray{4} = ReadDisk(db,"$Outpt/VDT",year) # Vehicle Distance Traveled (Million Veh Pass-Miles or Ton-Miles/Yr)
    VehicleStockTotal::VariableArray{3} = ReadDisk(db,"$Outpt/VehicleStockTotal",year) # Stock of Vehicles (Vehicles) [Enduse,EC,Area]
    VehicleRetire::VariableArray{4} = ReadDisk(db,"$Outpt/VehicleRetire",year) # Retirement of Vehicles (Vehicles) [Enduse,Tech,EC,Area]
    VehicleStockTotalPrior::VariableArray{3} = ReadDisk(db,"$Outpt/VehicleStockTotal",prior) # Stock of Vehicles (Vehicles) [Enduse,EC,Area]
    VehicleSales::VariableArray{4} = ReadDisk(db,"$Outpt/VehicleSales",year) # Total Sales of Vehicles (Vehicles) [Enduse,Tech,EC,Area]
    VehicleStock::VariableArray{4} = ReadDisk(db,"$Outpt/VehicleStock",year) # Stock of Vehicles (Vehicles) [Enduse,Tech,EC,Area]
    VehicleStockPrior::VariableArray{4} = ReadDisk(db,"$Outpt/VehicleStock",prior) # Stock of Vehicles (Vehicles) [Enduse,Tech,EC,Area]
    xVehiclesPerHousehold::VariableArray{1} = ReadDisk(db,"$Input/xVehiclesPerHousehold",year) # Vehicles per Household (Vehicle/Household) [Area]
    xEnergyPerStockPrior::VariableArray{4} = ReadDisk(db,"$Input/xEnergyPerStock",prior) # Energy Capital per Vehicle Stock (Btu/Vehicle)
    xEnergyPerStock::VariableArray{4} = ReadDisk(db,"$Input/xEnergyPerStock",year) # Energy Capital per Vehicle Stock (Btu/Vehicle) [Enduse,Tech,EC,Area]
    xTrMEPol::VariableArray{4} = ReadDisk(db,"$Input/xTrMEPol",year) # Non-Energy Pollution (Tonnes/Yr) [Tech,EC,Poll,Area]


    VehicleSalesTotal::VariableArray{3} = zeros(Float32,length(Enduse),length(EC),length(Area))
    VehicleRetireTotal::VariableArray{3} = zeros(Float32,length(Enduse),length(EC),length(Area))
    VehicleSalesTotalEst::VariableArray{3} = zeros(Float32,length(Enduse),length(EC),length(Area))
    VehicleSalesEst::VariableArray{4} = zeros(Float32,length(Enduse),length(Tech),length(EC),length(Area))

end

function TotalVehicleStock(data::Data,ECSet)
    (; db,year) = data
    (; Areas,Enduses) = data
    (; VehicleStockTotal,xVehiclesPerHousehold,THHS) = data

    #@info "TotalVehicleStock Function Call"

    for enduse in Enduses, area in Areas
        VehicleStockTotal[enduse,ECSet,area] = THHS[area]*xVehiclesPerHousehold[area]
    end

    WriteDisk(db,"$Outpt/VehicleStockTotal",year,VehicleStockTotal)
end

function RetirementOfVehicles(data::Data,ECSet)
    (; db,year) = data
    (; Areas,Enduses,Techs) = data
    (; VehicleRetire,VehicleRetireTotal,DERR,EnergyPerStockPrior) = data

    #@info "RetirementOfVehicles Function Call"

    for enduse in Enduses, area in Areas, tech in Techs
        @finite_math VehicleRetire[enduse,tech,ECSet,area] =
          DERR[enduse,tech,ECSet,area]/EnergyPerStockPrior[enduse,tech,ECSet,area]
    end    
    WriteDisk(db,"$Outpt/VehicleRetire",year,VehicleRetire)
end

function SalesOfVehicles(data::Data,ECSet)
    (; db,year) = data
    (; Areas,Enduses,Techs) = data
    (; VehicleSalesTotal,VehicleStockTotal,VehicleStockTotalPrior,VehicleRetireTotal) = data
    (; VehicleSalesEst,DERA,EnergyPerStockPrior,VehicleSalesTotalEst,VehicleRetire) = data
    (; VehicleSales) = data

    #@info "SalesOfVehicles Function Call"
    
    #
    # Moved equation below from earlier procedure - Ian 06/02/25
    #
    for enduse in Enduses, area in Areas
        VehicleRetireTotal[enduse,ECSet,area] =
          sum(VehicleRetire[enduse,tech,ECSet,area] for tech in Techs)
    end
    
    for enduse in Enduses, area in Areas
        VehicleSalesTotal[enduse,ECSet,area] = VehicleStockTotal[enduse,ECSet,area]-
        VehicleStockTotalPrior[enduse,ECSet,area]+VehicleRetireTotal[enduse,ECSet,area]
    end

    for enduse in Enduses, area in Areas, tech in Techs
        @finite_math VehicleSalesEst[enduse,tech,ECSet,area] = DERA[enduse,tech,ECSet,area]/
        EnergyPerStockPrior[enduse,tech,ECSet,area]
    end

    for enduse in Enduses, area in Areas
        VehicleSalesTotalEst[enduse,ECSet,area] =
          sum(VehicleSalesEst[enduse,tech,ECSet,area] for tech in Techs)
    end

    for enduse in Enduses, area in Areas, tech in Techs
        @finite_math VehicleSales[enduse,tech,ECSet,area] = VehicleSalesTotal[enduse,ECSet,area]*
        VehicleSalesEst[enduse,tech,ECSet,area]/VehicleSalesTotalEst[enduse,ECSet,area]
    end
    
    WriteDisk(db,"$Outpt/VehicleSales",year,VehicleSales)

end

function StockOfVehicles(data::Data,ECSet)
    (; db,year) = data
    (; Areas,Enduses,Techs) = data
    (; VehicleStock,VehicleStockPrior,VehicleSales,VehicleRetire) = data

    #@info "StockOfVehicles Function Call"

    for enduse in Enduses, area in Areas, tech in Techs
        @finite_math VehicleStock[enduse,tech,ECSet,area] = VehicleStockPrior[enduse,tech,ECSet,area]+
                     VehicleSales[enduse,tech,ECSet,area]-VehicleRetire[enduse,tech,ECSet,area]
    end

    WriteDisk(db,"$Outpt/VehicleStock",year,VehicleStock)
end

function EnergyPerVehicle(data::Data,ECSet)
    (; db,year) = data
    (; Areas,Enduses,Techs) = data
    (; DER,EnergyPerStock,VehicleStock) = data

    #@info "StockOfVehicles Function Call"

    for enduse in Enduses, area in Areas, tech in Techs
        @finite_math EnergyPerStock[enduse,tech,ECSet,area] =
                     DER[enduse,tech,ECSet,area]/VehicleStock[enduse,tech,ECSet,area]
    end

    WriteDisk(db,"$Outpt/EnergyPerStock",year,EnergyPerStock)

end

function NumberOfVehicles(data::Data)
    (; db,year,CTime) = data
    (; Areas,EC,Enduses,Techs) = data
    (; EnergyPerStockPrior,xEnergyPerStockPrior,xEnergyPerStock,EnergyPerStock) = data
    (; VehicleStockTotalPrior,VehicleStockTotal,DER,VehicleStock) = data

    #@info "NumberOfVehicles Function Call"

    Passenger = Select(EC,"Passenger")
    FirstTime = First+ITime-1

    if CTime > HisTime
        TotalVehicleStock(data,Passenger)
        RetirementOfVehicles(data,Passenger)
        SalesOfVehicles(data,Passenger)
        StockOfVehicles(data,Passenger)
        EnergyPerVehicle(data,Passenger)
    else
        TotalVehicleStock(data,Passenger)
        @. EnergyPerStockPrior = xEnergyPerStockPrior
        if CTime == FirstTime
            @. VehicleStockTotalPrior = VehicleStockTotal
        end
        
        RetirementOfVehicles(data,Passenger)
        SalesOfVehicles(data,Passenger)
        for enduse in Enduses, area in Areas, tech in Techs
            @finite_math VehicleStock[enduse,tech,Passenger,area] = DER[enduse,tech,Passenger,area]/
            xEnergyPerStock[enduse,tech,Passenger,area]
        end
        WriteDisk(db,"$Outpt/VehicleStock",year,VehicleStock)
        @. EnergyPerStock = xEnergyPerStock
        WriteDisk(db,"$Outpt/EnergyPerStock",year,EnergyPerStock)
    end
end

function ProcessEmissions(data::Data)
    (; db,year) = data
    (; Areas,EC,ECs,ECC,Enduses,Polls,Techs) = data
    (; VDT,DEEA,Dmd,MEDriver,TrMEPol,TrMEPX,MEPolSwitch,xTrMEPol,MEPol) = data
    (; ORMEPOCX,ORMEPol,MEPOCX) = data

    #@info "ProcessEmissions Function Call"
    #
    # Driver for Process Emissions (Vehicle Miles Traveled)
    #
    @. VDT = Dmd*DEEA

    for ec in ECs, area in Areas
        ecc = Select(ECC,EC[ec])
        MEDriver[ecc,area] = sum(VDT[enduse,tech,ec,area] for tech in Techs, enduse in Enduses)
    end
    #
    # Road Dust emissions uses freight VDT as a driver
    #
    RoadDust = Select(ECC,"RoadDust")
    Freight = Select(ECC,"Freight")
    for area in Areas
        MEDriver[RoadDust,area] = MEDriver[Freight,area]
    end
    WriteDisk(db,"$Outpt/VDT",year,VDT)
    WriteDisk(db,"MOutput/MEDriver",year,MEDriver)
    #
    # Process Emissions
    #
    for area in Areas, tech in Techs, ec in ECs, poll in Polls
        ecc = Select(ECC,EC[ec])
        @finite_math TrMEPol[tech,ec,poll,area] = sum(VDT[enduse,tech,ec,area] for enduse in Enduses)*
        TrMEPX[tech,ec,poll,area]*MEPolSwitch[ecc,poll,area]+
        (xTrMEPol[tech,ec,poll,area]*(1-MEPolSwitch[ecc,poll,area]))
    end
    for area in Areas, ec in ECs, poll in Polls
        ecc = Select(ECC,EC[ec])
        @finite_math MEPol[ecc,poll,area] = sum(TrMEPol[tech,ec,poll,area] for tech in Techs)
    end
    #
    # Off Road emissions input is just at the sector level - Ian 10/06/14
    #
    for area in Areas, ec in ECs, poll in Polls
        ecc = Select(ECC,EC[ec])
        @finite_math ORMEPol[ecc,poll,area] = ORMEPOCX[ecc,poll,area]*MEDriver[ecc,area]
        @finite_math MEPOCX[ecc,poll,area] = sum(TrMEPol[tech,ec,poll,area] for tech in Techs)/
        MEDriver[ecc,area]
    end
    WriteDisk(db,"SOutput/MEPol",year,MEPol)
    WriteDisk(db,"$Outpt/TrMEPol",year,TrMEPol)
    WriteDisk(db,"SOutput/ORMEPol",year,ORMEPol)
    WriteDisk(db,"MEInput/MEPOCX",year,MEPOCX)

end

function LowCarbonCredits(data::Data)
    (; db,year) = data
    (; Areas,EC,ECs,ECC,Enduses,Fuels,Tech,Techs) = data
    (; CreditsTech,DmdFuelTechBaseYr,EIGoal,EIOfficial,DmdFuelTech,CreditSwitch,CoverageCFS) = data
    (; CreditsLowCarbon ) = data

    # @info "LowCarbonCredits Function Call"

    #
    # "Also, historical electricity demand assigned to electric buses
    # should be removed from credit generation. These ‘buses’ represent
    # subways and light rail, but are misclassified in the RESD and in
    # the National Inventory Report. So we are proposing to grant credits
    # only to incremental electric bus demand in the projections, ie only
    # credits granted to electricity demand greater than 2018 levels for
    # electric buses. Let me know if you want to talk about this."
    # From: Matthew Lewis Email on Friday, May 28, 2021 10:57 AM
    # Jeff Amlin 6/22/21
    #
    for ec in ECs, enduse in Enduses, fuel in Fuels, tech in Techs, area in Areas
        ecc = Select(ECC,EC[ec])
        CreditsTech[enduse,fuel,tech,ec,area] =
          max(EIGoal[enduse,fuel,tech,ec,area]-EIOfficial[fuel,area],0)*
          DmdFuelTech[enduse,fuel,tech,ec,area]*(1-CreditSwitch[fuel,ecc,area])*
          CoverageCFS[fuel,ecc,area]
    end

    ec = Select(EC,"Passenger")
    ecc = Select(ECC,EC[ec])
    tech = Select(Tech,"BusElectric")
    for enduse in Enduses, fuel in Fuels, area in Areas
      CreditsTech[enduse,fuel,tech,ec,area] = 
        max(EIGoal[enduse,fuel,tech,ec,area]-EIOfficial[fuel,area],0)*
        max(DmdFuelTech[enduse,fuel,tech,ec,area],DmdFuelTechBaseYr[enduse,fuel,tech,ec,area])*
        (1-CreditSwitch[fuel,ecc,area])*
        CoverageCFS[fuel,ecc,area]
    end

    for ec in ECs, fuel in Fuels, area in Areas
        ecc = Select(ECC,EC[ec])
        CreditsLowCarbon[fuel,ecc,area] = sum(CreditsTech[enduse,fuel,tech,ec,area]
                                              for enduse in Enduses, tech in Techs)
    end
    
    WriteDisk(db,"SOutput/CreditsLowCarbon",year,CreditsLowCarbon)
    WriteDisk(db,"$Outpt/CreditsTech",year,CreditsTech)
end

end

