#
# CInput.jl - Input Database creation file
#

Base.@kwdef struct CInput <: HDF5GroupDatabase
  db::String=DB
  ########################
  #
  # Define Sets
  #
  CTech = ReadSetFromCSV("CTechCom","Key")
  tv = ReadSetFromCSV("tv","Key")
  EC = ReadSetFromCSV("ECCom","Key")
  Enduse = ReadSetFromCSV("EnduseCom","Key")
  PI = ReadSetFromCSV("PICom","Key")
  Tech = ReadSetFromCSV("TechCom","Key")
  Vintage = ReadSetFromCSV("VintageCom","Key")
  Area = ReadSetFromCSV("Area","Key")
  Year = ReadSetFromCSV("Year","Key")
  Fuel = ReadSetFromCSV("Fuel","Key")
  Plant = ReadSetFromCSV("Plant","Key")
  Node = ReadSetFromCSV("Node","Key")
  FuelEP = ReadSetFromCSV("FuelEP","Key")
  Poll = ReadSetFromCSV("Poll","Key")
  PollX = ReadSetFromCSV("PollX","Key")
  Month = ReadSetFromCSV("Month","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  ES = ReadSetFromCSV("ES","Key")
  PCov = ReadSetFromCSV("PCov","Key")
  vEnduse = ReadSetFromCSV("vEnduse","Key")
  vTech = ReadSetFromCSV("vTech","Key")
  Hour = ReadSetFromCSV("Hour","Key")
  Day = ReadSetFromCSV("Day","Key")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
  CTechDS = ReadSetFromCSV("CTechCom","DS")
  CTechKey = ReadSetFromCSV("CTechCom","Key")
  ECDS = ReadSetFromCSV("ECCom","DS")
  ECKey = ReadSetFromCSV("ECCom","Key")
  EnduseDS = ReadSetFromCSV("EnduseCom","DS")
  EnduseKey = ReadSetFromCSV("EnduseCom","Key")
  PIDS = ReadSetFromCSV("PICom","DS")
  PIKey = ReadSetFromCSV("PICom","Key")
  TechDS = ReadSetFromCSV("TechCom","DS")
  TechKey = ReadSetFromCSV("TechCom","Key")
  VintageDS = ReadSetFromCSV("VintageCom","DS")
  VintageKey = ReadSetFromCSV("VintageCom","Key")
  BAT = CreateVariableInHDF5(db, "CInput/BAT", (:tv,),"Short Term Utilization Adjustment Time (Yr)","Yr")
  BE = CreateVariableInHDF5(db, "CInput/BE", (:tv,),"Budget Elasticity Factor (\$/\$)","\$/\$")
  BMM = CreateVariableInHDF5(db, "CInput/BMM", (:Enduse, :Tech, :EC, :Area, :Year),"Budget Multiplier Adjustment (Btu/Btu)","Btu/Btu")
  CalibTime = CreateVariableInHDF5(db, "CInput/CalibTime", (:EC, :Area),"Last Year of Calibration (Year)","Year")
  CFraction = CreateVariableInHDF5(db, "CInput/CFraction", (:Enduse, :Tech, :EC, :Area, :Year),"Fraction of Production Capacity open to Conversion (\$/\$)","\$/\$")
  CgAT = CreateVariableInHDF5(db, "CInput/CgAT", (:Tech, :EC, :Area, :Year),"Cogeneration Implementation Time (Years)","Years")
  CgBL = CreateVariableInHDF5(db, "CInput/CgBL", (:Tech, :EC, :Area),"Cogeneration Equipment Book Value Lifetime (Years)","Years")
  CgCC = CreateVariableInHDF5(db, "CInput/CgCC", (:Tech, :EC, :Area, :Year),"Cogeneration Capital Cost (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  CgCUFP = CreateVariableInHDF5(db, "CInput/CgCUFP", (:Tech, :EC, :Area),"Cogeneration Capacity Utilization Factor used for Planning (Btu/Btu)","Btu/Btu")
  CgDC = CreateVariableInHDF5(db, "CInput/CgDC", (:Tech, :Area),"Cogeneration Delivery Charge (\$/mmBtu)","\$/mmBtu")
  CgDmSw = CreateVariableInHDF5(db, "CInput/CgDmSw", (:Tech,),"Cogeneration Depletion Multiplier Switch (1=Active) (Switch)","1=Active")
  CgElectricFraction = CreateVariableInHDF5(db, "CInput/CgElectricFraction", (:Plant, :EC, :Area, :Year),"Cogeneration Electric Tech to Plant Fraction (MW/MW)","MW/MW")
  CgHRtM = CreateVariableInHDF5(db, "CInput/CgHRtM", (:Tech, :EC, :Area, :Year),"Marginal Cogeneration Heat Rate (Btu/KWh)","Btu/KWh")
  CgIVTC = CreateVariableInHDF5(db, "CInput/CgIVTC", (:Year,),"Cogeneration Investment Tax Credit (\$/\$)","\$/\$")
  CgLoad = CreateVariableInHDF5(db, "CInput/CgLoad", (:Tech,),"Cogeneration Demand Load to ECD (0=No, 1=Yes)","0=No, 1=Yes")
  CgMSMM = CreateVariableInHDF5(db, "CInput/CgMSMM", (:Tech, :EC, :Area, :Year),"Cogeneration Market Share Mult. Policy (\$/\$)","\$/\$")
  CgNodeFraction = CreateVariableInHDF5(db, "CInput/CgNodeFraction", (:EC, :Node, :Area, :Year),"Cogeneration EC and Area to Node Fraction (MW/MW)","MW/MW")
  CgOF = CreateVariableInHDF5(db, "CInput/CgOF", (:Tech, :EC, :Area),"Cogeneration Operation Cost Fraction (\$/Yr/\$)","\$/Yr/\$")
  CgOUREG = CreateVariableInHDF5(db, "CInput/CgOUREG", (:Tech, :EC, :Area, :Year),"Cogeneration Own Use Rate for Generation (GWh/GWh)","GWh/GWh")
  CgPL = CreateVariableInHDF5(db, "CInput/CgPL", (:Tech, :EC, :Area),"Cogeneration Equipment Lifetime (Years)","Years")
  CgPlantFraction = CreateVariableInHDF5(db, "CInput/CgPlantFraction", (:Tech, :Plant, :Year),"Cogeneration Tech to Plant Fraction (MW/MW)","MW/MW")
  CgPOCX = CreateVariableInHDF5(db, "CInput/CgPOCX", (:FuelEP, :EC, :Poll, :Area, :Year),"Cogeneration Pollution Coeff. (Tonnes/TBtu)","Tonnes/TBtu")
  CgPotMult = CreateVariableInHDF5(db, "CInput/CgPotMult", (:Tech, :EC, :Area, :Year),"Cogeneration Potential Multiplier (Btu/Btu)","Btu/Btu")
  CgPotSw = CreateVariableInHDF5(db, "CInput/CgPotSw", (:Tech, :EC, :Area),"Cogeneration Potential Switch (0=Steam, 1=Electric)","0=Steam, 1=Electric")
  CgResI = CreateVariableInHDF5(db, "CInput/CgResI", (:Tech, :Area),"Cogeneration Resource Base (mmBtu)","mmBtu")
  CgRisk = CreateVariableInHDF5(db, "CInput/CgRisk", (:Tech,),"Cogeneration Risk Premium (\$/\$)","\$/\$")
  CgSCM = CreateVariableInHDF5(db, "CInput/CgSCM", (:Tech,),"Cogeneration Shared Cost Mult. (\$/\$)","\$/\$")
  CgSqFr = CreateVariableInHDF5(db, "CInput/CgSqFr", (:FuelEP, :EC, :Poll, :Area, :Year),"Cogeneration Sequestered Pollution Fraction (Tonne/Tonne)","Tonne/Tonne")
  CgTL = CreateVariableInHDF5(db, "CInput/CgTL", (:Tech, :EC, :Area),"Cogeneration Tax Life (Years)","Years")
  CgVCSw = CreateVariableInHDF5(db, "CInput/CgVCSw", (:Tech,),"Cogeneration Switch for Incorporating Fuel Costs in Variable Costs (1=Include) (Switch)","1=Include")
  CHRM = CreateVariableInHDF5(db, "CInput/CHRM", (:EC, :Area, :Year),"Cooling to Heating Ratio Multiplier","NoUnit")
  CM = CreateVariableInHDF5(db, "CInput/CM", (:FuelEP, :Poll, :PollX),"Cross-over Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  CnvrtEU = CreateVariableInHDF5(db, "CInput/CnvrtEU", (:Enduse, :EC, :Area, :Year),"Conversion Switch","NoUnit")
  CROIN = CreateVariableInHDF5(db, "CInput/CROIN", (:Enduse, :Tech, :EC, :Area, :Year),"Conservation Return on Investment (\$/Yr/\$)","\$/Yr/\$")
  CurTime = CreateVariableInHDF5(db, "CInput/CurTime", (:tv,),"Year for capital costs (Time)","Time")
  DCCA0 = CreateVariableInHDF5(db, "CInput/DCCA0", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost A0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DCCB0 = CreateVariableInHDF5(db, "CInput/DCCB0", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost B0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DCCC0 = CreateVariableInHDF5(db, "CInput/DCCC0", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost C0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DCCLimit = CreateVariableInHDF5(db, "CInput/DCCLimit", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost Limit Multiplier (\$/\$)","\$/\$")
  DCCSubsidy = CreateVariableInHDF5(db, "CInput/DCCSubsidy", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost Subsidy (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  DCDEM = CreateVariableInHDF5(db, "CInput/DCDEM", (:Enduse, :Tech, :EC, :Area, :Year),"Device Cost to Efficiency Multiplier for Efficiency Program (\$/\$/(Btu/Btu))","\$/\$/(Btu/Btu")
  DCMM = CreateVariableInHDF5(db, "CInput/DCMM", (:Enduse, :Tech, :EC, :Area, :Year),"Capital Cost Maximum Mult.  (\$/\$)","\$/\$")
  DDay = CreateVariableInHDF5(db, "CInput/DDay", (:Enduse, :Area, :Year),"Annual Degree Days (Degree Days)","Degree Days")
  DDayMonthly = CreateVariableInHDF5(db, "CInput/DDayMonthly", (:Enduse, :Month, :Area, :Year),"Monthly Degree Days (Degree Days)","Degree Days")
  DDayNorm = CreateVariableInHDF5(db, "CInput/DDayNorm", (:Enduse, :Area),"Normal Annual Degree Days (Degree Days)","Degree Days")
  DDCoefficient = CreateVariableInHDF5(db, "CInput/DDCoefficient", (:Enduse, :EC, :Area, :Year),"Annual Energy Degree Day Coefficient (DD/DD)","DD/DD")
  DDHourly = CreateVariableInHDF5(db, "CInput/DDHourly", (:Enduse, :Month, :Area, :Year),"Hourly Degree Days (Degree Days)","Degree Days")
  DDHourlyCoefficient = CreateVariableInHDF5(db, "CInput/DDHourlyCoefficient", (:Enduse, :EC, :Area, :Year),"Hourly Demand Degree Day Coefficient (DD/DD)","DD/DD")
  DDSatFlag = CreateVariableInHDF5(db, "CInput/DDSatFlag", (:Enduse, :Month),"Flag for Degree Days in Saturation Equation (1=include)","1=include")
  DDSmoothingTime = CreateVariableInHDF5(db, "CInput/DDSmoothingTime", (:Enduse, :Area, :Year),"Smoothing Time for Annual Degree Days (Years)","Years")
  DEEA0 = CreateVariableInHDF5(db, "CInput/DEEA0", (:Enduse, :Tech, :EC, :Area, :Year),"Device A0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DEEAM = CreateVariableInHDF5(db, "CInput/DEEAM", (:Enduse, :Tech, :EC, :Area, :Year),"Average Device Efficiency Multiplier (Fraction)","Fraction")
  DEEB0 = CreateVariableInHDF5(db, "CInput/DEEB0", (:Enduse, :Tech, :EC, :Area, :Year),"Device B0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DEEC0 = CreateVariableInHDF5(db, "CInput/DEEC0", (:Enduse, :Tech, :EC, :Area, :Year),"Device C0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DEEFloorSw = CreateVariableInHDF5(db, "CInput/DEEFloorSw", (:EC, :Area, :Year),"Switch to Activate Floor for Device Efficiency (1=Activate)","1=Activate")
  DEEThermalMax = CreateVariableInHDF5(db, "CInput/DEEThermalMax", (:Enduse, :Tech, :EC, :Area),"Thermal Maximum Device Efficiency (Btu/Btu)","Btu/Btu")
  DEESw = CreateVariableInHDF5(db, "CInput/DEESw", (:Enduse, :Tech, :EC, :Area, :Year),"Switch for Device Efficiency (Switch)","Switch")
  DEM = CreateVariableInHDF5(db, "CInput/DEM", (:Enduse, :Tech, :EC, :Area),"Maximum Device Efficiency (Btu/Btu)","Btu/Btu")
  DEPM = CreateVariableInHDF5(db, "CInput/DEPM", (:Enduse, :Tech, :EC, :Area, :Year),"Device Energy Price Multiplier (\$/\$)","\$/\$")
  DERReduction = CreateVariableInHDF5(db, "CInput/DERReduction", (:Enduse, :Tech, :EC, :Area, :Year),"Device Energy Reduction Fraction ((mmBtu/Yr)/(mmBtu/Yr))","(mmBtu/Yr")
  DEStd = CreateVariableInHDF5(db, "CInput/DEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Device Eff. Standards (Btu/Btu)","Btu/Btu")
  DEStdP = CreateVariableInHDF5(db, "CInput/DEStdP", (:Enduse, :Tech, :EC, :Area, :Year),"Device Eff. Standards Policy (Btu/Btu)","Btu/Btu")
  DGF = CreateVariableInHDF5(db, "CInput/DGF", (:Enduse, :Tech, :EC, :Area, :Year),"Domestic Grant Fraction (\$/\$)","\$/\$")
  DInvTechExo = CreateVariableInHDF5(db, "CInput/DInvTechExo", (:Enduse, :Tech, :EC, :Area, :Year),"Device Exogenous Investments (M\$/Yr)","M\$/Yr")
  DIVTC = CreateVariableInHDF5(db, "CInput/DIVTC", (:Tech, :Area, :Year),"Device Investment Tax Credit (\$/\$)","\$/\$")
  DmdSw = CreateVariableInHDF5(db, "CInput/DmdSw", (:Tech, :EC, :Area, :Year),"DmdEnduse Switch (Switch)","Switch")
  xDmFrac = CreateVariableInHDF5(db, "CInput/xDmFrac", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Energy Demands Fuel/Tech Split (Fraction)","Fraction")
  DmFracMax = CreateVariableInHDF5(db, "CInput/DmFracMax", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Demand Fuel/Tech Fraction Maximum (Btu/Btu)","Btu/Btu")
  DmFracMin = CreateVariableInHDF5(db, "CInput/DmFracMin", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Demand Fuel/Tech Fraction Minimum (Btu/Btu)","Btu/Btu")
  DmFracVF = CreateVariableInHDF5(db, "CInput/DmFracVF", (:Enduse, :Fuel, :Tech, :EC, :Area),"Demand Fuel/Tech Fraction Variance Factor (Btu/Btu)","Btu/Btu")
  DOCF = CreateVariableInHDF5(db, "CInput/DOCF", (:Enduse, :Tech, :EC, :Area, :Year),"Device Operating Cost Fraction (\$/Yr/\$)","\$/Yr/\$")
  DPIVTC = CreateVariableInHDF5(db, "CInput/DPIVTC", (:Year,),"Device Policy Investment Tax Credit (\$/\$)","\$/\$")
  DRisk = CreateVariableInHDF5(db, "CInput/DRisk", (:Enduse, :Tech),"Device Risk Premium (\$/\$)","\$/\$")
  DRIVTC = CreateVariableInHDF5(db, "CInput/DRIVTC", (:Tech, :Area, :Year),"Device Retrofit Investment Tax Credit (\$/\$)","\$/\$")
  DSMEU = CreateVariableInHDF5(db, "CInput/DSMEU", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Enduse DSM Adjustment (GWh/Yr)","GWh/Yr")
  DSMEUInv = CreateVariableInHDF5(db, "CInput/DSMEUInv", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Enduse DSM Adjustment Investments (1985 M\$/Yr)","1985 M\$/Yr")
  DStA0 = CreateVariableInHDF5(db, "CInput/DStA0", (:Enduse, :EC, :Area, :Year),"Device Saturation Degree Day Coefficient (Btu/Btu/DD)","Btu/Btu/DD")
  DStB0 = CreateVariableInHDF5(db, "CInput/DStB0", (:Enduse, :EC, :Area, :Year),"Device Saturation Coefficient","NoUnit")
  DStC0 = CreateVariableInHDF5(db, "CInput/DStC0", (:Enduse, :EC, :Area, :Year),"Device Saturation Constant Term (Btu/Btu)","Btu/Btu")
  DStMax = CreateVariableInHDF5(db, "CInput/DStMax", (:Enduse, :EC, :Area),"Maximum Device Saturation (Btu/Btu)","Btu/Btu")
  DStMin = CreateVariableInHDF5(db, "CInput/DStMin", (:Enduse, :EC, :Area),"Minimum Device Saturation (Btu/Btu)","Btu/Btu")
  DUCFSw = CreateVariableInHDF5(db, "CInput/DUCFSw", (:Enduse,),"Daily Use Switch for Loading Cogeneration and Feedstock Demand (Switch)","Switch")
  ECCMap = CreateVariableInHDF5(db, "CInput/ECCMap", (:EC, :ECC),"Map between EC and ECC (Map)","Map")
  ECESMap = CreateVariableInHDF5(db, "CInput/ECESMap", (:EC, :ES),"Map between EC and ES for Prices (Map)","Map")
  ECMap = CreateVariableInHDF5(db, "CInput/ECMap", (:EC,),"Map between EC and ECC (Map)","Map")
  ECoverage = CreateVariableInHDF5(db, "CInput/ECoverage", (:EC, :Poll, :PCov, :Area, :Year),"Emissions Coverage (1=Covered)","1=Covered")
  ECovExo = CreateVariableInHDF5(db, "CInput/ECovExo", (:EC, :Poll, :PCov, :Area, :Year),"Emissions Coverage for Exogenous Cap-and-Trade (1=Covered)","1=Covered")
  EEImpact = CreateVariableInHDF5(db, "CInput/EEImpact", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Efficiency Impact (Btu/Btu)","Btu/Btu")
  EESat = CreateVariableInHDF5(db, "CInput/EESat", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Efficiency Saturation (Btu/Btu)","Btu/Btu")
  EESw = CreateVariableInHDF5(db, "CInput/EESw", (:Year,),"Energy Efficiency Switch (Endogenous=1, Exogenous=0, Skip=-1)","Endogenous=1, Exogenous=0, Skip=-1")
  EEUCosts = CreateVariableInHDF5(db, "CInput/EEUCosts", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Efficiency Unit Costs (\$/mmBtu)","\$/mmBtu")
  ElecMap = CreateVariableInHDF5(db, "CInput/ElecMap", (:Tech,),"Primary Electricity Technology (Map)","Map")
  EORDInv = CreateVariableInHDF5(db, "CInput/EORDInv", (:Area, :Year),"Device Investments for EOR (M\$/TBtu)","M\$/TBtu")
  EORDmd = CreateVariableInHDF5(db, "CInput/EORDmd", (:Area, :Year),"Demand for Motors for EOR (TBtu/TBtu)","TBtu/TBtu")
  ESHRt = CreateVariableInHDF5(db, "CInput/ESHRt", (:Tech, :EC, :Area, :Year),"Excess Steam Heat Rate (Btu/KWh)","Btu/KWh")
  ETSwitch = CreateVariableInHDF5(db, "CInput/ETSwitch", (:Tech, :Area, :Year),"Emerging Technology Switch (1=Emerging Technology)","1=Emerging Technology")
  FDCC = CreateVariableInHDF5(db, "CInput/FDCC", (:Enduse, :Tech, :CTech, :Area),"Fixed Device Capital Cost (\$/(MBTU/Yr))","\$/(MBTU/Yr")
  FDCCU = CreateVariableInHDF5(db, "CInput/FDCCU", (:Enduse, :Tech, :CTech, :Area, :Year),"Conversion Rebate","NoUnit")
  FPCPFrac = CreateVariableInHDF5(db, "CInput/FPCPFrac", (:Fuel, :EC, :Area, :Year),"Portion of Carbon Price which impacts Fungible Fuel Fraction (\$/\$)","\$/\$")
  FsPOCX = CreateVariableInHDF5(db, "CInput/FsPOCX", (:Fuel, :EC, :Poll, :Area, :Year),"Feedstock Marginal Pollution Coefficients (Tonnes/TBtu)","Tonnes/TBtu")
  FTMap = CreateVariableInHDF5(db, "CInput/FTMap", (:Fuel, :Tech),"Map between Fuel and Tech (Map)","Map")
  HPGeoFraction = CreateVariableInHDF5(db, "CInput/HPGeoFraction", (:EC, :Area, :Year),"Air Source Heat Pump Fraction of Geothermal Demand (TBtu/TBtu)","TBtu/TBtu")
  IdrtCost = CreateVariableInHDF5(db, "CInput/IdrtCost", (:Enduse, :Tech, :EC, :Area, :Year),"Indirect Costs (\$/mmBtu)","\$/mmBtu")
  InitialDemandYear = CreateVariableInHDF5(db, "CInput/InitialDemandYear", (:EC, :Area),"First Year of Calibration","NoUnit")
  MMSFExogenous = CreateVariableInHDF5(db, "CInput/MMSFExogenous", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Market Share Fraction by Device (Fraction)","Fraction")
  MMSFSwitch = CreateVariableInHDF5(db, "CInput/MMSFSwitch", (:Enduse, :Tech, :EC, :Area, :Year),"Market Share Switch (1=Endogenous, 0=Exogenous)","1=Endogenous, 0=Exogenous")
  MSMM = CreateVariableInHDF5(db, "CInput/MSMM", (:Enduse, :Tech, :EC, :Area, :Year),"Non-Price Market Share Factor Multiplier (\$/\$)","\$/\$")
  PCCA0 = CreateVariableInHDF5(db, "CInput/PCCA0", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost A0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PCCB0 = CreateVariableInHDF5(db, "CInput/PCCB0", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost B0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PCCC0 = CreateVariableInHDF5(db, "CInput/PCCC0", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost C0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PCCMM = CreateVariableInHDF5(db, "CInput/PCCMM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost Maximum Multiplier (\$/\$)","\$/\$")
  PCostExo = CreateVariableInHDF5(db, "CInput/PCostExo", (:FuelEP, :EC, :Poll, :Area, :Year),"Marginal Exogenous Permit Cost (Real \$/Tonnes)","Real \$/Tonnes")
  PCostM = CreateVariableInHDF5(db, "CInput/PCostM", (:FuelEP, :EC, :Poll, :Area, :Year),"Permit Cost Multiplier (\$/Tonne/\$/Tonne)","\$/Tonne/\$/Tonne")
  PCostN = CreateVariableInHDF5(db, "CInput/PCostN", (:FuelEP, :EC, :Poll, :Area),"Pollution Reduction Cost Normal (\$/Tonne)","\$/Tonne")
  PCPEM = CreateVariableInHDF5(db, "CInput/PCPEM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Cost to Efficiency Multiplier for Efficiency Program (\$/\$/(\$/Btu/(\$/Btu)))","\$/\$/(\$/Btu/(\$/Btu")
  PDif = CreateVariableInHDF5(db, "CInput/PDif", (:Enduse, :Tech, :EC, :Area),"Difference between the Initial Process Efficiency for each Technology (Btu/Btu)","Btu/Btu")
  PEEA0 = CreateVariableInHDF5(db, "CInput/PEEA0", (:Enduse, :Tech, :EC, :Area, :Year),"Process A0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEEB0 = CreateVariableInHDF5(db, "CInput/PEEB0", (:Enduse, :Tech, :EC, :Area, :Year),"Process B0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEEC0 = CreateVariableInHDF5(db, "CInput/PEEC0", (:Enduse, :Tech, :EC, :Area, :Year),"Process C0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEEFloorSw = CreateVariableInHDF5(db, "CInput/PEEFloorSw", (:EC, :Area, :Year),"Switch to Activate Floor for Process Efficiency (1=Activate)","1=Activate")
  PEElas = CreateVariableInHDF5(db, "CInput/PEElas", (:Enduse, :Tech, :EC, :Area, :Year),"Long Term Price Elasticity for Process Efficiency (\$/Btu)","\$/Btu")
  PEESw = CreateVariableInHDF5(db, "CInput/PEESw", (:Enduse, :Tech, :EC, :Area, :Year),"Switch for Process Efficiency (Switch)","Switch")
  PEMMSw = CreateVariableInHDF5(db, "CInput/PEMMSw", (:EC, :Area),"Process Efficiency Update Switch (1=Yes, 0=No)","1=Yes, 0=No")
  PEMMYr = CreateVariableInHDF5(db, "CInput/PEMMYr", (:tv,),"Process Efficiency Update Year (Year)","Year")
  PEMX = CreateVariableInHDF5(db, "CInput/PEMX", (:Enduse, :Tech, :EC, :Area),"Ratio of Maximum to Average Process Efficiency (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEPM = CreateVariableInHDF5(db, "CInput/PEPM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Energy Price Multiplier (\$/\$)","\$/\$")
  PERReduction = CreateVariableInHDF5(db, "CInput/PERReduction", (:Enduse, :Tech, :EC, :Area, :Year),"Process Energy Exogenous Retrofits Percentage ((mmBtu/Yr)/(mmBtu/Yr))","(mmBtu/Yr")
  PEStd = CreateVariableInHDF5(db, "CInput/PEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Standards (\$/Btu)","\$/Btu")
  PEStdP = CreateVariableInHDF5(db, "CInput/PEStdP", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Standards Policy (\$/Btu)","\$/Btu")
  PInvExo = CreateVariableInHDF5(db, "CInput/PInvExo", (:Enduse, :Tech, :EC, :Area, :Year),"Process Exogenous Investments (M\$/Yr)","M\$/Yr")
  PInvMinFrac = CreateVariableInHDF5(db, "CInput/PInvMinFrac", (:EC, :Area, :Year),"Minimum Fraction for Process Investments (\$/\$)","\$/\$")
  PIVTC = CreateVariableInHDF5(db, "CInput/PIVTC", (:Year,),"Process Investment Tax Credit (\$/\$)","\$/\$")
  POCAM = CreateVariableInHDF5(db, "CInput/POCAM", (:FuelEP, :EC, :Poll, :Area, :Year),"Average Pollution Coefficients Multiplier (Fraction)","Fraction")
  POCX = CreateVariableInHDF5(db, "CInput/POCX", (:Enduse, :FuelEP, :EC, :Poll, :Area, :Year),"Marginal Pollution Coeff. (Tonnes/TBtu)","Tonnes/TBtu")
  PolSw = CreateVariableInHDF5(db, "CInput/PolSw", (:Tech, :EC, :Poll, :Area, :Year),"Switch for Pollution Coefficients (Switch)","Switch")
  PPIVTC = CreateVariableInHDF5(db, "CInput/PPIVTC", (:Year,),"Process Policy Investment Tax Credit (\$/\$)","\$/\$")
  PrPCostAT = CreateVariableInHDF5(db, "CInput/PrPCostAT", (:EC, :Area),"Pollution Cost Adjustment Time (Years)","Years")
  PrPCostSw = CreateVariableInHDF5(db, "CInput/PrPCostSw", (:Year,),"Pollution Cost Switch","NoUnit")
  PVF = CreateVariableInHDF5(db, "CInput/PVF", (:FuelEP, :EC, :Poll, :Area),"Pollution Reduction Variance Factor ((\$/Tonne)/(\$/Tonne))","(\$/Tonne")
  RCD = CreateVariableInHDF5(db, "CInput/RCD", (:EC, :Poll),"Reduction Capital Construction Delay (Years)","Years")
  RCostM = CreateVariableInHDF5(db, "CInput/RCostM", (:FuelEP, :Poll, :Year),"Reduction Cost Technology Multiplier (\$/\$)","\$/\$")
  RCPL = CreateVariableInHDF5(db, "CInput/RCPL", (:EC, :Poll),"Reduction Capital Physical Life (Years)","Years")
  RCROIN = CreateVariableInHDF5(db, "CInput/RCROIN", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Conservation Return on Investment (\$/Yr/\$)","\$/Yr/\$")
  RDCCM = CreateVariableInHDF5(db, "CInput/RDCCM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Device Capital Cost Multiplier (\$/\$)","\$/\$")
  RDEMM = CreateVariableInHDF5(db, "CInput/RDEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Maximum Device Efficiency Multiplier (Btu/Btu)","Btu/Btu")
  RDEStd = CreateVariableInHDF5(db, "CInput/RDEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Device Eff. Standards (Btu/Btu)","Btu/Btu")
  RDVF = CreateVariableInHDF5(db, "CInput/RDVF", (:EC, :Area),"Device Retrofit Market Share Variance Factor (DLESS)","DLESS")
  RetroSw = CreateVariableInHDF5(db, "CInput/RetroSw", (:Enduse, :EC, :Area, :Year),"Retrofit Switch (Switch)","Switch")
  RetroSwExo = CreateVariableInHDF5(db, "CInput/RetroSwExo", (:Year,),"Switch for Exogneous Retrofit Policy (=Method)","=Method")
  RGF = CreateVariableInHDF5(db, "CInput/RGF", (:Enduse, :Tech, :EC, :Area, :Year),"Device Retrofit Rebate Fraction (Fraction)","Fraction")
  RHCM = CreateVariableInHDF5(db, "CInput/RHCM", (:EC, :Area, :Year),"Retrofit Hassle-Cost Multiplier (\$/\$)","\$/\$")
  ROCF = CreateVariableInHDF5(db, "CInput/ROCF", (:FuelEP, :EC, :Poll, :Area),"Polution Reducution O&M (\$/Tonne)","\$/Tonne")
  ROIN = CreateVariableInHDF5(db, "CInput/ROIN", (:EC, :Area),"Return on Investment (\$/Yr/\$)","\$/Yr/\$")
  RPCCM = CreateVariableInHDF5(db, "CInput/RPCCM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Process Capital Cost Multiplier (\$/\$)","\$/\$")
  RPCSw = CreateVariableInHDF5(db, "CInput/RPCSw", (:EC, :Poll, :Area, :Year),"Pollution Reduction Curve Switch (1=2009, 2=2004)","1=2009, 2=2004")
  RPEEFr = CreateVariableInHDF5(db, "CInput/RPEEFr", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Fraction for Retrofits (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  RPEIX = CreateVariableInHDF5(db, "CInput/RPEIX", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Impact of Pollution Reduction Coefficient (Btu/Btu/Tonne/Tonne)","Btu/Btu/Tonne/Tonne")
  RPEMM = CreateVariableInHDF5(db, "CInput/RPEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Maximum Device Efficiency Multiplier (Btu/Btu)","Btu/Btu")
  RPEStd = CreateVariableInHDF5(db, "CInput/RPEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Standards (\$/Btu)","\$/Btu")
  RPIVTC = CreateVariableInHDF5(db, "CInput/RPIVTC", (:Area, :Year),"Process Retrofit Policy Investment Tax Credit (\$/\$)","\$/\$")
  RPMSLimit = CreateVariableInHDF5(db, "CInput/RPMSLimit", (:EC, :Area, :Year),"Process Retrofit Market Share Limit (1/Yr)","1/Yr")
  RPVF = CreateVariableInHDF5(db, "CInput/RPVF", (:EC, :Area),"Process Retrofit Market Share Variance Factor (DLESS)","DLESS")
  RRisk = CreateVariableInHDF5(db, "CInput/RRisk", (:Enduse, :Tech, :Area, :Year),"Retrofit Excess Risk (\$/\$)","\$/\$")
  SqEUTechMap = CreateVariableInHDF5(db, "CInput/SqEUTechMap", (:Enduse, :Tech),"Sequestering Enduse Map to Tech (1=include)","1=include")
  SqEnMap = CreateVariableInHDF5(db, "CInput/SqEnMap", (:Enduse,),"Sequestering Enduse Map (1=include)","1=include")
  SqPenaltyFuel = CreateVariableInHDF5(db, "CInput/SqPenaltyFuel", (:Fuel, :EC, :Area, :Year),"Sequestering Energy Penalty (TBtu/Tonne CO2)","TBtu/Tonne CO2")
  SqPenaltyTech = CreateVariableInHDF5(db, "CInput/SqPenaltyTech", (:Tech, :EC, :Poll, :Area, :Year),"Sequestering Energy Penalty (TBtu/Tonne)","TBtu/Tonne")
  SbMSM0 = CreateVariableInHDF5(db, "CInput/SbMSM0", (:Enduse, :Tech, :EC, :Area, :Year),"Non-Price Factor for High Efficiency Device Market Share (\$/\$)","\$/\$")
  SbVF = CreateVariableInHDF5(db, "CInput/SbVF", (:Enduse, :Tech, :EC, :Area, :Year),"Price Variance Factor for High Efficiency Device Market Share (\$/\$)","\$/\$")
  STFSw = CreateVariableInHDF5(db, "CInput/STFSw", (:Fuel, :Area),"Short Term Forecast Switch (1=On, 0=Off)","1=On, 0=Off")
  StockAdjustment = CreateVariableInHDF5(db, "CInput/StockAdjustment", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Capital Stock Adjustment (\$/\$)","\$/\$")
  STX = CreateVariableInHDF5(db, "CInput/STX", (:Area, :Year),"Sales Tax Rate on Energy Consumer (\$/\$)","\$/\$")
  TAXPCT = CreateVariableInHDF5(db, "CInput/TAXPCT", (:Area, :Year),"Standard accounting percent of device life that is taxed. (%)","%")
  TSLoad = CreateVariableInHDF5(db, "CInput/TSLoad", (:Enduse, :EC, :Area),"Temperature Sensitive Fraction of Load (Btu/Btu)","Btu/Btu")
  TxRt = CreateVariableInHDF5(db, "CInput/TxRt", (:EC, :Area, :Year),"Income Tax Rate on Energy Consumer (\$/\$)","\$/\$")
  vEUMap = CreateVariableInHDF5(db, "CInput/vEUMap", (:vEnduse, :Enduse),"Map between Enduse and vEnduse","NoUnit")
  vFlMap = CreateVariableInHDF5(db, "CInput/vFlMap", (:Fuel, :Tech),"Map between Tech and Fuel","NoUnit")
  vFsMap = CreateVariableInHDF5(db, "CInput/vFsMap", (:Fuel, :Tech),"Feedstock Map between Tech and Fuel","NoUnit")
  VRP = CreateVariableInHDF5(db, "CInput/VRP", (:FuelEP, :EC, :Poll, :Area, :Year),"Voluntary Reduction Policy (Tonnes/Tonnes)","Tonnes/Tonnes")
  VRRT = CreateVariableInHDF5(db, "CInput/VRRT", (:EC,),"Voluntary Reduction response time (Years)","Years")
  vTechMap = CreateVariableInHDF5(db, "CInput/vTechMap", (:vTech, :Tech),"Map between Tech and vTech","NoUnit")
  xCgDmd = CreateVariableInHDF5(db, "CInput/xCgDmd", (:Tech, :EC, :Area, :Year),"Historical Cogeneration (TBtu/Yr)","TBtu/Yr")
  xCgEG = CreateVariableInHDF5(db, "CInput/xCgEG", (:Tech, :EC, :Area, :Year),"Historical Electricity from Cogeneration (GWh/Yr)","GWh/Yr")
  xCgHRtA = CreateVariableInHDF5(db, "CInput/xCgHRtA", (:Tech, :EC, :Area, :Year),"Historical Average Cogeneration Heat Rate (Btu/KWh)","Btu/KWh")
  xCgIGC = CreateVariableInHDF5(db, "CInput/xCgIGC", (:Tech, :EC, :Area, :Year),"Exogenous Indicated Cogeneration Capacity (MW)","MW")
  xCgLSF = CreateVariableInHDF5(db, "CInput/xCgLSF", (:Tech, :EC, :Hour, :Day, :Month, :Area),"Cogeneration Load Shape (MW/MW)","MW/MW")
  xCgLSFSold = CreateVariableInHDF5(db, "CInput/xCgLSFSold", (:EC, :Hour, :Day, :Month, :Area),"Cogeneration Sold to Grid Load Shape (MW/MW)","MW/MW")
  xCgVF = CreateVariableInHDF5(db, "CInput/xCgVF", (:Tech, :EC),"Cogeneration Variance Factor (\$/\$)","\$/\$")
  xCMSF = CreateVariableInHDF5(db, "CInput/xCMSF", (:Enduse, :Tech, :CTech, :EC, :Area, :Year),"Conversion Market Share by Device (\$/\$)","\$/\$")
  xDCC = CreateVariableInHDF5(db, "CInput/xDCC", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  xDCCPolicy = CreateVariableInHDF5(db, "CInput/xDCCPolicy", (:Enduse, :Tech, :EC, :Area, :Year),"Capital Cost of Policy Device (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  xDCMM = CreateVariableInHDF5(db, "CInput/xDCMM", (:Enduse, :Tech, :EC, :Area, :Year),"Maximum Capital Cost Multiplier (Btu/Btu)","Btu/Btu")
  xDEE = CreateVariableInHDF5(db, "CInput/xDEE", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Device Efficiency (Btu/Btu)","Btu/Btu")
  xDEEA = CreateVariableInHDF5(db, "CInput/xDEEA", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Average Device Efficiency (Btu/Btu)","Btu/Btu")
  xDEEPolicy = CreateVariableInHDF5(db, "CInput/xDEEPolicy", (:Enduse, :Tech, :EC, :Area, :Year),"Policy Device Efficiency (Btu/Btu) (Btu/Btu)","Btu/Btu")
  xDEEPolicyMSF = CreateVariableInHDF5(db, "CInput/xDEEPolicyMSF", (:Enduse, :Tech, :EC, :Area, :Year),"Policy Participation Response (Btu/Btu)","Btu/Btu")
  xDEMM = CreateVariableInHDF5(db, "CInput/xDEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Maximum Device Efficiency Multiplier (Btu/Btu)","Btu/Btu")
  xDmd = CreateVariableInHDF5(db, "CInput/xDmd", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Energy Demand (TBtu/Yr)","TBtu/Yr")
  xDmdTrend = CreateVariableInHDF5(db, "CInput/xDmdTrend", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Energy Demand (TBtu/Yr)","TBtu/Yr")
  xDPL = CreateVariableInHDF5(db, "CInput/xDPL", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Physical Life of Equipment (Years)","Years")
  xDSt = CreateVariableInHDF5(db, "CInput/xDSt", (:Enduse, :EC, :Area, :Year),"Device Saturation (Btu/Btu)","Btu/Btu")
  xDUF = CreateVariableInHDF5(db, "CInput/xDUF", (:Enduse, :EC, :Day, :Month, :Area),"Daily Use Factor (Therm/Therm)","Therm/Therm")
  xEE = CreateVariableInHDF5(db, "CInput/xEE", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Energy Efficiency (TBtu)","TBtu")
  xFsDmd = CreateVariableInHDF5(db, "CInput/xFsDmd", (:Tech, :EC, :Area, :Year),"Feedstock Energy (TBtu/Yr)","TBtu/Yr")
  xFsFrac = CreateVariableInHDF5(db, "CInput/xFsFrac", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Demands Fuel/Tech Split (Fraction)","Fraction")
  xLSF = CreateVariableInHDF5(db, "CInput/xLSF", (:Enduse, :EC, :Hour, :Day, :Month, :Area),"Load Shape Factor (MW/MW)","MW/MW")
  xMVF = CreateVariableInHDF5(db, "CInput/xMVF", (:Enduse, :Tech, :EC, :Area, :Year),"Market Share Variance Factor (\$/\$)","\$/\$")
  xPCC = CreateVariableInHDF5(db, "CInput/xPCC", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost (\$/(\$/Yr))","\$/(\$/Yr")
  xPEE = CreateVariableInHDF5(db, "CInput/xPEE", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Process Efficiency (\$/Btu)","\$/Btu")
  xPEEA = CreateVariableInHDF5(db, "CInput/xPEEA", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Average Process Efficiency (\$/Btu)","\$/Btu")
  xPEMM = CreateVariableInHDF5(db, "CInput/xPEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Maximum Multiplier(\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  xPkSav = CreateVariableInHDF5(db, "CInput/xPkSav", (:Enduse, :EC, :Area, :Year),"Exogenous Peak Savings (MW)","MW")
  xPolute = CreateVariableInHDF5(db, "CInput/xPolute", (:Enduse, :FuelEP, :EC, :Poll, :Area, :Year),"Exogenous Pollution Adjustment (Tonnes/Yr)","Tonnes/Yr")
  xProcSw = CreateVariableInHDF5(db, "CInput/xProcSw", (:PI, :Year),"Procedure Switch (1=on, 0=off)","1=on, 0=off")
  xRDMSF = CreateVariableInHDF5(db, "CInput/xRDMSF", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Device Retrofit Market Share Fraction by Device (1/Yr)","1/Yr")
  xRM = CreateVariableInHDF5(db, "CInput/xRM", (:FuelEP, :EC, :Poll, :Area, :Year),"Exogenous Average Pollution Coefficient Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  xRPCC = CreateVariableInHDF5(db, "CInput/xRPCC", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Process Retrofit Capital Cost (\$/(\$/Yr))","\$/(\$/Yr")
  xRPEE = CreateVariableInHDF5(db, "CInput/xRPEE", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Retrofit Process Efficiency (\$/BTU)","\$/BTU")
  xRPMSF = CreateVariableInHDF5(db, "CInput/xRPMSF", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Process Retrofit Market Share Fraction by Device (1/Yr)","1/Yr")
  xSqDmd = CreateVariableInHDF5(db, "CInput/xSqDmd", (:Tech, :EC, :Area, :Year),"Sequestering Energy Demand (TBtu/Yr)","TBtu/Yr")
  xXProcSw = CreateVariableInHDF5(db, "CInput/xXProcSw", (:PI, :Year),"Procedure Switch (1=on, 0=off)","1=on, 0=off")
  YCERSM = CreateVariableInHDF5(db, "CInput/YCERSM", (:Enduse, :EC, :Area, :Year),"CERSM Calibration Control (Switch)","Switch")
  YCgCUF = CreateVariableInHDF5(db, "CInput/YCgCUF", (:Tech, :EC, :Area, :Year),"CgCUF Calibration Control (Switch)","Switch")
  YCgMSM = CreateVariableInHDF5(db, "CInput/YCgMSM", (:Tech, :EC, :Area, :Year),"CgMSM Calibration Control (Switch)","Switch")
  YCUF = CreateVariableInHDF5(db, "CInput/YCUF", (:Enduse, :Tech, :EC, :Area, :Year),"CUF Calibration Control (Switch)","Switch")
  YDCMM = CreateVariableInHDF5(db, "CInput/YDCMM", (:Enduse, :Tech, :Area, :Year),"DCMM Calibration Control (Switch)","Switch")
  YDEMM = CreateVariableInHDF5(db, "CInput/YDEMM", (:Enduse, :Tech, :Area, :Year),"DEMM Calibration Control (Switch)","Switch")
  YDSt = CreateVariableInHDF5(db, "CInput/YDSt", (:Enduse, :EC, :Area, :Year),"DSt Calibration Control (Switch)","Switch")
  YEndTime = CreateVariableInHDF5(db, "CInput/YEndTime", (:tv,),"Last Year of Calibration (Date)","Date")
  YFsPEE = CreateVariableInHDF5(db, "CInput/YFsPEE", (:Tech, :EC, :Area, :Year),"FsPEE Calibration Control (Switch)","Switch")
  YMMSM = CreateVariableInHDF5(db, "CInput/YMMSM", (:Enduse, :Tech, :EC, :Area, :Year),"MMSM Calibration Control (Switch)","Switch")
  YPEMM = CreateVariableInHDF5(db, "CInput/YPEMM", (:Enduse, :Tech, :EC, :Area, :Year),"PEMM Calibration Control (Switch)","Switch")
  CMSFSwitch = CreateVariableInHDF5(db, "CInput/CMSFSwitch", (:Enduse, :Tech, :CTech, :EC, :Area, :Year),"Conversion Market Share Switch (1=Endogenous, 0=Exogenous)","1=Endogenous, 0=Exogenous")
  DActV = CreateVariableInHDF5(db, "CInput/DActV", (:Enduse, :Tech, :EC, :Area, :Vintage),"Activity Rate of Equipment by Vintage (1/1)","1/1")
  DmdFuel = CreateVariableInHDF5(db, "CInput/DmdFuel", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Enduse Demands (TBtu/Yr)","TBtu/Yr")
  DmFracTime = CreateVariableInHDF5(db, "CInput/DmFracTime", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Demand Fuel/Tech Adjustment Time (Years)","Years")
  DPLV = CreateVariableInHDF5(db, "CInput/DPLV", (:Enduse, :Tech, :EC, :Area, :Vintage, :Year),"Scrappage Rate of Equipment by Vintage (1/1)","1/1")
  FsDmdFuel = CreateVariableInHDF5(db, "CInput/FsDmdFuel", (:Fuel, :Tech, :EC, :Area, :Year),"Historical Feedstock Demands by Fuel","NoUnit")
  FsFracMax = CreateVariableInHDF5(db, "CInput/FsFracMax", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Fraction Maximum (Btu/Btu)","Btu/Btu")
  FsFracMin = CreateVariableInHDF5(db, "CInput/FsFracMin", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Fraction Minimum (Btu/Btu)","Btu/Btu")
  FsFracTime = CreateVariableInHDF5(db, "CInput/FsFracTime", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Adjustment Time (Years)","Years")
  FsFracVF = CreateVariableInHDF5(db, "CInput/FsFracVF", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Fraction Variance Factor (Btu/Btu)","Btu/Btu")
  FsPOCS = CreateVariableInHDF5(db, "CInput/FsPOCS", (:Fuel, :EC, :Poll, :Area, :Year),"Feedstock Pollution Standards (Tonnes/TBtu)","Tonnes/TBtu")
  POCS = CreateVariableInHDF5(db, "CInput/POCS", (:Enduse, :FuelEP, :EC, :Poll, :Area, :Year),"Pollution Standards (Tonnes/TBtu)","Tonnes/TBtu")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
end # struct CInput2
