#
# EGInput.jl - Input Database creation file
#

Base.@kwdef struct EGInput <: HDF5GroupDatabase
  db::String=DB
  ########################
  #
  # Define Sets
  #
  Node = ReadSetFromCSV("Node","Key")
  Area65 = ReadSetFromCSV("Area65","Key")
  Year = ReadSetFromCSV("Year","Key")
  tv = ReadSetFromCSV("tv","Key")
  GenCo = ReadSetFromCSV("GenCo","Key")
  Area = ReadSetFromCSV("Area","Key")
  Plant = ReadSetFromCSV("Plant","Key")
  TimeP = ReadSetFromCSV("TimeP","Key")
  Month = ReadSetFromCSV("Month","Key")
  Power = ReadSetFromCSV("Power","Key")
  FuelEP = ReadSetFromCSV("FuelEP","Key")
  Poll = ReadSetFromCSV("Poll","Key")
  Nation = ReadSetFromCSV("Nation","Key")
  PollX = ReadSetFromCSV("PollX","Key")
  Fuel = ReadSetFromCSV("Fuel","Key")
  NodeX = ReadSetFromCSV("NodeX","Key")
  Horizon = ReadSetFromCSV("Horizon","Key")
  Market = ReadSetFromCSV("Market","Key")
  PI = ReadSetFromCSV("PIElec","Key")
  Unit = ReadSetFromCSV("Unit","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
  A65NMap = CreateVariableInHDF5(db, "EGInput/A65NMap", (:Node, :Area65, :Year),"Map between Node and Area65 (Map)","Map")
  AFCM = CreateVariableInHDF5(db, "EGInput/AFCM", (:GenCo, :Year),"Average Fixed Cost Multiplier (Dless)","Dless")
  ArGenFr = CreateVariableInHDF5(db, "EGInput/ArGenFr", (:Area, :GenCo, :Year),"Fraction of the Area going to each GenCo (Fraction)","Fraction")
  ArGenMap = CreateVariableInHDF5(db, "EGInput/ArGenMap", (:Area, :GenCo),"Area from which GenCo gets Prices (Map)","Map")
  ArNdFr = CreateVariableInHDF5(db, "EGInput/ArNdFr", (:Area, :Node, :Year),"Fraction of the Area in each Node (MW/MW)","MW/MW")
  AvFactor = CreateVariableInHDF5(db, "EGInput/AvFactor", (:Plant, :TimeP, :Month, :Area, :Year),"Availability Factor (MW/MW)","MW/MW")
  AwardSwitch = CreateVariableInHDF5(db, "EGInput/AwardSwitch", (:Area, :Year),"New Capacity Award Switch (1=Cost, 2=Portfolio)","1=Cost, 2=Portfolio")
  BFracMax = CreateVariableInHDF5(db, "EGInput/BFracMax", (:Area, :Year),"Maximum Fraction of Capacity Built Endogenously (MW/MW)","MW/MW")
  BlkSw = CreateVariableInHDF5(db, "EGInput/BlkSw", (:Area, :Year),"Block switch (Switch)","Switch")
  BsBdFr = CreateVariableInHDF5(db, "EGInput/BsBdFr", (:Power, :Area, :Year),"Base Build Fraction (Fraction)","Fraction")
  BuildFr = CreateVariableInHDF5(db, "EGInput/BuildFr", (:Area, :Year),"Building fraction (Fraction)","Fraction")
  BuildSw = CreateVariableInHDF5(db, "EGInput/BuildSw", (:Area, :Year),"Build switch (Switch)","Switch")
  CapCredit = CreateVariableInHDF5(db, "EGInput/CapCredit", (:Plant, :Area, :Year),"Capacity Credit (MW/MW)","MW/MW")
  CD = CreateVariableInHDF5(db, "EGInput/CD", (:Plant, :Year),"Construction Delay (Years)","Years")
  CFStd = CreateVariableInHDF5(db, "EGInput/CFStd", (:FuelEP, :Plant, :Poll, :Area, :Year),"Clean Fuel Standard (kg/MWh)","kg/MWh")
  CgFlFrNew = CreateVariableInHDF5(db, "EGInput/CgFlFrNew", (:FuelEP, :Plant, :Area, :Year),"Fuel Type Fraction (Btu/Btu)","Btu/Btu")
  CgORNew = CreateVariableInHDF5(db, "EGInput/CgORNew", (:Plant, :Area, :TimeP, :Month, :Year),"Outage Rate for New Plants (MW/MW)","MW/MW")
  CoverNew = CreateVariableInHDF5(db, "EGInput/CoverNew", (:Plant, :Poll, :Area, :Year),"Fraction of New Plants Covered in Emissions Market (1=100% Covered)","1=100% Covered")
  CUCLimit = CreateVariableInHDF5(db, "EGInput/CUCLimit", (:Year,),"Build Decision Capacity Under Construction Limit","NoUnit")
  CurtailFraction = CreateVariableInHDF5(db, "EGInput/CurtailFraction", (:Plant, :Area, :Year),"Fraction of Generation Curtailed (GWh/GWh)","GWh/GWh")
  DesHr = CreateVariableInHDF5(db, "EGInput/DesHr", (:Plant, :Power, :Area, :Year),"Design Hours (Hours)","Hours")
  DInvFr = CreateVariableInHDF5(db, "EGInput/DInvFr", (:Plant, :Area, :Year),"Device Investments Fraction (\$/\$)","\$/\$")
  DIVTC = CreateVariableInHDF5(db, "EGInput/DIVTC", (:Plant, :Area, :Year),"Device Investment Tax Credit (\$/\$)","\$/\$")
  DPRSL = CreateVariableInHDF5(db, "EGInput/DPRSL", (:Area, :Year),"Straight Line Depreciation Rate (1/Yr)","1/Yr")
  DRisk = CreateVariableInHDF5(db, "EGInput/DRisk", (:Plant, :Area, :Year),"Device Risk Premium (DLESS)","DLESS")
  EAF = CreateVariableInHDF5(db, "EGInput/EAF", (:Plant, :Area, :Month, :Year),"Energy Avaliability Factor (MWh/MWh)","MWh/MWh")
  ECFPAdder = CreateVariableInHDF5(db, "EGInput/ECFPAdder", (:FuelEP, :Month, :Area, :Year),"Monthly Fuel Price Adder (\$/mmBtu)","\$/mmBtu")
  ECFPMinMult = CreateVariableInHDF5(db, "EGInput/ECFPMinMult", (:Year,),"Minimum Monthly Fuel Price Multiplier (\$/mmBtu)","\$/mmBtu")
  EGCalSw = CreateVariableInHDF5(db, "EGInput/EGCalSw", (:Nation, :Year),"Switch for Years to Calibrate Generation (1=Calibrate)","1=Calibrate")
  EICoverage = CreateVariableInHDF5(db, "EGInput/EICoverage", (:FuelEP, :Poll, :Area, :Year),"Fuels and Polutants included in Emission Intensity (1=Included)","1=Included")
  EmitNew = CreateVariableInHDF5(db, "EGInput/EmitNew", (:Plant, :Area),"Do New Plants Emit Pollution? (1=Yes)","1=Yes")
  EmitSw = CreateVariableInHDF5(db, "EGInput/EmitSw", (:Plant,),"Does this Plant Type Emit Pollution (1=Yes)","1=Yes")
  ESTime = CreateVariableInHDF5(db, "EGInput/ESTime", (:Area,),"Starting Time for Simulation (Time)","Time")
  EUCCR = CreateVariableInHDF5(db, "EGInput/EUCCR", (:Area, :Year),"Polution Reducution Capital Charge Rate (\$/\$)","\$/\$")
  EUCM = CreateVariableInHDF5(db, "EGInput/EUCM", (:FuelEP, :Plant, :Poll, :PollX),"Cross-over Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  EUPCostN = CreateVariableInHDF5(db, "EGInput/EUPCostN", (:FuelEP, :Plant, :Poll, :Area),"Pollution Reduction Cost Normal (\$/Tonne)","\$/Tonne")
  EUPVF = CreateVariableInHDF5(db, "EGInput/EUPVF", (:FuelEP, :Plant, :Poll, :Area),"Pollution Reduction Variance Factor ((\$/Tonne)/(\$/Tonne))","(\$/Tonne")
  EURCD = CreateVariableInHDF5(db, "EGInput/EURCD", (:Poll,),"Reduction Capital Construction Delay (Years)","Years")
  EURCPL = CreateVariableInHDF5(db, "EGInput/EURCPL", (:Poll,),"Reduction Capital Pysical Life (Years)","Years")
  EURCstM = CreateVariableInHDF5(db, "EGInput/EURCstM", (:FuelEP, :Plant, :Poll, :Year),"Reduction Cost Technology Multiplier (\$/\$)","\$/\$")
  EUROCF = CreateVariableInHDF5(db, "EGInput/EUROCF", (:FuelEP, :Plant, :Poll, :Area),"Polution Reducution O&M (\$/Tonne)","\$/Tonne")
  EURPCSw = CreateVariableInHDF5(db, "EGInput/EURPCSw", (:Plant, :Poll, :Area, :Year),"Pollution Reduction Curve Switch (1=2009, 2=2004)","1=2009, 2=2004")
  EUVRP = CreateVariableInHDF5(db, "EGInput/EUVRP", (:FuelEP, :Plant, :Poll, :Area, :Year),"Voluntary Reduction Policy (Tonnes/Tonnes)","Tonnes/Tonnes")
  EUVRRT = CreateVariableInHDF5(db, "EGInput/EUVRRT", (:FuelEP, :Plant),"Voluntary Reduction response time (Years)","Years")
  ExpUVCost = CreateVariableInHDF5(db, "EGInput/ExpUVCost", (:Month, :Year),"Expected Spot Price for LLH Time Period (\$/MWh)","\$/MWh")
  F1New = CreateVariableInHDF5(db, "EGInput/F1New", (:Plant, :Area),"Fuel Type 1 (Name)","Name")
  FIT = CreateVariableInHDF5(db, "EGInput/FIT", (:Plant, :Area, :Year),"Feed-In Tariff for Renewable Power (nominal \$/MWh)","nominal \$/MWh")
  FlFrMax = CreateVariableInHDF5(db, "EGInput/FlFrMax", (:FuelEP, :Plant, :Area, :Year),"Fuel Fraction Maximum (Btu/Btu)","Btu/Btu")
  FlFrMin = CreateVariableInHDF5(db, "EGInput/FlFrMin", (:FuelEP, :Plant, :Area, :Year),"Fuel Fraction Minimum (Btu/Btu)","Btu/Btu")
  FlFrMSM0 = CreateVariableInHDF5(db, "EGInput/FlFrMSM0", (:FuelEP, :Plant, :Area, :Year),"Fuel Fraction Non-Price Factor (Btu/Btu)","Btu/Btu")
  FlFrNew = CreateVariableInHDF5(db, "EGInput/FlFrNew", (:FuelEP, :Plant, :Area, :Year),"Fuel Type Fraction (Btu/Btu)","Btu/Btu")
  FlFrTime = CreateVariableInHDF5(db, "EGInput/FlFrTime", (:FuelEP, :Plant, :Area, :Year),"Fuel Adjustment Time (Years)","Years")
  FlFrVF = CreateVariableInHDF5(db, "EGInput/FlFrVF", (:FuelEP, :Plant, :Area),"Fuel Fraction Variance Factor (Btu/Btu)","Btu/Btu")
  FlPlnMap = CreateVariableInHDF5(db, "EGInput/FlPlnMap", (:Fuel, :Plant),"Fuel/Plant Map","NoUnit")
  GCBL = CreateVariableInHDF5(db, "EGInput/GCBL", (:Plant, :Area, :Year),"Generation Capacity Book Life (Years)","Years")
  GCCCFlag = CreateVariableInHDF5(db, "EGInput/GCCCFlag", (:Plant, :Area, :Year),"Plant Capital Cost Flag","NoUnit")
  GCCCN = CreateVariableInHDF5(db, "EGInput/GCCCN", (:Plant, :Area, :Year),"Overnight Construction Costs (\$/KW)","\$/KW")
  GCDevTime = CreateVariableInHDF5(db, "EGInput/GCDevTime", (:Plant, :Year),"Generation Capacity Development Time (Years)","Years")
  GCExpSw = CreateVariableInHDF5(db, "EGInput/GCExpSw", (:Plant, :Area, :Year),"Generation Capacity Expansion Switch (Switch)","Switch")
  GCTCB0 = CreateVariableInHDF5(db, "EGInput/GCTCB0", (:Plant, :Area, :Year),"ETC Capital Cost Coefficiency (\$/\$)","\$/\$")
  GCTCMap = CreateVariableInHDF5(db, "EGInput/GCTCMap", (:Area, :Nation, :Year),"Area to Nation Map for ETC","NoUnit")
  GCTL = CreateVariableInHDF5(db, "EGInput/GCTL", (:Plant, :Area, :Year),"Generation Capacity Tax Life (Years)","Years")
  GrImpMult = CreateVariableInHDF5(db, "EGInput/GrImpMult", (:NodeX, :Area, :Year),"Gross Import Multiplier (GWh/GWH)","GWh/GWH")
  GrMSM = CreateVariableInHDF5(db, "EGInput/GrMSM", (:Plant, :Node, :Area, :Year),"Green Power Market Share Non-Price Factors (MW/MW)","MW/MW")
  GrSysFr = CreateVariableInHDF5(db, "EGInput/GrSysFr", (:Node, :Area, :Year),"Green Power Capacity as Fraction of System (MW/MW)","MW/MW")
  GrVF = CreateVariableInHDF5(db, "EGInput/GrVF", (:Year,),"Green Power Market Share Variance Factor (MW/MW)","MW/MW")
  HDFCFR = CreateVariableInHDF5(db, "EGInput/HDFCFR", (:Plant, :GenCo, :TimeP, :Year),"Fraction of Fixed Costs Bid (\$/\$)","\$/\$")
  HDFlowFr = CreateVariableInHDF5(db, "EGInput/HDFlowFr", (:Node, :NodeX, :Year),"Fraction of Power Contracts in Firm Capacity (MW/MW)","MW/MW")
  HDGCFR = CreateVariableInHDF5(db, "EGInput/HDGCFR", (:Plant, :GenCo, :Node, :TimeP, :Month, :Year),"Fraction of Available Generating Capacity in Block (Fraction)","Fraction")
  HDVCFR = CreateVariableInHDF5(db, "EGInput/HDVCFR", (:Plant, :GenCo, :Node, :TimeP, :Month, :Year),"Fraction of Variable Costs Bid (\$/\$)","\$/\$")
  HDXLoad = CreateVariableInHDF5(db, "EGInput/HDXLoad", (:Node, :NodeX, :TimeP, :Month, :Year),"Exogenous Loading on Transmission Lines (MW)","MW")
  HRtM = CreateVariableInHDF5(db, "EGInput/HRtM", (:Plant, :Area, :Year),"Marginal Heat Rate (Btu/KWh)","Btu/KWh")
  HorizonDS = ReadSetFromCSV("Horizon","DS")
  HorizonKey = ReadSetFromCSV("Horizon","Key")
  IPExpSw = CreateVariableInHDF5(db, "EGInput/IPExpSw", (:Plant, :Area, :Year),"Intermittent Power Capacity Expansion Switch (1=Build)","1=Build")
  IPTPMap = CreateVariableInHDF5(db, "EGInput/IPTPMap", (:TimeP, :Area),"Intermittent Power Price Time Period Map (1=use TimeP)","1=use TimeP")
  LLEff = CreateVariableInHDF5(db, "EGInput/LLEff", (:Node, :NodeX, :Year),"Transmission Line Efficiency (MW/MW)","MW/MW")
  LLMax = CreateVariableInHDF5(db, "EGInput/LLMax", (:Node, :NodeX, :TimeP, :Month, :Year),"Maximum Loading on Transmission Lines (MW)","MW")
  LLPOCX = CreateVariableInHDF5(db, "EGInput/LLPOCX", (:Node, :NodeX, :Market, :Year),"Transmission Emissions (kg/MWH)","kg/MWH")
  LLPoTxRExo = CreateVariableInHDF5(db, "EGInput/LLPoTxRExo", (:Node, :NodeX, :Year),"Exogenous Pollution Costs for Transmission (Real US\$/MWH)","Real US\$/MWH")
  MCELimit = CreateVariableInHDF5(db, "EGInput/MCELimit", (:Area, :Year),"Build Decision Cost of Power Limit","NoUnit")
  MEPOCX = CreateVariableInHDF5(db, "EGInput/MEPOCX", (:Plant, :Poll, :Area, :Year),"Process Emission Coefficients (Tonnes/GWh)","Tonnes/GWh")
  MRunNew = CreateVariableInHDF5(db, "EGInput/MRunNew", (:Plant, :Area),"New Plant Must Run Switch (1=Must Run)","1=Must Run")
  NdArFr = CreateVariableInHDF5(db, "EGInput/NdArFr", (:Node, :Area, :Year),"Fraction of the Node in each Area (MW/MW)","MW/MW")
  NdArMap = CreateVariableInHDF5(db, "EGInput/NdArMap", (:Node, :Area),"Map between Node and Area","NoUnit")
  NdNMap = CreateVariableInHDF5(db, "EGInput/NdNMap", (:Node, :Nation),"Map between Node and Nation","NoUnit")
  NdXArMap = CreateVariableInHDF5(db, "EGInput/NdXArMap", (:NodeX, :Area),"Map between NodeX and Area","NoUnit")
  NdXNMap = CreateVariableInHDF5(db, "EGInput/NdXNMap", (:NodeX, :Nation),"Map between NodeX and Nation","NoUnit")
  NodeSw = CreateVariableInHDF5(db, "EGInput/NodeSw", (:Node,),"Switch to indicate if Node is Active (1=Active)","1=Active")
  NodeXSw = CreateVariableInHDF5(db, "EGInput/NodeXSw", (:NodeX,),"Switch to indicate if NodeX is Active (1=Active)","1=Active")
  NuclearFuelCost = CreateVariableInHDF5(db, "EGInput/NuclearFuelCost", (:Area, :Year),"Nuclear Fuel Costs (\$/MWh)","\$/MWh")
  OffNew = CreateVariableInHDF5(db, "EGInput/OffNew", (:Plant, :Poll, :Area, :Year),"Offset Permits for New Plants (Tonnes/TBtu)","Tonnes/TBtu")
  OffSw = CreateVariableInHDF5(db, "EGInput/OffSw", (:Area, :Year),"GHG Electric Utility Offsets Required Switch (1=Required)","1=Required")
  OGCCFraction = CreateVariableInHDF5(db, "EGInput/OGCCFraction", (:Area, :Year),"Fraction of new OG capacity which is OGCC (MW/MW)","MW/MW")
  OGCCSmallFraction = CreateVariableInHDF5(db, "EGInput/OGCCSmallFraction", (:Area, :Year),"Fraction of new OGCC capacity which is Small (MW/MW)","MW/MW")
  ORNew = CreateVariableInHDF5(db, "EGInput/ORNew", (:Plant, :Area, :TimeP, :Month, :Year),"Outage Rate for New Plants (MW/MW)","MW/MW")
  OtISw = CreateVariableInHDF5(db, "EGInput/OtISw", (:Area, :Year),"Other (Unspecified) Imports Switch","Unspecified")
  OUREG = CreateVariableInHDF5(db, "EGInput/OUREG", (:Plant, :Area, :Year),"Own Use Rate for Generation (GWh/GWh)","GWh/GWh")
  OURGC = CreateVariableInHDF5(db, "EGInput/OURGC", (:Plant, :Area, :Year),"Own Use Rate for Generating Capacity (MW/MW)","MW/MW")
  PCostM = CreateVariableInHDF5(db, "EGInput/PCostM", (:FuelEP, :Plant, :Poll, :Area, :Year),"Permit Cost Multiplier (\$/Tonne/\$/Tonne)","\$/Tonne/\$/Tonne")
  PEDCSwitch = CreateVariableInHDF5(db, "EGInput/PEDCSwitch", (:Area, :Year),"Switch to execute alternative PEDC calculation (1=execute)","1=execute")
  PFFrac = CreateVariableInHDF5(db, "EGInput/PFFrac", (:FuelEP, :Plant, :Area, :Year),"Fuel Usage Fraction (Btu/Btu)","Btu/Btu")
  PHSpillage = CreateVariableInHDF5(db, "EGInput/PHSpillage", (:TimeP, :Month, :Node, :Year),"Peak Hydro Spillage (MW/MW)","MW/MW")
  PjMax = CreateVariableInHDF5(db, "EGInput/PjMax", (:Plant, :Area),"Maximum Project Size (MW)","MW")
  PjMnPS = CreateVariableInHDF5(db, "EGInput/PjMnPS", (:Plant, :Area),"Minimum Project Size (MW)","MW")
  PjNSw = CreateVariableInHDF5(db, "EGInput/PjNSw", (:Node, :GenCo, :Area, :Year),"Project Selection Node Switch (1=Build)","1=Build")
  PkHydSw = CreateVariableInHDF5(db, "EGInput/PkHydSw", (:Year,),"Switch for Allocation Method for Peak Hydro (1=new method)","1=new method")
  PlantSw = CreateVariableInHDF5(db, "EGInput/PlantSw", (:Plant,),"Iteration when this Plant Type begins to be calibrated","NoUnit")
  POCX = CreateVariableInHDF5(db, "EGInput/POCX", (:FuelEP, :Plant, :Poll, :Area, :Year),"Marginal Pollution Coefficients (Tonnes/TBtu)","Tonnes/TBtu")
  POCXOthImports = CreateVariableInHDF5(db, "EGInput/POCXOthImports", (:Poll, :NodeX, :Area, :Year),"Imported Emissions Coefficients (Tonnes/GWh)","Tonnes/GWh")
  POCXRnImports = CreateVariableInHDF5(db, "EGInput/POCXRnImports", (:Poll, :Area, :Year),"Renewable Imports Emissions Coefficient (Tonnes/GWh)","Tonnes/GWh")
  PollLimitGHGFlag = CreateVariableInHDF5(db, "EGInput/PollLimitGHGFlag", (:Area, :Year),"Pollution Limit GHG Flag (1=Annual Limit, 2=Cumulative Limit)","1=Annual Limit, 2=Cumulative Limit")
  PollutionLimit = CreateVariableInHDF5(db, "EGInput/PollutionLimit", (:Poll, :Area, :Year),"Electric Utility Pollution Limit (Tonnes)","Tonnes")
  PolSw = CreateVariableInHDF5(db, "EGInput/PolSw", (:Poll, :Year),"Switch to Execute Pollution Procedure (Switch)","Switch")
  Portfolio = CreateVariableInHDF5(db, "EGInput/Portfolio", (:Plant, :Power, :Node, :Area, :Year),"Portfolio Fraction of New Capacity (MW/MW)","MW/MW")
  PoTRNewExo = CreateVariableInHDF5(db, "EGInput/PoTRNewExo", (:Plant, :Area, :Year),"Exogenous Emission Cost for New Plants (Real \$/MWH)","Real \$/MWH")
  PrDiFr = CreateVariableInHDF5(db, "EGInput/PrDiFr", (:Power, :Area, :Year),"Price Differential Fraction (Fraction)","Fraction")
  PIDS = ReadSetFromCSV("PIElec","DS")
  PIKey = ReadSetFromCSV("PIElec","Key")
  RAvNew = CreateVariableInHDF5(db, "EGInput/RAvNew", (:Plant, :Node, :Year),"Reserve Availability (MW/MW)","MW/MW")
  RnBuildFr = CreateVariableInHDF5(db, "EGInput/RnBuildFr", (:Plant, :Area, :Year),"Build Fraction for Renewable Capacity as Fraction of Area (MW/MW)","MW/MW")
  RnFr = CreateVariableInHDF5(db, "EGInput/RnFr", (:Area, :Year),"Renewable Fraction (GWh/GWh)","GWh/GWh")
  RnGoalSwitch = CreateVariableInHDF5(db, "EGInput/RnGoalSwitch", (:Area, :Year),"Renewable Generation Goal Switch (0=Sales, 1=New Capacity)","0=Sales, 1=New Capacity")
  RnMSM = CreateVariableInHDF5(db, "EGInput/RnMSM", (:Plant, :Node, :GenCo, :Area, :Year),"Renewable Market Share Non-Price Factors (GWh/GWh)","GWh/GWh")
  RnOption = CreateVariableInHDF5(db, "EGInput/RnOption", (:Area, :Year),"Renewable Expansion Option (1=Local RPS, 2=Regional RPS, 3=FIT)","1=Local RPS, 2=Regional RPS, 3=FIT")
  RnSwitch = CreateVariableInHDF5(db, "EGInput/RnSwitch", (:Plant, :Area),"Renewable Plant Type Switch (1=Renewable)","1=Renewable")
  RnVF = CreateVariableInHDF5(db, "EGInput/RnVF", (:Area, :Year),"Renewable Market Share Variance Factor (\$/\$)","\$/\$")
  RRqNew = CreateVariableInHDF5(db, "EGInput/RRqNew", (:Plant, :Node, :Year),"Reserve Requirements (MW/MW)","MW/MW")
  RSwNew = CreateVariableInHDF5(db, "EGInput/RSwNew", (:Plant, :Node, :Year),"Reserve Availability Switch (MW/MW)","MW/MW")
  SensitivityNew = CreateVariableInHDF5(db, "EGInput/SensitivityNew", (:Plant, :Area, :Year),"Outage Rate Sensitivity to Decline with Driver for New Cogeneration (Driver/Driver)","Driver/Driver")
  SqFr = CreateVariableInHDF5(db, "EGInput/SqFr", (:Plant, :Poll, :Area, :Year),"Sequestered Pollution Fraction (Tonne/Tonne)","Tonne/Tonne")
  StorageEfficiency = CreateVariableInHDF5(db, "EGInput/StorageEfficiency", (:Plant, :Area, :Year),"Storage Efficiency (GWh/GWh)","GWh/GWh")
  StorageFraction = CreateVariableInHDF5(db, "EGInput/StorageFraction", (:Plant, :Area, :Year),"Storage as a Fraction of Wind Developed (MW/MW)","MW/MW")
  StorageSwitch = CreateVariableInHDF5(db, "EGInput/StorageSwitch", (:Plant,),"Storage Technology Switch (1=Storage)","1=Storage")
  Subsidy = CreateVariableInHDF5(db, "EGInput/Subsidy", (:Plant, :Area, :Year),"Generating Capacity Subsidy (\$/MWh)","\$/MWh")
  TaxR = CreateVariableInHDF5(db, "EGInput/TaxR", (:Area, :Year),"Income Tax Rate (\$/\$)","\$/\$")
  TDInvFr = CreateVariableInHDF5(db, "EGInput/TDInvFr", (:Plant, :Area, :Year),"Electric Transmission and Distribution Investments Fraction (\$/\$)","\$/\$")
  TPRMap = CreateVariableInHDF5(db, "EGInput/TPRMap", (:TimeP, :Power),"TimeP to Power Map (Map)","Map")
  UFOMC = CreateVariableInHDF5(db, "EGInput/UFOMC", (:Plant, :Area, :Year),"Unit Fixed O&M Costs (1985 \$/KW)","1985 \$/KW")
  UnArea::SetArray = Unit
  UnCode::SetArray = Unit
  UnCogen = CreateVariableInHDF5(db, "EGInput/UnCogen", (:Unit,),"Industrial Generation Switch (Switch) (1=Industrial Generation)","Switch")
  CgUnCode = CreateVariableInHDF5(db, "EGInput/CgUnCode", (:Plant, :ECC, :Node, :Area),"Cogeneration Unit Number (Number)","Number")
  UnCounter = CreateVariableInHDF5(db, "EGInput/UnCounter", (:Year,),"Number of Units (Number)","Number")
  UnCoverage = CreateVariableInHDF5(db, "EGInput/UnCoverage", (:Unit, :Poll, :Year),"Fraction of Unit Covered in Emission Market (1=100% Covered)","1=100% Covered")
  UnCurtailedSwitch = CreateVariableInHDF5(db, "EGInput/UnCurtailedSwitch", (:Unit, :Year),"Unit Curtailment Swtich (1=Curtail)","1=Curtail")
  UnEAF = CreateVariableInHDF5(db, "EGInput/UnEAF", (:Unit, :Month, :Year),"Energy Avaliability Factor (MWh/MWh)","MWh/MWh")
  UnEffStorage = CreateVariableInHDF5(db, "EGInput/UnEffStorage", (:Unit,),"Storage Efficiency (GWH/GWH)","GWH/GWH")
  UnEIBase = CreateVariableInHDF5(db, "EGInput/UnEIBase", (:Unit, :Poll, :Year),"Baseline Emissions Intensity (Tonnes/GWh)","Tonnes/GWh")
  UnEIStd = CreateVariableInHDF5(db, "EGInput/UnEIStd", (:Unit, :Poll, :Year),"Emissions Intensity Standard (Tonnes/GWh)","Tonnes/GWh")
  UnEmit = CreateVariableInHDF5(db, "EGInput/UnEmit", (:Unit,),"Does this Unit Emit Pollution (Switch) (1=Yes)","Switch")
  UnF1::SetArray = Unit
  UnFacility::SetArray = Unit
  xUnFlFr = CreateVariableInHDF5(db, "EGInput/xUnFlFr", (:Unit, :FuelEP, :Year),"Fuel Fraction (Btu/Btu)","Btu/Btu")
  UnFlFrMax = CreateVariableInHDF5(db, "EGInput/UnFlFrMax", (:Unit, :FuelEP, :Year),"Fuel Fraction Maximum (Btu/Btu)","Btu/Btu")
  UnFlFrMin = CreateVariableInHDF5(db, "EGInput/UnFlFrMin", (:Unit, :FuelEP, :Year),"Fuel Fraction Minimum (Btu/Btu)","Btu/Btu")
  UnFlFrTime = CreateVariableInHDF5(db, "EGInput/UnFlFrTime", (:Unit, :FuelEP, :Year),"Fuel Fraction Adjustment Time (Years)","Years")
  UnFlFrVF = CreateVariableInHDF5(db, "EGInput/UnFlFrVF", (:Unit, :FuelEP),"Fuel Fraction Variance Factor (Btu/Btu)","Btu/Btu")
  UnFrImports = CreateVariableInHDF5(db, "EGInput/UnFrImports", (:Unit, :Area, :Year),"Fraction of Unit Imported to Area (GWH/GWH)","GWH/GWH")
  UnGenCo::SetArray = Unit
  UnHRt = CreateVariableInHDF5(db, "EGInput/UnHRt", (:Unit, :Year),"Heat Rate (BTU/KWh)","BTU/KWh")
  UnLimited = CreateVariableInHDF5(db, "EGInput/UnLimited", (:Unit, :Year),"Limited Energy Units Switch (Switch) (1=Limited Energy Unit)","Switch")
  UnMECX = CreateVariableInHDF5(db, "EGInput/UnMECX", (:Unit, :Poll, :Year),"Pollution Coefficient (Tonnes/GWh)","Tonnes/GWh")
  UnMustRun = CreateVariableInHDF5(db, "EGInput/UnMustRun", (:Unit,),"Must Run (Switch) (1=Must Run)","Switch")
  UnName::SetArray = Unit
  UnNation::SetArray = Unit
  UnNewNumber = CreateVariableInHDF5(db, "EGInput/UnNewNumber", (:Plant, :Node, :GenCo, :Area, :Year),"Unit Number for New Unit","NoUnit")
  UnNode::SetArray = Unit
  UnOffsets = CreateVariableInHDF5(db, "EGInput/UnOffsets", (:Unit, :Poll, :Year),"Offsets (Tonnes/GWh)","Tonnes/GWh")
  UnOnLine = CreateVariableInHDF5(db, "EGInput/UnOnLine", (:Unit,),"On-Line Date (Year)","Year")
  UnOR = CreateVariableInHDF5(db, "EGInput/UnOR", (:Unit, :TimeP, :Month, :Year),"Outage Rate (MW/MW)","MW/MW")
  UnOUREG = CreateVariableInHDF5(db, "EGInput/UnOUREG", (:Unit, :Year),"Own Use Rate for Generation (GWh/GWh)","GWh/GWh")
  UnOURGC = CreateVariableInHDF5(db, "EGInput/UnOURGC", (:Unit, :Year),"Own Use Rate for Generating Capacity (MW/MW)","MW/MW")
  UnOwner::SetArray = Unit
  UnPCFMax = CreateVariableInHDF5(db, "EGInput/UnPCFMax", (:Unit, :Year),"Maximum Unit Capacity Factor (MW/MW)","MW/MW")
  UnPlant::SetArray = Unit
  UnPOCX = CreateVariableInHDF5(db, "EGInput/UnPOCX", (:Unit, :FuelEP, :Poll, :Year),"Pollution Coefficient (Tonnes/TBtu)","Tonnes/TBtu")
  UnPoTRExo = CreateVariableInHDF5(db, "EGInput/UnPoTRExo", (:Unit, :Year),"Exogenous Pollution Tax Rate (Real \$/MWh)","Real \$/MWh")
  UnPointer = CreateVariableInHDF5(db, "EGInput/UnPointer", (:Plant, :Node, :GenCo, :Area, :Year),"Unit Pointer","NoUnit")
  UnPRSw = CreateVariableInHDF5(db, "EGInput/UnPRSw", (:Unit, :Poll, :Year),"Pollution Reduction Switch (Number)","Number")
  UnPSoMaxGridFraction = CreateVariableInHDF5(db, "EGInput/UnPSoMaxGridFraction", (:Unit, :Year),"Maximum Fraction Sold to Grid (GWh/GWh)","GWh/GWh")
  UnRAv = CreateVariableInHDF5(db, "EGInput/UnRAv", (:Unit,),"Reserves Available (MW/MW)","MW/MW")
  UnRetire = CreateVariableInHDF5(db, "EGInput/UnRetire", (:Unit, :Year),"Retirement Date (Year)","Year")
  UnROCF = CreateVariableInHDF5(db, "EGInput/UnROCF", (:Unit, :Poll, :Year),"Pollution Reduction O&M Cost Factor (\$/\$)","\$/\$")
  UnRRq = CreateVariableInHDF5(db, "EGInput/UnRRq", (:Unit,),"Reserve Requirements (MW/MW)","MW/MW")
  UnRSwitch = CreateVariableInHDF5(db, "EGInput/UnRSwitch", (:Unit,),"Switch for Units Forced to Supply Reserve Requirements (Switch) (1=Yes)","Switch")
  UnSector::SetArray = Unit
  UnSensitivity = CreateVariableInHDF5(db, "EGInput/UnSensitivity", (:Unit, :Year),"Outage Rate Sensitivity to Decline in Driver (Driver/Driver)","Driver/Driver")
  UnSource = CreateVariableInHDF5(db, "EGInput/UnSource", (:Unit,),"Source (Switch) (1=Endogenous, 0=Exogenous)","Switch")
  UnSqFr = CreateVariableInHDF5(db, "EGInput/UnSqFr", (:Unit, :Poll, :Year),"Sequestered Pollution Fraction (Tonne/Tonne)","Tonne/Tonne")
  UnStorage = CreateVariableInHDF5(db, "EGInput/UnStorage", (:Unit,),"Storage Switch (Switch) (1=Storage Unit)","Switch")
  UnUFOMC = CreateVariableInHDF5(db, "EGInput/UnUFOMC", (:Unit, :Year),"Fixed O&M Costs (1985 US\$/Kw/Yr)","1985 US\$/Kw/Yr")
  UnUOMC = CreateVariableInHDF5(db, "EGInput/UnUOMC", (:Unit, :Year),"Variable O&M Costs (1985 US\$/MWh)","1985 US\$/MWh")
  UnXSw = CreateVariableInHDF5(db, "EGInput/UnXSw", (:Unit, :Year),"Exogneous Unit Data Switch (Switch) (0=Exogenous)","Switch")
  UnZeroFr = CreateVariableInHDF5(db, "EGInput/UnZeroFr", (:Unit, :FuelEP, :Poll, :Year),"Fraction of Emissions from Zero Emission Sources (Tonnes/Tonnes)","Tonnes/Tonnes")
  UOMC = CreateVariableInHDF5(db, "EGInput/UOMC", (:Plant, :Area, :Year),"Variable O&M Costs (1985 MILLS/kWh)","1985 MILLS/kWh")
  USMT = CreateVariableInHDF5(db, "EGInput/USMT", (:Horizon,),"Smoothing Time (Year)","Year")
  WCC = CreateVariableInHDF5(db, "EGInput/WCC", (:Area, :Year),"Weighted Cost of Capital (\$/(\$/Yr))","\$/(\$/Yr")
  xAreaPurchases = CreateVariableInHDF5(db, "EGInput/xAreaPurchases", (:Area, :Year),"Historical Purchases from Areas in the same Country (GWh/Yr)","GWh/Yr")
  xAreaSales = CreateVariableInHDF5(db, "EGInput/xAreaSales", (:Area, :Year),"Historical Sales to Areas in the same Country (GWh/Yr)","GWh/Yr")
  xDmdFA = CreateVariableInHDF5(db, "EGInput/xDmdFA", (:Fuel, :Area, :Year),"Electric Generation Fuel Demands (TBtu/Yr)","TBtu/Yr")
  xEGFA = CreateVariableInHDF5(db, "EGInput/xEGFA", (:Fuel, :Area, :Year),"Electricity Generated (GWh/Yr)","GWh/Yr")
  xEGPA = CreateVariableInHDF5(db, "EGInput/xEGPA", (:Plant, :Area, :Year),"Electricity Generated (GWh/Yr)","GWh/Yr")
  xEMGVCost = CreateVariableInHDF5(db, "EGInput/xEMGVCost", (:Node, :Year),"Dispatch Price for Emergency Power (\$/MWh)","\$/MWh")
  xEUD = CreateVariableInHDF5(db, "EGInput/xEUD", (:FuelEP, :Area, :Year),"Electric Utility Fuel Demands (tBtu/Yr)","tBtu/Yr")
  xEUDmd = CreateVariableInHDF5(db, "EGInput/xEUDmd", (:Fuel, :Area, :Year),"Electric Utility Fuel Demands (TBtu/Yr)","TBtu/Yr")
  xEURM = CreateVariableInHDF5(db, "EGInput/xEURM", (:FuelEP, :Plant, :Poll, :Area, :Year),"Exogenous Reduction Multiplier by Area (Tonnes/Tonnes)","Tonnes/Tonnes")
  xExpPurchases = CreateVariableInHDF5(db, "EGInput/xExpPurchases", (:Area, :Year),"Historical Purchases from Areas in a different Country (GWh/Yr)","GWh/Yr")
  xExpSales = CreateVariableInHDF5(db, "EGInput/xExpSales", (:Area, :Year),"Historical Sales to Areas in a different Country (GWh/Yr)","GWh/Yr")
  xUnGCCC = CreateVariableInHDF5(db, "EGInput/xUnGCCC", (:Unit, :Year),"Generating Unit Capital Cost (1985 US\$/Kw)","1985 US\$/Kw")
  xGCFA = CreateVariableInHDF5(db, "EGInput/xGCFA", (:Fuel, :Area, :Year),"Generating Capacity (MW)","MW")
  xGCPot = CreateVariableInHDF5(db, "EGInput/xGCPot", (:Plant, :Node, :Area, :Year),"Exogenous Maximum Potential Generation Capacity (MW)","MW")
  xGPNew = CreateVariableInHDF5(db, "EGInput/xGPNew", (:FuelEP, :Plant, :Poll, :Area, :Year),"Gratis Permits for New Plants (kg/MWh)","kg/MWh")
  xLLVC = CreateVariableInHDF5(db, "EGInput/xLLVC", (:Node, :NodeX, :Year),"Transmission Rate (Real US\$/MWh)","Real US\$/MWh")
  xPolOthImports = CreateVariableInHDF5(db, "EGInput/xPolOthImports", (:Poll, :Area, :Year),"Exogenous Imported Emissions (Tonnes)","Tonnes")
  xRnImports = CreateVariableInHDF5(db, "EGInput/xRnImports", (:Area, :Year),"Exogenous Renewable Generation Imports (GWh/Yr)","GWh/Yr")
  xUnDmd = CreateVariableInHDF5(db, "EGInput/xUnDmd", (:Unit, :FuelEP, :Year),"Historical Unit Energy Demands (TBtu)","TBtu")
  xUnEGA = CreateVariableInHDF5(db, "EGInput/xUnEGA", (:Unit, :Year),"Historical Unit Generation (GWh)","GWh")
  xUnEGC = CreateVariableInHDF5(db, "EGInput/xUnEGC", (:Unit, :TimeP, :Month, :Year),"Effective Generating Capacity (MW)","MW")
  xUnGC = CreateVariableInHDF5(db, "EGInput/xUnGC", (:Unit, :Year),"Generating Capacity (MW)","MW")
  xUnGCCI = CreateVariableInHDF5(db, "EGInput/xUnGCCI", (:Unit, :Year),"Exogenous Generating Capacity Initiated (MW)","MW")
  xUnGCCR = CreateVariableInHDF5(db, "EGInput/xUnGCCR", (:Unit, :Year),"Generating Capacity Completed (MW)","MW")
  xUnGP = CreateVariableInHDF5(db, "EGInput/xUnGP", (:Unit, :FuelEP, :Poll, :Year),"Unit Intensity Target or Gratis Permits (kg/MWh)","kg/MWh")
  xUnPOCGWh = CreateVariableInHDF5(db, "EGInput/xUnPOCGWh", (:Unit, :Poll, :Year),"Pollution Coefficient (Tonnes/GWh)","Tonnes/GWh")
  xUnPol = CreateVariableInHDF5(db, "EGInput/xUnPol", (:Unit, :FuelEP, :Poll, :Year),"Pollution in Reference Case (Tonnes)","Tonnes")
  xUnPolSw = CreateVariableInHDF5(db, "EGInput/xUnPolSw", (:Unit, :Poll, :Year),"Historical Pollution Switch (1=No Unit Data)","1=No Unit Data")
  xUnRCC = CreateVariableInHDF5(db, "EGInput/xUnRCC", (:Unit, :FuelEP, :Poll, :Year),"Pollution Reduction Capital Cost (\$/(Tonnes/Yr))","\$/(Tonnes/Yr")
  xUnRP = CreateVariableInHDF5(db, "EGInput/xUnRP", (:Unit, :FuelEP, :Poll, :Year),"Pollution Reduction Requirement (Tonnes/Tonnes)","Tonnes/Tonnes")
  xUnVCost = CreateVariableInHDF5(db, "EGInput/xUnVCost", (:Unit, :TimeP, :Month, :Year),"Exogenous Market Price Bid (\$/MWh)","\$/MWh")
  YEndTime = CreateVariableInHDF5(db, "EGInput/YEndTime", (:tv,),"Last Year of Calibration (Date)","NoUnit")
end # struct EGInput
