#
# EOutput.jl - Input Database creation file
#

Base.@kwdef struct EOutput <: HDF5GroupDatabase
  db::String=DB
  ########################
  #
  # Define Sets
  #
  Plant = ReadSetFromCSV("Plant","Key")
  GenCo = ReadSetFromCSV("GenCo","Key")
  Year = ReadSetFromCSV("Year","Key")
  tv = ReadSetFromCSV("tv","Key")
  Month = ReadSetFromCSV("Month","Key")
  Area = ReadSetFromCSV("Area","Key")
  TimeP = ReadSetFromCSV("TimeP","Key")
  Contracts = ReadSetFromCSV("Contracts","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  ES = ReadSetFromCSV("ES","Key")
  Node = ReadSetFromCSV("Node","Key")
  Fuel = ReadSetFromCSV("Fuel","Key")
  Day = ReadSetFromCSV("Day","Key")
  Power = ReadSetFromCSV("Power","Key")
  Class = ReadSetFromCSV("Class","Key")
  PPSet = ReadSetFromCSV("PPSet","Key")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
  ACE = CreateVariableInHDF5(db, "EOutput/ACE", (:Plant, :GenCo, :Year),"Average Cost of Power (\$/MWh)","\$/MWh")
  ADP = CreateVariableInHDF5(db, "EOutput/ADP", (:Month, :Area, :Year),"Average Demand (MW)","MW")
  AFC = CreateVariableInHDF5(db, "EOutput/AFC", (:Plant, :GenCo, :Year),"Average Fixed Costs (\$/KW)","\$/KW")
  AGPV = CreateVariableInHDF5(db, "EOutput/AGPV", (:Plant, :GenCo, :Year),"Average Gratis Permit Value (US\$/MWh)","US\$/MWh")
  AVC = CreateVariableInHDF5(db, "EOutput/AVC", (:Plant, :GenCo, :Year),"Average Variable Costs (\$/MWh)","\$/MWh")
  Capacity = CreateVariableInHDF5(db, "EOutput/Capacity", (:Area, :GenCo, :Plant, :TimeP, :Month, :Year),"Capacity under Contract (MW)","MW")
  CnCap = CreateVariableInHDF5(db, "EOutput/CnCap", (:Contracts, :Area, :TimeP, :Month),"Contract Capacity (MW)","MW")
  CnEG = CreateVariableInHDF5(db, "EOutput/CnEG", (:Contracts, :Area, :TimeP, :Month),"Contract Generartion (GWh)","GWh")
  CnEnergy = CreateVariableInHDF5(db, "EOutput/CnEnergy", (:Contracts, :Area, :TimeP, :Month),"Contract Energy (GWh)","GWh")
  CnGenCo = CreateVariableInHDF5(db, "EOutput/CnGenCo", (:Contracts, :Area, :TimeP, :Month),"Contract GenCo","NoUnit")
  CnMDS = CreateVariableInHDF5(db, "EOutput/CnMDS", (:Contracts, :Area, :TimeP, :Month),"Contract Maximum Demand Satisfied (MW)","MW")
  CnPlant = CreateVariableInHDF5(db, "EOutput/CnPlant", (:Contracts, :Area, :TimeP, :Month),"Contract Plant Type","NoUnit")
  CnUECost = CreateVariableInHDF5(db, "EOutput/CnUECost", (:Contracts, :Area, :TimeP, :Month),"Contract Energy Cost (US\$/MWh)","US\$/MWh")
  DACost = CreateVariableInHDF5(db, "EOutput/DACost", (:Area, :Year),"Direct Access Contract (M\$/Yr)","M\$/Yr")
  DCCost = CreateVariableInHDF5(db, "EOutput/DCCost", (:Area, :Year),"Capacity Cost (M\$/Yr)","M\$/Yr")
  DVCost = CreateVariableInHDF5(db, "EOutput/DVCost", (:Area, :Year),"Variable Cost (M\$/Yr)","M\$/Yr")
  ECCRV = CreateVariableInHDF5(db, "EOutput/ECCRV", (:ECC, :Area, :Year),"Electricity Revenues (M\$/Yr)","M\$/Yr")
  EGA = CreateVariableInHDF5(db, "EOutput/EGA", (:Plant, :Area, :Year),"Electricity Dispatched (GWh/Yr)","GWh/Yr")
  EGBI = CreateVariableInHDF5(db, "EOutput/EGBI", (:Area, :GenCo, :Plant, :Year),"Electricity sold thru Contracts (GWh/Yr)","GWh/Yr")
  EGBIPG = CreateVariableInHDF5(db, "EOutput/EGBIPG", (:Area, :Year),"Electricity sold thru Contracts (GWh/Yr)","GWh/Yr")
  EGBITM = CreateVariableInHDF5(db, "EOutput/EGBITM", (:Area, :GenCo, :Plant, :TimeP, :Month, :Year),"Electricity sold thru Contracts (GWh/Yr)","GWh/Yr")
  Energy = CreateVariableInHDF5(db, "EOutput/Energy", (:Area, :GenCo, :Plant, :Year),"Energy Limit on Contracts (GWh/Yr)","GWh/Yr")
  ExportsPE = CreateVariableInHDF5(db, "EOutput/ExportsPE", (:Area, :Year),"Electric Exports Unit Revenues in Price (\$/MWh)","\$/MWh")
  ExportsUR = CreateVariableInHDF5(db, "EOutput/ExportsUR", (:Area, :Year),"Electric Exports Unit Revenue (\$/MWh)","\$/MWh")
  FPSMR = CreateVariableInHDF5(db, "EOutput/FPSMR", (:ES, :Area, :Year),"Electric Sales Tax (\$/\$)","\$/\$")
  FPTaxR = CreateVariableInHDF5(db, "EOutput/FPTaxR", (:ES, :Area, :Year),"Electric Excise Tax (\$/MWh)","\$/MWh")
  GC = CreateVariableInHDF5(db, "EOutput/GC", (:Plant, :Node, :GenCo, :Year),"Generation Capacity (MW)","MW")
  GCap = CreateVariableInHDF5(db, "EOutput/GCap", (:Plant, :GenCo, :Year),"Generating Capacity (MW)","MW")
  GCAr = CreateVariableInHDF5(db, "EOutput/GCAr", (:Plant, :Node, :GenCo, :Area, :Year),"Generation Capacity (MW)","MW")
  GCFA = CreateVariableInHDF5(db, "EOutput/GCFA", (:Fuel, :Area, :Year),"Generation Capacity (MW)","MW")
  GCFANet = CreateVariableInHDF5(db, "EOutput/GCFANet", (:Fuel, :Area, :Year),"Net Generation Capacity (MW)","MW")
  GCG = CreateVariableInHDF5(db, "EOutput/GCG", (:Plant, :GenCo, :Year),"Generation Capacity (MW)","MW")
  GCPA = CreateVariableInHDF5(db, "EOutput/GCPA", (:Plant, :Area, :Year),"Generation Capacity (MW)","MW")
  GCPANet = CreateVariableInHDF5(db, "EOutput/GCPANet", (:Plant, :Area, :Year),"Net Generation Capacity (MW)","MW")
  GPURef = CreateVariableInHDF5(db, "EOutput/GPURef", (:Area, :Year),"Gratis Permit Unit Refund (\$/MWh)","\$/MWh")
  HDPrA = CreateVariableInHDF5(db, "EOutput/HDPrA", (:Node, :TimeP, :Month, :Year),"Spot Market Marginal Price (\$/MWh)","\$/MWh")
  HDPrAUS = CreateVariableInHDF5(db, "EOutput/HDPrAUS", (:Node, :TimeP, :Month),"Spot Market Marginal Price (US\$/MWh)","US\$/MWh")
  HMADP = CreateVariableInHDF5(db, "EOutput/HMADP", (:Node, :Area, :TimeP, :Month, :Year),"Average Load in Interval (MW)","MW")
  HMEGMn = CreateVariableInHDF5(db, "EOutput/HMEGMn", (:Node, :Area, :TimeP, :Month, :Year),"Energy below Lowest Point in Interval (GWh)","GWh")
  HMEGPk = CreateVariableInHDF5(db, "EOutput/HMEGPk", (:Node, :Area, :TimeP, :Month, :Year),"Energy below Highest Load in Interval (GWh)","GWh")
  HMEnergy = CreateVariableInHDF5(db, "EOutput/HMEnergy", (:Node, :Area, :TimeP, :Month, :Year),"Energy in Interval (GWh)","GWh")
  HMMDP = CreateVariableInHDF5(db, "EOutput/HMMDP", (:Node, :Area, :TimeP, :Month, :Year),"Minimum (Lowest) Load in Interval (MW)","Lowest")
  HMPDP = CreateVariableInHDF5(db, "EOutput/HMPDP", (:Node, :Area, :TimeP, :Month, :Year),"Peak (Highest) Load in Interval (MW)","Highest")
  HMPr = CreateVariableInHDF5(db, "EOutput/HMPr", (:Area, :TimeP, :Month, :Year),"Spot Market Price (\$/MWh)","\$/MWh")
  HMPrA = CreateVariableInHDF5(db, "EOutput/HMPrA", (:Area, :Year),"Average Spot Price (\$/MWh)","\$/MWh")
  LDCDN = CreateVariableInHDF5(db, "EOutput/LDCDN", (:ECC, :Day, :Month, :Area, :Node, :Year),"Electric Load Curve (MW)","MW")
  LDCMS = CreateVariableInHDF5(db, "EOutput/LDCMS", (:Day, :Month, :Node, :Area, :Year),"Marketer System Load Curve (MW)","MW")
  LDCNd = CreateVariableInHDF5(db, "EOutput/LDCNd", (:ECC, :Day, :Month, :Node, :Area, :Year),"Detailed Load Curve (MW)","MW")
  LDCSA = CreateVariableInHDF5(db, "EOutput/LDCSA", (:Day, :Area, :Year),"Annual System Load Curve (MW)","MW")
  MBP = CreateVariableInHDF5(db, "EOutput/MBP", (:Month, :Area, :Year),"Maximum Baseload Point on Load Duration Curve (MW)","MW")
  MCE = CreateVariableInHDF5(db, "EOutput/MCE", (:Plant, :Power, :Area, :Year),"Marginal Cost of Energy from New Capacity (\$/MWh)","\$/MWh")
  MDP = CreateVariableInHDF5(db, "EOutput/MDP", (:Month, :Area, :Year),"Minimum Demand (MW)","MW")
  MFC = CreateVariableInHDF5(db, "EOutput/MFC", (:Plant, :Area, :Year),"Marginal Fixed Costs (\$/KW)","\$/KW")
  MILP = CreateVariableInHDF5(db, "EOutput/MILP", (:Month, :Area, :Year),"Maximum Base Load Power (MW)","MW")
  MVC = CreateVariableInHDF5(db, "EOutput/MVC", (:Plant, :Area, :Year),"Marginal Variable Costs (\$/MWh)","\$/MWh")
  NPAC = CreateVariableInHDF5(db, "EOutput/NPAC", (:ECC, :Area, :Year),"Non-Power Average Unit Cost (\$/MWh)","\$/MWh")
  NPAdd = CreateVariableInHDF5(db, "EOutput/NPAdd", (:ECC, :Area, :Year),"Non-Power Cost Additions (M\$/Yr)","M\$/Yr")
  NPCosts = CreateVariableInHDF5(db, "EOutput/NPCosts", (:ECC, :Area, :Year),"Non-Power Costs (M\$/Yr)","M\$/Yr")
  NPICosts = CreateVariableInHDF5(db, "EOutput/NPICosts", (:ECC, :Area, :Year),"Non-Power Indicated Costs (M\$/Yr)","M\$/Yr")
  NPRetire = CreateVariableInHDF5(db, "EOutput/NPRetire", (:ECC, :Area, :Year),"Non-Power Cost Retirements (M\$/Yr)","M\$/Yr")
  PAF = CreateVariableInHDF5(db, "EOutput/PAF", (:Plant, :GenCo, :Year),"Plant Availability Fractor (MW/MW)","MW/MW")
  PDP = CreateVariableInHDF5(db, "EOutput/PDP", (:Month, :Area, :Year),"Annual Peak Load (MW)","MW")
  PDPT = CreateVariableInHDF5(db, "EOutput/PDPT", (:Area, :Year),"Total Peak Demand (MW)","MW")
  PE = CreateVariableInHDF5(db, "EOutput/PE", (:ECC, :Area, :Year),"Price of Electricity (\$/MWh)","\$/MWh")
  PECalc = CreateVariableInHDF5(db, "EOutput/PECalc", (:ECC, :Area, :Year),"Calculated Price of Electricity (\$/MWh)","\$/MWh")
  PEClass = CreateVariableInHDF5(db, "EOutput/PEClass", (:Class, :Area, :Year),"Price of Electricity (\$/MWh)","\$/MWh")
  PPCT = CreateVariableInHDF5(db, "EOutput/PPCT", (:PPSet, :Area, :Year),"Cost of Purchase Power (M\$/Yr)","M\$/Yr")
  PPEGA = CreateVariableInHDF5(db, "EOutput/PPEGA", (:PPSet, :Area, :Year),"Purchased Power (GWh/Yr)","GWh/Yr")
  PPEGTM = CreateVariableInHDF5(db, "EOutput/PPEGTM", (:Area, :TimeP, :Month, :Year),"Power Purchases (GWh)","GWh")
  PPUC = CreateVariableInHDF5(db, "EOutput/PPUC", (:Area, :Year),"Unit Cost of Purchased Power (\$/MWh)","\$/MWh")
  PPVCost = CreateVariableInHDF5(db, "EOutput/PPVCost", (:PPSet, :Month, :Area, :Year),"Estimated Spot Market Price (\$/MWh)","\$/MWh")
  PUCT = CreateVariableInHDF5(db, "EOutput/PUCT", (:Area, :Year),"Cost of Purchase Power (M\$/Yr)","M\$/Yr")
  PUCTBI = CreateVariableInHDF5(db, "EOutput/PUCTBI", (:Area, :Year),"Cost of Purchase Power from Bilateral Contracts (M\$/Yr)","M\$/Yr")
  PUCTSM = CreateVariableInHDF5(db, "EOutput/PUCTSM", (:Area, :Year),"Cost of Purchase Power from Spot Market (M\$/Yr)","M\$/Yr")
  Rev = CreateVariableInHDF5(db, "EOutput/Rev", (:Area, :Year),"Revenue (M\$/Yr)","M\$/Yr")
  RnACE = CreateVariableInHDF5(db, "EOutput/RnACE", (:Year,),"Average Unit Cost of Renewable Power (\$/MWh)","\$/MWh")
  RnPE = CreateVariableInHDF5(db, "EOutput/RnPE", (:Area, :Year),"RECs Contribution to Retail Price (\$/MWh)","\$/MWh")
  RnCosts = CreateVariableInHDF5(db, "EOutput/RnCosts", (:Area, :Year),"Renewable RECs Costs (\$)","\$")
  RnRq = CreateVariableInHDF5(db, "EOutput/RnRq", (:Area, :Year),"Renewable Purchases Required (GWh)","GWh")
  RnSelf = CreateVariableInHDF5(db, "EOutput/RnSelf", (:Area, :Year),"Renewable Purchases from Bilateral Contracts (GWh)","GWh")
  RV = CreateVariableInHDF5(db, "EOutput/RV", (:Class, :Area, :Year),"Electricity Revenues (M\$/Yr)","M\$/Yr")
  SACL = CreateVariableInHDF5(db, "EOutput/SACL", (:Class, :Area, :Year),"Electricity Sales (GWh/Yr)","GWh/Yr")
  SAEC = CreateVariableInHDF5(db, "EOutput/SAEC", (:ECC, :Area, :Year),"Electricity Sales (GWh/Yr)","GWh/Yr")
  SAECN = CreateVariableInHDF5(db, "EOutput/SAECN", (:ECC, :Node, :Area, :Year),"Electricity Sales by Node (GWh/Yr)","GWh/Yr")
  SelfCap = CreateVariableInHDF5(db, "EOutput/SelfCap", (:Area, :GenCo, :Year),"Fraction of Capacity Sold through Self Dealing (MW/MW)","MW/MW")
  SelfFr = CreateVariableInHDF5(db, "EOutput/SelfFr", (:Area, :GenCo, :Year),"Self Dealing Fraction as Output (MW/MW)","MW/MW")
  SICstG = CreateVariableInHDF5(db, "EOutput/SICstG", (:GenCo, :Year),"Stranded Investment Cost by GenCo (M\$/Yr)","M\$/Yr")
  SICstPE = CreateVariableInHDF5(db, "EOutput/SICstPE", (:Area, :Year),"Stranded Investment Cost in Retail Price (\$/MWh)","\$/MWh")
  SICstR = CreateVariableInHDF5(db, "EOutput/SICstR", (:Area, :Year),"Stranded Investment Cost by Area (M\$/Yr)","M\$/Yr")
  TPPEGA = CreateVariableInHDF5(db, "EOutput/TPPEGA", (:Area, :Year),"Total Purchase Power (GWh)","GWh")
  TSales = CreateVariableInHDF5(db, "EOutput/TSales", (:Area, :Year),"Total Electricity Sales (GWh/Yr)","GWh/Yr")
  UCConts = CreateVariableInHDF5(db, "EOutput/UCConts", (:Area, :Year),"Unit Cost of Contracts (\$/KW)","\$/KW")
  UCCost = CreateVariableInHDF5(db, "EOutput/UCCost", (:Area, :GenCo, :Plant, :Year),"Contract Capacity Cost (US\$/KW)","US\$/KW")
  UECOST = CreateVariableInHDF5(db, "EOutput/UECOST", (:Area, :GenCo, :Plant, :Year),"Contract Energy Cost (US\$/MWh)","US\$/MWh")
  UPURPP = CreateVariableInHDF5(db, "EOutput/UPURPP", (:Area, :Year),"UNIT Cost OF PURCHASES","NoUnit")
  UVCost = CreateVariableInHDF5(db, "EOutput/UVCost", (:Area, :GenCo, :Plant, :Year),"Contract Variable Cost (US\$/MWh)","US\$/MWh")
end # struct EOutput
