#
# KOutput.jl - Input Database creation file
#

Base.@kwdef struct KOutput <: HDF5GroupDatabase
  db::String=DB
  
  #
  # Define Sets
  #
  Area = ReadSetFromCSV("Area","Key")
  AreaTOM = ReadSetFromCSV("AreaTOM","Key")
  CNAreaTOM = ReadSetFromCSV("CNAreaTOM","Key")
  ECCTOM = ReadSetFromCSV("ECCTOM","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  ECCFloorspaceTOM = ReadSetFromCSV("ECCFloorspaceTOM","Key")
  ECCResTOM = ReadSetFromCSV("ECCResTOM","Key")
  Fleet = ReadSetFromCSV("Fleet","Key")
  Fuel = ReadSetFromCSV("Fuel","Key")
  FuelAggTOM = ReadSetFromCSV("FuelAggTOM","Key")
  FuelTOM = ReadSetFromCSV("FuelTOM","Key")
  NationTOM = ReadSetFromCSV("NationTOM","Key")
  PriceTOM = ReadSetFromCSV("PriceTOM","Key")
  ResEnergyTOM = ReadSetFromCSV("ResEnergyTOM","Key")
  tv = ReadSetFromCSV("tv","Key")
  VehicleTOM = ReadSetFromCSV("VehicleTOM","Key")
  WorldTOM = ReadSetFromCSV("WorldTOM","Key")
  Year = ReadSetFromCSV("Year","Key")

  #
  # Define Variables on Database
  #
  EnVehicleTOM = CreateVariableInHDF5(db, "KOutput/EnVehicleTOM", (:FuelTOM, :VehicleTOM, :AreaTOM, :Year),"Transportation Energy Demand Mapped to VehicleTOM (TBtu)","TBtu")
  FleetInvestments = CreateVariableInHDF5(db, "KOutput/FleetInvestments", (:Fleet, :AreaTOM, :Year),"ENERGY 2020 Fleet Investments (2012 CN\$M/Yr)","2012 CN\$M/Yr")
  FleetInvestmentsChange = CreateVariableInHDF5(db, "KOutput/FleetInvestmentsChange", (:Fleet, :AreaTOM, :Year),"ENERGY 2020 Policy Change in Fleet Investments (2012 CN\$M/Yr)","2012 CN\$M/Yr")
  FleetInvestmentsRef = CreateVariableInHDF5(db, "KOutput/FleetInvestmentsRef", (:Fleet, :AreaTOM, :Year),"ENERGY 2020 Reference Case Fleet Investments (2012 CN\$M/Yr)","2012 CN\$M/Yr")
  GrossDemands = CreateVariableInHDF5(db, "KOutput/GrossDemands", (:Fuel, :ECC, :Area, :Year),"Gross Energy Demands (TBtu/Yr)","TBtu/Yr")
  GYinto = CreateVariableInHDF5(db, "KOutput/GYinto", (:ECCTOM, :AreaTOM, :Year),"Gross Output for TOM Inputs (2012 CN\$M/Yr)","2012 CN\$M/Yr")
  GYAdjust = CreateVariableInHDF5(db, "KOutput/GYAdjust", (:ECCTOM, :AreaTOM, :Year),"Gross Output from TOM, Adjusted to Fix Missing TOM Data (2012 CN\$M/Yr)","2012 CN\$M/Yr")
  IFCinto = CreateVariableInHDF5(db, "KOutput/IFCinto", (:ECCTOM, :AreaTOM, :Year),"Construction Investments (2017 \$M/Yr)","2017 \$M/Yr")
  IFMEinto = CreateVariableInHDF5(db, "KOutput/IFMEinto", (:ECCTOM, :AreaTOM, :Year),"Investments in Machinery & Equipment  (2017 \$M/Yr)","2017 \$M/Yr")
  K_TOM = CreateVariableInHDF5(db, "KOutput/K_TOM", (:ECC, :Area, :Year),"Total Capital Stock (\$M)","\$M")
  KC_TOM = CreateVariableInHDF5(db, "KOutput/KC_TOM", (:ECC, :Area, :Year),"Capital Stock Construction (\$M)","\$M")
  KME_TOM = CreateVariableInHDF5(db, "KOutput/KME_TOM", (:ECC, :Area, :Year),"Capital Stock Machines & Equipment (\$M)","\$M")
  KMFuel = CreateVariableInHDF5(db, "KOutput/KMFuel", (:FuelTOM, :VehicleTOM, :AreaTOM, :Year),"Vehicle Distance Traveled by Vehicle Type and Fuel (KM/Yr)","KM/Yr")
  ResTranspInvest = CreateVariableInHDF5(db, "KOutput/ResTranspInvest", (:AreaTOM, :Year),"Residential Transportation Investments (2017 \$M/Yr)","2017 \$M/Yr")
  SplitECCtoTOM = CreateVariableInHDF5(db, "KOutput/SplitECCtoTOM", (:ECC, :ECCTOM, :AreaTOM, :Year),"Split ECC into TOM based on Gross Output (\$/\$)","\$/\$")
  SplitECCtoTOMIFC = CreateVariableInHDF5(db, "KOutput/SplitECCtoTOMIFC", (:ECC, :ECCTOM, :AreaTOM, :Year),"Split ECC to TOM based on Construction Investments, IFC (\$/\$)","\$/\$")
  SplitECCtoTOMIFME = CreateVariableInHDF5(db, "KOutput/SplitECCtoTOMIFME", (:ECC, :ECCTOM, :AreaTOM, :Year),"Split ECC to TOM based on M&E Investments, IFME (\$/\$)","\$/\$")
  VehicleSalesImplied = CreateVariableInHDF5(db, "KOutput/VehicleSalesImplied", (:Fleet, :ECCTOM, :AreaTOM, :Year),"Vehicle Sales by Industry Implied by Historical Fraction of Gross Output (2017 \$M/Yr)","2017 \$M/Yr")
  VehicleSalesImpliedFrac = CreateVariableInHDF5(db, "KOutput/VehicleSalesImpliedFrac", (:Fleet, :ECCTOM, :AreaTOM, :Year),"Vehicle Sales by Industry Implied by Historical Fraction of Gross Output (\$/\$)","\$/\$")
  xDeviceInvestments = CreateVariableInHDF5(db, "KOutput/xDeviceInvestments", (:ECC, :Area, :Year),"Device Investments (M\$/Yr)","M\$/Yr")
  xPC_TOM = CreateVariableInHDF5(db, "KOutput/xPC_TOM", (:ECC, :Area, :Year),"Production Capacity (M\$/Yr)","M\$/Yr")
  xPInv = CreateVariableInHDF5(db, "KOutput/xPInv", (:ECC, :Area, :Year),"Process Investments (M\$/Yr)","M\$/Yr")
  C = CreateVariableInHDF5(db, "KOutput/C", (:AreaTOM, :Year),"Personal Consumption (2017 \$M/Yr)","2017 \$M/Yr")
  CNation = CreateVariableInHDF5(db, "KOutput/CNation", (:NationTOM, :Year),"Personal Consumption by Nation (2017 \$M/Yr)","2017 \$M/Yr")
  CD = CreateVariableInHDF5(db, "KOutput/CD", (:AreaTOM, :Year),"Household Appliance Investments (2017 \$M/Yr)","2017 \$M/Yr")
  CPI = CreateVariableInHDF5(db, "KOutput/CPI", (:AreaTOM, :Year),"Consumer Price Index (Index 2002=100)","Index 2002=100")
  CPINation = CreateVariableInHDF5(db, "KOutput/CPINation", (:NationTOM, :Year),"Consumer Price Index by Nation (Index 2002=100)","Index 2002=100")
  CUMOD = CreateVariableInHDF5(db, "KOutput/CUMOD", (:ECCTOM, :AreaTOM, :Year),"Output Gap (\$/\$)","\$/\$")
  EmpTOM = CreateVariableInHDF5(db, "KOutput/EmpTOM", (:ECCTOM, :AreaTOM, :Year),"Employment (Persons)","Persons")
  FlrSpc = CreateVariableInHDF5(db, "KOutput/FlrSpc", (:ECCFloorspaceTOM, :CNAreaTOM, :Year),"Floorspace (1000 Sq Meters)","1000 Sq Meters")
  GDP = CreateVariableInHDF5(db, "KOutput/GDP", (:AreaTOM, :Year),"Gross Domestic Product (2017 \$M/Yr)","2017 \$M/Yr")
  GDPNation = CreateVariableInHDF5(db, "KOutput/GDPNation", (:NationTOM, :Year),"Gross Domestic Product (2017 \$M/Yr)","2017 \$M/Yr")
  GExp = CreateVariableInHDF5(db, "KOutput/GExp", (:NationTOM, :Year),"Government expenditures (Nominal \$M)","Nominal \$M")
  GY = CreateVariableInHDF5(db, "KOutput/GY", (:ECCTOM, :AreaTOM, :Year),"Gross Output (2017 \$M/Yr)","2017 \$M/Yr")
  HH = CreateVariableInHDF5(db, "KOutput/HH", (:ECCResTOM, :CNAreaTOM, :Year),"Households (HouseHolds)","HouseHolds")
  HSA = CreateVariableInHDF5(db, "KOutput/HSA", (:ECCResTOM, :AreaTOM, :Year),"Housing Stock by Dwelling (Units)","Units")
  HSATot = CreateVariableInHDF5(db, "KOutput/HSATot", (:AreaTOM, :Year),"Housing Stock Total (Thousand Units)","Thousand Units")
  HSATotNation = CreateVariableInHDF5(db, "KOutput/HSATotNation", (:NationTOM, :Year),"Housing Stock Total by Nation (Thousand Units)","Thousand Units")
  IFC = CreateVariableInHDF5(db, "KOutput/IFC", (:ECCTOM, :AreaTOM, :Year),"Investments in Construction (2017 \$M/Yr)","2017 \$M/Yr")
  IFCHH = CreateVariableInHDF5(db, "KOutput/IFCHH", (:AreaTOM, :Year),"Residential Investments in Construction (2017 \$M/Yr)","2017 \$M/Yr")
  IFME = CreateVariableInHDF5(db, "KOutput/IFME", (:ECCTOM, :AreaTOM, :Year),"Investments in Machinery & Equipment (2017 \$M/Yr)","2017 \$M/Yr")
  IPRD = CreateVariableInHDF5(db, "KOutput/IPRD", (:AreaTOM, :Year),"Residential Investments (2017 \$M/Yr)","2017 \$M/Yr")
  K = CreateVariableInHDF5(db, "KOutput/K", (:ECCTOM, :AreaTOM, :Year),"Total Capital Stock (2012 \$M)","2012 \$M")
  KC = CreateVariableInHDF5(db, "KOutput/KC", (:ECCTOM, :AreaTOM, :Year),"Capital Stock Construction (2012 \$M)","2012 \$M")
  KME = CreateVariableInHDF5(db, "KOutput/KME", (:ECCTOM, :AreaTOM, :Year),"Capital Stock Machinery & Equipment (2012 \$M)","2012 \$M")
  KRD = CreateVariableInHDF5(db, "KOutput/KRD", (:AreaTOM, :Year),"Residential Housing Capital Stock (2012 \$M)","2012 \$M")
  LS = CreateVariableInHDF5(db, "KOutput/LS", (:NationTOM, :Year),"Labor Force (Persons)","Persons")
  PEDY = CreateVariableInHDF5(db, "KOutput/PEDY", (:AreaTOM, :Year),"Personal Disposable Income (2017 \$M/Yr)","2017 \$M/Yr")
  PEY = CreateVariableInHDF5(db, "KOutput/PEY", (:AreaTOM, :Year),"Personal Income (2017 \$M/Yr)","2017 \$M/Yr")
  PGDP = CreateVariableInHDF5(db, "KOutput/PGDP", (:NationTOM, :Year),"Implicit Price Deflator: GDP at market prices (Index)","Index")
  PopTOM = CreateVariableInHDF5(db, "KOutput/PopTOM", (:AreaTOM, :Year),"Population, total (Persons)","Persons")
  RXD = CreateVariableInHDF5(db, "KOutput/RXD", (:NationTOM, :Year),"Exchange Rates (CN\$/US\$)","CN\$/US\$")
  GVA_TOM = CreateVariableInHDF5(db, "KOutput/GVA_TOM", (:ECCTOM, :AreaTOM, :Year),"Gross Value Added (2017 \$M/Yr)","2017 \$M/Yr")
  YHAT = CreateVariableInHDF5(db, "KOutput/YHAT", (:ECCTOM, :AreaTOM, :Year),"Potential Output (2017 \$M/Yr)","2017 \$M/Yr")
  #
  # E2020 Outputs (To TOM) 
  #
  CDe = CreateVariableInHDF5(db, "KOutput/CDe", (:AreaTOM, :Year),"E2020 Household Appliance Investments (2017 \$M/Yr)","2017 \$M/Yr")
  CD_NRG = CreateVariableInHDF5(db, "KOutput/CD_NRG", (:AreaTOM, :Year),"E2020 Household Energy Appliance Investments from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  CD_Tra = CreateVariableInHDF5(db, "KOutput/CD_Tra", (:AreaTOM, :Year),"E2020 Household Transportation Appliance Investments from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  EPermit = CreateVariableInHDF5(db, "KOutput/EPermit", (:ECCTOM, :AreaTOM, :Year),"Cost of Emission Permits in TOM (M\$/Yr)","M\$/Yr")
  EPermitE = CreateVariableInHDF5(db, "KOutput/EPermitE", (:ECCTOM, :AreaTOM, :Year),"Cost of Emission Permits in ENERGY 2020 (M\$/Yr)","M\$/Yr")
  EPermitHH = CreateVariableInHDF5(db, "KOutput/EPermitHH", (:AreaTOM, :Year),"Household Cost of Emissions Permits in TOM (\$M/Yr)","\$M/Yr")
  EPermitHHe = CreateVariableInHDF5(db, "KOutput/EPermitHHe", (:AreaTOM, :Year),"Household Cost of Emissions Permits in ENERGY 2020 (\$M/Yr)","\$M/Yr")
  EInt = CreateVariableInHDF5(db, "KOutput/EInt", (:FuelTOM, :ECCTOM, :AreaTOM, :Year),"Energy Intensity from Macro Model (mmBtu/2012 \$M)","mmBtu/2017 \$M")
  EIntE = CreateVariableInHDF5(db, "KOutput/EIntE", (:FuelTOM, :ECCTOM, :AreaTOM, :Year),"Energy Intensity from ENERGY 2020(mmBtu/2012 \$M)","mmBtu/2017 \$M")
  EIntTr = CreateVariableInHDF5(db, "KOutput/EIntTr", (:FuelTOM, :VehicleTOM, :AreaTOM, :Year),"Transportation Energy Intensity from Macro Model (TBtu/Thousand KM)","TBtu/Thousand KM")
  EIntETr = CreateVariableInHDF5(db, "KOutput/EIntETr", (:FuelTOM, :VehicleTOM, :AreaTOM, :Year),"Transportation Energy Intensity from E2020 (mmBtu/Thousand KM)","mmBtu/Thousand KM")
  En = CreateVariableInHDF5(db, "KOutput/En", (:FuelTOM, :ECCTOM, :AreaTOM, :Year),"Energy Demands from Macro Model (TBtu/Yr)","TBtu/Yr")
  EnRes = CreateVariableInHDF5(db, "KOutput/EnRes", (:ResEnergyTOM, :AreaTOM, :Year),"Residential Energy Demands including Transportation from Macro Model (TBtu/Yr)","TBtu/Yr")
  ENe = CreateVariableInHDF5(db, "KOutput/ENe", (:FuelTOM, :ECCTOM, :AreaTOM, :Year),"Energy Demands from ENERGY 2020 (TBtu/Yr)","TBtu/Yr")
  EnResE = CreateVariableInHDF5(db, "KOutput/EnResE", (:ResEnergyTOM, :AreaTOM, :Year),"Residential Energy Demands including Transportation from ENERGY 2020 (TBtu/Yr)","TBtu/Yr")
  GExp_Pol = CreateVariableInHDF5(db, "KOutput/GExp_Pol", (:AreaTOM, :Year),"TOM Government expenditure, total, LCU [C\$] (Real \$M)","Real \$M")
  GExp_PolE = CreateVariableInHDF5(db, "KOutput/GExp_PolE", (:AreaTOM, :Year),"E2020 Government expenditure, total, LCU [C\$] (Real \$M)","Real \$M")
  GYEONominal = CreateVariableInHDF5(db, "KOutput/GYEONominal", (:AreaTOM, :Year),"Gross Output Nominal from TOM (M\$/Yr)","M\$/Yr")
  GYEONominalE = CreateVariableInHDF5(db, "KOutput/GYEONominalE", (:AreaTOM, :Year),"Gross Output Nominal from ENERGY 2020 (M\$/Yr)","M\$/Yr")
  IF_Oth = CreateVariableInHDF5(db, "KOutput/IF_Oth", (:ECCTOM, :AreaTOM, :Year),"Non-productive Investments in TOM (2017 \$M/Yr)","2017 \$M/Yr")
  IF_OthE = CreateVariableInHDF5(db, "KOutput/IF_OthE", (:ECCTOM, :AreaTOM, :Year),"Non-productive Investments in ENERGY 2020 (2017 \$M/Yr)","2017 \$M/Yr")
  IFCe = CreateVariableInHDF5(db, "KOutput/IFCe", (:ECCTOM, :AreaTOM, :Year),"E2020 Investments in Construction (2017 \$M/Yr)","2017 \$M/Yr")
  IFC_Pol = CreateVariableInHDF5(db, "KOutput/IFC_Pol", (:ECCTOM, :AreaTOM, :Year),"TOM Investments in Construction from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  IFC_PolE = CreateVariableInHDF5(db, "KOutput/IFC_PolE", (:ECCTOM, :AreaTOM, :Year),"E2020 Investments in Construction from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  IFCHHe = CreateVariableInHDF5(db, "KOutput/IFCHHe", (:AreaTOM, :Year),"E2020 Residential Investments in Construction (2017 \$M/Yr)","2017 \$M/Yr")
  IFCHH_Pol = CreateVariableInHDF5(db, "KOutput/IFCHH_Pol", (:AreaTOM, :Year),"TOM Residential Investments in Construction from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  IFCHH_PolE = CreateVariableInHDF5(db, "KOutput/IFCHH_PolE", (:AreaTOM, :Year),"E2020 Policy Driver Residential Investments in Construction from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  IF_NRG = CreateVariableInHDF5(db, "KOutput/IF_NRG", (:ECCTOM, :AreaTOM, :Year),"E2020 Investments in Energy Machinery & Equipment from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  IF_Tra = CreateVariableInHDF5(db, "KOutput/IF_Tra", (:ECCTOM, :AreaTOM, :Year),"E2020 Investments in Transportation Machinery & Equipment from Policy (2017 \$M/Yr)","2017 \$M/Yr")
  IFMEe = CreateVariableInHDF5(db, "KOutput/IFMEe", (:ECCTOM, :AreaTOM, :Year),"E2020 Investments in Machinery & Equipment (2017 \$M/Yr)","2017 \$M/Yr")
  KM = CreateVariableInHDF5(db, "KOutput/KM", (:VehicleTOM, :AreaTOM, :Year),"Kilometers Traveled by Vehicle Type from TOM (Million KM)","Million KM")
  KM_e = CreateVariableInHDF5(db, "KOutput/KM_e", (:VehicleTOM, :AreaTOM, :Year),"Kilometers Traveled by Vehicle Type from E2020 (Million KM)","Million KM")
  KMShare = CreateVariableInHDF5(db, "KOutput/KMShare", (:FuelTOM, :VehicleTOM, :AreaTOM, :Year),"Fuel Share of Kilometers Traveled by Vehicle Type from TOM (km/km)","km/km")
  KMShare_e = CreateVariableInHDF5(db, "KOutput/KMShare_e", (:FuelTOM, :VehicleTOM, :AreaTOM, :Year),"Fuel Share of Kilometers Traveled by Vehicle Type from E2020 (km/km)","km/km")
  LDV_SALES = CreateVariableInHDF5(db, "KOutput/LDV_SALES", (:AreaTOM, :Year),"Vehicle Sales (Number of Vehicle)","Number of Vehicle")
  MN = CreateVariableInHDF5(db, "KOutput/MN", (:FuelAggTOM, :AreaTOM, :Year),"TOM Domestic Imports (TBtu)","TBtu")
  MNe = CreateVariableInHDF5(db, "KOutput/MNe", (:FuelAggTOM, :AreaTOM, :Year),"ENERGY 2020 Domestic Imports (TBtu)","TBtu")
  MX = CreateVariableInHDF5(db, "KOutput/MX", (:FuelAggTOM, :AreaTOM, :Year),"TOM International Imports (TBtu)","TBtu")
  MXe = CreateVariableInHDF5(db, "KOutput/MXe", (:FuelAggTOM, :AreaTOM, :Year),"ENERGY 2020 International Imports (TBtu)","TBtu")
  OMExpE = CreateVariableInHDF5(db, "KOutput/OMExpE", (:ECCTOM, :AreaTOM, :Year),"O&M Expenditures from ENERGY 2020 (2017 M\$)","2017 M\$")
  OMExpTOM = CreateVariableInHDF5(db, "KOutput/OMExpTOM", (:ECCTOM, :AreaTOM, :Year),"O&M Expenditures from TOM (2012 M\$)","2012 M\$")
  P = CreateVariableInHDF5(db, "KOutput/P", (:PriceTOM, :AreaTOM, :Year),"Delivered Prices from Macro Model (\$/mmBtu)","\$/mmBtu")
  Pe = CreateVariableInHDF5(db, "KOutput/Pe", (:PriceTOM, :AreaTOM, :Year),"Delivered Prices from ENERGY 2020 (\$/mmBtu)","\$/mmBtu")
  Q = CreateVariableInHDF5(db, "KOutput/Q", (:FuelAggTOM, :AreaTOM, :Year),"Energy Production from Macro Model (TBtu/Yr)","TBtu/Yr")
  Qe = CreateVariableInHDF5(db, "KOutput/Qe", (:FuelAggTOM, :AreaTOM, :Year),"Energy Production from ENERGY 2020 (TBtu/Yr)","TBtu/Yr")
  WPCL = CreateVariableInHDF5(db, "KOutput/WPCL", (:WorldTOM, :Year),"Coal Price from Macro Model (Index 2005=100)","Index 2005=100")
  WPCLe = CreateVariableInHDF5(db, "KOutput/WPCLe", (:WorldTOM, :Year),"Coal Price from ENERGY 2020 (Index 2005=100)","Index 2005=100")
  WPGasHH = CreateVariableInHDF5(db, "KOutput/WPGasHH", (:WorldTOM, :Year),"Gas World from TOM (US\$/mmBtu)","US\$/mmBtu")
  WPGasHHe = CreateVariableInHDF5(db, "KOutput/WPGasHHe", (:WorldTOM, :Year),"Gas World from ENERGY 2020 (US\$/mmBtu)","US\$/mmBtu")
  WPO_WCS = CreateVariableInHDF5(db, "KOutput/WPO_WCS", (:WorldTOM, :Year),"WCS Oil Price from TOM (US\$/bbl)","US\$/bbl")
  WPO_WCSe = CreateVariableInHDF5(db, "KOutput/WPO_WCSe", (:WorldTOM, :Year),"WCS Oil Price from ENERGY 2020 (US\$/bbl)","US\$/bbl")
  WPO_WTI = CreateVariableInHDF5(db, "KOutput/WPO_WTI", (:WorldTOM, :Year),"WTI Oil Price from TOM (US\$/bbl)","US\$/bbl")
  WPO_WTIe = CreateVariableInHDF5(db, "KOutput/WPO_WTIe", (:WorldTOM, :Year),"WTI Oil Price from ENERGY 2020 (US\$/bbl)","US\$/bbl")
  XN = CreateVariableInHDF5(db, "KOutput/XN", (:FuelAggTOM, :AreaTOM, :Year),"TOM Domestic Exports (TBtu)","TBtu")
  XNe = CreateVariableInHDF5(db, "KOutput/XNe", (:FuelAggTOM, :AreaTOM, :Year),"ENERGY 2020 Domestic Exports (TBtu)","TBtu")
  XX = CreateVariableInHDF5(db, "KOutput/XX", (:FuelAggTOM, :AreaTOM, :Year),"TOM International Exports (TBtu)","TBtu")
  XXe = CreateVariableInHDF5(db, "KOutput/XXe", (:FuelAggTOM, :AreaTOM, :Year),"ENERGY 2020 International Exports (TBtu)","TBtu")
  #
  # E2020 Outputs - Second List - for connection testing
  #
  IF_Sub = CreateVariableInHDF5(db, "KOutput/IF_Sub", (:ECCTOM, :AreaTOM, :Year),"Investment Subsidy (Nominal \$M/Yr)","Nominal \$M/Yr")
  IF_SubE = CreateVariableInHDF5(db, "KOutput/IF_SubE", (:ECCTOM, :AreaTOM, :Year),"Investment Subsidy (Nominal \$M/Yr)","Nominal \$M/Yr")
  PMXUE = CreateVariableInHDF5(db, "KOutput/PMXUE", (:NationTOM, :Year),"Deflator on Imports of Electricity (Index 2012=100)","Index 2012=100")
  #
  # E2020 Outputs - Third List - needs new Promula code
  #
  ScrapRt_LDV = CreateVariableInHDF5(db, "KOutput/ScrapRt_LDV", (:AreaTOM, :Year),"Fraction of LDV Scrappage from Retrofits (\$/\$)","\$/\$")
  ScrapRtC = CreateVariableInHDF5(db, "KOutput/ScrapRtC", (:ECCTOM, :AreaTOM, :Year),"Fraction of Scrappage from Capital Stock Retrofits (\$/\$)","\$/\$")
  ScrapRtME = CreateVariableInHDF5(db, "KOutput/ScrapRtME", (:ECCTOM, :AreaTOM, :Year),"Fraction of Scrappage from Machinery & Equipment Retrofits (\$/\$)","\$/\$")
end # struct KOutput
