#
# MEInput.jl - Input Database creation file
#

Base.@kwdef struct MEInput <: HDF5GroupDatabase
  db::String=DB
  ########################
  #
  # Define Sets
  #
  Area = ReadSetFromCSV("Area","Key")
  Year = ReadSetFromCSV("Year","Key")
  tv = ReadSetFromCSV("tv","Key")
  FuelEP = ReadSetFromCSV("FuelEP","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  Poll = ReadSetFromCSV("Poll","Key")
  LU = ReadSetFromCSV("LU","Key")
  PollX = ReadSetFromCSV("PollX","Key")
  Offset = ReadSetFromCSV("Offset","Key")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
  DfC0 = CreateVariableInHDF5(db, "MEInput/DfC0", (:Area, :Year),"C Term for Deforestation Emissions Curve","NoUnit")
  EnPOCX = CreateVariableInHDF5(db, "MEInput/EnPOCX", (:FuelEP, :ECC, :Poll, :Area, :Year),"Energy Pollution Coefficient (Tonnes/\$B-output)","Tonnes/\$B-output")
  EORCreditMultiplier = CreateVariableInHDF5(db, "MEInput/EORCreditMultiplier", (:ECC, :Area, :Year),"EOR Credit Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  EORFraction = CreateVariableInHDF5(db, "MEInput/EORFraction", (:ECC, :Area, :Year),"Fraction of Sequestered CO2 used for EOR (Tonnes/Tonnes)","Tonnes/Tonnes")
  EORLimit = CreateVariableInHDF5(db, "MEInput/EORLimit", (:Area, :Year),"Maximum Amonut of Sequestered CO2 which can be used for EOR (Tonnes)","Tonnes")
  EORRate = CreateVariableInHDF5(db, "MEInput/EORRate", (:Area, :Year),"EOR Production per unit of Sequestered CO2 (TBtu/Tonne)","TBtu/Tonne")
  FlC2H6PerCH4 = CreateVariableInHDF5(db, "MEInput/FlC2H6PerCH4", (:ECC, :Area, :Year),"Flaring C2H6 Captured per CH4 Captured (Tonnes/Tonne CH4)","Tonnes/Tonne CH4")
  FlCC = CreateVariableInHDF5(db, "MEInput/FlCC", (:ECC, :Area, :Year),"Flaring Reduction Capital Cost (\$/Tonne CH4)","\$/Tonne CH4")
  FlCH4CapturedFraction = CreateVariableInHDF5(db, "MEInput/FlCH4CapturedFraction", (:ECC, :Area, :Year),"CH4 Captured from CO2 Flaring Reductions (Tonnes CH4/Tonne CO2)","Tonnes CH4/Tonne CO2")
  FlPOCX = CreateVariableInHDF5(db, "MEInput/FlPOCX", (:ECC, :Poll, :Area, :Year),"Flaring Emissions Coefficient (Tonnes/Driver)","Tonnes/Driver")
  FlPOCXMult = CreateVariableInHDF5(db, "MEInput/FlPOCXMult", (:ECC, :Poll, :Area, :Year),"Flaring Pollution Coefficient Multiplier (Tonnes/Driver)","Tonnes/Driver")
  FlRP = CreateVariableInHDF5(db, "MEInput/FlRP", (:ECC, :Poll, :Area, :Year),"Fraction of Flaring Reduced (Tonnes/Tonnes)","Tonnes/Tonnes")
  FuA0 = CreateVariableInHDF5(db, "MEInput/FuA0", (:ECC, :Area),"A Term in Other Fugitives Reduction Curve (??)","??")
  FuB0 = CreateVariableInHDF5(db, "MEInput/FuB0", (:ECC, :Area),"B Term in Other Fugitives Reduction Curve (??)","??")
  FuC0 = CreateVariableInHDF5(db, "MEInput/FuC0", (:ECC, :Area, :Year),"C Term in Other Fugitives Reduction Curve (??)","??")
  FuC2H6PerCH4 = CreateVariableInHDF5(db, "MEInput/FuC2H6PerCH4", (:ECC, :Area, :Year),"Other Fugitives C2H6 Captured per CH4 Captured (Tonnes/Tonne CH4)","Tonnes/Tonne CH4")
  FuCCA0 = CreateVariableInHDF5(db, "MEInput/FuCCA0", (:ECC, :Area),"A Term in Other Fugitives Reduction Capital Cost Curve (\$/\$)","\$/\$")
  FuCCB0 = CreateVariableInHDF5(db, "MEInput/FuCCB0", (:ECC, :Area),"B Term in Other Fugitives Reduction Capital Cost Curve (\$/\$)","\$/\$")
  FuCCC0 = CreateVariableInHDF5(db, "MEInput/FuCCC0", (:ECC, :Area, :Year),"C Term in Other Fugitives Reduction Capital Cost Curve (\$/\$)","\$/\$")
  FuCCReplace = CreateVariableInHDF5(db, "MEInput/FuCCReplace", (:ECC, :Area, :Year),"Other Fugitives Reduction Replacement Capital Cost (\$/Tonne CH4)","\$/Tonne CH4")
  FuCH4CapturedFraction = CreateVariableInHDF5(db, "MEInput/FuCH4CapturedFraction", (:ECC, :Area, :Year),"Fraction of CH4 Captured from Other Fugitives Reductions (Tonnes/Tonnes)","Tonnes/Tonnes")
  FuCH4FlaredPOCF = CreateVariableInHDF5(db, "MEInput/FuCH4FlaredPOCF", (:ECC, :Poll, :Area, :Year),"Pollution Coefficient for Flared CH4 (Tonnes/Tonnes)","Tonnes/Tonnes")
  FuGFr = CreateVariableInHDF5(db, "MEInput/FuGFr", (:ECC, :Area, :Year),"Other Fugitives Reduction Grant Fraction (\$/\$)","\$/\$")
  FuOCF = CreateVariableInHDF5(db, "MEInput/FuOCF", (:ECC, :Area, :Year),"Other Fugitives Reduction Operating Cost Factor (\$/\$)","\$/\$")
  FuPL = CreateVariableInHDF5(db, "MEInput/FuPL", (:ECC, :Area, :Year),"Other Fugitives Reduction Physical Lifetime (Years)","Years")
  FuPOCF = CreateVariableInHDF5(db, "MEInput/FuPOCF", (:ECC, :Poll, :Area, :Year),"Other Fugitives Emission Factor (Tonnes/Tonne CH4)","Tonnes/Tonne CH4")
  FuPOCX = CreateVariableInHDF5(db, "MEInput/FuPOCX", (:ECC, :Poll, :Area, :Year),"Other Fugitives Emissions Coefficient (Tonnes/Driver)","Tonnes/Driver")
  FuPOCXMult = CreateVariableInHDF5(db, "MEInput/FuPOCXMult", (:ECC, :Poll, :Area, :Year),"Other Fugitives Pollution Coefficient Multiplier (Tonnes/Driver)","Tonnes/Driver")
  FuPriceSw = CreateVariableInHDF5(db, "MEInput/FuPriceSw", (:Year,),"Other Fugitives Reduction Curve Price Switch (1=Endogenous, 0=Exogenous)","1=Endogenous, 0=Exogenous")
  LandArea = CreateVariableInHDF5(db, "MEInput/LandArea", (:Area,),"Land Use Area (Acres)","Acres")
  LUPOCX = CreateVariableInHDF5(db, "MEInput/LUPOCX", (:LU, :Poll, :Area, :Year),"Land Use Area Pollution Coefficient (Tonnes/Acre)","Tonnes/Acre")
  MEA0 = CreateVariableInHDF5(db, "MEInput/MEA0", (:ECC, :Poll, :Area, :Year),"A Term in eCO2 Reduction Curve (CDN 1999\$)","CDN 1999\$")
  MEB0 = CreateVariableInHDF5(db, "MEInput/MEB0", (:ECC, :Poll, :Area, :Year),"B Term in eCO2 Reduction Curve (CDN 1999\$)","CDN 1999\$")
  MEC0 = CreateVariableInHDF5(db, "MEInput/MEC0", (:ECC, :Poll, :Area, :Year),"C Term in eCO2 Reduction Curve (CDN 1999\$)","CDN 1999\$")
  MECM = CreateVariableInHDF5(db, "MEInput/MECM", (:Poll, :PollX),"Cross-over Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  MEGFr = CreateVariableInHDF5(db, "MEInput/MEGFr", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Grant Fraction (\$/\$)","\$/\$")
  MEIVTC = CreateVariableInHDF5(db, "MEInput/MEIVTC", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Investment Tax Credit (\$/\$)","\$/\$")
  MEOCF = CreateVariableInHDF5(db, "MEInput/MEOCF", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Operating Cost Factor (\$/\$)","\$/\$")
  MEPCstN = CreateVariableInHDF5(db, "MEInput/MEPCstN", (:ECC, :Poll, :Area),"Pollution Reduction Cost Normal (\$/Tonne)","\$/Tonne")
  MEPL = CreateVariableInHDF5(db, "MEInput/MEPL", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Physical Lifetime (Years)","Years")
  MEPOCX = CreateVariableInHDF5(db, "MEInput/MEPOCX", (:ECC, :Poll, :Area, :Year),"Non-Energy Pollution Coefficient (Tonnes/\$B-output)","Tonnes/\$B-output")
  MEPOCS = CreateVariableInHDF5(db, "MEInput/MEPOCS", (:ECC, :Poll, :Area, :Year),"Non-Energy Pollution Standard (Tonnes/\$B-output)","Tonnes/\$B-output")
  MEPriceSw = CreateVariableInHDF5(db, "MEInput/MEPriceSw", (:Year,),"Process Emission Reduction Curve Price Switch (1=Endogenous, 0=Exogenous)","1=Endogenous, 0=Exogenous")
  MEPVF = CreateVariableInHDF5(db, "MEInput/MEPVF", (:ECC, :Poll, :Area),"Pollution Reduction Variance Factor ((\$/Tonne)/(\$/Tonne))","(\$/Tonne")
  MERCA0 = CreateVariableInHDF5(db, "MEInput/MERCA0", (:ECC, :Poll, :Area, :Year),"A Term in Emission Reduction Curve (US\$2000)","US\$2000")
  MERCB0 = CreateVariableInHDF5(db, "MEInput/MERCB0", (:ECC, :Poll, :Area, :Year),"B Term in Emission Reduction Curve (US\$2000)","US\$2000")
  MERCC0 = CreateVariableInHDF5(db, "MEInput/MERCC0", (:ECC, :Poll, :Area, :Year),"C Term in Emission Reduction Curve (US\$2000)","US\$2000")
  MERCD = CreateVariableInHDF5(db, "MEInput/MERCD", (:ECC, :Poll),"Reduction Capital Construction Delay (Years)","Years")
  MERCPL = CreateVariableInHDF5(db, "MEInput/MERCPL", (:ECC, :Poll),"Reduction Capital Pysical Life (Years)","Years")
  MERCstM = CreateVariableInHDF5(db, "MEInput/MERCstM", (:ECC, :Poll, :Year),"Reduction Cost Technology multiplier (\$/\$)","\$/\$")
  MERCSw = CreateVariableInHDF5(db, "MEInput/MERCSw", (:ECC, :Poll, :Area, :Year),"Emission Reduction Curve Switch (1=Old, 2=New, 0=None)","1=Old, 2=New, 0=None")
  MEROCF = CreateVariableInHDF5(db, "MEInput/MEROCF", (:ECC, :Poll),"Polution Reducution O&M (\$/Tonne/(\$/Tonne))","\$/Tonne/(\$/Tonne")
  MEROIN = CreateVariableInHDF5(db, "MEInput/MEROIN", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Return on Investment (\$/\$)","\$/\$")
  METL = CreateVariableInHDF5(db, "MEInput/METL", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Tax Lifetime (Years)","Years")
  METxRt = CreateVariableInHDF5(db, "MEInput/METxRt", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Tax Rate (\$/\$)","\$/\$")
  MEVRP = CreateVariableInHDF5(db, "MEInput/MEVRP", (:ECC, :Poll, :Area, :Year),"Voluntary Reduction Policy (Tonnes/Tonnes)","Tonnes/Tonnes")
  MEVRRT = CreateVariableInHDF5(db, "MEInput/MEVRRT", (:ECC,),"Voluntary Reduction response time (Years)","Years")
  MWDecayTime = CreateVariableInHDF5(db, "MEInput/MWDecayTime", (:Area,),"Municipal Waste Decay Time (Years)","Years")
  ORMEPOCX = CreateVariableInHDF5(db, "MEInput/ORMEPOCX", (:ECC, :Poll, :Area, :Year),"Non-Energy Off Road Pollution Coefficient (Tonnes/\$B-output)","Tonnes/\$B-output")
  ReA0 = CreateVariableInHDF5(db, "MEInput/ReA0", (:Offset, :Area),"A Term in Reduction Curve (\$/Tonne)","\$/Tonne")
  ReB0 = CreateVariableInHDF5(db, "MEInput/ReB0", (:Offset, :Area),"B Term in Reduction Curve (\$/Tonne)","\$/Tonne")
  ReC0 = CreateVariableInHDF5(db, "MEInput/ReC0", (:Offset, :Area, :Year),"C Term in Reduction Curve (Tonnes/Yr)","Tonnes/Yr")
  ReC2H6PerCH4 = CreateVariableInHDF5(db, "MEInput/ReC2H6PerCH4", (:Offset, :Area, :Year),"Flaring C2H6 Captured per CH4 Captured (Tonnes/Tonne CH4)","Tonnes/Tonne CH4")
  ReCapturedFraction = CreateVariableInHDF5(db, "MEInput/ReCapturedFraction", (:Offset, :Poll, :Area, :Year),"Reductions Captured Fraction (Tonnes/Yr)","Tonnes/Yr")
  ReCCA0 = CreateVariableInHDF5(db, "MEInput/ReCCA0", (:Offset, :Area),"A Term in Reduction Capital Cost Curve (\$/\$)","\$/\$")
  ReCCB0 = CreateVariableInHDF5(db, "MEInput/ReCCB0", (:Offset, :Area),"B Term in Reduction Capital Cost Curve (\$/\$)","\$/\$")
  ReCCC0 = CreateVariableInHDF5(db, "MEInput/ReCCC0", (:Offset, :Area, :Year),"C Term in Reduction Capital Cost Curve (\$/\$)","\$/\$")
  ReCCReplace = CreateVariableInHDF5(db, "MEInput/ReCCReplace", (:Offset, :Area, :Year),"Reduction Replacement Capital Cost (\$/Tonne CH4)","\$/Tonne CH4")
  ReCCSwitch = CreateVariableInHDF5(db, "MEInput/ReCCSwitch", (:Offset, :Area, :Year),"Reduction Capital Cost Switch (1=Default)","1=Default")
  ReCD = CreateVariableInHDF5(db, "MEInput/ReCD", (:Offset,),"Reduction Construction Time (Years)","Years")
  ReCDOrder = CreateVariableInHDF5(db, "MEInput/ReCDOrder", (:Offset, :Year),"Number of Levels Reduction Construction Delay (Number)","Number")
  ReDevelopedFraction = CreateVariableInHDF5(db, "MEInput/ReDevelopedFraction", (:Offset, :Area, :Year),"Fraction of Captured Gas Developed into Electric Generating Capacity (MW/MW)","MW/MW")
  ReECC::SetArray = Offset
  ReElectricPotentialFactor = CreateVariableInHDF5(db, "MEInput/ReElectricPotentialFactor", (:Offset, :Area, :Year),"Electric Generating Capacity Potential from Captured Gas Factor (MW/MT)","MW/MT")
  ReGFr = CreateVariableInHDF5(db, "MEInput/ReGFr", (:Offset, :Area, :Year),"Reduction Grant Fraction (\$/\$)","\$/\$")
  ReInvSwitch = CreateVariableInHDF5(db, "MEInput/ReInvSwitch", (:Offset, :Area, :Year),"Reduction Investment Switch (1=Default)","1=Default")
  ReIVTC = CreateVariableInHDF5(db, "MEInput/ReIVTC", (:Offset, :Area, :Year),"Reduction Investment Tax Credit (\$/\$)","\$/\$")
  ReOCF = CreateVariableInHDF5(db, "MEInput/ReOCF", (:Offset, :Area, :Year),"Reduction Operating Cost Factor (\$/\$)","\$/\$")
  ReOMExpSwitch = CreateVariableInHDF5(db, "MEInput/ReOMExpSwitch", (:Offset, :Area, :Year),"Reduction O&M Expenses Switch (1=Default)","1=Default")
  RePL = CreateVariableInHDF5(db, "MEInput/RePL", (:Offset, :Area, :Year),"Reduction Physical Lifetime (Years)","Years")
  RePOCF = CreateVariableInHDF5(db, "MEInput/RePOCF", (:Offset, :Poll, :Area, :Year),"Reduction Factor (Tonnes/Tonnes)","Tonnes/Tonnes")
  RePollutant::SetArray = Offset
  RePriceSwitch = CreateVariableInHDF5(db, "MEInput/RePriceSwitch", (:Offset, :Area, :Year),"Reduction Emission Price Switch (1=Default)","1=Default")
  RePriceX = CreateVariableInHDF5(db, "MEInput/RePriceX", (:Offset, :Area, :Year),"Emission Exogenous Prices (\$/Tonne)","\$/Tonne")
  ReReductionsSwitch = CreateVariableInHDF5(db, "MEInput/ReReductionsSwitch", (:Offset, :Area, :Year),"Reductions Switch (1=Default)","1=Default")
  ReReductionsX = CreateVariableInHDF5(db, "MEInput/ReReductionsX", (:Offset, :Area, :Year),"Reductions Exogenous (Tonnes/Yr)","Tonnes/Yr")
  ReROIN = CreateVariableInHDF5(db, "MEInput/ReROIN", (:Offset, :Area, :Year),"Reduction Return on Investment (\$/\$)","\$/\$")
  ReTL = CreateVariableInHDF5(db, "MEInput/ReTL", (:Offset, :Area, :Year),"Reduction Tax Lifetime (Years)","Years")
  ReTxRt = CreateVariableInHDF5(db, "MEInput/ReTxRt", (:Offset, :Area, :Year),"Reduction Tax Rate (\$/\$)","\$/\$")
  ReType::SetArray = Offset
  SAC0 = CreateVariableInHDF5(db, "MEInput/SAC0", (:Area, :Year),"C Term in eCO2 Agriculture Sinks Curve","NoUnit")
  SFC0 = CreateVariableInHDF5(db, "MEInput/SFC0", (:Area, :Year),"C Term in eCO2 Forest Offset Curve","NoUnit")
  SqA0 = CreateVariableInHDF5(db, "MEInput/SqA0", (:ECC, :Area, :Year),"A Term in eCO2 Sequestering Curve (units assume 2016 CN\$)","units assume 2016 CN\$")
  SqB0 = CreateVariableInHDF5(db, "MEInput/SqB0", (:ECC, :Area, :Year),"B Term in eCO2 Sequestering Curve (Dimensionless)","Dimensionless")
  SqBL = CreateVariableInHDF5(db, "MEInput/SqBL", (:Area, :Year),"Sequestering Book Lifetime (Years)","Years")
  SqC0 = CreateVariableInHDF5(db, "MEInput/SqC0", (:ECC, :Area, :Year),"C Term in eCO2 Sequestering Curve (Tonnes/Tonnes)","Tonnes/Tonnes")
  SqCCA0 = CreateVariableInHDF5(db, "MEInput/SqCCA0", (:ECC, :Area, :Year),"A Term in eCO2 Sequestering Capital Cost Curve (2012 CN\$)","2012 CN\$")
  SqCCB0 = CreateVariableInHDF5(db, "MEInput/SqCCB0", (:ECC, :Area, :Year),"B Term in eCO2 Sequestering Capital Cost Curve (2012 CN\$)","2012 CN\$")
  SqCCC0 = CreateVariableInHDF5(db, "MEInput/SqCCC0", (:ECC, :Area, :Year),"C Term in eCO2 Sequestering Capital Cost Curve (2012 CN\$)","2012 CN\$")
  SqCCSw = CreateVariableInHDF5(db, "MEInput/SqCCSw", (:ECC, :Area, :Year),"Sequestering Capital Cost Switch (1=CC Curve)","1=CC Curve")
  SqCCThreshold = CreateVariableInHDF5(db, "MEInput/SqCCThreshold", (:ECC, :Area, :Year),"Levelized Cost Threshold for Sequestering Curve (2016 CN\$/Tonne)","2016 CN\$/Tonne")
  SqCD = CreateVariableInHDF5(db, "MEInput/SqCD", (:ECC, :Area, :Year),"Sequestering Construction Delay (Years)","Years")
  SqCDOrder = CreateVariableInHDF5(db, "MEInput/SqCDOrder", (:ECC, :Year),"Number of Levels in the Sequestering Construction Delay (Number)","Number")
  SqGFr = CreateVariableInHDF5(db, "MEInput/SqGFr", (:Area, :Year),"Sequestering eCO2 Reduction Grant Fraction (\$/\$)","\$/\$")
  SqIVTC = CreateVariableInHDF5(db, "MEInput/SqIVTC", (:Area, :Year),"Sequestering eCO2 Reduction Investment Tax Credit (\$/\$)","\$/\$")
  SqPenaltyFrac = CreateVariableInHDF5(db, "MEInput/SqPenaltyFrac", (:ECC, :Poll, :Area, :Year),"Sequestering Emission Penalty (Tonne/Tonne)","Tonne/Tonne")
  SqPL = CreateVariableInHDF5(db, "MEInput/SqPL", (:Area, :Year),"Sequestering eCO2 Reduction Physical Lifetime (Years)","Years")
  SqPOCF = CreateVariableInHDF5(db, "MEInput/SqPOCF", (:ECC, :Poll, :Area, :Year),"Sequestering Emission Factor (Tonnes/Tonne CO2)","Tonnes/Tonne CO2")
  SqROIN = CreateVariableInHDF5(db, "MEInput/SqROIN", (:Area, :Year),"Sequestering eCO2 Reduction Return on Investment (\$/\$)","\$/\$")
  SqTL = CreateVariableInHDF5(db, "MEInput/SqTL", (:Area, :Year),"Sequestering eCO2 Reduction Tax Lifetime (Years)","Years")
  SqTM = CreateVariableInHDF5(db, "MEInput/SqTM", (:ECC, :Area, :Year),"Sequestering eCO2 Reduction Tax Lifetime (Years)","Years")
  SqTransStorageCost = CreateVariableInHDF5(db, "MEInput/SqTransStorageCost", (:Area, :Year),"Sequestering Transportation and Storage Costs (2016 CN\$/tonne CO2e)","2016 CN\$/tonne CO2e")
  SqTSCapitalFraction = CreateVariableInHDF5(db, "MEInput/SqTSCapitalFraction", (:Area, :Year),"Captial Fraction of Sequestering Transportation and Storage Costs (\$/\$)","\$/\$")
  SqTxRt = CreateVariableInHDF5(db, "MEInput/SqTxRt", (:Area, :Year),"Sequestering eCO2 Reduction Tax Rate (\$/\$)","\$/\$")
  VnA0 = CreateVariableInHDF5(db, "MEInput/VnA0", (:ECC, :Area),"A Term in Venting Reduction Curve (??)","??")
  VnB0 = CreateVariableInHDF5(db, "MEInput/VnB0", (:ECC, :Area),"B Term in Venting Reduction Curve (??)","??")
  VnC0 = CreateVariableInHDF5(db, "MEInput/VnC0", (:ECC, :Area, :Year),"C Term in Venting Reduction Curve (??)","??")
  VnC2H6PerCH4 = CreateVariableInHDF5(db, "MEInput/VnC2H6PerCH4", (:ECC, :Area, :Year),"Venting C2H6 Captured per CH4 Captured (Tonnes/Tonne CH4)","Tonnes/Tonne CH4")
  VnCCA0 = CreateVariableInHDF5(db, "MEInput/VnCCA0", (:ECC, :Area),"A Term in Venting Reduction Capital Cost Curve (\$/\$)","\$/\$")
  VnCCB0 = CreateVariableInHDF5(db, "MEInput/VnCCB0", (:ECC, :Area),"B Term in Venting Reduction Capital Cost Curve (\$/\$)","\$/\$")
  VnCCC0 = CreateVariableInHDF5(db, "MEInput/VnCCC0", (:ECC, :Area, :Year),"C Term in Venting Reduction Capital Cost Curve (\$/\$)","\$/\$")
  VnCH4CapturedFraction = CreateVariableInHDF5(db, "MEInput/VnCH4CapturedFraction", (:ECC, :Area, :Year),"Fraction of Captured from Venting Reductions (Tonnes/Tonnes)","Tonnes/Tonnes")
  VnCH4FlaredPOCF = CreateVariableInHDF5(db, "MEInput/VnCH4FlaredPOCF", (:ECC, :Poll, :Area, :Year),"Pollution Coefficient for Flared CH4 (Tonnes/Tonnes)","Tonnes/Tonnes")
  VnGFr = CreateVariableInHDF5(db, "MEInput/VnGFr", (:ECC, :Area, :Year),"Venting Reduction Grant Fraction (\$/\$)","\$/\$")
  VnOCF = CreateVariableInHDF5(db, "MEInput/VnOCF", (:ECC, :Area, :Year),"Venting Reduction Operating Cost Factor (\$/\$)","\$/\$")
  VnPL = CreateVariableInHDF5(db, "MEInput/VnPL", (:ECC, :Area, :Year),"Venting Reduction Physical Lifetime (Years)","Years")
  VnPOCF = CreateVariableInHDF5(db, "MEInput/VnPOCF", (:ECC, :Poll, :Area, :Year),"Venting Other Pollutant Emission Factor (Tonnes/Tonne CH4)","Tonnes/Tonne CH4")
  VnPOCX = CreateVariableInHDF5(db, "MEInput/VnPOCX", (:ECC, :Poll, :Area, :Year),"Venting Emissions Coefficient (Tonnes/Driver)","Tonnes/Driver")
  VnPOCXMult = CreateVariableInHDF5(db, "MEInput/VnPOCXMult", (:ECC, :Poll, :Area, :Year),"Venting Pollution Coefficient Multiplier (Tonnes/Driver)","Tonnes/Driver")
  VnPriceSw = CreateVariableInHDF5(db, "MEInput/VnPriceSw", (:Year,),"Venting Reduction Curve Price Switch (1=Endogenous, 0=Exogenous)","1=Endogenous, 0=Exogenous")
  xFuPrice = CreateVariableInHDF5(db, "MEInput/xFuPrice", (:ECC, :Area, :Year),"Exogenous Price for Other Fugitives Reduction Curve (\$/Tonne)","\$/Tonne")
  xLUFr = CreateVariableInHDF5(db, "MEInput/xLUFr", (:LU, :Area, :Year),"Exogenous Land Use Area Fraction (Acre/Acre)","Acre/Acre")
  xMEPrice = CreateVariableInHDF5(db, "MEInput/xMEPrice", (:ECC, :Poll, :Area, :Year),"Exogenous Price for Process Emission Reduction Curve (\$/Tonne)","\$/Tonne")
  xMERM = CreateVariableInHDF5(db, "MEInput/xMERM", (:ECC, :Poll, :Area, :Year),"Exogenous Average Pollution Coefficient Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  xSqPol = CreateVariableInHDF5(db, "MEInput/xSqPol", (:ECC, :Poll, :Area, :Year),"Exogenous Sequestering Emissions (Tonnes/Yr)","Tonnes/Yr")
  xSqPolCCNet = CreateVariableInHDF5(db, "MEInput/xSqPolCCNet", (:ECC, :Poll, :Area, :Year),"Exogenous Sequestering Net Emissions (Tonnes/Yr)","Tonnes/Yr")
  xSqPrice = CreateVariableInHDF5(db, "MEInput/xSqPrice", (:ECC, :Area, :Year),"Exogenous Sequestering Cost Curve Price (\$/tonne CO2e)","\$/tonne CO2e")
  xSqPriceAdd = CreateVariableInHDF5(db, "MEInput/xSqPriceAdd", (:ECC, :Area, :Year),"Exogenous Adder to Sequestering Cost Curve Price (Real \$/tonne CO2e)","Real \$/tonne CO2e")
  xVnPrice = CreateVariableInHDF5(db, "MEInput/xVnPrice", (:ECC, :Area, :Year),"Exogenous Price for Venting Reduction Curve (\$/Tonne)","\$/Tonne")
end # struct MEInput
