#
# MEOutput.jl - Input Database creation file
#

Base.@kwdef struct MEOutput <: HDF5GroupDatabase
  db::String=DB
  ########################
  #
  # Define Sets
  #
  Poll = ReadSetFromCSV("Poll","Key")
  Area = ReadSetFromCSV("Area","Key")
  Year = ReadSetFromCSV("Year","Key")
  tv = ReadSetFromCSV("tv","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  LU = ReadSetFromCSV("LU","Key")
  Offset = ReadSetFromCSV("Offset","Key")
  Level = ReadSetFromCSV("Level","Key")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
  DfPol = CreateVariableInHDF5(db, "MEOutput/DfPol", (:Poll, :Area, :Year),"Deforestation Emissions (Tonnes/Yr)","Tonnes/Yr")
  FlCH4Captured = CreateVariableInHDF5(db, "MEOutput/FlCH4Captured", (:ECC, :Area, :Year),"CH4 Captured from Flaring Reductions (Tonnes/Yr)","Tonnes/Yr")
  FuCap = CreateVariableInHDF5(db, "MEOutput/FuCap", (:ECC, :Area, :Year),"Other Fugitives Reduction Capacity (Tonnes/Yr)","Tonnes/Yr")
  FuCapPrior = CreateVariableInHDF5(db, "MEOutput/FuCapPrior", (:ECC, :Area, :Year),"Other Fugitives Reduction Capacity in Previous Year (Tonnes/Yr)","Tonnes/Yr")
  FuCC = CreateVariableInHDF5(db, "MEOutput/FuCC", (:ECC, :Area, :Year),"Other Fugitives Reduction Capital Cost (\$/Tonne)","\$/Tonne")
  FuCCEm = CreateVariableInHDF5(db, "MEOutput/FuCCEm", (:ECC, :Area, :Year),"Other Fugitives Reduction Embedded Capital Cost (\$/Tonne)","\$/Tonne")
  FuCCEmPrior = CreateVariableInHDF5(db, "MEOutput/FuCCEmPrior", (:ECC, :Area, :Year),"Other Fugitives Reduction Embedded Capital Cost in Previous Year  (\$/Tonne)","\$/Tonne")
  FuCH4Captured = CreateVariableInHDF5(db, "MEOutput/FuCH4Captured", (:ECC, :Area, :Year),"CH4 Captured from Other Fugitives Reductions (Tonnes/Yr)","Tonnes/Yr")
  FuCH4Flared = CreateVariableInHDF5(db, "MEOutput/FuCH4Flared", (:ECC, :Area, :Year),"CH4 Flared from Other Fugitives Reductions (Tonnes/Yr)","Tonnes/Yr")
  FuCH4FlPol = CreateVariableInHDF5(db, "MEOutput/FuCH4FlPol", (:ECC, :Poll, :Area, :Year),"Emissions from Flaring CH4 (Tonnes/Yr)","Tonnes/Yr")
  FuCR = CreateVariableInHDF5(db, "MEOutput/FuCR", (:ECC, :Area, :Year),"Other Fugitives Reduction Capacity Completion Rate (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  FuGExp = CreateVariableInHDF5(db, "MEOutput/FuGExp", (:ECC, :Area, :Year),"Other Fugitives Reduction Government Expenses (M\$/Yr)","M\$/Yr")
  FuPrice = CreateVariableInHDF5(db, "MEOutput/FuPrice", (:ECC, :Area, :Year),"Price for Other Fugitives Reduction Curve (\$/Tonne)","\$/Tonne")
  FuRP = CreateVariableInHDF5(db, "MEOutput/FuRP", (:ECC, :Poll, :Area, :Year),"Fraction of Other Fugitives Reduced (Tonnes/Tonnes)","Tonnes/Tonnes")
  LUArea = CreateVariableInHDF5(db, "MEOutput/LUArea", (:LU, :Area, :Year),"Land Use Area (Acres)","Acres")
  LUFr = CreateVariableInHDF5(db, "MEOutput/LUFr", (:LU, :Area, :Year),"Land Use Area Fraction (Acre/Acre)","Acre/Acre")
  LUPol = CreateVariableInHDF5(db, "MEOutput/LUPol", (:Poll, :Area, :Year),"Land Use Pollution (Tonnes)","Tonnes")
  LUPolLU = CreateVariableInHDF5(db, "MEOutput/LUPolLU", (:LU, :Poll, :Area, :Year),"Land Use Pollution (Tonnes)","Tonnes")
  MECC = CreateVariableInHDF5(db, "MEOutput/MECC", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Capital Cost (\$/Tonne)","\$/Tonne")
  MECCR = CreateVariableInHDF5(db, "MEOutput/MECCR", (:ECC, :Area, :Year),"Non Energy eCO2 Reduction Capital Charge Rate (\$/\$)","\$/\$")
  MEIRP = CreateVariableInHDF5(db, "MEOutput/MEIRP", (:ECC, :Poll, :Area, :Year),"Indicated Pollutant Reduction (Tonnes/Tonnes)","Tonnes/Tonnes")
  MEPOCA = CreateVariableInHDF5(db, "MEOutput/MEPOCA", (:ECC, :Poll, :Area, :Year),"Non-Energy Pollution Coefficient (Tonnes/\$B-output)","Tonnes/\$B-output")
  MEPOCM = CreateVariableInHDF5(db, "MEOutput/MEPOCM", (:ECC, :Poll, :Area, :Year),"Non-Energy Pollution Coefficient Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  MEPrice = CreateVariableInHDF5(db, "MEOutput/MEPrice", (:ECC, :Poll, :Area, :Year),"Process Emission Reduction Price (\$/Tonne)","\$/Tonne")
  MERCap = CreateVariableInHDF5(db, "MEOutput/MERCap", (:ECC, :Poll, :Area, :Year),"Reduction Capital (Tonnes/Yr)","Tonnes/Yr")
  MERCC = CreateVariableInHDF5(db, "MEOutput/MERCC", (:ECC, :Poll, :Area, :Year),"Reduction Capital Cost (\$/Tonne)","\$/Tonne")
  MERCCEm = CreateVariableInHDF5(db, "MEOutput/MERCCEm", (:ECC, :Poll, :Area, :Year),"Embedied Reduction Capital Cost (\$)","\$")
  MERCI = CreateVariableInHDF5(db, "MEOutput/MERCI", (:ECC, :Poll, :Area, :Year),"Reduction Capital Initiation (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  MERCR = CreateVariableInHDF5(db, "MEOutput/MERCR", (:ECC, :Poll, :Area, :Year),"Reduction Capital Completion Rate (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  MERICap = CreateVariableInHDF5(db, "MEOutput/MERICap", (:ECC, :Poll, :Area, :Year),"Indicated Reduction Capital (Tonnes/Yr)","Tonnes/Yr")
  MERM = CreateVariableInHDF5(db, "MEOutput/MERM", (:ECC, :Poll, :Area, :Year),"Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  MERP = CreateVariableInHDF5(db, "MEOutput/MERP", (:ECC, :Poll, :Area, :Year),"Pollutant Reduction (Tonnes/Tonnes)","Tonnes/Tonnes")
  MEVR = CreateVariableInHDF5(db, "MEOutput/MEVR", (:ECC, :Poll, :Area, :Year),"Voluntary Reduction Policy (Tonnes/Tonnes)","Tonnes/Tonnes")
  MWEPol = CreateVariableInHDF5(db, "MEOutput/MWEPol", (:Poll, :Area, :Year),"Embedded Solid Waste Pollution (Tonnes/Yr)","Tonnes/Yr")
  MWPolAdd = CreateVariableInHDF5(db, "MEOutput/MWPolAdd", (:Poll, :Area, :Year),"Solid Waste Pollution Additions (Tonnes/Yr)","Tonnes/Yr")
  ORMEPOCA = CreateVariableInHDF5(db, "MEOutput/ORMEPOCA", (:ECC, :Poll, :Area, :Year),"Non-Energy Off Road Pollution Coefficient (Tonnes/\$B-output)","Tonnes/\$B-output")
  ReCapacity = CreateVariableInHDF5(db, "MEOutput/ReCapacity", (:Offset, :Area, :Year),"Reduction Capacity (Tonnes/Yr)","Tonnes/Yr")
  ReCapacityInitiated = CreateVariableInHDF5(db, "MEOutput/ReCapacityInitiated", (:Offset, :Area, :Year),"Reductions Capacity Initiation Rate (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  ReCapacityCompleted = CreateVariableInHDF5(db, "MEOutput/ReCapacityCompleted", (:Offset, :Area, :Year),"Reduction Capacity Completion Rate (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  ReCapacityRetirements = CreateVariableInHDF5(db, "MEOutput/ReCapacityRetirements", (:Offset, :Area, :Year),"Reduction Capacity Retirements (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  ReCapacityUnderConstruction = CreateVariableInHDF5(db, "MEOutput/ReCapacityUnderConstruction", (:Offset, :Area, :Year),"Reduction Capacity Under Construction (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  ReCaptured = CreateVariableInHDF5(db, "MEOutput/ReCaptured", (:Offset, :Poll, :Area, :Year),"Reductions Captured (Tonnes/Yr)","Tonnes/Yr")
  ReCC = CreateVariableInHDF5(db, "MEOutput/ReCC", (:Offset, :Area, :Year),"Reduction Capital Cost (\$/Tonne)","\$/Tonne")
  ReCCEm = CreateVariableInHDF5(db, "MEOutput/ReCCEm", (:Offset, :Area, :Year),"Reduction Embedded Capital Cost (\$/Tonne)","\$/Tonne")
  ReCCR = CreateVariableInHDF5(db, "MEOutput/ReCCR", (:Offset, :Area, :Year),"Reduction Capital Charge Rate (\$/\$)","\$/\$")
  ReCDInput = CreateVariableInHDF5(db, "MEOutput/ReCDInput", (:Level, :Offset, :Area, :Year),"Input to Reduction Delay Level (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  ReCDLevel = CreateVariableInHDF5(db, "MEOutput/ReCDLevel", (:Level, :Offset, :Area, :Year),"Reduction Delay Level (Tonnes/Yr)","Tonnes/Yr")
  ReCDOutput = CreateVariableInHDF5(db, "MEOutput/ReCDOutput", (:Level, :Offset, :Area, :Year),"Output from Reduction Delay Level (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  ReGC = CreateVariableInHDF5(db, "MEOutput/ReGC", (:Offset, :Area, :Year),"Electric Generating Capacity (MW/Yr)","MW/Yr")
  ReGCCMOff = CreateVariableInHDF5(db, "MEOutput/ReGCCMOff", (:Offset, :Area, :Year),"Incremental Electric Generating Capacity from Reductions (MW)","MW")
  ReGExp = CreateVariableInHDF5(db, "MEOutput/ReGExp", (:Offset, :Area, :Year),"Government Expenses (M\$/Yr)","M\$/Yr")
  ReGProdOff = CreateVariableInHDF5(db, "MEOutput/ReGProdOff", (:Offset, :Area, :Year),"Natural Gas Produced from Reductions (TBtu/Yr)","TBtu/Yr")
  RePol = CreateVariableInHDF5(db, "MEOutput/RePol", (:Offset, :Area, :Year),"Pollution (Tonnes/Yr)","Tonnes/Yr")
  ReReductions = CreateVariableInHDF5(db, "MEOutput/ReReductions", (:Offset, :Poll, :Area, :Year),"Reductions (Tonnes/Yr)","Tonnes/Yr")
  ReInv = CreateVariableInHDF5(db, "MEOutput/ReInv", (:Offset, :Area, :Year),"Reduction Investments (M\$/Yr)","M\$/Yr")
  ReOMExp = CreateVariableInHDF5(db, "MEOutput/ReOMExp", (:Offset, :Area, :Year),"Reduction O&M Expenses(M\$/Yr)","M\$/Yr")
  RePExp = CreateVariableInHDF5(db, "MEOutput/RePExp", (:Offset, :Area, :Year),"Private Expenses (M\$/Yr)","M\$/Yr")
  RePrice = CreateVariableInHDF5(db, "MEOutput/RePrice", (:Offset, :Area, :Year),"Emission Prices (\$/Tonne)","\$/Tonne")
  ReReductionsIndicated = CreateVariableInHDF5(db, "MEOutput/ReReductionsIndicated", (:Offset, :Area, :Year),"Reductions Indicated (Tonnes/Yr)","Tonnes/Yr")
  ReRP = CreateVariableInHDF5(db, "MEOutput/ReRP", (:Offset, :Area, :Year),"Reduction (Tonnes/Tonnes)","Tonnes/Tonnes")
  SAPol = CreateVariableInHDF5(db, "MEOutput/SAPol", (:Poll, :Area, :Year),"Agriculture Sinks Emissions (Tonnes/Yr)","Tonnes/Yr")
  SFPol = CreateVariableInHDF5(db, "MEOutput/SFPol", (:Poll, :Area, :Year),"Forest Sinks Emissions (Tonnes/Yr)","Tonnes/Yr")
  SqCap = CreateVariableInHDF5(db, "MEOutput/SqCap", (:ECC, :Area, :Year),"Sequestering Capacity (Tonnes/Yr)","Tonnes/Yr")
  SqCapCI = CreateVariableInHDF5(db, "MEOutput/SqCapCI", (:ECC, :Area, :Year),"Sequestering Capacity Construction Initiation (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  SqCapCR = CreateVariableInHDF5(db, "MEOutput/SqCapCR", (:ECC, :Area, :Year),"Sequestering Capacity Completion Rate (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  SqCapRR = CreateVariableInHDF5(db, "MEOutput/SqCapRR", (:ECC, :Area, :Year),"Sequestering Capacity Retirement Rate (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  SqCC = CreateVariableInHDF5(db, "MEOutput/SqCC", (:ECC, :Area, :Year),"Sequestering eCO2 Reduction Capital Cost (\$/Tonne)","\$/Tonne")
  SqCCEm = CreateVariableInHDF5(db, "MEOutput/SqCCEm", (:ECC, :Area, :Year),"Sequestering eCO2 Reduction Embedded Capital Cost (\$/Tonne)","\$/Tonne")
  SqCCLevelized = CreateVariableInHDF5(db, "MEOutput/SqCCLevelized", (:ECC, :Area, :Year),"Sequestering Levelized Cost for Cost Curve (2016 CN\$/tonne CO2e)","2016 CN\$/tonne CO2e")
  SqCCR = CreateVariableInHDF5(db, "MEOutput/SqCCR", (:Area, :Year),"Sequestering eCO2 Reduction Capital Charge Rate (\$/\$)","\$/\$")
  SqCCRMult = CreateVariableInHDF5(db, "MEOutput/SqCCRMult", (:Area, :Year),"Sequestering eCO2 Reduction Capital Charge Rate Multiplier (\$/\$)","\$/\$")
  SqCDInput = CreateVariableInHDF5(db, "MEOutput/SqCDInput", (:Level, :ECC, :Area, :Year),"Input to Sequestering Delay Level (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  SqCDLevel = CreateVariableInHDF5(db, "MEOutput/SqCDLevel", (:Level, :ECC, :Area, :Year),"Sequestering Delay Level (Tonnes/Yr)","Tonnes/Yr")
  SqCDOutput = CreateVariableInHDF5(db, "MEOutput/SqCDOutput", (:Level, :ECC, :Area, :Year),"Output from Sequestering Delay Level (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  SqGExp = CreateVariableInHDF5(db, "MEOutput/SqGExp", (:ECC, :Area, :Year),"Sequestering Government Expenses (M\$/Yr)","M\$/Yr")
  SqIPol = CreateVariableInHDF5(db, "MEOutput/SqIPol", (:ECC, :Poll, :Area, :Year),"CCS Indicated for Construction (Tonnes/Yr)","Tonnes/Yr")
  SqIPolCC = CreateVariableInHDF5(db, "MEOutput/SqIPolCC", (:ECC, :Poll, :Area, :Year),"CCS Indicated from Cost Curves (Tonnes/Yr)","Tonnes/Yr")
  SqPrice = CreateVariableInHDF5(db, "MEOutput/SqPrice", (:ECC, :Area, :Year),"Sequestering Cost Curve Price (\$/tonne CO2e)","\$/tonne CO2e")
  SqReduction = CreateVariableInHDF5(db, "MEOutput/SqReduction", (:ECC, :Poll, :Area, :Year),"Sequestering Fraction Captured Marginal(tonne/tonne)","tonne/tonne")
  SqReductionEm = CreateVariableInHDF5(db, "MEOutput/SqReductionEm", (:ECC, :Poll, :Area, :Year),"Sequestering Fraction Captured Embedded (tonne/tonne)","tonne/tonne")
  SqTSCost = CreateVariableInHDF5(db, "MEOutput/SqTSCost", (:Area, :Year),"Sequestering Transportation and Storage Costs (2016 CN\$/tonne CO2e)","2016 CN\$/tonne CO2e")
  VnCap = CreateVariableInHDF5(db, "MEOutput/VnCap", (:ECC, :Area, :Year),"Venting Reduction Capacity (Tonnes/Yr)","Tonnes/Yr")
  VnCapPrior = CreateVariableInHDF5(db, "MEOutput/VnCapPrior", (:ECC, :Area, :Year),"Venting Reduction Capacity in Previous Year (Tonnes/Yr)","Tonnes/Yr")
  VnCC = CreateVariableInHDF5(db, "MEOutput/VnCC", (:ECC, :Area, :Year),"Venting Reduction Capital Cost (\$/Tonne)","\$/Tonne")
  VnCCEm = CreateVariableInHDF5(db, "MEOutput/VnCCEm", (:ECC, :Area, :Year),"Venting Reduction Embedded Capital Cost (\$/Tonne)","\$/Tonne")
  VnCCEmPrior = CreateVariableInHDF5(db, "MEOutput/VnCCEmPrior", (:ECC, :Area, :Year),"Venting Reduction Embedded Capital Cost in Previous Year  (\$/Tonne)","\$/Tonne")
  VnCH4Captured = CreateVariableInHDF5(db, "MEOutput/VnCH4Captured", (:ECC, :Area, :Year),"CH4 Captured from Venting Reductions (Tonnes/Yr)","Tonnes/Yr")
  VnCH4Flared = CreateVariableInHDF5(db, "MEOutput/VnCH4Flared", (:ECC, :Area, :Year),"CH4 Flared from Venting Reductions (Tonnes/Yr)","Tonnes/Yr")
  VnCH4FlPol = CreateVariableInHDF5(db, "MEOutput/VnCH4FlPol", (:ECC, :Poll, :Area, :Year),"Emissions from Flaring CH4 (Tonnes/Yr)","Tonnes/Yr")
  VnCR = CreateVariableInHDF5(db, "MEOutput/VnCR", (:ECC, :Area, :Year),"Venting Reduction Capacity Completion Rate (Tonnes/Yr/Yr)","Tonnes/Yr/Yr")
  VnGExp = CreateVariableInHDF5(db, "MEOutput/VnGExp", (:ECC, :Area, :Year),"Venting Reduction Government Expenses (M\$/Yr)","M\$/Yr")
  VnPrice = CreateVariableInHDF5(db, "MEOutput/VnPrice", (:ECC, :Area, :Year),"Price for Venting Reduction Curve (\$/Tonne)","\$/Tonne")
  VnRP = CreateVariableInHDF5(db, "MEOutput/VnRP", (:ECC, :Poll, :Area, :Year),"Fraction of Venting Reduced (Tonnes/Tonnes)","Tonnes/Tonnes")
end # struct MEOutput
