#
# MInput.jl - Input Database creation file
#

Base.@kwdef struct MInput <: HDF5GroupDatabase
  db::String=DB
  ########################
  #
  # Define Sets
  #
  Waste = ReadSetFromCSV("Waste","Key")
  Area = ReadSetFromCSV("Area","Key")
  Year = ReadSetFromCSV("Year","Key")
  tv = ReadSetFromCSV("tv","Key")
  Nation = ReadSetFromCSV("Nation","Key")
  CNArea = ReadSetFromCSV("CNArea","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  Age = ReadSetFromCSV("Age","Key")
  PI = ReadSetFromCSV("PIMacro","Key")
  GNode = ReadSetFromCSV("GNode","Key")
  Node = ReadSetFromCSV("Node","Key")
  OGUnit = ReadSetFromCSV("OGUnit","Key")
  RfUnit = ReadSetFromCSV("RfUnit","Key")
  Unit = ReadSetFromCSV("Unit","Key")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
  CH4CorrectionFactor = CreateVariableInHDF5(db, "MInput/CH4CorrectionFactor", (:Waste, :Area, :Year),"CH4 Correction Factor <MCF> for Aerobic Decomposition (1/1)","1/1")
  CH4FlaringFraction = CreateVariableInHDF5(db, "MInput/CH4FlaringFraction", (:Waste, :Area, :Year),"CH4 Flaring Fraction (Tonnes/Tonnes)","Tonnes/Tonnes")
  CH4GenerationRate = CreateVariableInHDF5(db, "MInput/CH4GenerationRate", (:Waste, :Area, :Year),"CH4 Generation Constant <k>","NoUnit")
  CH4MolarRatio = CreateVariableInHDF5(db, "MInput/CH4MolarRatio", (:tv,),"Molar Ratio CH4/C (1/1)","1/1")
  CH4RecoveryFraction = CreateVariableInHDF5(db, "MInput/CH4RecoveryFraction", (:Waste, :Area, :Year),"CH4 Recovery Fraction (Tonnes/Tonnes)","Tonnes/Tonnes")
  CH4Volume = CreateVariableInHDF5(db, "MInput/CH4Volume", (:Waste,),"Fraction of CH4 by Volume in Landfill Gas <F> (1/1)","1/1")
  CPIndex = CreateVariableInHDF5(db, "MInput/CPIndex", (:Area, :Year),"Consumer Price Index By Area (1992=100)","1992=100")
  CPIndexNation = CreateVariableInHDF5(db, "MInput/CPIndexNation", (:Nation, :Year),"Consumer Price Index By Nation (1992=100)","1992=100")
  CNAMap = CreateVariableInHDF5(db, "MInput/CNAMap", (:Area, :CNArea),"Map between Area and Canada Areas (CNArea)","CNArea")
  DisposedSwitch = CreateVariableInHDF5(db, "MInput/DisposedSwitch", (:Waste, :Area, :Year),"Disposed Waste Policy Switch (1=Active)","1=Active")
  DisposedWastePerDriver = CreateVariableInHDF5(db, "MInput/DisposedWastePerDriver", (:Waste, :Area, :Year),"Disposed Waste per Driver <DsWC> (Tonnes/person)","Tonnes/person")
  DivertedPolicyFraction = CreateVariableInHDF5(db, "MInput/DivertedPolicyFraction", (:Waste, :Area, :Year),"Fraction of Disposed Waste Policy which is Diverted (Tonne/Tonne)","Tonne/Tonne")
  DOCDecomposeFraction = CreateVariableInHDF5(db, "MInput/DOCDecomposeFraction", (:Waste, :Area, :Year),"Fraction of Decomposable DOC <DOCf> (Tonnes/Tonnes)","Tonnes/Tonnes")
  DOCPerWaste = CreateVariableInHDF5(db, "MInput/DOCPerWaste", (:Waste, :Area, :Year),"Fraction of Degradable Organic Carbon per Waste Landfilled (Tonnes/Tonnes)","Tonnes/Tonnes")
  DriverBaseline = CreateVariableInHDF5(db, "MInput/DriverBaseline", (:ECC, :Area, :Year),"Emissions Baseline Economic Driver (Various Units/Yr)","Various Units/Yr")
  DriverMultiplier = CreateVariableInHDF5(db, "MInput/DriverMultiplier", (:ECC, :Area, :Year),"Economic Driver (Driver/Driver)","Driver/Driver")
  DrSwitch = CreateVariableInHDF5(db, "MInput/DrSwitch", (:ECC, :Area, :Year),"Economic Driver Switch","NoUnit")
  DWFR = CreateVariableInHDF5(db, "MInput/DWFR", (:ECC, :Area, :Year),"Fraction of Homes by Dwelling Type (Home/Home)","Home/Home")
  FlaringEfficiency = CreateVariableInHDF5(db, "MInput/FlaringEfficiency", (:Waste, :Area, :Year),"Emissions Efficiency of Flaring (Tonnes/Tonnes)","Tonnes/Tonnes")
  FSFraction = CreateVariableInHDF5(db, "MInput/FSFraction", (:ECC, :Year),"Fraction to Split Economic Model Floorspace into ENERGY 2100 Sectors (Sq Ft/Sq Ft)","Sq Ft/Sq Ft")
  FSUnit = CreateVariableInHDF5(db, "MInput/FSUnit", (:ECC, :Area, :Year),"Floorspace per Unit (Sq Units/Building)","Sq Units/Building")
  GDPDeflTOM = CreateVariableInHDF5(db, "MInput/GDPDeflTOM", (:Nation, :Year),"Implicit Price Deflator: GDP at Market Prices (Index 2012=100)","Index 2012=100")
  GDPSector = CreateVariableInHDF5(db, "MInput/GDPSector", (:ECC, :Area, :Year),"GDP By Sector (Real Million \$/Yr)","Real Million \$/Yr")
  GDPSectorTOM = CreateVariableInHDF5(db, "MInput/GDPSectorTOM", (:ECC, :Area, :Year),"Gross Value Added from TOM (Real Million \$/Yr)","Real Million \$/Yr")
  GOMAT = CreateVariableInHDF5(db, "MInput/GOMAT", (:ECC, :Area, :Year),"Adjustment Time for Gross Output Multiplier (Years)","Years")
  GRPAdj = CreateVariableInHDF5(db, "MInput/GRPAdj", (:Area, :Year),"Gross Regional Product Adjustment (Fraction)","Fraction")
  HHSFr = CreateVariableInHDF5(db, "MInput/HHSFr", (:ECC, :Area, :Year),"Household Fraction (Fraction)","Fraction")
  INST = CreateVariableInHDF5(db, "MInput/INST", (:tv,),"Inflation Rate Smooth Time (Years)","NoUnit")
  IPPRatio = CreateVariableInHDF5(db, "MInput/IPPRatio", (:ECC, :Area, :Year),"IPP ratio","NoUnit")
  LaborForce = CreateVariableInHDF5(db, "MInput/LaborForce", (:Nation, :Year),"Total Labor Force, Age 15+ (000s)","000s")
  MacroSwitch::SetArray = Nation
  MapOther = CreateVariableInHDF5(db, "MInput/MapOther", (:ECC, :Area),"Map for Economic Sectors to sum as Other (1=Include)","1=Include")
  MoneyUnitDS::SetArray = Area
  MPC = CreateVariableInHDF5(db, "MInput/MPC", (:tv,),"Production Capacity of a Mature Industry (M\$/Yr)","NoUnit")
  NGasFr = CreateVariableInHDF5(db, "MInput/NGasFr", (:ECC, :Area, :Year),"Fraction of National Natural Gas Driver allocated to each Area (Btu/Btu)","Btu/Btu")
  OxidationFactor = CreateVariableInHDF5(db, "MInput/OxidationFactor", (:Waste, :Area, :Year),"Oxidation Factor <OX> (1/1)","1/1")
  PCgRF = CreateVariableInHDF5(db, "MInput/PCgRF", (:Age, :ECC, :Area),"Fraction of Energy Requirement by Age (Fraction)","Fraction")
  PCLVI = CreateVariableInHDF5(db, "MInput/PCLVI", (:Age, :ECC, :Area),"Initial Production Capacity (\$/Yr)","\$/Yr")
  PCMGR = CreateVariableInHDF5(db, "MInput/PCMGR", (:ECC,),"Maximum Growth Rate of Production Capacity (\$/Yr)","\$/Yr")
  PCPL = CreateVariableInHDF5(db, "MInput/PCPL", (:ECC, :Area, :Year),"Physical Life of Production Capacity (Years)","Years")
  PIDS = ReadSetFromCSV("PIMacro","DS")
  PIKey = ReadSetFromCSV("PIMacro","Key")
  ProportionDivertedWaste = CreateVariableInHDF5(db, "MInput/ProportionDivertedWaste", (:Waste, :Area, :Year),"Proportion of Diverted Waste <PDvW> (Tonnes/Tonnes)","Tonnes/Tonnes")
  RealDispInc = CreateVariableInHDF5(db, "MInput/RealDispInc", (:Area, :Year),"Real Disposable Income (Million Real CN\$)","Million Real CN\$")
  RPIFR = CreateVariableInHDF5(db, "MInput/RPIFR", (:ECC, :Area, :Year),"Personal Income Split Between Res. Categories (\$/\$)","\$/\$")
  StockAdjustment = CreateVariableInHDF5(db, "MInput/StockAdjustment", (:ECC, :Area, :Year),"Exogenous Driverl Stock Adjustment (\$/\$)","\$/\$")
  VehiclesPerPerson = CreateVariableInHDF5(db, "MInput/VehiclesPerPerson", (:Area, :Year),"Average Vehicle Stock Per Person (Vehicles Per Population)","Vehicles Per Population")
  WasteExportedFraction = CreateVariableInHDF5(db, "MInput/WasteExportedFraction", (:Waste, :Area, :Year),"Fraction of Waste Exported (Tonnes/Tonnes)","Tonnes/Tonnes")
  WasteIncineratedFraction = CreateVariableInHDF5(db, "MInput/WasteIncineratedFraction", (:Waste, :Area, :Year),"Fraction of Waste Incinerated (Tonnes/Tonnes)","Tonnes/Tonnes")
  WastePerDriver = CreateVariableInHDF5(db, "MInput/WastePerDriver", (:Waste, :Area, :Year),"Waste Generated per Driver <WGC> (Tonnes/person)","Tonnes/person")
  WasteSwitch = CreateVariableInHDF5(db, "MInput/WasteSwitch", (:Year,),"Waste Switch (1=Use Waste Sector)","1=Use Waste Sector")
  xCH4Emitted = CreateVariableInHDF5(db, "MInput/xCH4Emitted", (:Waste, :Area, :Year),"Exogenous CH4 Generated After Recovery <Qt>  (Tonnes/Yr)","Tonnes/Yr")
  xCPITOM = CreateVariableInHDF5(db, "MInput/xCPITOM", (:Area, :Year),"Consumer Price Index By Area (2002=100)","2002=100")
  xCPINationTOM = CreateVariableInHDF5(db, "MInput/xCPINationTOM", (:Nation, :Year),"Consumer Price Index By Nation (2002=100)","2002=100")
  xDOCStock = CreateVariableInHDF5(db, "MInput/xDOCStock", (:Waste, :Area, :Year),"Initial Landfill Stock of Decomposable DOC <DDOCma> (Tonnes)","Tonnes")
  xDriver = CreateVariableInHDF5(db, "MInput/xDriver", (:ECC, :Area, :Year),"Economic Driver (Various Units)","Various Units")
  xECUF = CreateVariableInHDF5(db, "MInput/xECUF", (:ECC, :Area, :Year),"Driverl Utilization Fraction (Fraction)","Fraction")
  xEmp = CreateVariableInHDF5(db, "MInput/xEmp", (:ECC, :Area, :Year),"Employment (Thousands)","Thousands")
  xExchangeRate = CreateVariableInHDF5(db, "MInput/xExchangeRate", (:Area, :Year),"Local Currency/US\$ Exchange Rate (Local\$/US\$)","Local\$/US\$")
  xExchangeRateGNode = CreateVariableInHDF5(db, "MInput/xExchangeRateGNode", (:GNode, :Year),"Local Currency/US\$ Exchange Rate (Local\$/US\$)","Local\$/US\$")
  xExchangeRateNation = CreateVariableInHDF5(db, "MInput/xExchangeRateNation", (:Nation, :Year),"Local Currency/US\$ Exchange Rate (Local\$/US\$)","Local\$/US\$")
  xExchangeRateNode = CreateVariableInHDF5(db, "MInput/xExchangeRateNode", (:Node, :Year),"Local Currency/US\$ Exchange Rate (Local\$/US\$)","Local\$/US\$")
  xExchangeRateOGUnit = CreateVariableInHDF5(db, "MInput/xExchangeRateOGUnit", (:OGUnit, :Year),"Local Currency/US\$ Exchange Rate (Local\$/US\$)","Local\$/US\$")
  xExchangeRateRfUnit = CreateVariableInHDF5(db, "MInput/xExchangeRateRfUnit", (:RfUnit, :Year),"Refinery Exchange Rate(\$/\$)","\$/\$")
  xExchangeRateUnit = CreateVariableInHDF5(db, "MInput/xExchangeRateUnit", (:Unit, :Year),"Local Currency/US\$ Exchange Rate (Local\$/US\$","")
  xFloorspaceAEO = CreateVariableInHDF5(db, "MInput/xFloorspaceAEO", (:ECC, :Area, :Year),"Floorspace from AEO (Million Sq Ft)","Million Sq Ft")
  xFloorspaceTOM = CreateVariableInHDF5(db, "MInput/xFloorspaceTOM", (:ECC, :Area, :Year),"Floorspace from TOM (Million Sq Ft)","Million Sq Ft")
  xGDPChained = CreateVariableInHDF5(db, "MInput/xGDPChained", (:Nation, :Year),"Chained National GDP(Chained 2017 Million \$/Yr)","Chained 2017 Million \$/Yr")
  xGO = CreateVariableInHDF5(db, "MInput/xGO", (:ECC, :Area, :Year),"Gross Output (1985 M\$/Yr)","1985 M\$/Yr")
  xGOAEO = CreateVariableInHDF5(db, "MInput/xGOAEO", (:ECC, :Area, :Year),"Gross Output from AEO (Real M\$/Yr)","Real M\$/Yr")
  xGOTOM = CreateVariableInHDF5(db, "MInput/xGOTOM", (:ECC, :Area, :Year),"Gross Output from TOM (Real M\$/Yr)","Real M\$/Yr")
  xGRP = CreateVariableInHDF5(db, "MInput/xGRP", (:Area, :Year),"Gross Regional Product (Real M\$/Yr)","Real M\$/Yr")
  xGRPAEO = CreateVariableInHDF5(db, "MInput/xGRPAEO", (:Area, :Year),"Gross Regional Product (Real M\$/Yr)","Real M\$/Yr")
  xGRPTOM = CreateVariableInHDF5(db, "MInput/xGRPTOM", (:Area, :Year),"Gross Regional Product (Real M\$/Yr)","Real M\$/Yr")
  xHHS = CreateVariableInHDF5(db, "MInput/xHHS", (:ECC, :Area, :Year),"Households (Number)","Number")
  xHHSAEO = CreateVariableInHDF5(db, "MInput/xHHSAEO", (:ECC, :Area, :Year),"Households from AEO (Number)","Number")
  xHHSTOM = CreateVariableInHDF5(db, "MInput/xHHSTOM", (:ECC, :Area, :Year),"Households from TOM (Number)","Number")
  xHSize = CreateVariableInHDF5(db, "MInput/xHSize", (:ECC, :Area, :Year),"Average Household Size (People/Household)","People/Household")
  xInflation = CreateVariableInHDF5(db, "MInput/xInflation", (:Area, :Year),"Inflation Index (\$/\$)","\$/\$")
  xInflationGNode = CreateVariableInHDF5(db, "MInput/xInflationGNode", (:GNode, :Year),"Inflation Index (\$/\$)","\$/\$")
  xInflationNation = CreateVariableInHDF5(db, "MInput/xInflationNation", (:Nation, :Year),"Inflation Index (\$/\$)","\$/\$")
  xInflationNode = CreateVariableInHDF5(db, "MInput/xInflationNode", (:Node, :Year),"Inflation Index (\$/\$)","\$/\$")
  xInflationOGUnit = CreateVariableInHDF5(db, "MInput/xInflationOGUnit", (:OGUnit, :Year),"Inflation Index (\$/\$)","\$/\$")
  xInflationRfUnit = CreateVariableInHDF5(db, "MInput/xInflationRfUnit", (:RfUnit, :Year),"Inflation Index (\$/\$)","\$/\$")
  xInflationUnit = CreateVariableInHDF5(db, "MInput/xInflationUnit", (:Unit, :Year),"Inflation Index (\$/\$)","\$/\$")
  xInflationRate = CreateVariableInHDF5(db, "MInput/xInflationRate", (:Area, :Year),"Inflation Rate (1/Yr)","1/Yr")
  xInflationRateNation = CreateVariableInHDF5(db, "MInput/xInflationRateNation", (:Nation, :Year),"Inflation Rate (1/Yr)","1/Yr")
  xInSm = CreateVariableInHDF5(db, "MInput/xInSm", (:Area, :Year),"Smoothed Inflation Rate (1/Yr)","1/Yr")
  xPC = CreateVariableInHDF5(db, "MInput/xPC", (:ECC, :Area, :Year),"Production Capacity (Real M\$)","Real M\$")
  xPop = CreateVariableInHDF5(db, "MInput/xPop", (:ECC, :Area, :Year),"Population (Millions)","Millions")
  xPopAEO = CreateVariableInHDF5(db, "MInput/xPopAEO", (:ECC, :Area, :Year),"Population from AEO (Millions)","Millions")
  xPopTOM = CreateVariableInHDF5(db, "MInput/xPopTOM", (:ECC, :Area, :Year),"Population from TOM (Millions)","Millions")
  xPopT = CreateVariableInHDF5(db, "MInput/xPopT", (:Area, :Year),"Population (Millions)","Millions")
  xPopTAEO = CreateVariableInHDF5(db, "MInput/xPopTAEO", (:Area, :Year),"Population from AEO (Millions)","Millions")
  xPopTTOM = CreateVariableInHDF5(db, "MInput/xPopTTOM", (:Area, :Year),"Population from TOM (Millions)","Millions")
  xProcSw = CreateVariableInHDF5(db, "MInput/xProcSw", (:PI, :Year),"Procedure on/off Switch","2,0")
  xRPI = CreateVariableInHDF5(db, "MInput/xRPI", (:Area, :Year),"Personal Income (Real M\$/Yr)","Real M\$/Yr")
  xRPIAEO = CreateVariableInHDF5(db, "MInput/xRPIAEO", (:Area, :Year),"Personal Income from AEO (Real M\$/Yr)","Real M\$/Yr")
  xRPITOM = CreateVariableInHDF5(db, "MInput/xRPITOM", (:Area, :Year),"Personal Income from TOM (Real M\$/Yr)","Real M\$/Yr")
  xSuProd = CreateVariableInHDF5(db, "MInput/xSuProd", (:Area, :Year),"Sugar Production (Thou. \$)","Thou. \$")
  xTHHS = CreateVariableInHDF5(db, "MInput/xTHHS", (:Area, :Year),"Total Households (Households)","Households")
  YUPC = CreateVariableInHDF5(db, "MInput/YUPC", (:tv,),"Upper Error Limit for PC (PERCENT)","NoUnit")
end # struct MInput
