#
# TInput.jl - Input Database creation file
#

Base.@kwdef struct TInput <: HDF5GroupDatabase
  db::String=DB
  ########################
  #
  # Define Sets
  #
  CTech = ReadSetFromCSV("CTechTrans","Key")
  tv = ReadSetFromCSV("tv","Key")
  EC = ReadSetFromCSV("ECTrans","Key")
  Enduse = ReadSetFromCSV("EnduseTrans","Key")
  PI = ReadSetFromCSV("PITrans","Key")
  Tech = ReadSetFromCSV("TechTrans","Key")
  Vintage = ReadSetFromCSV("VintageTrans","Key")
  Area = ReadSetFromCSV("Area","Key")
  Year = ReadSetFromCSV("Year","Key")
  Fuel = ReadSetFromCSV("Fuel","Key")
  Plant = ReadSetFromCSV("Plant","Key")
  Node = ReadSetFromCSV("Node","Key")
  FuelEP = ReadSetFromCSV("FuelEP","Key")
  Poll = ReadSetFromCSV("Poll","Key")
  PollX = ReadSetFromCSV("PollX","Key")
  Month = ReadSetFromCSV("Month","Key")
  ECC = ReadSetFromCSV("ECC","Key")
  ES = ReadSetFromCSV("ES","Key")
  PCov = ReadSetFromCSV("PCov","Key")
  Hour = ReadSetFromCSV("Hour","Key")
  Day = ReadSetFromCSV("Day","Key")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
  CTechDS = ReadSetFromCSV("CTechTrans","DS")
  CTechKey = ReadSetFromCSV("CTechTrans","Key")
  ECDS = ReadSetFromCSV("ECTrans","DS")
  ECKey = ReadSetFromCSV("ECTrans","Key")
  EnduseDS = ReadSetFromCSV("EnduseTrans","DS")
  EnduseKey = ReadSetFromCSV("EnduseTrans","Key")
  PIDS = ReadSetFromCSV("PITrans","DS")
  PIKey = ReadSetFromCSV("PITrans","Key")
  TechDS = ReadSetFromCSV("TechTrans","DS")
  TechKey = ReadSetFromCSV("TechTrans","Key")
  VintageDS = ReadSetFromCSV("VintageTrans","DS")
  VintageKey = ReadSetFromCSV("VintageTrans","Key")
  BAT = CreateVariableInHDF5(db, "TInput/BAT", (:tv,),"Short Term Utilization Adjustment Time (Yr)","Yr")
  BCMultTr = CreateVariableInHDF5(db, "TInput/BCMultTr", (:Fuel, :Tech, :EC, :Area, :Year),"Multipler between Black Carbon and PM 2.5 (Tonnes/Tonnes)","Tonnes/Tonnes")
  BE = CreateVariableInHDF5(db, "TInput/BE", (:tv,),"Budget Elasticity Factor (\$/\$)","\$/\$")
  BMM = CreateVariableInHDF5(db, "TInput/BMM", (:Enduse, :Tech, :EC, :Area, :Year),"Budget Multiplier Adjustment (Btu/Btu)","Btu/Btu")
  CalibTime = CreateVariableInHDF5(db, "TInput/CalibTime", (:EC, :Area),"Last Year of Calibration (Year)","Year")
  CFraction = CreateVariableInHDF5(db, "TInput/CFraction", (:Enduse, :Tech, :EC, :Area, :Year),"Fraction of Production Capacity open to Conversion (\$/\$)","\$/\$")
  CgAT = CreateVariableInHDF5(db, "TInput/CgAT", (:Tech, :EC, :Area, :Year),"Cogeneration Implementation Time (Years)","Years")
  CgBL = CreateVariableInHDF5(db, "TInput/CgBL", (:Tech, :EC, :Area),"Cogeneration Equipment Book Value Lifetime (Years)","Years")
  CgCC = CreateVariableInHDF5(db, "TInput/CgCC", (:Tech, :EC, :Area, :Year),"Cogeneration Capital Cost (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  CgCUFP = CreateVariableInHDF5(db, "TInput/CgCUFP", (:Tech, :EC, :Area),"Cogeneration Capacity Utilization Factor used for Planning (Btu/Btu)","Btu/Btu")
  CgDC = CreateVariableInHDF5(db, "TInput/CgDC", (:Tech, :Area),"Cogeneration Delivery Charge (\$/mmBtu)","\$/mmBtu")
  CgDmSw = CreateVariableInHDF5(db, "TInput/CgDmSw", (:Tech,),"Cogeneration Depletion Multiplier Switch (1=Active) (Switch)","1=Active")
  CgElectricFraction = CreateVariableInHDF5(db, "TInput/CgElectricFraction", (:Plant, :EC, :Area, :Year),"Cogeneration Electric Tech to Plant Fraction (MW/MW)","MW/MW")
  CgHRtM = CreateVariableInHDF5(db, "TInput/CgHRtM", (:Tech, :EC, :Area, :Year),"Marginal Cogeneration Heat Rate (Btu/KWh)","Btu/KWh")
  CgIVTC = CreateVariableInHDF5(db, "TInput/CgIVTC", (:Year,),"Cogeneration Investment Tax Credit (\$/\$)","\$/\$")
  CgLoad = CreateVariableInHDF5(db, "TInput/CgLoad", (:Tech,),"Cogeneration Demand Load to ECD (0=No, 1=Yes)","0=No, 1=Yes")
  CgMSMM = CreateVariableInHDF5(db, "TInput/CgMSMM", (:Tech, :EC, :Area, :Year),"Cogeneration Market Share Mult. Policy (\$/\$)","\$/\$")
  CgNodeFraction = CreateVariableInHDF5(db, "TInput/CgNodeFraction", (:EC, :Node, :Area, :Year),"Cogeneration EC and Area to Node Fraction (MW/MW)","MW/MW")
  CgOF = CreateVariableInHDF5(db, "TInput/CgOF", (:Tech, :EC, :Area),"Cogeneration Operation Cost Fraction (\$/Yr/\$)","\$/Yr/\$")
  CgOUREG = CreateVariableInHDF5(db, "TInput/CgOUREG", (:Tech, :EC, :Area, :Year),"Cogeneration Own Use Rate for Generation (GWh/GWh)","GWh/GWh")
  CgPL = CreateVariableInHDF5(db, "TInput/CgPL", (:Tech, :EC, :Area),"Cogeneration Equipment Lifetime (Years)","Years")
  CgPlantFraction = CreateVariableInHDF5(db, "TInput/CgPlantFraction", (:Tech, :Plant, :Year),"Cogeneration Tech to Plant Fraction (MW/MW)","MW/MW")
  CgPOCX = CreateVariableInHDF5(db, "TInput/CgPOCX", (:FuelEP, :EC, :Poll, :Area, :Year),"Cogeneration Pollution Coeff. (Tonnes/TBtu)","Tonnes/TBtu")
  CgPotMult = CreateVariableInHDF5(db, "TInput/CgPotMult", (:Tech, :EC, :Area, :Year),"Cogeneration Potential Multiplier (Btu/Btu)","Btu/Btu")
  CgPotSw = CreateVariableInHDF5(db, "TInput/CgPotSw", (:Tech, :EC, :Area),"Cogeneration Potential Switch (0=Steam, 1=Electric)","0=Steam, 1=Electric")
  CgResI = CreateVariableInHDF5(db, "TInput/CgResI", (:Tech, :Area),"Cogeneration Resource Base (mmBtu)","mmBtu")
  CgRisk = CreateVariableInHDF5(db, "TInput/CgRisk", (:Tech,),"Cogeneration Risk Premium (\$/\$)","\$/\$")
  CgSCM = CreateVariableInHDF5(db, "TInput/CgSCM", (:Tech,),"Cogeneration Shared Cost Mult. (\$/\$)","\$/\$")
  CgSqFr = CreateVariableInHDF5(db, "TInput/CgSqFr", (:FuelEP, :EC, :Poll, :Area, :Year),"Cogeneration Sequestered Pollution Fraction (Tonne/Tonne)","Tonne/Tonne")
  CgTL = CreateVariableInHDF5(db, "TInput/CgTL", (:Tech, :EC, :Area),"Cogeneration Tax Life (Years)","Years")
  CgVCSw = CreateVariableInHDF5(db, "TInput/CgVCSw", (:Tech,),"Cogeneration Switch for Incorporating Fuel Costs in Variable Costs (1=Include) (Switch)","1=Include")
  CHRM = CreateVariableInHDF5(db, "TInput/CHRM", (:EC, :Area, :Year),"Cooling to Heating Ratio Multiplier","NoUnit")
  CM = CreateVariableInHDF5(db, "TInput/CM", (:Tech, :Poll, :PollX),"Cross-over Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  CnvrtEU = CreateVariableInHDF5(db, "TInput/CnvrtEU", (:Enduse, :EC, :Area, :Year),"Conversion Switch","NoUnit")
  CROIN = CreateVariableInHDF5(db, "TInput/CROIN", (:Enduse, :Tech, :EC, :Area, :Year),"Conservation Return on Investment (\$/Yr/\$)","\$/Yr/\$")
  CurTime = CreateVariableInHDF5(db, "TInput/CurTime", (:tv,),"Year for capital costs (Time)","Time")
  DAct = CreateVariableInHDF5(db, "TInput/DAct", (:Enduse, :Tech, :EC, :Area, :Year),"Device Activity Level (Ton-Miles/Vehicle-Mile)","Ton-Miles/Vehicle-Mile")
  DCCA0 = CreateVariableInHDF5(db, "TInput/DCCA0", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost A0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DCCB0 = CreateVariableInHDF5(db, "TInput/DCCB0", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost B0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DCCC0 = CreateVariableInHDF5(db, "TInput/DCCC0", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost C0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DCCLimit = CreateVariableInHDF5(db, "TInput/DCCLimit", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost Limit Multiplier (\$/\$)","\$/\$")
  DCCSubsidy = CreateVariableInHDF5(db, "TInput/DCCSubsidy", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost Subsidy (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  DCDEM = CreateVariableInHDF5(db, "TInput/DCDEM", (:Enduse, :Tech, :EC, :Area, :Year),"Device Cost to Efficiency Multiplier for Efficiency Program (\$/\$/(Btu/Btu))","\$/\$/(Btu/Btu")
  DCMM = CreateVariableInHDF5(db, "TInput/DCMM", (:Enduse, :Tech, :EC, :Area, :Year),"Capital Cost Maximum Mult.  (\$/\$)","\$/\$")
  DDay = CreateVariableInHDF5(db, "TInput/DDay", (:Enduse, :Area, :Year),"Annual Degree Days (Degree Days)","Degree Days")
  DDayMonthly = CreateVariableInHDF5(db, "TInput/DDayMonthly", (:Enduse, :Month, :Area, :Year),"Monthly Degree Days (Degree Days)","Degree Days")
  DDayNorm = CreateVariableInHDF5(db, "TInput/DDayNorm", (:Enduse, :Area),"Normal Annual Degree Days (Degree Days)","Degree Days")
  DDCoefficient = CreateVariableInHDF5(db, "TInput/DDCoefficient", (:Enduse, :EC, :Area, :Year),"Annual Energy Degree Day Coefficient (DD/DD)","DD/DD")
  DDHourly = CreateVariableInHDF5(db, "TInput/DDHourly", (:Enduse, :Month, :Area, :Year),"Hourly Degree Days (Degree Days)","Degree Days")
  DDHourlyCoefficient = CreateVariableInHDF5(db, "TInput/DDHourlyCoefficient", (:Enduse, :EC, :Area, :Year),"Hourly Demand Degree Day Coefficient (DD/DD)","DD/DD")
  DDSatFlag = CreateVariableInHDF5(db, "TInput/DDSatFlag", (:Enduse, :Month),"Flag for Degree Days in Saturation Equation (1=include)","1=include")
  DDSmoothingTime = CreateVariableInHDF5(db, "TInput/DDSmoothingTime", (:Enduse, :Area, :Year),"Smoothing Time for Annual Degree Days (Years)","Years")
  DEEA0 = CreateVariableInHDF5(db, "TInput/DEEA0", (:Enduse, :Tech, :EC, :Area, :Year),"Device A0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DEEAM = CreateVariableInHDF5(db, "TInput/DEEAM", (:Enduse, :Tech, :EC, :Area, :Year),"Average Device Efficiency Multiplier (Fraction)","Fraction")
  DEEB0 = CreateVariableInHDF5(db, "TInput/DEEB0", (:Enduse, :Tech, :EC, :Area, :Year),"Device B0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DEEC0 = CreateVariableInHDF5(db, "TInput/DEEC0", (:Enduse, :Tech, :EC, :Area, :Year),"Device C0 Coeffcient for Efficiency Program (Btu/Btu)","Btu/Btu")
  DEEFloorSw = CreateVariableInHDF5(db, "TInput/DEEFloorSw", (:EC, :Area, :Year),"Switch to Activate Floor for Device Efficiency (1=Activate)","1=Activate")
  DEEThermalMax = CreateVariableInHDF5(db, "TInput/DEEThermalMax", (:Enduse, :Tech, :EC, :Area),"Thermal Maximum Device Efficiency (Btu/Btu)","Btu/Btu")
  DEESw = CreateVariableInHDF5(db, "TInput/DEESw", (:Enduse, :Tech, :EC, :Area, :Year),"Switch for Device Efficiency (Switch)","Switch")
  DEM = CreateVariableInHDF5(db, "TInput/DEM", (:Enduse, :Tech, :EC, :Area),"Maximum Device Efficiency (Btu/Btu)","Btu/Btu")
  DEPM = CreateVariableInHDF5(db, "TInput/DEPM", (:Enduse, :Tech, :EC, :Area, :Year),"Device Energy Price Multiplier (\$/\$)","\$/\$")
  DERReduction = CreateVariableInHDF5(db, "TInput/DERReduction", (:Enduse, :Tech, :EC, :Area, :Year),"Device Energy Reduction Fraction ((mmBtu/Yr)/(mmBtu/Yr))","(mmBtu/Yr")
  DEStd = CreateVariableInHDF5(db, "TInput/DEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Device Eff. Standards (Btu/Btu)","Btu/Btu")
  DEStdP = CreateVariableInHDF5(db, "TInput/DEStdP", (:Enduse, :Tech, :EC, :Area, :Year),"Device Eff. Standards Policy (Btu/Btu)","Btu/Btu")
  DGF = CreateVariableInHDF5(db, "TInput/DGF", (:Enduse, :Tech, :EC, :Area, :Year),"Domestic Grant Fraction (\$/\$)","\$/\$")
  DInvTechExo = CreateVariableInHDF5(db, "TInput/DInvTechExo", (:Enduse, :Tech, :EC, :Area, :Year),"Device Exogenous Investments (M\$/Yr)","M\$/Yr")
  DIVTC = CreateVariableInHDF5(db, "TInput/DIVTC", (:Tech, :Area, :Year),"Device Investment Tax Credit (\$/\$)","\$/\$")
  DmdFuel = CreateVariableInHDF5(db, "TInput/DmdFuel", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Enduse Demands (TBtu/Yr)","TBtu/Yr")
  DmdSw = CreateVariableInHDF5(db, "TInput/DmdSw", (:Tech, :EC, :Area, :Year),"DmdEnduse Switch (Switch)","Switch")
  xDmFrac = CreateVariableInHDF5(db, "TInput/xDmFrac", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Energy Demands Fuel/Tech Split (Fraction)","Fraction")
  DmFracMax = CreateVariableInHDF5(db, "TInput/DmFracMax", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Demand Fuel/Tech Fraction Maximum (Btu/Btu)","Btu/Btu")
  DmFracMin = CreateVariableInHDF5(db, "TInput/DmFracMin", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Demand Fuel/Tech Fraction Minimum (Btu/Btu)","Btu/Btu")
  DmFracVF = CreateVariableInHDF5(db, "TInput/DmFracVF", (:Enduse, :Fuel, :Tech, :EC, :Area),"Demand Fuel/Tech Fraction Variance Factor (Btu/Btu)","Btu/Btu")
  DOCF = CreateVariableInHDF5(db, "TInput/DOCF", (:Enduse, :Tech, :EC, :Area, :Year),"Device Operating Cost Fraction (\$/Yr/\$)","\$/Yr/\$")
  DPConv = CreateVariableInHDF5(db, "TInput/DPConv", (:Enduse, :Tech, :EC, :Area, :Year),"Device Process Conversion (Vehicle Mile/Passenger Mile)","Vehicle Mile/Passenger Mile")
  DPIVTC = CreateVariableInHDF5(db, "TInput/DPIVTC", (:Year,),"Device Policy Investment Tax Credit (\$/\$)","\$/\$")
  DRisk = CreateVariableInHDF5(db, "TInput/DRisk", (:Enduse, :Tech),"Device Risk Premium (\$/\$)","\$/\$")
  DRIVTC = CreateVariableInHDF5(db, "TInput/DRIVTC", (:Tech, :Area, :Year),"Device Retrofit Investment Tax Credit (\$/\$)","\$/\$")
  DSMEU = CreateVariableInHDF5(db, "TInput/DSMEU", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Enduse DSM Adjustment (GWh/Yr)","GWh/Yr")
  DSMEUInv = CreateVariableInHDF5(db, "TInput/DSMEUInv", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Enduse DSM Adjustment Investments (1985 M\$/Yr)","1985 M\$/Yr")
  DStA0 = CreateVariableInHDF5(db, "TInput/DStA0", (:Enduse, :EC, :Area, :Year),"Device Saturation Degree Day Coefficient (Btu/Btu/DD)","Btu/Btu/DD")
  DStB0 = CreateVariableInHDF5(db, "TInput/DStB0", (:Enduse, :EC, :Area, :Year),"Device Saturation Coefficient","NoUnit")
  DStC0 = CreateVariableInHDF5(db, "TInput/DStC0", (:Enduse, :EC, :Area, :Year),"Device Saturation Constant Term (Btu/Btu)","Btu/Btu")
  DStMax = CreateVariableInHDF5(db, "TInput/DStMax", (:Enduse, :EC, :Area),"Maximum Device Saturation (Btu/Btu)","Btu/Btu")
  DStMin = CreateVariableInHDF5(db, "TInput/DStMin", (:Enduse, :EC, :Area),"Minimum Device Saturation (Btu/Btu)","Btu/Btu")
  DUCFSw = CreateVariableInHDF5(db, "TInput/DUCFSw", (:Enduse,),"Daily Use Switch for Loading Cogeneration and Feedstock Demand (Switch)","Switch")
  ECCMap = CreateVariableInHDF5(db, "TInput/ECCMap", (:EC, :ECC),"Map between EC and ECC (Map)","Map")
  ECESMap = CreateVariableInHDF5(db, "TInput/ECESMap", (:EC, :ES),"Map between EC and ES for Prices (Map)","Map")
  ECMap = CreateVariableInHDF5(db, "TInput/ECMap", (:EC,),"Map between EC and ECC (Map)","Map")
  ECoverage = CreateVariableInHDF5(db, "TInput/ECoverage", (:EC, :Poll, :PCov, :Area, :Year),"Emissions Coverage (1=Covered)","1=Covered")
  ECovExo = CreateVariableInHDF5(db, "TInput/ECovExo", (:EC, :Poll, :PCov, :Area, :Year),"Emissions Coverage for Exogenous Cap-and-Trade (1=Covered)","1=Covered")
  EEImpact = CreateVariableInHDF5(db, "TInput/EEImpact", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Efficiency Impact (Btu/Btu)","Btu/Btu")
  EESat = CreateVariableInHDF5(db, "TInput/EESat", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Efficiency Saturation (Btu/Btu)","Btu/Btu")
  EESw = CreateVariableInHDF5(db, "TInput/EESw", (:Year,),"Energy Efficiency Switch (Endogenous=1, Exogenous=0, Skip=-1)","Endogenous=1, Exogenous=0, Skip=-1")
  EEUCosts = CreateVariableInHDF5(db, "TInput/EEUCosts", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Efficiency Unit Costs (\$/mmBtu)","\$/mmBtu")
  EICreditMult = CreateVariableInHDF5(db, "TInput/EICreditMult", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Multipler for CFS Credits (Tonne/Tonne)","Tonne/Tonne")
  ElecMap = CreateVariableInHDF5(db, "TInput/ElecMap", (:Tech,),"Primary Electricity Technology (Map)","Map")
  EORDInv = CreateVariableInHDF5(db, "TInput/EORDInv", (:Area, :Year),"Device Investments for EOR (M\$/TBtu)","M\$/TBtu")
  EORDmd = CreateVariableInHDF5(db, "TInput/EORDmd", (:Area, :Year),"Demand for Motors for EOR (TBtu/TBtu)","TBtu/TBtu")
  ESHRt = CreateVariableInHDF5(db, "TInput/ESHRt", (:Tech, :EC, :Area, :Year),"Excess Steam Heat Rate (Btu/KWh)","Btu/KWh")
  ETSwitch = CreateVariableInHDF5(db, "TInput/ETSwitch", (:Tech, :Area, :Year),"Emerging Technology Switch (1=Emerging Technology)","1=Emerging Technology")
  FDCC = CreateVariableInHDF5(db, "TInput/FDCC", (:Enduse, :Tech, :CTech, :Area),"Fixed Device Capital Cost (\$/(MBTU/Yr))","\$/(MBTU/Yr")
  FDCCU = CreateVariableInHDF5(db, "TInput/FDCCU", (:Enduse, :Tech, :CTech, :Area, :Year),"Conversion Rebate","NoUnit")
  FPCPFrac = CreateVariableInHDF5(db, "TInput/FPCPFrac", (:Fuel, :EC, :Area, :Year),"Portion of Carbon Price which impacts Fungible Fuel Fraction (\$/\$)","\$/\$")
  FsDmdFuel = CreateVariableInHDF5(db, "TInput/FsDmdFuel", (:Fuel, :Tech, :EC, :Area, :Year),"Historical Feedstock Demands by Fuel","NoUnit")
  FsPOCX = CreateVariableInHDF5(db, "TInput/FsPOCX", (:Fuel, :Tech, :EC, :Poll, :Area, :Year),"Feedstock Pollution Coefficients (Tonnes/TBtu)","Tonnes/TBtu")
  FTMap = CreateVariableInHDF5(db, "TInput/FTMap", (:Fuel, :EC, :Tech),"Map between Fuel and Tech (Map)","Map")
  HPGeoFraction = CreateVariableInHDF5(db, "TInput/HPGeoFraction", (:EC, :Area, :Year),"Air Source Heat Pump Fraction of Geothermal Demand (TBtu/TBtu)","TBtu/TBtu")
  IdrtCost = CreateVariableInHDF5(db, "TInput/IdrtCost", (:Enduse, :Tech, :EC, :Area, :Year),"Indirect Costs (\$/mmBtu)","\$/mmBtu")
  InitialDemandYear = CreateVariableInHDF5(db, "TInput/InitialDemandYear", (:EC, :Area),"First Year of Calibration","NoUnit")
  MMSFExogenous = CreateVariableInHDF5(db, "TInput/MMSFExogenous", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Market Share Fraction by Device (Fraction)","Fraction")
  MMSFSwitch = CreateVariableInHDF5(db, "TInput/MMSFSwitch", (:Enduse, :Tech, :EC, :Area, :Year),"Market Share Switch (1=Endogenous, 0=Exogenous)","1=Endogenous, 0=Exogenous")
  MSMM = CreateVariableInHDF5(db, "TInput/MSMM", (:Enduse, :Tech, :EC, :Area, :Year),"Non-Price Market Share Factor Multiplier (\$/\$)","\$/\$")
  PCCA0 = CreateVariableInHDF5(db, "TInput/PCCA0", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost A0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PCCB0 = CreateVariableInHDF5(db, "TInput/PCCB0", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost B0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PCCC0 = CreateVariableInHDF5(db, "TInput/PCCC0", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost C0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PCCMM = CreateVariableInHDF5(db, "TInput/PCCMM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost Maximum Multiplier (\$/\$)","\$/\$")
  PCostExo = CreateVariableInHDF5(db, "TInput/PCostExo", (:Tech, :EC, :Poll, :Area, :Year),"Marginal Exogenous Permit Cost (Real \$/Tonnes)","Real \$/Tonnes")
  PCostM = CreateVariableInHDF5(db, "TInput/PCostM", (:Tech, :EC, :Poll, :Area, :Year),"Permit Cost Multiplier (\$/Tonne/\$/Tonne)","\$/Tonne/\$/Tonne")
  PCostN = CreateVariableInHDF5(db, "TInput/PCostN", (:Tech, :EC, :Poll, :Area),"Pollution Reduction Cost Normal (\$/Tonne)","\$/Tonne")
  PCPEM = CreateVariableInHDF5(db, "TInput/PCPEM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Cost to Efficiency Multiplier for Efficiency Program (\$/\$/(\$/Btu/(\$/Btu)))","\$/\$/(\$/Btu/(\$/Btu")
  PDif = CreateVariableInHDF5(db, "TInput/PDif", (:Enduse, :Tech, :EC, :Area),"Difference between the Initial Process Efficiency for each Technology (Btu/Btu)","Btu/Btu")
  PEEA0 = CreateVariableInHDF5(db, "TInput/PEEA0", (:Enduse, :Tech, :EC, :Area, :Year),"Process A0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEEB0 = CreateVariableInHDF5(db, "TInput/PEEB0", (:Enduse, :Tech, :EC, :Area, :Year),"Process B0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEEC0 = CreateVariableInHDF5(db, "TInput/PEEC0", (:Enduse, :Tech, :EC, :Area, :Year),"Process C0 Coeffcient for Efficiency Program (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEEFloorSw = CreateVariableInHDF5(db, "TInput/PEEFloorSw", (:EC, :Area, :Year),"Switch to Activate Floor for Process Efficiency (1=Activate)","1=Activate")
  PEElas = CreateVariableInHDF5(db, "TInput/PEElas", (:Enduse, :Tech, :EC, :Area, :Year),"Long Term Price Elasticity for Process Efficiency (\$/Btu)","\$/Btu")
  PEEP = CreateVariableInHDF5(db, "TInput/PEEP", (:Enduse, :Tech, :EC, :Area, :Year),"Policy Process Efficiency (\$/Btu)","\$/Btu")
  PEESw = CreateVariableInHDF5(db, "TInput/PEESw", (:Enduse, :Tech, :EC, :Area, :Year),"Switch for Process Efficiency (Switch)","Switch")
  PEMMSw = CreateVariableInHDF5(db, "TInput/PEMMSw", (:EC, :Area),"Process Efficiency Update Switch (1=Yes, 0=No)","1=Yes, 0=No")
  PEMMYr = CreateVariableInHDF5(db, "TInput/PEMMYr", (:tv,),"Process Efficiency Update Year (Year)","Year")
  PEMX = CreateVariableInHDF5(db, "TInput/PEMX", (:Enduse, :Tech, :EC, :Area),"Ratio of Maximum to Average Process Efficiency (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  PEPM = CreateVariableInHDF5(db, "TInput/PEPM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Energy Price Multiplier (\$/\$)","\$/\$")
  PERReduction = CreateVariableInHDF5(db, "TInput/PERReduction", (:Enduse, :Tech, :EC, :Area, :Year),"Process Energy Exogenous Retrofits Percentage ((mmBtu/Yr)/(mmBtu/Yr))","(mmBtu/Yr")
  PEStd = CreateVariableInHDF5(db, "TInput/PEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Standards (\$/Btu)","\$/Btu")
  PEStdP = CreateVariableInHDF5(db, "TInput/PEStdP", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Standards Policy (\$/Btu)","\$/Btu")
  PInvExo = CreateVariableInHDF5(db, "TInput/PInvExo", (:Enduse, :Tech, :EC, :Area, :Year),"Process Exogenous Investments (M\$/Yr)","M\$/Yr")
  PInvMinFrac = CreateVariableInHDF5(db, "TInput/PInvMinFrac", (:EC, :Area, :Year),"Minimum Fraction for Process Investments (\$/\$)","\$/\$")
  PIVTC = CreateVariableInHDF5(db, "TInput/PIVTC", (:Year,),"Process Investment Tax Credit (\$/\$)","\$/\$")
  POCX = CreateVariableInHDF5(db, "TInput/POCX", (:Enduse, :FuelEP, :Tech, :EC, :Poll, :Area, :Year),"Pollution Coefficient (Tonnes/TBtu)","Tonnes/TBtu")
  PPIVTC = CreateVariableInHDF5(db, "TInput/PPIVTC", (:Year,),"Process Policy Investment Tax Credit (\$/\$)","\$/\$")
  PrPCostAT = CreateVariableInHDF5(db, "TInput/PrPCostAT", (:EC, :Area),"Pollution Cost Adjustment Time (Years)","Years")
  PrPCostSw = CreateVariableInHDF5(db, "TInput/PrPCostSw", (:Year,),"Pollution Cost Switch","NoUnit")
  PVF = CreateVariableInHDF5(db, "TInput/PVF", (:Tech, :EC, :Poll, :Area),"Pollution Reduction Variance Factor ((\$/Tonne)/(\$/Tonne))","(\$/Tonne")
  RCD = CreateVariableInHDF5(db, "TInput/RCD", (:EC, :Poll),"Reduction Capital Construction Delay (Years)","Years")
  RCostM = CreateVariableInHDF5(db, "TInput/RCostM", (:Tech, :Poll, :Year),"Reduction Cost Technology Multiplier (\$/\$)","\$/\$")
  RCPL = CreateVariableInHDF5(db, "TInput/RCPL", (:EC, :Poll),"Reduction Capital Physical Life (Years)","Years")
  RCROIN = CreateVariableInHDF5(db, "TInput/RCROIN", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Conservation Return on Investment (\$/Yr/\$)","\$/Yr/\$")
  RDCCM = CreateVariableInHDF5(db, "TInput/RDCCM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Device Capital Cost Multiplier (\$/\$)","\$/\$")
  RDEMM = CreateVariableInHDF5(db, "TInput/RDEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Maximum Device Efficiency Multiplier (Btu/Btu)","Btu/Btu")
  RDEStd = CreateVariableInHDF5(db, "TInput/RDEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Device Eff. Standards (Btu/Btu)","Btu/Btu")
  RDVF = CreateVariableInHDF5(db, "TInput/RDVF", (:EC, :Area),"Device Retrofit Market Share Variance Factor (DLESS)","DLESS")
  RetroSw = CreateVariableInHDF5(db, "TInput/RetroSw", (:Enduse, :EC, :Area, :Year),"Retrofit Switch (Switch)","Switch")
  RetroSwExo = CreateVariableInHDF5(db, "TInput/RetroSwExo", (:Year,),"Switch for Exogneous Retrofit Policy (=Method)","=Method")
  RGF = CreateVariableInHDF5(db, "TInput/RGF", (:Enduse, :Tech, :EC, :Area, :Year),"Device Retrofit Rebate Fraction (Fraction)","Fraction")
  RHCM = CreateVariableInHDF5(db, "TInput/RHCM", (:EC, :Area, :Year),"Retrofit Hassle-Cost Multiplier (\$/\$)","\$/\$")
  ROCF = CreateVariableInHDF5(db, "TInput/ROCF", (:Tech, :EC, :Poll, :Area),"Polution Reducution O&M (\$/Tonne)","\$/Tonne")
  ROIN = CreateVariableInHDF5(db, "TInput/ROIN", (:EC, :Area),"Return on Investment (\$/Yr/\$)","\$/Yr/\$")
  RPCCM = CreateVariableInHDF5(db, "TInput/RPCCM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Process Capital Cost Multiplier (\$/\$)","\$/\$")
  RPCSw = CreateVariableInHDF5(db, "TInput/RPCSw", (:EC, :Poll, :Area, :Year),"Pollution Reduction Curve Switch (1=2009, 2=2004)","1=2009, 2=2004")
  RPEEFr = CreateVariableInHDF5(db, "TInput/RPEEFr", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Fraction for Retrofits (\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  RPEIX = CreateVariableInHDF5(db, "TInput/RPEIX", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Impact of Pollution Reduction Coefficient (Btu/Btu/Tonne/Tonne)","Btu/Btu/Tonne/Tonne")
  RPEMM = CreateVariableInHDF5(db, "TInput/RPEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Retrofit Maximum Device Efficiency Multiplier (Btu/Btu)","Btu/Btu")
  RPEStd = CreateVariableInHDF5(db, "TInput/RPEStd", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Standards (\$/Btu)","\$/Btu")
  RPIVTC = CreateVariableInHDF5(db, "TInput/RPIVTC", (:Area, :Year),"Process Retrofit Policy Investment Tax Credit (\$/\$)","\$/\$")
  RPMSLimit = CreateVariableInHDF5(db, "TInput/RPMSLimit", (:EC, :Area, :Year),"Process Retrofit Market Share Limit (1/Yr)","1/Yr")
  RPVF = CreateVariableInHDF5(db, "TInput/RPVF", (:EC, :Area),"Process Retrofit Market Share Variance Factor (DLESS)","DLESS")
  RRisk = CreateVariableInHDF5(db, "TInput/RRisk", (:Enduse, :Tech, :Area, :Year),"Retrofit Excess Risk (\$/\$)","\$/\$")
  SqEUTechMap = CreateVariableInHDF5(db, "TInput/SqEUTechMap", (:Enduse, :Tech),"Sequestering Enduse Map to Tech (1=include)","1=include")
  SqEnMap = CreateVariableInHDF5(db, "TInput/SqEnMap", (:Enduse,),"Sequestering Enduse Map (1=include)","1=include")
  SqPenaltyFuel = CreateVariableInHDF5(db, "TInput/SqPenaltyFuel", (:Fuel, :EC, :Area, :Year),"Sequestering Energy Penalty (TBtu/Tonne CO2)","TBtu/Tonne CO2")
  SqPenaltyTech = CreateVariableInHDF5(db, "TInput/SqPenaltyTech", (:Tech, :EC, :Poll, :Area, :Year),"Sequestering Energy Penalty (TBtu/Tonne)","TBtu/Tonne")
  SbMSM0 = CreateVariableInHDF5(db, "TInput/SbMSM0", (:Enduse, :Tech, :EC, :Area, :Year),"Non-Price Factor for High Efficiency Device Market Share (\$/\$)","\$/\$")
  SbVF = CreateVariableInHDF5(db, "TInput/SbVF", (:Enduse, :Tech, :EC, :Area, :Year),"Price Variance Factor for High Efficiency Device Market Share (\$/\$)","\$/\$")
  STFSw = CreateVariableInHDF5(db, "TInput/STFSw", (:Fuel, :Area),"Short Term Forecast Switch (1=On, 0=Off)","1=On, 0=Off")
  StockAdjustment = CreateVariableInHDF5(db, "TInput/StockAdjustment", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Capital Stock Adjustment (\$/\$)","\$/\$")
  STX = CreateVariableInHDF5(db, "TInput/STX", (:Area, :Year),"Sales Tax Rate on Energy Consumer (\$/\$)","\$/\$")
  TAXPCT = CreateVariableInHDF5(db, "TInput/TAXPCT", (:Area, :Year),"Standard accounting percent of device life that is taxed. (%)","%")
  TrPCovMap = CreateVariableInHDF5(db, "TInput/TrPCovMap", (:Tech, :EC, :PCov, :Area, :Year),"Transportation Technology Pollution Coverage Map (1=Mapped)","1=Mapped")
  TSLoad = CreateVariableInHDF5(db, "TInput/TSLoad", (:Enduse, :EC, :Area),"Temperature Sensitive Fraction of Load (Btu/Btu)","Btu/Btu")
  TxRt = CreateVariableInHDF5(db, "TInput/TxRt", (:EC, :Area, :Year),"Income Tax Rate on Energy Consumer (\$/\$)","\$/\$")
  vFsMap = CreateVariableInHDF5(db, "TInput/vFsMap", (:Fuel, :Tech),"Maps the Feedstock Fuels from vData into Tech","NoUnit")
  VRP = CreateVariableInHDF5(db, "TInput/VRP", (:Tech, :EC, :Poll, :Area, :Year),"Voluntary Reduction Policy (Tonnes/Tonnes)","Tonnes/Tonnes")
  VRRT = CreateVariableInHDF5(db, "TInput/VRRT", (:EC,),"Voluntary Reduction response time (Years)","Years")
  xCgDmd = CreateVariableInHDF5(db, "TInput/xCgDmd", (:Tech, :EC, :Area, :Year),"Historical Cogeneration (TBtu/Yr)","TBtu/Yr")
  xCgEG = CreateVariableInHDF5(db, "TInput/xCgEG", (:Tech, :EC, :Area, :Year),"Historical Electricity from Cogeneration (GWh/Yr)","GWh/Yr")
  xCgHRtA = CreateVariableInHDF5(db, "TInput/xCgHRtA", (:Tech, :EC, :Area, :Year),"Historical Average Cogeneration Heat Rate (Btu/KWh)","Btu/KWh")
  xCgIGC = CreateVariableInHDF5(db, "TInput/xCgIGC", (:Tech, :EC, :Area, :Year),"Exogenous Indicated Cogeneration Capacity (MW)","MW")
  xCgLSF = CreateVariableInHDF5(db, "TInput/xCgLSF", (:Tech, :EC, :Hour, :Day, :Month, :Area),"Cogeneration Load Shape (MW/MW)","MW/MW")
  xCgLSFSold = CreateVariableInHDF5(db, "TInput/xCgLSFSold", (:EC, :Hour, :Day, :Month, :Area),"Cogeneration Sold to Grid Load Shape (MW/MW)","MW/MW")
  xCgVF = CreateVariableInHDF5(db, "TInput/xCgVF", (:Tech, :EC),"Cogeneration Variance Factor (\$/\$)","\$/\$")
  xCMSF = CreateVariableInHDF5(db, "TInput/xCMSF", (:Enduse, :Tech, :CTech, :EC, :Area, :Year),"Conversion Market Share by Device (\$/\$)","\$/\$")
  xDCC = CreateVariableInHDF5(db, "TInput/xDCC", (:Enduse, :Tech, :EC, :Area, :Year),"Device Capital Cost (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  xDCCPolicy = CreateVariableInHDF5(db, "TInput/xDCCPolicy", (:Enduse, :Tech, :EC, :Area, :Year),"Capital Cost of Policy Device (\$/mmBtu/Yr)","\$/mmBtu/Yr")
  xDCMM = CreateVariableInHDF5(db, "TInput/xDCMM", (:Enduse, :Tech, :EC, :Area, :Year),"Maximum Capital Cost Multiplier (Btu/Btu)","Btu/Btu")
  xDEE = CreateVariableInHDF5(db, "TInput/xDEE", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Device Efficiency (Btu/Btu)","Btu/Btu")
  xXDEE = CreateVariableInHDF5(db, "TInput/xXDEE", (:Enduse, :Tech, :EC, :Area, :Year),"Device Efficiency w/ Standard (Btu/Btu)","Btu/Btu")
  xDEEA = CreateVariableInHDF5(db, "TInput/xDEEA", (:Enduse, :Tech, :EC, :Area, :Year),"Average Device Efficiency (Btu/Btu)","Btu/Btu")
  xDEEPolicy = CreateVariableInHDF5(db, "TInput/xDEEPolicy", (:Enduse, :Tech, :EC, :Area, :Year),"Policy Device Efficiency (Btu/Btu) (Btu/Btu)","Btu/Btu")
  xDEEPolicyMSF = CreateVariableInHDF5(db, "TInput/xDEEPolicyMSF", (:Enduse, :Tech, :EC, :Area, :Year),"Policy Participation Response (Btu/Btu)","Btu/Btu")
  xDEMM = CreateVariableInHDF5(db, "TInput/xDEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Maximum Device Efficiency Multiplier (Btu/Btu)","Btu/Btu")
  xDmd = CreateVariableInHDF5(db, "TInput/xDmd", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Energy Demand (TBtu/Yr)","TBtu/Yr")
  xDmdTrend = CreateVariableInHDF5(db, "TInput/xDmdTrend", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Energy Demand (TBtu/Yr)","TBtu/Yr")
  xDPL = CreateVariableInHDF5(db, "TInput/xDPL", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Physical Life of Equipment (Years)","Years")
  xDSt = CreateVariableInHDF5(db, "TInput/xDSt", (:Enduse, :EC, :Area, :Year),"Device Saturation (Btu/Btu)","Btu/Btu")
  xDUF = CreateVariableInHDF5(db, "TInput/xDUF", (:Enduse, :EC, :Day, :Month, :Area),"Daily Use Factor (Therm/Therm)","Therm/Therm")
  xEE = CreateVariableInHDF5(db, "TInput/xEE", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Energy Efficiency (TBtu)","TBtu")
  xEnergyPerStock = CreateVariableInHDF5(db, "TInput/xEnergyPerStock", (:Enduse, :Tech, :EC, :Area, :Year),"Energy Capital per Vehicle Stock (Btu/Vehicle)","Btu/Vehicle")
  xFsDmd = CreateVariableInHDF5(db, "TInput/xFsDmd", (:Tech, :EC, :Area, :Year),"Feedstock Energy (TBtu/Yr)","TBtu/Yr")
  xFsFrac = CreateVariableInHDF5(db, "TInput/xFsFrac", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Demands Fuel/Tech Split (Fraction)","Fraction")
  xLSF = CreateVariableInHDF5(db, "TInput/xLSF", (:Enduse, :EC, :Hour, :Day, :Month, :Area),"Load Shape Factor (MW/MW)","MW/MW")
  xMVF = CreateVariableInHDF5(db, "TInput/xMVF", (:Enduse, :Tech, :EC, :Area, :Year),"Market Share Variance Factor (\$/\$)","\$/\$")
  xPCC = CreateVariableInHDF5(db, "TInput/xPCC", (:Enduse, :Tech, :EC, :Area, :Year),"Process Capital Cost (\$/(\$/Yr))","\$/(\$/Yr")
  xPEE = CreateVariableInHDF5(db, "TInput/xPEE", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Process Efficiency (\$/Btu)","\$/Btu")
  xPEEA = CreateVariableInHDF5(db, "TInput/xPEEA", (:Enduse, :Tech, :EC, :Area, :Year),"Historical Average Process Efficiency (\$/Btu)","\$/Btu")
  xPEMM = CreateVariableInHDF5(db, "TInput/xPEMM", (:Enduse, :Tech, :EC, :Area, :Year),"Process Efficiency Maximum Multiplier(\$/Btu/(\$/Btu))","\$/Btu/(\$/Btu")
  xPkSav = CreateVariableInHDF5(db, "TInput/xPkSav", (:Enduse, :EC, :Area, :Year),"Exogenous Peak Savings (MW)","MW")
  xProcSw = CreateVariableInHDF5(db, "TInput/xProcSw", (:PI, :Year),"Procedure Switch (1=on, 0=off)","1=on, 0=off")
  xRDMSF = CreateVariableInHDF5(db, "TInput/xRDMSF", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Device Retrofit Market Share Fraction by Device (1/Yr)","1/Yr")
  xRM = CreateVariableInHDF5(db, "TInput/xRM", (:Tech, :EC, :Poll, :Area, :Year),"Exogenous Average Pollution Coefficient Reduction Multiplier (Tonnes/Tonnes)","Tonnes/Tonnes")
  xRPCC = CreateVariableInHDF5(db, "TInput/xRPCC", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Process Retrofit Capital Cost (\$/(\$/Yr))","\$/(\$/Yr")
  xRPEE = CreateVariableInHDF5(db, "TInput/xRPEE", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Retrofit Process Efficiency (\$/BTU)","\$/BTU")
  xRPMSF = CreateVariableInHDF5(db, "TInput/xRPMSF", (:Enduse, :Tech, :EC, :Area, :Year),"Exogenous Process Retrofit Market Share Fraction by Device (1/Yr)","1/Yr")
  xSqDmd = CreateVariableInHDF5(db, "TInput/xSqDmd", (:Tech, :EC, :Area, :Year),"Sequestering Energy Demand (TBtu/Yr)","TBtu/Yr")
  xVehiclesPerHousehold = CreateVariableInHDF5(db, "TInput/xVehiclesPerHousehold", (:Area, :Year),"Vehicles per Household (Vehicle/Household)","Vehicle/Household")
  xVehicleStock = CreateVariableInHDF5(db, "TInput/xVehicleStock", (:Tech, :Area, :Year),"Stock of Vehicles (Vehicles)","Vehicles")
  xXProcSw = CreateVariableInHDF5(db, "TInput/xXProcSw", (:PI, :Year),"Procedure Switch (1=on, 0=off)","1=on, 0=off")
  YCERSM = CreateVariableInHDF5(db, "TInput/YCERSM", (:Enduse, :EC, :Area, :Year),"CERSM Calibration Control (Switch)","Switch")
  YCgCUF = CreateVariableInHDF5(db, "TInput/YCgCUF", (:Tech, :EC, :Area, :Year),"CgCUF Calibration Control (Switch)","Switch")
  YCgMSM = CreateVariableInHDF5(db, "TInput/YCgMSM", (:Tech, :EC, :Area, :Year),"CgMSM Calibration Control (Switch)","Switch")
  YCUF = CreateVariableInHDF5(db, "TInput/YCUF", (:Enduse, :Tech, :EC, :Area, :Year),"CUF Calibration Control (Switch)","Switch")
  YDCMM = CreateVariableInHDF5(db, "TInput/YDCMM", (:Enduse, :Tech, :Area, :Year),"DCMM Calibration Control (Switch)","Switch")
  YDEMM = CreateVariableInHDF5(db, "TInput/YDEMM", (:Enduse, :Tech, :Area, :Year),"DEMM Calibration Control (Switch)","Switch")
  YDSt = CreateVariableInHDF5(db, "TInput/YDSt", (:Enduse, :EC, :Area, :Year),"DSt Calibration Control (Switch)","Switch")
  YEndTime = CreateVariableInHDF5(db, "TInput/YEndTime", (:tv,),"Last Year of Calibration (Date)","Date")
  YFsPEE = CreateVariableInHDF5(db, "TInput/YFsPEE", (:Tech, :EC, :Area, :Year),"FsPEE Calibration Control (Switch)","Switch")
  YMMSM = CreateVariableInHDF5(db, "TInput/YMMSM", (:Enduse, :Tech, :EC, :Area, :Year),"MMSM Calibration Control (Switch)","Switch")
  YPEMM = CreateVariableInHDF5(db, "TInput/YPEMM", (:Enduse, :Tech, :EC, :Area, :Year),"PEMM Calibration Control (Switch)","Switch")
  xTrEnFPol = CreateVariableInHDF5(db, "TInput/xTrEnFPol", (:Enduse, :FuelEP, :Tech, :EC, :Poll, :Area, :Year),"Transportation Energy Related Pollution (Tonnes/Yr)","Tonnes/Yr")
  CMSFSwitch = CreateVariableInHDF5(db, "TInput/CMSFSwitch", (:Enduse, :Tech, :CTech, :EC, :Area, :Year),"Conversion Market Share Switch (1=Endogenous, 0=Exogenous)","1=Endogenous, 0=Exogenous")
  DActV = CreateVariableInHDF5(db, "TInput/DActV", (:Enduse, :Tech, :EC, :Area, :Vintage),"Activity Rate of Equipment by Vintage (1/1)","1/1")
  DmFracTime = CreateVariableInHDF5(db, "TInput/DmFracTime", (:Enduse, :Fuel, :Tech, :EC, :Area, :Year),"Demand Fuel/Tech Adjustment Time (Years)","Years")
  DPLV = CreateVariableInHDF5(db, "TInput/DPLV", (:Enduse, :Tech, :EC, :Area, :Vintage, :Year),"Scrappage Rate of Equipment by Vintage (1/1)","1/1")
  FsFracMax = CreateVariableInHDF5(db, "TInput/FsFracMax", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Fraction Maximum (Btu/Btu)","Btu/Btu")
  FsFracMin = CreateVariableInHDF5(db, "TInput/FsFracMin", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Fraction Minimum (Btu/Btu)","Btu/Btu")
  FsFracVF = CreateVariableInHDF5(db, "TInput/FsFracVF", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Fraction Variance Factor (Btu/Btu)","Btu/Btu")
  FsFracTime = CreateVariableInHDF5(db, "TInput/FsFracTime", (:Fuel, :Tech, :EC, :Area, :Year),"Feedstock Fuel/Tech Adjustment Time (Years)","Years")
  FsPOCS = CreateVariableInHDF5(db, "TInput/FsPOCS", (:Fuel, :Tech, :EC, :Poll, :Area, :Year),"Feedstock Pollution Standards (Tonnes/TBtu)","Tonnes/TBtu")
  POCS = CreateVariableInHDF5(db, "TInput/POCS", (:Enduse, :FuelEP, :Tech, :EC, :Poll, :Area, :Year),"Pollution Standards (Tonnes/TBtu)","Tonnes/TBtu")
  POCAM = CreateVariableInHDF5(db, "TInput/POCAM", (:FuelEP, :Tech, :EC, :Poll, :Area, :Year),"Average Pollution Coefficients Multiplier (Fraction)","Fraction")
  PolSw = CreateVariableInHDF5(db, "TInput/PolSw", (:Tech, :EC, :Poll, :Area, :Year),"Switch for Pollution Coefficients (Switch)","Switch")
  TrMEPX = CreateVariableInHDF5(db, "TInput/TrMEPX", (:Tech, :EC, :Poll, :Area, :Year),"Non-Energy Pollution Coefficient (Tonnes/Vehicle Miles)","Tonnes/Vehicle Miles")
  xTrMEPol = CreateVariableInHDF5(db, "TInput/xTrMEPol", (:Tech, :EC, :Poll, :Area, :Year),"Non-Energy Pollution (Tonnes/Yr)","Tonnes/Yr")
  ########################
  #
  # Define Variables on Database
  #
  #! format: off
end # struct TInput2
