#
# MarketCFR.jl
#
using EnergyModel
import ...EnergyModel: ReadDisk,WriteDisk,Select,DT
import ...EnergyModel: ITime,HisTime,MaxTime,Zero,First,Last,Future,Final,Yr
import ...EnergyModel: @finite_math,EnergyModel,finite_inverse,finite_divide,finite_power,finite_exp,finite_log
import ...EnergyModel: DB
using   ..EnergyModel: HDF5DataSetNotFoundException,E2020Folder,OutputFolder,rm_dir_contents

using HDF5,DataFrames,CSV,Printf

const VariableArray{N} = Array{Float32,N} where {N}
const SetArray = Vector{String}


Base.@kwdef struct MarketCFRData
  db::String

  BCNameDB::String = ReadDisk(db,"MainDB/BCNameDB") #  Base Case Name

  Area::SetArray = ReadDisk(db, "MainDB/AreaKey")
  AreaDS::SetArray = ReadDisk(db, "MainDB/AreaDS")
  Areas::Vector{Int} = collect(Select(Area))

  EC::SetArray = ReadDisk(db, "TInput/ECKey")
  ECDS::SetArray = ReadDisk(db, "TInput/ECDS")
  ECs::Vector{Int} = collect(Select(EC))

  ECC::SetArray = ReadDisk(db, "MainDB/ECCKey")
  ECCDS::SetArray = ReadDisk(db, "MainDB/ECCDS")
  ECCs::Vector{Int} = collect(Select(ECC))

  EIType::SetArray = ReadDisk(db, "MainDB/EITypeKey")
  EITypeDS::SetArray = ReadDisk(db, "MainDB/EITypeDS")
  EITypes::Vector{Int} = collect(Select(EIType))

  ES::SetArray = ReadDisk(db, "MainDB/ESKey")
  ESDS::SetArray = ReadDisk(db, "MainDB/ESDS")
  ESes::Vector{Int} = collect(Select(ES))

  Enduse::SetArray = ReadDisk(db, "TInput/EnduseKey")
  EnduseDS::SetArray = ReadDisk(db, "TInput/EnduseDS")
  Enduses::Vector{Int} = collect(Select(Enduse))

  Fuel::SetArray = ReadDisk(db, "MainDB/FuelKey")
  FuelDS::SetArray = ReadDisk(db, "MainDB/FuelDS")
  Fuels::Vector{Int} = collect(Select(Fuel))

  FuelEP::SetArray = ReadDisk(db, "MainDB/FuelEPKey")
  FuelEPDS::SetArray = ReadDisk(db, "MainDB/FuelEPDS")
  FuelEPs::Vector{Int} = collect(Select(FuelEP))

  Market::SetArray = ReadDisk(db, "MainDB/MarketKey")
  Markets::Vector{Int} = collect(Select(Market))

  Nation::SetArray = ReadDisk(db, "MainDB/NationKey")
  NationDS::SetArray = ReadDisk(db, "MainDB/NationDS")
  Nations::Vector{Int} = collect(Select(Nation))

  Tech::SetArray = ReadDisk(db, "TInput/TechKey")
  TechDS::SetArray = ReadDisk(db, "TInput/TechDS")
  Techs::Vector{Int} = collect(Select(Tech))

  Poll::SetArray = ReadDisk(db, "MainDB/PollKey")
  PollDS::SetArray = ReadDisk(db, "MainDB/PollDS")
  Polls::Vector{Int} = collect(Select(Poll))

  Year::SetArray = ReadDisk(db, "MainDB/YearKey")

  CDTime::Int = ReadDisk(db, "SInput/CDTime")[1] # Constant Dollar Year for Model Outputs (Year)
  CDYear::Int = ReadDisk(db, "SInput/CDYear")[1] # Constant Dollar Year for Model Outputs (Year)
  SceName::String = ReadDisk(db,"SInput/SceName") #  Scenario Name
  
  Yr2030 = 2030 -1985 + 1

  #TODOJulia Add Reference Case Selections

  ANMap::VariableArray{2} = ReadDisk(db, "MainDB/ANMap") # [Area,Nation] Map between Area and Nation
  AreaMarket::VariableArray{3} = ReadDisk(db, "SInput/AreaMarket") # [Area,Market,Year] Areas included in Market
  CgDemand::VariableArray{4} = ReadDisk(db, "SOutput/CgDemand") # [Fuel,ECC,Area,Year] Cogeneration Demands (TBtu/Yr)
  CgDemandRef::VariableArray{4} = ReadDisk(BCNameDB, "SOutput/CgDemand") # [Fuel,ECC,Area,Year] Cogeneration Demands (TBtu/Yr)
  CoverageCFS::VariableArray{4} = ReadDisk(db, "SInput/CoverageCFS") # [Fuel,ECC,Area,Year] Fuel Coverage for CFR (1=Covered)
  CreditsBanked::VariableArray{2} = ReadDisk(db, "SOutput/CreditsBanked") # [Market,Year] CFR Credits Banked into Inventory (Tonnes/Yr)
  CreditsCogeneration::VariableArray{3} = ReadDisk(db, "SOutput/CreditsCogeneration") # [ECC,Area,Year] CFR Credits Generated by Cogeneration (Tonnes/Yr)
  CreditsFossil::VariableArray{4} = ReadDisk(db, "SOutput/CreditsFossil") # [Fuel,ECC,Area,Year] CFR Credits Generated by reducing Intensity of Fossil Fuels (Tonnes/Yr)
  CreditsFugitive::VariableArray{3} = ReadDisk(db, "SOutput/CreditsFugitive") # [ECC,Area,Year] Fugitive Credits (Tonnes/Yr)
  CreditsGenerated::VariableArray{2} = ReadDisk(db, "SOutput/CreditsGenerated") # [Area,Year] CFR Credits Generated (Tonnes/Yr)
  CreditsInventory::VariableArray{2} = ReadDisk(db, "SOutput/CreditsInventory") # [Market,Year] CFR Credits Inventory (Tonnes/Yr)
  CreditsLowCarbon::VariableArray{4} = ReadDisk(db, "SOutput/CreditsLowCarbon") # [Fuel,ECC,Area,Year] CFR Credits Generated by Low Carbon Fuels (Tonnes/Yr)
  CreditsNeeded::VariableArray{4} = ReadDisk(db, "SOutput/CreditsNeeded") # [Fuel,ECC,Area,Year] CFR Credits Needed (Tonnes/Yr)
  CreditsOther::VariableArray{2} = ReadDisk(db, "SInput/CreditsOther") # [Area,Year] CFR Credits Generated by Other Methods (Tonnes/Yr)
  CreditsRedeemed::VariableArray{2} = ReadDisk(db, "SOutput/CreditsRedeemed") # [Market,Year] CFR Credits Redeemed from Inventory (Tonnes/Yr)
  CreditsRequired::VariableArray{2} = ReadDisk(db, "SOutput/CreditsRequired") # [Area,Year] CFR Credits Required (Tonnes/Yr)
  CreditsSequester::VariableArray{3} = ReadDisk(db, "SOutput/CreditsSequester") # [ECC,Area,Year] CFR Credits from Sequestering (Tonnes/Yr)
  CreditsTech::VariableArray{6} = ReadDisk(db, "TOutput/CreditsTech") # [Enduse,Fuel,Tech,EC,Area,Year] Credits Generated by Low Carbon Fuels (Tonnes/Yr)
  CreditSwitch::VariableArray{4} = ReadDisk(db, "SInput/CreditSwitch") # [Fuel,ECC,Area,Year] Switch to Indicate Fuels which must Purchase CFR Credits (1=Purchase)
  DemandCFS::VariableArray{4} = ReadDisk(db, "SOutput/DemandCFS") # [Fuel,ECC,Area,Year] Energy Demands for CFR (TBtu/Yr)
  DemandCFSRef::VariableArray{4} = ReadDisk(BCNameDB, "SOutput/DemandCFS") # [Fuel,ECC,Area,Year] Energy Demands for CFR (TBtu/Yr)
  DmFrac::VariableArray{6} = ReadDisk(db, "TOutput/DmFrac") # [Enduse,Fuel,Tech,EC,Area,Year] Demand Fuel/Tech Fraction Split (Btu/Btu)
  Driver::VariableArray{3} = ReadDisk(db, "MOutput/Driver") # [ECC,Area,Year] Economic Driver (Various Millions/Yr)
  EIAverage::VariableArray{2} = ReadDisk(db, "SInput/EIAverage") # [Market,Year] Weighted Average EI of Stream (Tonne/TBtu)
  EICFS::VariableArray{3} = ReadDisk(db, "SOutput/EICFS") # [Fuel,Area,Year] Emission Intensity (Tonnes/TBtu)
  EICFSRef::VariableArray{3} = ReadDisk(BCNameDB, "SOutput/EICFS") # [Fuel,Area,Year] Emission Intensity (Tonnes/TBtu)
  EIDomestic::VariableArray{3} = ReadDisk(db, "SOutput/EIDomestic") # [Fuel,Area,Year] Emission Intensity for Domestic Fuels (Tonnes/TBtu)
  EIGapCFS::VariableArray{4} = ReadDisk(db, "SOutput/EIGapCFS") # [Fuel,ES,Area,Year] Emission Intensity Gap between EI and EI Goal (Tonnes/TBtu)
  EIGoal::VariableArray{6} = ReadDisk(db, "TOutput/EIGoal") # [Enduse,Fuel,Tech,EC,Area,Year] Emission Intensity Goal for CFR (Tonnes/TBtu)
  EIGoalCFS::VariableArray{4} = ReadDisk(db, "SInput/EIGoalCFS") # [Fuel,ES,Area,Year] Emission Intensity Goal for CFR (Tonnes/TBtu)
  EIImports::VariableArray{3} = ReadDisk(db, "SOutput/EIImports") # [Fuel,Area,Year] Emission Intensity for Imported Fuels (Tonnes/TBtu)
  EINation::VariableArray{4} = ReadDisk(db, "SOutput/EINation") # [EIType,Fuel,Nation,Year] Emission Intensity (Tonnes/TBtu)
  EIOfficial::VariableArray{3} = ReadDisk(db, "SInput/EIOfficial") # [Fuel,Area,Year] Official Value for Emission Intensity (Tonnes/TBtu)
  EIReduction::VariableArray{2} = ReadDisk(db, "SInput/EIReduction") # [Market,Year] EI Reduction Requirement (Tonne/TBtu)
  EISector::VariableArray{3} = ReadDisk(db, "SOutput/EISector") # [ECC,Area,Year] Sector Emission Intensity (Tonnes/TBtu)
  EISectorRef::VariableArray{3} = ReadDisk(BCNameDB, "SOutput/EISector") # [ECC,Area,Year] Sector Emission Intensity (Tonnes/TBtu)
  EISectorN::VariableArray{3} = ReadDisk(db, "SOutput/EISectorN") # [ECC,Nation,Year] Sector Emission Intensity (Tonnes/TBtu)
  EIStreamCredit::VariableArray{2} = ReadDisk(db, "SInput/EIStreamCredit") # [Market,Year] Stream Credit Reference Emission Intensity (Tonnes/TBtu)
  Enforce::VariableArray{1} = ReadDisk(db, "SInput/Enforce") # [Market] First Year Market Limits are Enforced (Year)
  EuFPol::VariableArray{5} = ReadDisk(db, "SOutput/EuFPol") # [FuelEP,ECC,Poll,Area,Year] Energy Related Pollution (Tonnes/Yr)
  EnFPolRef::VariableArray{5} = ReadDisk(BCNameDB, "SOutput/EuFPol") # [FuelEP,ECC,Poll,Area,Year] Energy Related Pollution (Tonnes/Yr)
  ETABY::VariableArray{1} = ReadDisk(db, "SInput/ETABY") # [Market] Base Year for CFR (Year)
  ETADAP::VariableArray{2} = ReadDisk(db, "SInput/ETADAP") # [Market,Year] Cost of Domestic Allowances from Government (Real US$/Tonne)
  ETAPr::VariableArray{2} = ReadDisk(db, "SOutput/ETAPr") # [Market,Year] Cost of Emission Trading Allowances (US$/Tonne)
  EuDemand::VariableArray{4} = ReadDisk(db, "SOutput/EuDemand") # [Fuel,ECC,Area,Year] Enduse Energy Demands (TBtu/Yr)
  EuDemandRef::VariableArray{4} = ReadDisk(BCNameDB, "SOutput/EuDemand") # [Fuel,ECC,Area,Year] Enduse Energy Demands (TBtu/Yr)
  ExchangeRate::VariableArray{2} = ReadDisk(db, "MOutput/ExchangeRate") # [Area,Year] Local Currency/$US Exchange Rate (Local/$US)
  FFPMap::VariableArray{2} = ReadDisk(db, "SInput/FFPMap") # [FuelEP,Fuel] Map between FuelEP and Fuel
  FPCFSCredit::VariableArray{4} = ReadDisk(db, "SOutput/FPCFSCredit") # [Fuel,ES,Area,Year] CFR Credit Price ($/Tonnes)
  FPCFSFuel::VariableArray{4} = ReadDisk(db, "SOutput/FPCFSFuel") # [Fuel,ES,Area,Year] CFR Fuel Price ($/mmBtu)
  FSell::VariableArray{2} = ReadDisk(db, "SOutput/FSell") # [Market,Year] Federal (Domestic) Credits Sold into Market (Tonnes/Yr)
  FSellFraction::VariableArray{2} = ReadDisk(db, "SInput/FSellFraction") # [Market,Year] Fraction of Credit Requirements Sold as Tech Fund Credits (Tonne/Tonne)
  Inflation::VariableArray{2} = ReadDisk(db, "MOutput/Inflation") # [Area,Year] Inflation Index ($/$)
  ISell::VariableArray{2} = ReadDisk(db, "SOutput/ISell") # [Market,Year] Credit Grant (Tonnes/Yr)
  ObligatedCFS::VariableArray{3} = ReadDisk(db, "SInput/ObligatedCFS") # [ECC,Area,Year] Obligated Sectors for CFR Emission Reductions (1=Obligated)
  OverBAB::VariableArray{2} = ReadDisk(db, "SOutput/OverBAB") # [Market,Year] Overage Before Adjustment to Bank (Tonnes)
  Part3::VariableArray{1} = ReadDisk(db, "SOutput/Part3") # [Year] Part3 Credits Generated (Tonnes/Yr)
  Part3AT::VariableArray{1} = ReadDisk(db, "SInput/Part3AT") # [Year] Part3 Averaging Time (Years)
  Part3GrossFraction::VariableArray{1} = ReadDisk(db, "SInput/Part3GrossFraction") # [Year] Fraction of Credit Requirements Sold as Part 3 Credits (Tonne/Tonne)
  Part3Lv1::VariableArray{1} = ReadDisk(db, "SOutput/Part3Lv1") # [Year] Part3 Credits in Level 1 (Tonnes)
  Part3Lv2::VariableArray{1} = ReadDisk(db, "SOutput/Part3Lv2") # [Year] Part3 Credits in Level 2 (Tonnes)
  Part3Rt1::VariableArray{1} = ReadDisk(db, "SOutput/Part3Rt1") # [Year] Part3 Credits leaving Level 1 (Tonnes)
  Part3Rt2::VariableArray{1} = ReadDisk(db, "SOutput/Part3Rt2") # [Year] Part3 Credits leaving Level 2 (Tonnes)
  PolConv::VariableArray{1} = ReadDisk(db, "SInput/PolConv") # [Poll] Pollution Conversion Factor (convert GHGs to eCO2)
  SecMap::VariableArray{1} = ReadDisk(db, "SInput/SecMap") #[ECC]  Map Between the Sector and ECC Sets
  SqPol::VariableArray{4} = ReadDisk(db, "SOutput/SqPol") # [ECC,Poll,Area,Year] Sequestering Emissions (Tonnes/Yr)
  SqPolRef::VariableArray{4} = ReadDisk(BCNameDB, "SOutput/SqPol") # [ECC,Poll,Area,Year] Sequestering Emissions in Reference Case (Tonnes/Yr)
  xFSell::VariableArray{2} = ReadDisk(db, "SInput/xFSell") # [Market,Year] Tech Fund Permits Available (Tonnes/Yr)
  xISell::VariableArray{2} = ReadDisk(db, "SInput/xISell") # [Market,Year] Exogenous Credit Grant (Tonnes/Yr)
end

function TransTechSelect_MCFR(data,eckey)
  (; EC,Tech) = data

  if eckey == "Passenger"
    techs = Select(Tech,(from="LDVGasoline", to="TrainFuelCell"))
  elseif eckey == "Freight"
    techs_a =  Select(Tech,(from="TrainDiesel", to="MarineFuelCell"))
    techs_b = Select(Tech,"OffRoad")
    techs = union(techs_a,techs_b)
  elseif eckey == "AirPassenger"
    techs = Select(Tech,["PlaneJetFuel","PlaneGasoline","OffRoad"])
  elseif eckey == "AirFreight"
    techs = Select(Tech,["PlaneJetFuel","PlaneGasoline","PlaneFuelCell","OffRoad"])
  elseif eckey == "ForeignPassenger"
    techs = Select(Tech,["PlaneJetFuel","PlaneGasoline","PlaneFuelCell","MarineLight","MarineHeavy","MarineFuelCell","OffRoad"])
  elseif eckey == "ForeignFreight"
    techs = Select(Tech,["PlaneJetFuel","PlaneGasoline","PlaneFuelCell","MarineLight","MarineHeavy","MarineFuelCell","OffRoad"])
  elseif eckey == "ResidentialOffRoad"
    techs = Select(Tech,"OffRoad")
  elseif eckey == "CommercialOffRoad"
    techs = Select(Tech,"OffRoad")
  else
    techs = Select(Tech)
  end

  return techs
end

function MarketCFR_DtaRun(data, market, areas, AreaName, AreaKey)
  (; Area,AreaDS,Areas,EC,ECDS,ECs,ECC,ECCDS,ECCs,EIType) = data
  (; EITypeDS,EITypes,ES,ESDS,ESes,Enduse,EnduseDS,Enduses) = data
  (; Fuel,FuelDS,Fuels,FuelEP,FuelEPDS,FuelEPs,Market,Markets) = data
  (; Nation,NationDS,Nations,Tech,TechDS,Techs) = data
  (; Poll,PollDS,Polls,Year,CDTime,CDYear,SceName,Yr2030) = data
  (; ANMap,AreaMarket,CgDemand,CgDemandRef,CoverageCFS,CreditsBanked) = data
  (; CreditsCogeneration,CreditsFossil,CreditsFugitive,CreditsGenerated) = data
  (; CreditsInventory,CreditsLowCarbon,CreditsNeeded,CreditsOther) = data
  (; CreditsRedeemed,CreditsRequired,CreditsSequester,CreditsTech) = data
  (; CreditSwitch,DemandCFS,DemandCFSRef,DmFrac,Driver,EIAverage) = data
  (; EICFS,EICFSRef,EIDomestic,EIGapCFS,EIGoal,EIGoalCFS,EIImports) = data
  (; EINation,EIOfficial,EIReduction,EISector,EISectorRef,EISectorN) = data
  (; EIStreamCredit,Enforce,EuFPol,EnFPolRef,ETABY,ETADAP,ETAPr) = data
  (; EuDemand,EuDemandRef,ExchangeRate,FFPMap,FPCFSCredit,FPCFSFuel) = data
  (; FSell,FSellFraction,Inflation,ISell,ObligatedCFS,OverBAB,Part3) = data
  (; Part3AT,Part3GrossFraction,Part3Lv1,Part3Lv2,Part3Rt1,Part3Rt2) = data
  (; PolConv,SecMap,SqPol,SqPolRef,xFSell,xISell) = data

  iob = IOBuffer()

  CreditsBalance = zeros(Float32, length(Year)) # Annual Balance of Credits (MT/Yr)
  CreditsDemand = zeros(Float32, length(Year)) # Demand for Credits (MT/Yr)
  CreditsFossilArea = zeros(Float32, length(Area), length(Year)) # CFR Credits Generated by reducing Intensity of Fossil Fuels (Tonnes/Yr)
  CreditsLowCarbonArea = zeros(Float32, length(Area), length(Year)) # CFR Credits Generated by Low Carbon Fuels (Tonnes/Yr)
  CreditsSupply = zeros(Float32, length(Year)) # Supply of Credits (MT/Yr)

  PolCovCFS = zeros(Float32, length(Fuel), length(ECC), length(Area), length(Year)) # 'CFR Covered Emissions (eCO2 MT/Yr)'
  PolCovCFSRef = zeros(Float32, length(Fuel), length(ECC), length(Area), length(Year)) # 'CFR Covered Emissions in Reference Case (eCO2 MT/Yr)'

  DDD = zeros(Float32, length(Year))
  PPP = zeros(Float32, length(Year))
  RRR = zeros(Float32, length(Year))
  XXX = zeros(Float32, length(Year))
  WWW = zeros(Float32, length(Year))
  ZZZ = zeros(Float32, length(Year))

  area_money = first(areas)
  Current = Int(max(Enforce[market],2010)-ITime+1)
  KJBtu = 1.054615

  println(iob, " ")
  println(iob, "$SceName; sheet name and scenario")
  println(iob, " ")
  println(iob, "This is the CFR Market Summary")
  println(iob, " ")

  years = collect(Yr(2010):Yr(2050))
  # year = Select(Year, (from = "2010", to = "2050"))
  # year = Select(Year)
  println(iob, "Year;", ";    ", join(Year[years], ";"))
  println(iob, " ")

  #
  # From PreCalculations
  #
  ghg = Select(Poll,["CO2","CH4","N2O","SF6","PFC","HFC"])
  BaseYearCFR=Int(min(ETABY[market],MaxTime)-ITime+1)

  #
  # Temporary change until re-run - Jeff Amlin 1/17/19
  #
  for year in years
    if year <= Current
      for area in areas, fuel in Fuels
        EIOfficial[fuel,area,year] = EIOfficial[fuel,area,Current]
        for ecc in ECCs
          CoverageCFS[fuel,ecc,area,year] = CoverageCFS[fuel,ecc,area,Current]
        end
      end
    end
  end

  for year in years, area in areas, ecc in ECCs, fuel in Fuels
    CreditSwitch[fuel,ecc,area,year] = CreditSwitch[fuel,ecc,area,Yr2030]
  end

  for area in areas, ecc in ECCs, fuel in Fuels
    for year in years
      PolCovCFSRef[fuel,ecc,area,year] = sum(EnFPolRef[fuelep,ecc,poll,area,year]*PolConv[poll]*
        FFPMap[fuelep,fuel] for poll in ghg, fuelep in FuelEPs)*CoverageCFS[fuel,ecc,area,year]/1e6

      PolCovCFS[fuel,ecc,area,year] = sum(EuFPol[fuelep,ecc,poll,area,year]*PolConv[poll]*
        FFPMap[fuelep,fuel] for poll in ghg, fuelep in FuelEPs)*CoverageCFS[fuel,ecc,area,year]/1e6

      DemandCFSRef[fuel,ecc,area,year] = (EuDemandRef[fuel,ecc,area,year]+
        CgDemandRef[fuel,ecc,area,year])*CoverageCFS[fuel,ecc,area,year]

      if year <= Current
        DemandCFS[fuel,ecc,area,year] = DemandCFSRef[fuel,ecc,area,year]
      end
    end
  end

  #
  ###############
  #
  for year in years, area in areas
    CreditsFossilArea[area,year] = sum(CreditsFossil[fuel,ecc,area,year] for ecc in ECCs, fuel in Fuels)
    CreditsLowCarbonArea[area,year] = sum(CreditsLowCarbon[fuel,ecc,area,year] for ecc in ECCs, fuel in Fuels)
  end

  for year in years
    CreditsDemand[year] = sum(CreditsRequired[area,year] for area in areas)+CreditsBanked[market,year]
  end

  for year in years
    CreditsSupply[year] = sum(CreditsLowCarbonArea[area,year] for area in areas)+
                      sum(CreditsFossilArea[area,year] for area in areas)+
                      sum(CreditsFugitive[ecc,area,year] for area in areas, ecc in ECCs)+
                      sum(CreditsCogeneration[ecc,area,year] for area in areas, ecc in ECCs)+
                      sum(CreditsSequester[ecc,area,year] for area in areas, ecc in ECCs)+
                      sum(CreditsOther[area,year] for area in areas)+
                      CreditsRedeemed[market,year]+
                      FSell[market,year]+
                      ISell[market,year]
  end

  for year in years
    CreditsBalance[year] = CreditsSupply[year]-CreditsDemand[year]
  end

  #
  # Continuing Ctrl
  #
  println(iob, AreaName, " CFR Credit Prices;;", join(Year[years], ";"))
  print(iob, "ETAPr;Clearing (Local \$/Tonnes)")
  for year in years
    ZZZ[year] = ETAPr[market,year]*ExchangeRate[area_money,year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "ETADAP;Tech Fund (Local \$/Tonnes)")
  for year in years
    ZZZ[year] = ETADAP[market,year]*Inflation[area_money,year]*ExchangeRate[area_money,year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "FPCFSCredit;Maximum Credit (Local \$/Tonnes)")
  for year in years
    ZZZ[year] = maximum(FPCFSCredit[fuel,es,area,year]*ExchangeRate[area,year] for area in areas, es in ESes, fuel in Fuels)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "ETAPr;Clearing ($CDTime \$/Tonnes)")
  for year in years
    ZZZ[year] = ETAPr[market,year]*ExchangeRate[area_money,year] ./ Inflation[area_money,year] * Inflation[area_money,CDYear]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "ETADAP;Tech Fund ($CDTime \$/Tonnes)")
  for year in years
    ZZZ[year] = ETADAP[market,year]*Inflation[area_money,year]*
      ExchangeRate[area_money,year]/Inflation[area_money,year]*Inflation[area_money,CDYear]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)

  println(iob, AreaName, " Emission Summary (eCO2 MT/Yr);;", join(Year[years], ";")) 
  for year in years
    ZZZ[year] = sum(PolCovCFSRef[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)
    RRR[year] = ZZZ[year]
  end
  print(iob, " ;Reference")
  for year in years
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Policy")
  for year in years
    ZZZ[year] = sum(PolCovCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Change")
  for year in years
    ZZZ[year] = ZZZ[year]-RRR[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)


  println(iob, AreaName, " Actual Emission Intensity Summary (g eCO2/MJ);;", join(Year[years], ";"))
  print(iob, " ;Reference Actual")
  for year in years
    @finite_math ZZZ[year] =
      sum(EICFSRef[fuel,area,year]*DemandCFSRef[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/
      sum(DemandCFSRef[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/
      KJBtu/1000
    RRR[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
 
   print(iob, " ;Policy Actual")
   for year in years
    @finite_math ZZZ[year] =
      sum(EICFS[fuel,area,year]*DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/
      sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/
      KJBtu/1000
    PPP[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
 
  print(iob, " ;Change")
  for year in years
    ZZZ[year] = PPP[year]-RRR[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  print(iob, " ;Fractional Change")
  for year in years
    @finite_math ZZZ[year] = (PPP[year]/RRR[year]-1)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Change from ",Int(ETABY[market]))
  for year in years
    ZZZ[year] = PPP[year]-RRR[BaseYearCFR]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Fractional Change from ",Int(ETABY[market]))
  for year in years
    @finite_math ZZZ[year] = (PPP[year]/RRR[BaseYearCFR]-1)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)


  println(iob, AreaName, " Official Emission Intensity Summary (g eCO2/MJ);;", join(Year[years], ";"))
  print(iob, " ;Reference Official")
  for year in years
    WWW[year] = sum(DemandCFSRef[fuel,ecc,area,year]*CreditSwitch[fuel,ecc,area,year]
                    for area in areas, ecc in ECCs, fuel in Fuels)
    @finite_math ZZZ[year] = sum(EIOfficial[fuel,area,year]*DemandCFSRef[fuel,ecc,area,year]*
      CreditSwitch[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/
      WWW[year]/KJBtu/1000
    RRR[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Policy Official")
  for year in years
    WWW[year] = sum(DemandCFS[fuel,ecc,area,year]*CreditSwitch[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)
    @finite_math ZZZ[year] = (sum(EIOfficial[fuel,area,year]*DemandCFS[fuel,ecc,area,year]*
      CreditSwitch[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)-
      sum(CreditsNeeded[fuel,ecc,area,year]*CreditSwitch[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels))/
      WWW[year]/KJBtu/1000
    PPP[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Change")
  for year in years
    ZZZ[year] = PPP[year]-RRR[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Fractional Change")
  for year in years
    @finite_math ZZZ[year] = (PPP[year]/RRR[year]-1)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Change from ",Int(ETABY[market]))
  for year in years
    ZZZ[year] = PPP[year]-RRR[BaseYearCFR]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Fractional Change from ",Int(ETABY[market]))
  for year in years
    @finite_math ZZZ[year] = (PPP[year]/RRR[BaseYearCFR]-1)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)


  println(iob, AreaName, " CFR Credits Summary (MT/Yr);;", join(Year[years], ";"))
  print(iob, " ;Credit Demands")
  for year in years
    ZZZ[year] = CreditsDemand[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;  Required")
  for year in years
    ZZZ[year] = sum(CreditsRequired[area,year] for area in areas)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;  Banked to Inventory")
  for year in years
    ZZZ[year] = CreditsBanked[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Credit Supply")
  for year in years
    ZZZ[year] = CreditsSupply[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;  Generated Total")
  for year in years
    ZZZ[year] = sum(CreditsGenerated[area,year] for area in areas)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;    Generated Low Carbon")
  for year in years
    ZZZ[year] = sum(CreditsLowCarbonArea[area,year] for area in areas)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;    Generated Fossil Fuels")
  for year in years
    ZZZ[year] = sum(CreditsFossilArea[area,year] for area in areas)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;    Generated Fugitive")
  for year in years
    ZZZ[year] = sum(CreditsFugitive[ecc,area,year] for area in areas, ecc in ECCs)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;    Generated Cogeneration")
  for year in years
    ZZZ[year] = sum(CreditsCogeneration[ecc,area,year] for area in areas, ecc in ECCs)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;    Generated Sequestering")
  for year in years
    ZZZ[year] = sum(CreditsSequester[ecc,area,year] for area in areas, ecc in ECCs)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;    Generated Other")
  for year in years
    ZZZ[year] = sum(CreditsOther[area,year] for area in areas)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;  Technology Fund")
  for year in years
    ZZZ[year] = FSell[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;  Credit Grant")
  for year in years
    ZZZ[year] = ISell[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;  Redeemed from Inventory")
  for year in years
    ZZZ[year] = CreditsRedeemed[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Inventory")
  for year in years
    ZZZ[year] = CreditsInventory[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Annual Balance")
  for year in years
    ZZZ[year] = CreditsBalance[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, " ;Cumulative Balance")
  for year in years
    ZZZ[year] = ZZZ[year-1] + CreditsBalance[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)


  println(iob, AreaName, " CFR Credits Generated by Low Carbon Fuels (MT/Yr);;", join(Year[years], ";"))
  print(iob, "CreditsLowCarbon;Total")
  for year in years
    ZZZ[year] = sum(CreditsLowCarbon[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for fuel in Fuels
    print(iob, "CreditsLowCarbon;",FuelDS[fuel])
    for year in years
      ZZZ[year] = sum(CreditsLowCarbon[fuel,ecc,area,year] for area in areas, ecc in ECCs)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  #
  println(iob)


  println(iob, AreaName, " Fossil Credits (MT/Year);;", join(Year[years], ";"))
  print(iob, "CreditsFossil;Total")
  for year in years
    ZZZ[year] = sum(CreditsFossil[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "CreditsFossil;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(CreditsFossil[fuel,ecc,area,year] for area in areas, fuel in Fuels)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  #
  println(iob)


  print(iob, AreaName, " Sequestering Credits (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "CreditsSequester;Total")
  for year in years
    ZZZ[year] = sum(CreditsSequester[ecc,area,year] for area in areas, ecc in ECCs)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "CreditsSequester;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(CreditsSequester[ecc,area,year] for area in areas)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  #
  println(iob)


  print(iob, AreaName, " Cogeneration Credits (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "CreditsCogeneration;Total")
  for year in years
    ZZZ[year] = sum(CreditsCogeneration[ecc,area,year] for area in areas, ecc in ECCs)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "CreditsCogeneration;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(CreditsCogeneration[ecc,area,year] for area in areas)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  #
  println(iob)


  print(iob, AreaName, " Fugitive Credits (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "CreditsFugitive;Total")
  for year in years
    ZZZ[year] = sum(CreditsFugitive[ecc,area,year] for area in areas, ecc in ECCs)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "CreditsFugitive;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(CreditsFugitive[ecc,area,year] for area in areas)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  #
  println(iob)


  print(iob, AreaName, " CFR Credits Generated by Fossil Fuels (MT/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "CreditsFossil;Total")
  for year in years
    ZZZ[year] = sum(CreditsFossil[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for fuel in Fuels
    print(iob, "CreditsFossil;",FuelDS[fuel])
    for year in years
      ZZZ[year] = sum(CreditsFossil[fuel,ecc,area,year] for area in areas, ecc in ECCs)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  #
  println(iob)


  print(iob, AreaName, " CFR Credits Generated by Low Carbon Fuels (MT/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "CreditsLowCarbon;Total")
  for year in years
    ZZZ[year] = sum(CreditsLowCarbon[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "CreditsLowCarbon;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(CreditsLowCarbon[fuel,ecc,area,year] for area in areas, fuel in Fuels)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  ecs = Select(EC,["Passenger","Freight"])
  for ec in ecs
    techs = TransTechSelect_MCFR(data,EC[ec])
    print(iob, AreaName, " ", ECDS[ec], " CFR Credits Generated by Low Carbon Fuels (MT/Yr);")
    for year in years
      print(iob,";",Year[year])
    end
    println(iob)    
    print(iob, "CreditsTech;Total")
    for year in years
      ZZZ[year] = sum(CreditsTech[enduse,fuel,tech,ec,area,year] for area in areas, tech in techs, fuel in Fuels, enduse in Enduses)/1e6
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
    for tech in techs
      print(iob, "CreditsTech;",TechDS[tech])
      for year in years
        ZZZ[year] = sum(CreditsTech[enduse,fuel,tech,ec,area,year] for area in areas, fuel in Fuels, enduse in Enduses)/1e6
        print(iob,";",@sprintf("%15.3f", ZZZ[year]))
      end
      println(iob)
    end
    println(iob)
  end


  print(iob, AreaName, " CFR Fuel Price (Local \$/mmBtu);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  for fuel in Fuels
    print(iob, "FPCFSFuel;",FuelDS[fuel])
    for year in years
      PPP[year] = 0.0
      DDD[year] = 0.0
      for es in ESes
        eccs = findall(SecMap[:] .== es)
        if !isempty(eccs)
          PPP[year] = PPP[year] + sum(FPCFSFuel[fuel,es,area,year] * DemandCFSRef[fuel,ecc,area,year] for area in areas, ecc in eccs)
          DDD[year] = DDD[year] + sum(DemandCFSRef[fuel,ecc,area,year] for area in areas, ecc in eccs)
        end
      end
      @finite_math ZZZ[year] = PPP[year]/DDD[year]
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  print(iob, AreaName, " Official Value for Emission Intensity (Tonnes/TBtu);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  for fuel in Fuels
    print(iob, "EIOfficial;",FuelDS[fuel])
    for year in years
      ZZZ[year] = EIOfficial[fuel,area_money,year]/KJBtu/1000
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  print(iob, AreaName, " Liquid Stream Emission Intensity Goal (Tonnes/TBtu);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "EIStreamCredit;Liquid")
  for year in years
    ZZZ[year] = EIStreamCredit[market,year]/KJBtu/1000
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  println(iob)


  eses = Select(ES,["Industrial","Transport"])
  for es in eses
    print(iob, AreaName," ",ESDS[es]," Emission Intensity Goal for CFR (Tonnes/TBtu);")
    for year in years
      print(iob,";",Year[year])
    end
    println(iob, ";")
    for fuel in Fuels
      print(iob, "EIGoalCFS;",FuelDS[fuel])
      for year in years
        ZZZ[year] = EIGoalCFS[fuel,es,area_money,year]/KJBtu/1000
        print(iob,";",@sprintf("%15.3f", ZZZ[year]))
      end
      println(iob)
    end
    println(iob)
    print(iob, AreaName," ",ESDS[es]," Emission Intensity Gap between EI and EI Goal (Tonnes/TBtu);")
    for year in years
      print(iob,";",Year[year])
    end
    println(iob, ";")
    for fuel in Fuels
      print(iob, "EIGapCFS;",FuelDS[fuel])
      for year in years
        ZZZ[year] = EIGapCFS[fuel,es,area_money,year]/KJBtu/1000
        print(iob,";",@sprintf("%15.3f", ZZZ[year]))
      end
      println(iob)
    end
    println(iob)
  end


  ecs = Select(EC,["Passenger","Freight"])
  for ec in ecs
    techs = TransTechSelect_MCFR(data,EC[ec])
    print(iob, AreaName, " ", ECDS[ec], " Emission Intensity Goal for CFR (Tonnes/TBtu);")
    for year in years
      print(iob,";",Year[year])
    end
    println(iob, ";")
    for tech in techs
      print(iob, "EIGoal;",TechDS[tech])
      for year in years
        ZZZ[year] = sum(EIGoal[enduse,fuel,tech,ec,area_money,year]*
          DmFrac[enduse,fuel,tech,ec,area_money,year] for fuel in Fuels, enduse in Enduses)/KJBtu/1000
        print(iob,";",@sprintf("%15.3f", ZZZ[year]))
      end
    println(iob)
    end
    println(iob)
  end


  print(iob, AreaName, " Emission Intensity (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "EISector;Average")
  for year in years
    WWW[year] = sum(Driver[ecc,area,year] for area in areas, ecc in ECCs)
    @finite_math ZZZ[year] =  sum(EISector[ecc,area,year] * Driver[ecc,area,year] for area in areas, ecc in ECCs) / WWW[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "EISector;",ECCDS[ecc])
    for year in years
      WWW[year] = sum(Driver[ecc,area,year] for area in areas)
      @finite_math ZZZ[year] =  sum(EISector[ecc,area,year] * Driver[ecc,area,year] for area in areas) / WWW[year]
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  print(iob, AreaName, " Driver (Various/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "Driver;Average;")
  for year in years
    ZZZ[year] = sum(Driver[ecc,area,year] for area in areas, ecc in ECCs)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "Driver;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(Driver[ecc,area,year] for area in areas)
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  print(iob, AreaName, " CFR Covered Fuel Demands (PJ/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "DemandCFS;Total")
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)*KJBtu
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for fuel in Fuels
    print(iob, "DemandCFS;",FuelDS[fuel])
    for year in years
      ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  print(iob, AreaName, " CFR Covered Fuel Demands (PJ/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "DemandCFS;Total")
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)*KJBtu
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "DemandCFS;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, fuel in Fuels)*KJBtu
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  print(iob, AreaName, " CFR Credit Price (Local \$/Tonnes);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "FPCFSCredit;Maximum")
  for year in years
    ZZZ[year] = maximum(FPCFSCredit[fuel,es,area,year]*ExchangeRate[area,year] for area in areas, es in ESes, fuel in Fuels)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for fuel in Fuels
    print(iob, "FPCFSCredit;",FuelDS[fuel])
    for year in years
      ZZZ[year] = maximum(FPCFSCredit[fuel,es,area,year]*ExchangeRate[area,year] for area in areas, es in ESes)
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  #
  # Reference Case Covered Emissions
  #
  print(iob, AreaName, " Reference Case Covered Emissions (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "PolCovCFSRef;Total")
  for year in years
    ZZZ[year] = sum(PolCovCFSRef[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for fuel in Fuels
    print(iob, "PolCovCFSRef;",FuelDS[fuel])
    for year in years
      ZZZ[year] = sum(PolCovCFSRef[fuel,ecc,area,year] for area in areas, ecc in ECCs)
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)
  
  #
  print(iob, AreaName, " Covered Emissions (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "PolCovCFSRef;Total")
  for year in years
    ZZZ[year] = sum(PolCovCFSRef[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "PolCovCFSRef;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(PolCovCFSRef[fuel,ecc,area,year] for area in areas, fuel in Fuels)
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  #
  # Reference Case Covered Emissions
  #
  print(iob, AreaName, " Covered Emissions (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "PolCovCFS;Total")
  for year in years
    ZZZ[year] = sum(PolCovCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for fuel in Fuels
    print(iob, "PolCovCFS;",FuelDS[fuel])
    for year in years
      ZZZ[year] = sum(PolCovCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)
  
  #
  print(iob, AreaName, " Covered Emissions (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "PolCovCFS;Total")
  for year in years
    ZZZ[year] = sum(PolCovCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs, fuel in Fuels)
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  for ecc in ECCs
    print(iob, "PolCovCFS;",ECCDS[ecc])
    for year in years
      ZZZ[year] = sum(PolCovCFS[fuel,ecc,area,year] for area in areas, fuel in Fuels)
      print(iob,";",@sprintf("%15.3f", ZZZ[year]))
    end
    println(iob)
  end
  println(iob)


  #
  # EI National
  #
  cn = Select(Nation,"CN")
  for fuel in Fuels
    if sum(CreditSwitch[fuel,ecc,area,Current] for area in areas, ecc in ECCs) > 0.0
      print(iob, FuelDS[fuel], " ", NationDS[cn]," Emission Intensity (Tonnes/TBtu);")
      for year in years
        print(iob,";",Year[year])
      end
      println(iob, ";")
      print(iob, "EINation;Total")
      for year in years
        ZZZ[year] = sum(EINation[eitype,fuel,cn,year] for eitype in EITypes)
        print(iob,";",@sprintf("%15.3f", ZZZ[year]))
      end
      println(iob)
      for eitype in EITypes
        print(iob, "EINation;",EITypeDS[eitype])
        for year in years
          ZZZ[year] = EINation[eitype,fuel,cn,year]
          print(iob,";",@sprintf("%15.3f", ZZZ[year]))
        end
        println(iob)
      end
      println(iob)
    end
  end

  fuel = Select(Fuel,"Gasoline")
  print(iob, AreaName, " CFR Covered Ethanol Demand Share (PJ/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "DemandCFS;",FuelDS[fuel])  
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    WWW[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  fuel = Select(Fuel,"Ethanol")
  print(iob, "DemandCFS;",FuelDS[fuel])
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    XXX[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "DemandCFS;Ethanol Share")
  for year in years
    @finite_math ZZZ[year] = XXX[year]/(XXX[year]+WWW[year])
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)

  fuel = Select(Fuel,"Diesel")
  print(iob, AreaName, " CFR Covered BioDiesel Demand Share (PJ/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "DemandCFS;",FuelDS[fuel])
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    WWW[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  fuel = Select(Fuel,"Biodiesel")
  print(iob, "DemandCFS;",FuelDS[fuel])
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    XXX[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "DemandCFS;Biodiesel Share")
  for year in years
    @finite_math ZZZ[year] = XXX[year]/(XXX[year]+WWW[year])
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)

  fuel = Select(Fuel,"JetFuel")
  print(iob, AreaName, " CFR Covered BioJet Demand Share (PJ/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "DemandCFS;",FuelDS[fuel])
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    WWW[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  fuel = Select(Fuel,"Biojet")
  print(iob, "DemandCFS;",FuelDS[fuel])
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    XXX[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "DemandCFS;Biojet Share")
  for year in years
    @finite_math ZZZ[year] = XXX[year]/(XXX[year]+WWW[year])
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)

  fuel = Select(Fuel,"NaturalGas")
  print(iob, AreaName, " CFR Covered RNG Demand Share (PJ/Yr);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "DemandCFS;",FuelDS[fuel])
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    WWW[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  fuel = Select(Fuel,"RNG")
  print(iob, "DemandCFS;",FuelDS[fuel])
  for year in years
    ZZZ[year] = sum(DemandCFS[fuel,ecc,area,year] for area in areas, ecc in ECCs)*KJBtu
    XXX[year] = ZZZ[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "DemandCFS;RNG Share")
  for year in years
    @finite_math ZZZ[year] = XXX[year]/(XXX[year]+WWW[year])
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)


  print(iob, AreaName, " Part 3 Credits (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "Part3;Credits Awarded")
  for year in years
    ZZZ[year] = Part3[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "Part3Lv1;Credits Level 1")
  for year in years
    ZZZ[year] = Part3Lv1[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "Part3Rt1;Credits Leaving Level 1")
  for year in years
    ZZZ[year] = Part3Rt1[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "Part3Lv2;Credits Level 2")
  for year in years
    ZZZ[year] = Part3Lv2[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "Part3Rt2;Credits Leaving Level 2")
  for year in years
    ZZZ[year] = Part3Rt2[year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "xFSell;Credits Available")
  for year in years
    ZZZ[year] = xFSell[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "FSell;Credits Used")
  for year in years
    ZZZ[year] = FSell[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "FSellFraction;Credits Fraction of Net Required (Tonne/Tonne)")
  for year in years
    ZZZ[year] = FSellFraction[market,year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "Part3GrossFraction;Credits Fraction of Gross Debits (Tonne/Tonne)")
  for year in years
    ZZZ[year] = Part3GrossFraction[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  
  #
  print(iob, "Part3AT;Part3 Credits Aging Time (Years)")
  for year in years
    ZZZ[year] = Part3AT[year]
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)


  print(iob, AreaName, " Overage Before Adjusting for Banking (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "OverBAB;Overage Before Banking")
  for year in years
    ZZZ[year] = OverBAB[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)

  print(iob, AreaName, " Credit Grant (MT/Year);")
  for year in years
    print(iob,";",Year[year])
  end
  println(iob, ";")
  print(iob, "xISell;Credit Grant")
  for year in years
    ZZZ[year] = xISell[market,year]/1e6
    print(iob,";",@sprintf("%15.3f", ZZZ[year]))
  end
  println(iob)
  #
  println(iob)


  filename = "MarketCFR$market-$AreaKey-$SceName.dta"
  open(joinpath(OutputFolder, filename), "w") do filename
    write(filename, String(take!(iob)))
  end
end


function MarketCFR_DtaControl(db)
  @info "MarketCFR_DtaControl"

  data = MarketCFRData(; db)
  Area = data.Area
  AreaDS = data.AreaDS
  Areas = data.Areas
  AreaMarket = data.AreaMarket
  Enforce = data.Enforce

  # Market = data.Market

  markets = [205]
  for market in markets
    Current = Int(max(Enforce[market],2010)-ITime+1)
    areas = findall(AreaMarket[:,market,Current] .== 1)
    if isempty(areas)
      areas = Areas
    end
    MarketCFR_DtaRun(data, market, areas, "All", "All")
    # for area in areas
    #   MarketCFR_DtaRun(data, market, areas, AreaDS[area], Area[area], SceName)
    # end
  end
end


if abspath(PROGRAM_FILE) == @__FILE__
MarketCFR_DtaControl(DB)
end
